### ISSUE TITLE
830-01 can't import charactor

### ISSUE THREAD

**Issue by chaociao** [simulationcraft/simc#5032] opened 2020-01-31 20:43 UTC
### Describe the bug
# Unable to download JSON from 'https://eu.api.blizzard.com/profile/wow/character/onyxia/endlessnight?namespace=profile-eu&locale=en_GB'.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft 830-01 x64

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by jesta777** [comment] 2020-02-13 12:11
I have the same issue...

# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://eu.api.blizzard.com/profile/wow/character/argent-dawn/torbhan?namespace=profile-eu&locale=en_GB'.

Simulationcraft is not crashing, just returns this error and does not attmept to go any further. (simc_gui.simc contains data from a previous attempt to sim a different character by pasting data from the simc addon. So has not been updated for the attempted import using Simulationcraft).

**Comment by guinness57** [comment] 2020-02-20 09:27
same for me, for eu realm

Unable to download JSON from 'https://eu.api.blizzard.com/profile/wow/character/marecage-de-zangar/agamainon?namespace=profile-eu&locale=en_GB'.

copying armory  and clicking import button link does nothing
https://worldofwarcraft.com/en-gb/character/eu/archimonde/efeldur

**Comment by esteinborn** [comment] 2020-02-27 00:34
same for me:

```
# Unable to generate profile from: 

# Unable to download JSON from 'https://us.api.blizzard.com/profile/wow/character/wildhammer/drpimento?namespace=profile-us&locale=en_US'.
```

**Comment by jesta777** [comment] 2020-03-10 13:36
Any news on this? I have tried periodically over the last 40 days or so. Both using /simc addon and importing into Simulationcraft app... same result

**Comment by navv1234** [comment] 2020-03-10 13:41
Character import (like in this ticket) cannot fail with /simc addon output. I have not been able to reproduce the character download issues here with any client that I have tried, except the "nonetwork" versions, where armory imports (including item imports) are supposed to fail.

**Comment by jesta777** [comment] 2020-03-10 13:57
My apologies. I have just retried using the /simc addon. It produces data that can be copied and pasted into the Import/Simc Addon tab of the app. This then sims successfully. (Which it had n't been doing... failure when trying to access and item).
So that is good and a way to sim my character. (I will try other charatcers after this post.
However I also tried to import the same character directly inot the app and I still received tha error:
# Unable to generate profile from: 

# Unable to download JSON from 'https://eu.api.blizzard.com/profile/wow/character/argent-dawn/torbhan?namespace=profile-eu&locale=en_GB'.

Thanks for replying... I will post result of other charatcers later.

**Comment by jesta777** [comment] 2020-03-10 14:07
Just tried a different character on same realm. /simc addon produced data, copied and pasted to import/addon tab in app. Imported successfully. Clicking Simulate button produces an error:

SimulationCraft encountered an error!

Simulation runtime error:
BCP API: Player 'Zelrys' unable to download item id '65996' at slot waist.
Player Zelrys unable to download item id '65996' from wowhead at slot waist.Initializing: Actor 'Zelrys': Item 'inactive' Slot 'waist': Cannot initialize data

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

Details in following file:
[SimulationCraft encountered an error 2020.03.10.docx](https://github.com/simulationcraft/simc/files/4312846/SimulationCraft.encountered.an.error.2020.03.10.docx)

**Comment by jesta777** [comment] 2020-03-10 14:09
Direct import of above character into app still produces error:

# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://eu.api.blizzard.com/profile/wow/character/argent-dawn/zelrys?namespace=profile-eu&locale=en_GB'.

**Comment by navv1234** [comment] 2020-03-10 14:10
It really feels like you are running the "nonetwork" version of simc that intentionally disables all network-related code from the binary.

**Comment by jesta777** [comment] 2020-03-10 14:18
Ok, how do i check to ensure I am running the correct version? (But the initial successful sim of first character implies it can get to items?)

Fyi, I have tried (addon import then simulate), three more characters on same realm, they all fail trying to get the waist item... with different waist item numbers)

**Comment by navv1234** [comment] 2020-03-10 14:22
I don't think we tag the binary at the moment in any way.

When you use the GUI, you can go to Options -> Globals -> "Generate Debug" and put it to "Gory Details", then click simulate! it'll spit a bunch of nonsense to the log tab, zip that up and attach it here.

Remember to turn off "Generate Debug" afterwards.

**Comment by jesta777** [comment] 2020-03-10 14:28
[Gory details 2020.03.10.txt](https://github.com/simulationcraft/simc/files/4312932/Gory.details.2020.03.10.txt)

Sorry, zipped info, then dropped standard txt file instead of zip file... gonna get some coffee, maybe it will wake me up :(

**Comment by navv1234** [comment] 2020-03-10 14:36
There should be heaps of it, not just what you have there. Did you copy everything from the log window or just the "first page"?

**Comment by jesta777** [comment] 2020-03-10 14:37
Log tab ends with the 'fluffy pillow' stuff... ?

**Comment by navv1234** [comment] 2020-03-10 14:40
The text cuts out in that file in such a way that does not really make sense to me. There should be pages and pages of text if you scroll down the contents of the log tab textbox.

**Comment by jesta777** [comment] 2020-03-10 14:44
here is word file with screen shot of the log tab. You can see scroll bar position at bottom...

[log tab 2020.03.10.docx](https://github.com/simulationcraft/simc/files/4313013/log.tab.2020.03.10.docx)

**Comment by jesta777** [comment] 2020-03-10 14:47
just looked and can't find E:\Simulationcraft(x64)\log.txt on my pc. I assume that is where the gory details output should go?

**Comment by navv1234** [comment] 2020-03-10 14:48
Yeah I managed to finally reproduce by building a GUI version of the "nonetwork" build. You are running a simulationcraft version that does not allow downloading of any kind from the network. 

I'd recommend using one of the nightly releases found from http://downloads.simulationcraft.org/?C=M;O=D

You'll need 7-Zip to unpack the release into the Simulationcraft installation directory.

In the mean time, I'll see about doing something slightly more useful for error messaging when the nonetwork build is used.

**Comment by jesta777** [comment] 2020-03-10 14:48
ok, thanks for your help

Edit: Can confirm that replacing my install with simc-830-02-win64-e9fb52843f.7z from the address supplied in navv1234's previous post has solved the problem. Thanks for your time and help navv1234.

**Comment by esteinborn** [comment] 2020-03-11 16:01
Can confirm that `nonetwork` was the version I downloaded which was causing the issue. Re-downloading the latest `live` version works great.

Thanks for the help!

**Comment by gillespie-stephen** [comment] 2020-05-02 17:34
I was having this issue and tried to reinstall using the 64 bit windows installer on the downloads page for 8.3.0 R1, but continued to have the same problem. After downloading the 7z archive and extracting directly it works.

Is it possible the installer was built using the nonetwork version?

**Comment by navv1234** [comment] 2020-05-03 17:30
Maybe I should have checked that first. Yeah. It's built with nonetworking. I'll rebuild 830-01 and re-upload it.

**Comment by navv1234** [comment] 2020-05-03 17:39
New version of the official release setup file is now uploaded. If you want to use it instead of the nightly builds, it should now properly work with armory imports.

**Comment by scamille** [comment] 2020-09-15 20:10
Closing this since this has been resolved with the new release, or even better by using nightly builds.

**Closed as completed by scamille** 2020-09-15 20:10 UTC

**Comment by jesta777** [comment] 2020-09-15 20:29
No problem. My problem.was solves.by using the -02 release.
Thanks for your time and efforts guys.
