### ISSUE TITLE
Error: Unknown option 'crucible' with value '1739:1770/1739:1779/1739:1770'

### ISSUE THREAD

**Issue by rogfleming** [simulationcraft/simc#4094] opened 2017-10-17 17:31 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

run /simc on character and import

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'crucible' with value '1739:1770/1739:1779/1739:1770'

## All options used for simulation:
``` ini
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=0
override.mortal_wounds=0
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,ap,crit,haste,mastery,vers
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
deathknight="Blacksix"
level=110
race=human
region=us
server=korialstrasz
role=tank
professions=alchemy=800/herbalism=800
talents=3112122
spec=blood
artifact=15:0:0:0:0:272:4:273:4:274:4:275:4:276:4:277:4:278:4:279:4:280:4:281:1:282:1:283:1:284:1:285:1:286:1:289:1:1331:1:1359:1:1481:4:1482:1:1483:1:1484:17:1627:1
crucible=1739:1770/1739:1779/1739:1770

head=,id=147124,bonus_id=3562/1502/3336
neck=,id=144479,enchant_id=5889,bonus_id=3418/1587/3337
shoulder=,id=144281,bonus_id=1811/3570
back=,id=147122,enchant_id=5434,bonus_id=3562/1497/3528
chest=,id=152378,bonus_id=3614/1472/3528
wrist=,id=132365,bonus_id=3459/3570
hands=,id=147123,gem_id=151583,bonus_id=3562/1808/1502/3336
waist=,id=147072,bonus_id=3562/1507/3528
legs=,id=147125,bonus_id=3562/1497/3528
feet=,id=137529,bonus_id=3573/1567/3336
finger1=,id=147195,enchant_id=5427,bonus_id=3561/1492/3528
finger2=,id=152779,enchant_id=5427,bonus_id=1758/3573/1502/3528
trinket1=,id=121287,gem_id=151583,bonus_id=3573/1808/41/604/1572/3528
trinket2=,id=128711,bonus_id=689/601/679
main_hand=,id=128402,enchant_id=3368,gem_id=152030/147111/137371,bonus_id=716,relic_id=3614:1472:3528/3562:1507:3528/3573:1567:3336

### Gear from Bags
#
# Crown of Burning Resolve (930)
# head=,id=152376,bonus_id=3614/1472/3528
#
# Dreadwyrm Crown (890)
# head=,id=138355,bonus_id=3516/1487/3528
#
# Prydaz, Xavaric's Magnum Opus (970)
# neck=,id=132444,enchant_id=5889,gem_id=151585,bonus_id=3529/3459/3570
#
# Nightborne's Jeweled Necklace (910)
# neck=,id=134275,enchant_id=5889,gem_id=151585,bonus_id=3573/1808/1572/3528
#
# Fierce Gladiator's Pendant (895)
# neck=,id=148031,bonus_id=3579/1527/3336
#
# Gravewarden Pauldrons (920)
# shoulder=,id=147126,enchant_id=5929,bonus_id=3562/1502/3336
#
# Spaulders of Vile Determination (935)
# shoulder=,id=152379,enchant_id=5929,bonus_id=3614/1477/3336
#
# Dreadwyrm Shoulderguards (890)
# shoulder=,id=138361,enchant_id=5883,gem_id=151585,bonus_id=3516/1808/1487/3528
#
# Dreadwyrm Greatcloak (890)
# back=,id=138364,bonus_id=3516/1487/3528
#
# Acherus Drapes (970)
# back=,id=132376,bonus_id=3459/3570
#
# Cloak of Stifling Brimstone (915)
# back=,id=146984,bonus_id=3562/1808/1497/3528
#
# Cloak of Growing Mistrust (935)
# back=,id=147764,bonus_id=3572/1517/3337
#
# Soulflayer's Corruption (970)
# chest=,id=151795,bonus_id=1811/3570
#
# Breastplate of the Remembered King (905)
# chest=,id=140913,bonus_id=3517/1502/3336
#
# Gravewarden Chestplate (915)
# chest=,id=147121,bonus_id=3562/1497/3528
#
# Si'vashi Guard's Breastplate (905)
# chest=,id=147751,bonus_id=3572/1487/3336
#
# Garothi Breastplate (890)
# chest=,id=150958,bonus_id=3396/1552/3528
#
# Dreadwyrm Breastplate (895)
# chest=,id=138349,bonus_id=3516/1492/3336
#
# Eternally Recurring Bracers (910)
# wrist=,id=140893,bonus_id=3573/1507/3528
#
# Bonemeal-Crusted Armplates (915)
# wrist=,id=147073,bonus_id=3562/1497/3528
#
# Garothi Vambraces (905)
# wrist=,id=150962,bonus_id=3397/1567/3336
#
# Moonshatter Vambraces (895)
# wrist=,id=146856,bonus_id=3573/1557/3337
#
# Garothi Gauntlets (900)
# hands=,id=150961,bonus_id=3397/1562/3336
#
# Dusk-Crusher Handguards (900)
# hands=,id=147061,bonus_id=3561/41/1482/3528
#
# Dusk-Crusher Handguards (915)
# hands=,id=147061,bonus_id=3562/1497/3528
#
# Gravewarden Handguards (915)
# hands=,id=147123,bonus_id=3562/1497/3528
#
# Groundshatter Gauntlets (900)
# hands=,id=147062,bonus_id=3561/1482/3528
#
# Gleaming Celestial Waistguard (900)
# waist=,id=144407,bonus_id=3444/1497/3337
#
# Waistguard of Fel Magics (930)
# waist=,id=152380,bonus_id=3614/1472/3528
#
# Shiversleet Waistguard (915)
# waist=,id=147071,bonus_id=3562/1497/3528
#
# Triumvirate High Guard's Greatbelt (880)
# waist=,id=153341,bonus_id=1704/1472/3528
#
# Rattlegore Bone Legplates (970)
# legs=,id=132453,bonus_id=3459/3570
#
# Aggramar's Stride (970)
# feet=,id=132443,bonus_id=1811/3570
#
# Garothi Sabatons (910)
# feet=,id=150963,gem_id=151583,bonus_id=3573/1808/1572/3528
#
# Iron Ballast Sabatons (915)
# feet=,id=147059,bonus_id=3562/40/1497/3528
#
# Sephuz's Secret (970)
# finger1=,id=132452,bonus_id=3459/3570
#
# Foul-Sadist's Seal (895)
# finger1=,id=150989,bonus_id=3397/1557/3528
#
# Band of the Abyssal Lord (141)
# finger1=,id=150459,enchant_id=5428,bonus_id=3589,drop_level=110
#
# Lana'thel's Lament (970)
# finger1=,id=133974,enchant_id=5430,gem_id=151585,bonus_id=3529/3459/3570
#
# Dreamwalker' s Band (910)
# finger1=,id=139065,enchant_id=5428,bonus_id=3573/42/1572/3528
#
# Warden Band (910)
# finger1=,id=136737,bonus_id=3573/1572/3528
#
# Band of Rescinded Truths (900)
# finger1=,id=147194,enchant_id=5430,bonus_id=3561/42/1482/3528
#
# Ring of Exclusive Servitude (890)
# finger1=,id=140906,enchant_id=5430,gem_id=151585,bonus_id=3516/1808/1487/3528
#
# Grasping Tentacle Loop (910)
# finger1=,id=133634,enchant_id=5428,bonus_id=3573/1562/3528
#
# Shifting Cosmic Sliver (925)
# trinket1=,id=147026,bonus_id=3562/1507/3528
#
# Engine of Eradication (925)
# trinket1=,id=147015,bonus_id=3562/40/1507/3336
#
# Astral Alchemist Stone (935)
# trinket1=,id=151607,bonus_id=3609/601/3608
#
# Archimonde's Hatred Reborn (970)
# trinket1=,id=144249,bonus_id=1811/3570
#
# Resilient Heart of the Forest (915)
# trinket1=,id=139064,bonus_id=3573/603/1577/3336
#
# Majordomo's Dinner Bell (885)
# trinket1=,id=142168,bonus_id=3573/40/1502/3336
#
# Resilient Heart of the Forest (910)
# trinket1=,id=139064,bonus_id=3573/605/1572/3528
#
# Raven Eidolon (910)
# trinket1=,id=142169,bonus_id=3573/1522/3528
#
# Mac'aree Focusing Amethyst (910)
# trinket1=,id=152783,bonus_id=3573/1502/3528
#
# Leviathan's Hunger (920)
# trinket1=,id=147023,bonus_id=3562/1502/3336
#
# Venerable Triad Statuette (910)
# trinket1=,id=152782,bonus_id=3573/1502/3528
#
# Infernal Cinders (915)
# trinket1=,id=147009,bonus_id=3562/1497/3528
#
# Vial of Ceaseless Toxins (910)
# trinket1=,id=147011,bonus_id=3561/1492/3336
#
# Fang of Tichondrius (910)
# trinket1=,id=140797,bonus_id=3573/1507/3528
#
# Ember of Nullification (910)
# trinket1=,id=136978,bonus_id=3573/1562/3528
#
# Reliquary of the Damned (900)
# trinket1=,id=147024,bonus_id=3561/1482/3528
#
# Nightborne Defender's Badge (890)
# trinket1=,id=134278,bonus_id=3573/41/605/1552/3336
#
# Animated Exoskeleton (885)
# trinket1=,id=140789,bonus_id=3444/1482/3528
#
# Specter of Betrayal (915)
# trinket1=,id=151190,bonus_id=3564/1497/3337
#
# Horn of Valor (925)
# trinket1=,id=133642,bonus_id=3573/1577/3337
#
# Feverish Carapace (915)
# trinket1=,id=147022,bonus_id=3562/1497/3528
#


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-10-17 21:07
Duplicate of #4000

**Closed as completed by vituscze** 2017-10-17 21:07 UTC
