### ISSUE TITLE
Simulation Error Importing from Simc Addon WoW

### ISSUE THREAD

**Issue by JimGme** [simulationcraft/simc#4641] opened 2018-12-16 18:31 UTC
### Describe the bug
Simulation fails to run

### Expected behavior
Simulation to run
### To Reproduce
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Zindhia': Item 'inactive' Slot 'head': Cannot parse option from ',id=163446,bonus_id=5125/1547/5136/5378/4775,context=28,azerite_powers=447/30/83/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=0
pvp=1
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
shaman="Zindhia"
level=120
race=goblin
region=us
server=area_52
role=attack
professions=mining=150/skinning=150
talents=3221133
spec=enhancement

head=,id=163446,bonus_id=5125/1547/5136/5378/4775,context=28,azerite_powers=447/30/83/13
neck=,id=158075,bonus_id=4936/4929/4930/1538,context=11,azerite_level=34
shoulder=,id=163441,bonus_id=5125/1562/4786/5400/4775,context=29,azerite_powers=486/459/14/13
back=,id=163366,bonus_id=5126/41/1567/4783,context=6
chest=,id=163282,bonus_id=5125/1547/5138/5380/4775,context=28,azerite_powers=416/31/15/13
shirt=,id=38,context=14
wrist=,id=163308,bonus_id=5126/4802/1572/4783,context=6
hands=,id=161644,bonus_id=4984/4802/5128/1547/4786,context=25
waist=,id=161368,bonus_id=4798/42/1477/4786,context=3
legs=,id=160631,bonus_id=4798/1482/4783,context=3
feet=,id=163449,bonus_id=5126/1562/4786,context=6
finger1=,id=158151,bonus_id=4803/1552/4784,context=28
finger2=,id=160646,bonus_id=4801/1467/4783,context=4
trinket1=,id=158163,bonus_id=4803/4802/1537/4784,context=27
trinket2=,id=161462,bonus_id=5119/1492/4786,context=3
main_hand=,id=166337,bonus_id=5125/1567/4783,context=29
off_hand=,id=166337,bonus_id=5125/1567/4783,context=29

### Gear from Bags
#
# Pa'ku Windrider Helm (360)
# head=,id=157921,bonus_id=1547/5136/5378/4775,context=28,azerite_powers=223/21/14/13
#
# Dread Gladiator's Chain Spaulders (360)
# shoulder=,id=161655,bonus_id=5450/5128/1547/4786/5397/4775,context=25,azerite_powers=222/30/14/13
#
# Honorbound Vanguard's Shoulderguards (345)
# shoulder=,id=163441,bonus_id=5125/1532/5140/4775,context=28,azerite_powers=417/459/14/13
#
# Pa'ku Windrider Shoulderguards (360)
# shoulder=,id=157923,bonus_id=1547/5140/5379/4775,context=28,azerite_powers=179/30/15/13
#
# Honorbound Vanguard's Shoulderguards (345)
# shoulder=,id=163441,bonus_id=5124/1532/4786/4775,context=3,azerite_powers=486/18/14/13
#
# Windswept Dinorider's Cape (360)
# back=,id=164384,bonus_id=4798/1482/4783,context=3
#
# Honorbound Vanguard's Cloak (355)
# back=,id=163366,bonus_id=5125/1547/4784,context=5
#
# Freehold Cape of the Peerless (266)
# back=,id=159228,bonus_id=4796/1683,drop_level=120
#
# Bilewing Jerkin (360)
# chest=,id=157950,bonus_id=1547/5138/5380/4775,context=28,azerite_powers=224/104/15/13
#
# Dread Gladiator's Chain Armor (360)
# chest=,id=161635,bonus_id=5107/5128/1547/4786/4775,context=25,azerite_powers=447/21/14/13
#
# Dreadmire Vest (345)
# chest=,id=157886,bonus_id=1532/5138/4775,context=28,azerite_powers=179/462/14/13
#
# Renowned Guild Tabard (1)
# tabard=,id=69210
#
# Oblivion Crushers (350)
# hands=,id=160721,bonus_id=4801/1472/4783,context=4
#
# Dread Gladiator's Chain Clasp (355)
# waist=,id=161767,bonus_id=5065/40/5129/1547/4786,context=56
#
# Cincture of Profane Deeds (345)
# waist=,id=160724,bonus_id=4801/41/1467/4783,context=4
#
# Honorbound Vanguard's Leggings (360)
# legs=,id=163445,bonus_id=5125/1552/4784,context=5
#
# Dread Gladiator's Chain Legguards (355)
# legs=,id=161759,bonus_id=4984/5129/1547/4786,context=25
#
# Honorbound Vanguard's Sabatons (370)
# feet=,id=163449,bonus_id=5125/1562/4786,context=29
#
# Dread Aspirant's Ring (335)
# finger1=,id=162865,bonus_id=1527/4783,context=47
#
# Dread Aspirant's Seal (335)
# finger1=,id=162965,bonus_id=1527/4783,context=47
#
# Murky Cerulean Signet (335)
# finger1=,id=158318,bonus_id=4778/1507/4783,context=2
#
# Dread Aspirant's Ring (330)
# finger1=,id=162865,bonus_id=1522/4785,context=47
#
# Golden Empire Signet (340)
# finger1=,id=158152,bonus_id=4803/1532/4786,context=28
#
# The Horseman's Ring (335)
# finger1=,id=143903,bonus_id=5134,drop_level=120
#
# Dread Aspirant's Medallion (330)
# trinket1=,id=162897,bonus_id=1522/4785,context=47
#
# Twitching Tentacle of Xalzaix (340)
# trinket1=,id=160656,bonus_id=4801/1462/4786,context=4
#
# Dread Aspirant's Emblem (340)
# trinket1=,id=162898,bonus_id=1532/4783,context=47
#
# Gilded Loa Figurine (340)
# trinket1=,id=158153,bonus_id=4803/1532/4784,context=26
#
# Vessel of Skittering Shadows (340)
# trinket1=,id=159610,bonus_id=4779/1512/4786,context=23
#
# Azerokk's Resonating Heart (340)
# trinket1=,id=159612,bonus_id=4779/1512/4786,context=23
#
# Tusk of the Reborn Prophet (340)
# main_hand=,id=160691,bonus_id=4801/1462/4786,context=4
#
# Dread Gladiator's Cleaver (345)
# main_hand=,id=161679,bonus_id=5110/5129/1537/4786,context=25
#
# Seth's Graphite Fishing Pole (58)
# main_hand=,id=25978,context=11
#
# Flaming Gavel of Truth (360)
# main_hand=,id=163960,bonus_id=1482/4783,context=54
#
# Honorbound Skullcleaver (340)
# main_hand=,id=163866,bonus_id=5124/1532/4786,context=3
#
# Barricade of Purifying Resolve (355)
# off_hand=,id=160699,bonus_id=4798/1477/4786,context=3
#
# Dread Gladiator's Cleaver (345)
# off_hand=,id=161679,bonus_id=5110/5129/1537/4786,context=25
#
# Honorbound Skullcleaver (340)
# off_hand=,id=163866,bonus_id=5124/1532/4786,context=3
#
# Flaming Gavel of Truth (360)
# off_hand=,id=163960,bonus_id=1482/4783,context=54
#
# Tusk of the Reborn Prophet (340)
# off_hand=,id=160691,bonus_id=4801/1462/4786,context=4

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=6

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

### Additional information
801-01
[log.txt](https://github.com/simulationcraft/simc/files/2683838/log.txt)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by seriallos** [comment] 2018-12-16 19:11
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by seriallos** 2018-12-16 19:11 UTC
Labels: duplicate

**Comment by JimGme** [comment] 2018-12-16 19:55
Thanks! I didn't realize that the download on the main page was not the most up to date version.

    On Sunday, December 16, 2018, 2:11:56 PM EST, Dave Hendler <notifications@github.com> wrote:  
 
 
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D
