### ISSUE TITLE
SimulationCraft encountered an error!

### ISSUE THREAD

**Issue by Buggi1909** [simulationcraft/simc#4653] opened 2018-12-19 11:16 UTC
Everytime I try to sim my character I got this report:

"SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Faít': Item 'inactive' Slot 'head': Cannot parse option from ',id=160616,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/87/13': Unexpected parameter 'context'."

Don't know how to fix it. Maybe you could help me.

This is the text I should copy:
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Faít': Item 'inactive' Slot 'head': Cannot parse option from ',id=160616,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/87/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=LightMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
mage="Faít"
level=120
race=undead
region=eu
server=onyxia
role=spell
professions=herbalism=139/tailoring=51
talents=1213133
spec=frost

head=,id=160616,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/87/13
neck=,id=158075,bonus_id=4933/4936/4929/1532,context=11,azerite_level=31
shoulder=,id=161454,bonus_id=5120/1492/4786/4775,context=3,azerite_powers=379/22/83/13
back=,id=160643,bonus_id=4799/40/1492/4786,context=5
chest=,id=157962,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=379/22/15/13
shirt=,id=89195,context=14
tabard=,id=69210,context=14
wrist=,id=160617,bonus_id=4799/1497/4783,context=5
hands=,id=160715,bonus_id=4799/1492/4786,context=5
waist=,id=160734,gem_id=154126,bonus_id=4799/1808/1497/4783,context=5
legs=,id=159234,bonus_id=5005/1547/4784,context=35
feet=,id=163285,gem_id=153710,bonus_id=5126/4802/1567/4783,context=6
finger1=,id=160647,enchant_id=5938,bonus_id=4799/1492/4786,context=5
finger2=,id=160645,enchant_id=5938,bonus_id=4799/1492/4786,context=5
trinket1=,id=160651,bonus_id=4799/1492/4786,context=5
trinket2=,id=159610,bonus_id=4780/1532/4784,context=16
main_hand=,id=160691,enchant_id=5949,bonus_id=4799/43/1497/4783,context=5
off_hand=,id=163876,bonus_id=5126/1567/4783,context=6

### Gear from Bags
#
# Haube des eidgebundenen Konstrukteurs (340)
# head=,id=163426,bonus_id=5124/1532/4786/5393,context=3,azerite_powers=
#
# Shadraseidenstirnband (370)
# head=,id=157905,bonus_id=1562/5136/5381,context=28,azerite_powers=
#
# Sandwirblermantelung (375)
# shoulder=,id=157939,bonus_id=1562/4786/5400/4775,context=28,azerite_powers=374/31/85/13
#
# Umhang des eidgebundenen Konstrukteurs (375)
# back=,id=163357,bonus_id=5126/1567/4783,context=6
#
# Roben des eidgebundenen Konstrukteurs (370)
# chest=,id=163280,bonus_id=5125/1562/4786/5398,context=29,azerite_powers=
#
# Wickeltuch des Fenngeists (375)
# chest=,id=157898,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=194/31/85/13
#
# Shadraseidenrobe (375)
# chest=,id=157930,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=481/22/87/13
#
# Splitter der Exodar (265)
# finger1=,id=132410,enchant_id=5424,gem_id=130220,bonus_id=3459/3630
#
# Ring der Fäulnisausmerzung (370)
# finger1=,id=160645,bonus_id=4799/1492/4786,context=5
#
# Band der sicheren Vernichtung (370)
# finger1=,id=160646,bonus_id=4799/1492/4786,context=5
#
# Ring des Ritualbinders (365)
# finger1=,id=159459,bonus_id=5005/1537/4783,context=35
#
# Dolch der goldenen Flotte der Schnellklinge (266)
# main_hand=,id=159532,bonus_id=4796/1679,drop_level=120
#
# Hexfokus des Kriegshafens des Feuersturms (266)
# off_hand=,id=159822,bonus_id=4796/1695,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-19 13:08
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-19 13:08 UTC
