### ISSUE TITLE
Simulation runtime error

### ISSUE THREAD

**Issue by chaz2582** [simulationcraft/simc#4626] opened 2018-12-14 00:02 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Chazgraybar': Item 'inactive' Slot 'head': Cannot parse option from ',id=163596,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/461/473/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
rogue="Chazgraybar"
level=120
race=troll
region=us
server=bleeding_hollow
role=attack
professions=leatherworking=127/jewelcrafting=144
talents=2122332
spec=outlaw

head=,id=163596,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/461/473/13
neck=,id=158075,bonus_id=4936/4929/4930/1536,context=11,azerite_level=33
shoulder=,id=157915,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=129/461/15/13
back=,id=160644,bonus_id=4799/1492/4786,context=5
chest=,id=160619,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/459/83/13
shirt=,id=6136
tabard=,id=43349
wrist=,id=160621,bonus_id=4799/1492/4786,context=5
hands=,id=160618,bonus_id=4799/1497/4783,context=5
waist=,id=160622,bonus_id=4800/1507/4786,context=6
legs=,id=160625,bonus_id=4799/1497/4783,context=5
feet=,id=163438,bonus_id=5126/1562/4786,context=6
finger1=,id=160647,enchant_id=5939,gem_id=154127,bonus_id=4799/1808/1497/4783,context=5
finger2=,id=159460,enchant_id=5943,bonus_id=5006/1542/4784,context=35
trinket1=,id=160652,gem_id=153708,bonus_id=4799/1808/1492/4786,context=5
trinket2=,id=161462,bonus_id=5119/1497/4783,context=3
main_hand=,id=160682,enchant_id=5962,bonus_id=4799/1492/4786,context=5
off_hand=,id=160693,enchant_id=5963,bonus_id=4798/1477/4786,context=3

### Gear from Bags
#
# Doom's Howl Vest (370)
# chest=,id=161456,bonus_id=5120/1492/4786,context=3,azerite_powers=491/18
#
# Venerated Raptorhide Bindings (370)
# wrist=,id=160214,bonus_id=4779/1542/4784,context=23
#
# Festerroot Grasps of the Quickblade (266)
# hands=,id=154818,bonus_id=4796/1677,drop_level=120
#
# Spiritbound Voodoo Burl (355)
# trinket1=,id=161412,bonus_id=4798/1477/4786,context=3
#
# Frenetic Corpuscle (355)
# trinket1=,id=160648,gem_id=154126,bonus_id=4798/1808/1477/4786,context=3
#
# Pursax, the Backborer (370)
# main_hand=,id=160684,enchant_id=5963,bonus_id=4799/1492/4786,context=5
#
# Nat's Lucky Fishing Pole (20)
# main_hand=,id=45858
#
# Latticework Scalpel (370)
# main_hand=,id=160683,enchant_id=5965,bonus_id=4799/1492/4786,context=5
#
# Latticework Scalpel (370)
# main_hand=,id=160683,enchant_id=5963,bonus_id=4799/1492/4786,context=5
#
# Pursax, the Backborer (370)
# off_hand=,id=160684,enchant_id=5963,bonus_id=4799/1492/4786,context=5
#
# Latticework Scalpel (370)
# off_hand=,id=160683,enchant_id=5965,bonus_id=4799/1492/4786,context=5
#
# Latticework Scalpel (370)
# off_hand=,id=160683,enchant_id=5963,bonus_id=4799/1492/4786,context=5

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-14 00:13
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-14 00:13 UTC
