### ISSUE TITLE
I don't really know if this is a bug. But it caused a crash.

### ISSUE THREAD

**Issue by oswaldovzki** [simulationcraft/simc#4639] opened 2018-12-16 11:26 UTC
Hello. I don't know what happend, I'm not able to understant what is writen below, so... I just paste the log from WoW to SimCraft e it did not simulate. that's it.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Saraste': Item 'inactive' Slot 'head': Cannot parse option from ',id=157945,bonus_id=1547/5136/5378/4775,context=28,azerite_powers=196/21/548/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.15
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# SimC Addon 1.10.8
rogue="Saraste"
level=120
race=blood_elf
region=us
server=goldrinn
role=attack
professions=leatherworking=140/skinning=150
talents=1321312
spec=subtlety

head=,id=157945,bonus_id=1547/5136/5378/4775,context=28,azerite_powers=196/21/548/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=161457,bonus_id=5120/1492/4786/4775,context=3,azerite_powers=445/22/84/13
back=,id=163360,gem_id=153713,bonus_id=5126/4802/1572/4783,context=6
chest=,id=161456,bonus_id=5120/1492/4786/4775,context=3,azerite_powers=240/30/15/13
wrist=,id=161392,bonus_id=4798/1477/4786,context=3
hands=,id=163437,bonus_id=5126/1562/4786,context=6
waist=,id=163439,bonus_id=5126/1562/4786,context=6
legs=,id=163298,bonus_id=5126/1567/4783,context=6
feet=,id=163438,bonus_id=5126/1562/4786,context=6
finger1=,id=160645,bonus_id=4801/1477/4784,context=4
finger2=,id=161898,bonus_id=5065/5128/1547/4786,context=56
trinket1=,id=160652,bonus_id=4799/1492/4786,context=5
trinket2=,id=166794,bonus_id=5479/1502/4786,context=3
main_hand=,id=160683,enchant_id=5965,bonus_id=4799/1492/4786,context=5
off_hand=,id=160683,bonus_id=4798/1477/4786,context=3

### Gear from Bags
#
# Cloak of Coordination (58)
# back=,id=65274,context=14
#
# Seal of the Regal Loa (350)
# finger1=,id=159458,bonus_id=4780/1522/4783,context=16
#
# Deepwarden Flintlock of the Fireflash (266)
# main_hand=,id=159497,bonus_id=4796/1695,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=5
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-16 11:33
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-16 11:33 UTC
