### ISSUE TITLE
Simulation Runtime Error

### ISSUE THREAD

**Issue by DjArthritis** [simulationcraft/simc#4631] opened 2018-12-15 08:04 UTC
### Describe the bug
After pasting the text from simc in game and clicking simulate, error window pops up

### Expected behavior
A simulation to be run

### To Reproduce
Trying to simulate with the same information

### Additional information
801-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files
[simc_gui.zip](https://github.com/simulationcraft/simc/files/2682484/simc_gui.zip)

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
[log.txt](https://github.com/simulationcraft/simc/files/2682490/log.txt)

**Comment by Pewtro** [comment] 2018-12-15 08:27
You're using quite the old version of SimulationCraft. 
Update to newest nightly from here http://downloads.simulationcraft.org/?C=M;O=D and it should be fine

duplicate of #4613

**Closed as completed by Pewtro** 2018-12-15 08:27 UTC
