### ISSUE TITLE
Simulation runtime error: Incorrect option format: Unexpected parameter

### ISSUE THREAD

**Issue by aaronjrojas** [simulationcraft/simc#4728] opened 2019-02-03 18:00 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Drusdalegend': Item 'inactive' Slot 'head': Cannot parse option from ',id=159310,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=411/30/15/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.10
rogue="Drusdalegend"
level=120
race=troll
region=us
server=area_52
role=attack
professions=mining=150/enchanting=109
talents=2112322
spec=outlaw

head=,id=159310,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=411/30/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1540,context=11,azerite_level=35
shoulder=,id=157915,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=129/30/15/13
back=,id=160642,gem_id=154126,bonus_id=4799/1808/1507/4784,context=5
chest=,id=157910,bonus_id=1577/4786/5413,context=28,azerite_powers=411/239/31
shirt=,id=45664
tabard=,id=45583,context=14
wrist=,id=160621,gem_id=154126,bonus_id=4799/1808/1497/4783,context=5
hands=,id=160618,enchant_id=5933,bonus_id=4799/1517/4784,context=5
waist=,id=160622,gem_id=154126,bonus_id=4799/1808/1492/4786,context=5
legs=,id=165521,bonus_id=4798/40/1507/4786,context=3
feet=,id=160624,gem_id=154126,bonus_id=4799/1808/1492/4786,context=5
finger1=,id=165678,enchant_id=5942,bonus_id=4803/1577/4786,context=28
finger2=,id=160645,enchant_id=5942,bonus_id=4799/1492/4786,context=5
trinket1=,id=165660,bonus_id=4803/1587/4783,context=28
trinket2=,id=165572,bonus_id=4798/1537/4784,context=3
main_hand=,id=158132,enchant_id=5965,bonus_id=4803/1582/4783,context=28
off_hand=,id=158120,enchant_id=5963,bonus_id=4803/1567/4783,context=28

### Gear from Bags
#
# Finely-Tailored Red Holiday Hat (1)
# head=,id=139299,context=5
#
# Shoulders of the Sanguine Monstrosity (355)
# shoulder=,id=159323,bonus_id=4818/1527/4785/5466,context=2,azerite_powers=
#
# Deathsnap Jerkin (375)
# chest=,id=157942,bonus_id=1562/4786/5398/4775,context=28,azerite_powers=129/22/15/13
#
# Honorbound Outrider's Pants (385)
# legs=,id=163298,bonus_id=5125/1577/4784,context=29
#
# Bloodhex Anklewraps of the Peerless (266)
# feet=,id=154837,bonus_id=4796/1688,drop_level=120
#
# Loop of Pulsing Veins (355)
# finger1=,id=159463,bonus_id=4778/1527/4785,context=2
#
# Permafrost-Encrusted Heart (355)
# trinket1=,id=161381,gem_id=154127,bonus_id=4798/1808/1477/4786,context=3
#
# Frenetic Corpuscle (370)
# trinket1=,id=160648,bonus_id=4799/1492/4786,context=5
#
# Harlan's Loaded Dice (370)
# trinket1=,id=155881,bonus_id=5010/41/1542/4786,context=16
#
# Kul Tiran Cannonball Runner (370)
# trinket1=,id=159628,bonus_id=4779/1542/4786,context=23
#
# Heart-Piercing Stalactite (370)
# main_hand=,id=159134,bonus_id=4779/1542/4786,context=23
#
# Mother's Twin Gaze (370)
# main_hand=,id=160682,enchant_id=5965,bonus_id=4799/1492/4786,context=5
#
# Plundered Frost Scepter (325)
# main_hand=,id=164346,context=11
#
# Strong Fishing Pole (10)
# main_hand=,id=6365,enchant_id=5930
#
# Heart-Piercing Stalactite (370)
# off_hand=,id=159134,bonus_id=4779/1542/4786,context=23
#
# Mother's Twin Gaze (370)
# off_hand=,id=160682,enchant_id=5965,bonus_id=4799/1492/4786,context=5
#
# Plundered Frost Scepter (325)
# off_hand=,id=164346,context=11

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by Melekus** [comment] 2019-02-04 05:26
Duplicate of https://github.com/simulationcraft/simc/issues/4613

**Closed as completed by Melekus** 2019-02-04 05:26 UTC
