### ISSUE TITLE
Error simming Deathknight

### ISSUE THREAD

**Issue by Veito** [simulationcraft/simc#4662] opened 2018-12-25 11:52 UTC
### Describe the bug
I get the below described error when I try to sim my character. 

### Expected behavior
I expected to get a simulation for my character, including a pawn string.

### To Reproduce
I attempted to Sim without the line that seemed to be giving the error (Headpiece) but that led to me getting the same result except with the neck instead of the head being the issue.

### Additional information
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Incorrect option format: Unexpected parameter '*'. Expected format: name=value

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=bfahead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers,wdps,wohdps
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Incorrect option format: Unexpected parameter '*'. Expected format: name=value

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=bfahead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers,wdps,wohdps
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Schopholl': Item 'inactive' Slot 'head': Cannot parse option from ',id=155885,bonus_id=4819/1512/4786/5393/4775,context=23,azerite_powers=479/461/15/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=bfahead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers,wdps,wohdps
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
deathknight="Schopholl"
level=120
race=tauren
region=eu
server=tarren_mill
role=attack
professions=mining=59/engineering=7
talents=3113133
spec=frost

head=,id=155885,bonus_id=4819/1512/4786/5393/4775,context=23,azerite_powers=479/461/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1520,context=11,azerite_level=25
shoulder=,id=161460,bonus_id=5120/1492/4786/5400,context=3,azerite_powers=108/22
back=,id=159293,bonus_id=4779/1512/4786,context=23
chest=,id=159440,bonus_id=4819/1512/4786/5392,context=23,azerite_powers=192/30/14
tabard=,id=69210
wrist=,id=164657,bonus_id=1690,context=13
hands=,id=157960,bonus_id=4803/1552/4786,context=28
waist=,id=165495,bonus_id=5126/1502/4786,context=6
legs=,id=164655,bonus_id=1676,context=13
feet=,id=165489,gem_id=153707,bonus_id=5124/4802/1457/4786,context=3
finger1=,id=158152,bonus_id=4803/1552/4784,context=26
finger2=,id=162542,bonus_id=4779/1517/4783,context=23
trinket1=,id=159125,context=13
trinket2=,id=159625,bonus_id=4779/1517/4783,context=23
main_hand=,id=164649,enchant_id=3370,bonus_id=1692,context=13
off_hand=,id=164649,enchant_id=3368,bonus_id=1688,context=13

### Gear from Bags
#
# Finely-Tailored Green Holiday Hat (1)
# head=,id=139300,context=23
#
# Finely-Tailored Green Holiday Hat (1)
# head=,id=139300,context=23
#
# Bonepicker Helmet of the Peerless (266)
# head=,id=160175,bonus_id=4796/1687,drop_level=120
#
# Devoted Defender's Cloak (286)
# back=,id=155457,bonus_id=4790,drop_level=120,context=11
#
# Nazmani Warplate Chestpiece (285)
# chest=,id=159010,bonus_id=1452/4785/4775,context=25,azerite_powers=346/83/13
#
# Unraveling Cloth Handwraps (108)
# hands=,id=154790
#
# Sinister Combatant's Plate Gauntlets of the Aurora (340)
# hands=,id=164654,bonus_id=1705,context=13
#
# Rethu's Incessant Courage (265)
# waist=,id=146667,gem_id=151583/151583/151583,bonus_id=3459/3630,context=13
#
# Willow Pants of the Fireflash (58)
# legs=,id=6540,bonus_id=1691/4279,drop_level=120,context=54
#
# Exiled Veteran's Legguards (286)
# legs=,id=159992,bonus_id=4790,drop_level=120,context=11
#
# Unraveling Cloth Pants (108)
# legs=,id=154789
#
# Cracked Hide Boots (108)
# feet=,id=154771
#
# Embellished Ritual Sabatons (340)
# feet=,id=155861,bonus_id=4779/1512/4786,context=23
#
# Unraveling Cloth Sandals (108)
# feet=,id=154788
#
# Cracked Hide Boots (108)
# feet=,id=154771
#
# Insignia of the Grand Army (265)
# finger1=,id=152626,bonus_id=1811/3630,context=11
#
# Band of Certain Annihilation (375)
# finger1=,id=160646,bonus_id=4799/1497/4783,context=5
#
# Cracked Crawg Shackles (286)
# trinket1=,id=161182,bonus_id=4790,drop_level=120,context=11
#
# Vindictive Golem Core (281)
# trinket1=,id=159977,bonus_id=4787,drop_level=120,context=11
#
# Spireguard's Waraxe (298)
# main_hand=,id=155418,bonus_id=4813,drop_level=120,context=11
#
# Sinister Combatant's Deckpounder of the Peerless (340)
# main_hand=,id=164650,bonus_id=1683,context=13
#
# Spireguard's Waraxe (298)
# off_hand=,id=155418,bonus_id=4813,drop_level=120,context=11

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=1

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```
### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### END ###
```

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2018-12-25 17:21
Duplicate of #4613

**Closed as completed by vituscze** 2018-12-25 17:21 UTC

**Comment by Melekus** [comment] 2018-12-25 17:22
Duplicate of https://github.com/simulationcraft/simc/issues/4613

Make sure you download the last version of the simulationcraft client at http://downloads.simulationcraft.org/?C=M;O=D
