### ISSUE TITLE
[Warlock] Demonology - Various bugs causing inflated damage

### ISSUE THREAD

**Issue by Vanishoxyact** [simulationcraft/simc#3057] opened 2016-10-28 18:50 UTC
I have been doing some sims with Demonology and came across a few bugs which may be worth looking into.

1) Shadowflame dot stacking does not seem to be working as intended. When comparing the tick damage between having two stacks and a single stack, the tick damage only seems to increase by around 50%, rather than double. The tick damage for a single stack is also too high, indicating it might be stacking per tick rather than per cast? This can reproduced by comparing:
`actions=shadowflame,if=time<1`
to
`actions=shadowflame,if=time<3`
with no other actions in the action list, and all talents removed aside from shadowflame.

2) Imps created by Improved Dreadstalkers do not cast as frequently as summoned imps in-game, even if they are both empowered. This can be seen in this log:
https://www.warcraftlogs.com/reports/compare/DLbqCY2Xyc7jtTNR/DLbqCY2Xyc7jtTNR#source=5.1,7.1&fight=1,4&type=casts&view=timeline
This "feature" is not taken into account when simming, making Improved Dreadstalkers seem better than it is. This can be re-produced by using the action list below and comparing if with the above log:
`actions=call_dreadstalkers,if=time<1`
`actions+=/demonic_empowerment,if=prev_gcd.call_dreadstalkers`
`actions+=/demonbolt`

3) Dreadstalkers seem to have lower ap ingame compared to simming causing them to deal ~30% more damage. I suspect this may be due to line 1986 in the sc_warlock.cpp file:
`owner_coeff.ap_from_sp = 1.1; // HOTFIX`
but I am probably wrong.

These are just a few things I have found when simming which combined cause quite a large increase in simmed damage compared to ingame.

I hope these findings are helpful.

**Comment by nasirabtw** [comment] 2016-10-28 23:15
1) was fixed in 48761950f660dcbb157ea65e23b594c844b003c6

2) isn't accurate. Wild imps spawned by dogs have no input lag, wild imps spawned by hog and doom do. If you actually check a combatlog improved dreadstalker imps begin casting the second they're spawned but doom/hog ones have a random 500-1500ms delay before they begin casting.

3) the damage the dogs are doing is correct based on the information available about them. However, they appear to be doing less damage than they should be in-game. They're doing about 31-32% below expected damage in-game, I pinged a QA friend but no reply yet.

**Comment by Vanishoxyact** [comment] 2016-10-29 10:10
1) Great news to hear this has been fixed, good work.

2) I believe you may have misunderstood the issue slightly. If I understand what your saying, you would expect the imps spawned from dogs to cast at least as often as those spawned by hog (since they begin casting instantly). If you take a look at that log, you will see that these imps actually cast significantly less often, which seems to be due to them not chain casting but waiting between casts. This causes them to only cast around 7 times in their lifespan comparing to the 12 times of imps summoned by hog (with my current haste).

3) Interesting, we will have to see what they say.

**Comment by Pestitschek** [comment] 2016-10-30 16:15
Confirmed number 2).
Hog imps casted 12 to 13 times. Hog from dreadstalker casted 7 times (constant). It is almost equivalent as if they they have a permanent 1.5s gcd - unaffected by haste.

**Comment by nasirabtw** [comment] 2016-10-30 18:00
Yea ok the issue is they aren't scaling with haste. I reported it to QA so hopefully it gets nuked soon. I'll throw it in simc when I have time.

**Comment by Kyrosiris** [comment] 2016-11-10 22:00
It would appear that the issue with Improved Dreadstalkers-spawned Wild Imps having a fixed cast time is resolved as of the November 8th hotfix. I've got a snag of a combat log - tried my best to keep polluting data out of it, but here's a direct zoom-in of Summon Dreadstalkers-spawned Wild Imps Firebolt; the second activity chunk was with Demonic Empowerment active.

https://www.warcraftlogs.com/reports/w2QYV7NnvZAkP4a8/#type=casts&source=7&start=72883&end=105616

I can also provide raw logs (or hell, recount screenshots of cast instances) if that doesn't work. :)

**Comment by nasirabtw** [comment] 2016-11-11 07:01
Never got around to coding the improved dreadstalkers bug in the first place. Looks like everything here has been resolved. Closing the issue.

**Closed as completed by nasirabtw** 2016-11-11 07:01 UTC
Labels: Fixed
