### ISSUE TITLE
unable to sim

### ISSUE THREAD

**Issue by Eradoryn** [simulationcraft/simc#4646] opened 2018-12-17 20:18 UTC
unable to sim my character when importing profile by copy paste. 

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Eradorin': Item 'inactive' Slot 'head': Cannot parse option from ',id=161404,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=353/21/85/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
dps_plot_stat=str,agi,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
dps_plot_points=20
dps_plot_step=150
dps_plot_target_error=0.5
dps_plot_iterations=0
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
demonhunter="Eradorin"
level=120
race=blood_elf
region=us
server=zuljin
role=attack
professions=alchemy=150/herbalism=150
talents=3211213
spec=havoc

head=,id=161404,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=353/21/85/13
neck=,id=158075,bonus_id=4936/4929/4930/1528,context=11,azerite_level=29
shoulder=,id=163432,bonus_id=5126/1562/4786,context=6,azerite_powers=352/459/14
back=,id=163360,bonus_id=5126/4802/1562/4786,context=6
chest=,id=157942,bonus_id=1547/5138/5380/4775,context=28,azerite_powers=196/459/15/13
wrist=,id=163309,bonus_id=5125/1557/4786,context=29
hands=,id=157880,enchant_id=5932,bonus_id=4803/4802/1557/4786,context=28
waist=,id=163439,bonus_id=5124/1532/4786,context=3
legs=,id=163298,bonus_id=5126/1562/4786,context=6
feet=,id=160624,bonus_id=4798/42/1482/4783,context=3
finger1=,id=162548,bonus_id=4780/1517/4786,context=16
finger2=,id=159460,bonus_id=4779/1512/4786,context=23
trinket1=,id=161462,bonus_id=5119/1497/4783,context=3
trinket2=,id=158155,bonus_id=4803/1527/4784,context=25
main_hand=,id=160681,bonus_id=4799/1492/4786,context=5
off_hand=,id=160110,bonus_id=4779/1512/4786,context=23

### Gear from Bags
#
# Finely-Tailored Green Holiday Hat (1)
# head=,id=139300,context=1
#
# Grubby Servant-Grabbers (310)
# hands=,id=159346,bonus_id=4777/1482/4785,context=1
#
# Bloodhex Grips of the Feverflare (266)
# hands=,id=154834,bonus_id=4796/1703,drop_level=120
#
# Blood Bog Waistband (335)
# waist=,id=157884,bonus_id=4803/4802/1527/4783,context=26
#
# Zandalari Band (325)
# finger1=,id=158151,bonus_id=4803/4802/1517/4785,context=26
#
# Mining Pick (4)
# main_hand=,id=2901,context=14

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=1

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-17 20:29
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-17 20:29 UTC
