### ISSUE TITLE
SimuilationCraft encountered an error

### ISSUE THREAD

**Issue by Selara60** [simulationcraft/simc#4235] opened 2018-01-15 15:59 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

I get an error when attempting to sim my fire mage - contents of the error message copied below:

# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'crucible' with value '1739:1782/0/1739'

## All options used for simulation:
``` ini
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
mage="Syrai"
level=110
race=human
region=us
server=anvilmar
role=spell
professions=tailoring=800/enchanting=775
talents=2132121
spec=fire
artifact=54:0:0:0:0:748:1:749:4:750:4:751:4:752:4:753:4:754:4:755:4:756:4:757:4:758:1:759:1:760:1:761:1:762:1:763:1:1340:1:1372:1:1533:4:1534:1:1535:1:1536:12:1640:1
crucible=1739:1782/0/1739

head=,id=146877,gem_id=130221,bonus_id=3394/1808/1562/3337
neck=,id=134376,enchant_id=5439,bonus_id=1825/1562/3337
shoulder=,id=146666,enchant_id=5440,gem_id=130220/130248/130221,bonus_id=3459/3630
back=,id=152400
chest=,id=133977,bonus_id=1811/3630
wrist=,id=134310,bonus_id=3394/1562/3337
hands=,id=148492,bonus_id=3573/1707/1542/3528
waist=,id=149856,bonus_id=3573/1709/1572/3528
legs=,id=152352,bonus_id=3614/1477/3336
feet=,id=146987,bonus_id=3561/1482/3528
finger1=,id=144478,enchant_id=5423,bonus_id=3573/1572/3336
finger2=,id=148564,enchant_id=5423,bonus_id=3573/1557/3337
trinket1=,id=153172,bonus_id=3573/1507/3336
trinket2=,id=137398,gem_id=130221,bonus_id=3573/1808/1562/3528
main_hand=,id=128820,gem_id=151009/0/151009,bonus_id=730,relic_id=3395:3169:3336/0/3395:3169:3336
off_hand=,id=133959

### Gear from Bags
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by vituscze** [comment] 2018-01-19 16:17
Duplicate of #4000

**Closed as completed by vituscze** 2018-01-19 16:17 UTC
