### ISSUE TITLE
Bug DK Frost

### ISSUE THREAD

**Issue by S4nt04K** [simulationcraft/simc#5264] opened 2020-09-12 20:24 UTC
good evening, i'll just post the bug report, maybe someone will figure it out

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Setup failure: Unable to open output file 'C:\Users\User\Desktop\simc-830-01-win64\simc_report.txt'.

## All options used for simulation:
``` ini
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
### Using QT 5.12.6 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=500
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers,wdps,leech
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Kaîden - Frost - 2020-09-12 22:12 - EU/Eredar
# SimC Addon 1.12.5
# Requires SimulationCraft 820-01 or newer

deathknight="Kaîden"
level=68
race=kul_tiran
region=eu
server=eredar
role=attack
professions=blacksmithing=6/mining=6
talents=1132000
spec=frost

head=,id=35875,bonus_id=3686,drop_level=68,context=11
neck=,id=44375,bonus_id=4139/5569,drop_level=61,context=11
shoulder=,id=35843,bonus_id=3686,drop_level=67,context=11
back=,id=113685,bonus_id=4242/28,drop_level=61,context=1
chest=,id=35822,bonus_id=3686,drop_level=59,context=11
tabard=,id=45574,context=14
wrist=,id=35924,bonus_id=3686,drop_level=67,context=11
hands=,id=113692,bonus_id=4242/30,drop_level=63,context=1
waist=,id=112361,bonus_id=4242/29,drop_level=65,context=1
legs=,id=35848,bonus_id=3686/5545,drop_level=67,context=11
feet=,id=40755,bonus_id=4115,drop_level=65,context=11
finger1=,id=38218,bonus_id=4139,drop_level=61,context=11
finger2=,id=38672
trinket1=,id=37166,bonus_id=4131,drop_level=63,context=1
trinket2=,id=37723,bonus_id=4115,drop_level=64,context=1
main_hand=,id=35824,enchant_id=3368,bonus_id=3686,drop_level=59,context=11
off_hand=,id=174662,enchant_id=3370,context=11

### Gear from Bags
#
# Spitzhacke (4)
# main_hand=,id=2901,context=14

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by scamille** [comment] 2020-09-13 06:36
It looks like you do not have write permission to 'C:\Users\User\Desktop\simc-830-01-win64\simc_report.txt' 

Are you maybe opening SimulationCraft when logged in as a different user from the one you installed it on the Desktop, or is it from your own Desktop?

**Comment by S4nt04K** [comment] 2020-09-13 13:49
thanks for the answer, I only have my own desktop, I only have one profile on my PC

**Comment by S4nt04K** [comment] 2020-09-13 13:52
i believe that the program does not find all items and therefore gives an error 

SimulationCraft encountered an error!

Simulation runtime error:
BCP API: Player 'Kaîden' unable to download item id '35924' at slot wrists.
Player Kaîden unable to download item id '35924' from wowhead at slot wrists.Initializing: Actor 'Kaîden': Item 'inactive' Slot 'wrists': Cannot initialize data

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: BCP API: Player 'Kaîden' unable to download item id '35924' at slot wrists.
Player Kaîden unable to download item id '35924' from wowhead at slot wrists.Initializing: Actor 'Kaîden': Item 'inactive' Slot 'wrists': Cannot initialize data

## All options used for simulation:
``` ini
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
### Using QT 5.12.6 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=500
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers,wdps,leech
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Kaîden - Frost - 2020-09-13 15:49 - EU/Eredar
# SimC Addon 1.12.5
# Requires SimulationCraft 820-01 or newer

deathknight="Kaîden"
level=75
race=kul_tiran
region=eu
server=eredar
role=attack
professions=blacksmithing=6/mining=6
talents=1132100
spec=frost

head=,id=122245,bonus_id=582
neck=,id=113688,bonus_id=4242/39,drop_level=75,context=1
shoulder=,id=122388,bonus_id=5805
back=,id=122266,bonus_id=582
chest=,id=122381,bonus_id=582
tabard=,id=45574,context=14
wrist=,id=35924,bonus_id=3686,drop_level=67,context=11
hands=,id=113692,bonus_id=4242/30,drop_level=63,context=1
waist=,id=37088,bonus_id=4127,drop_level=69,context=1
legs=,id=122251,bonus_id=582
feet=,id=43174,bonus_id=4117,drop_level=73,context=11
finger1=,id=38218,bonus_id=4139,drop_level=61,context=11
finger2=,id=43178,bonus_id=4117,drop_level=73,context=11
trinket1=,id=122361
trinket2=,id=122530
main_hand=,id=122389
off_hand=,id=122389

### Gear from Bags
#
# Ewiger Talisman des glühenden Zorns (93)
# neck=,id=122667
#
# Eisige Panzerarmschienen (80)
# wrist=,id=33393,bonus_id=3841,drop_level=72,context=29
#
# Schnalle des gefallenen Halbgotts (91)
# waist=,id=43168,bonus_id=4117,drop_level=73,context=11
#
# Frostumhüllte Plattenbeinschützer des Feuersturms (91)
# legs=,id=112354,bonus_id=4242/20,drop_level=73,context=1
#
# Stiefel der Dominanz (89)
# feet=,id=39466,bonus_id=3690,drop_level=75,context=11
#
# Golemsabatons des Feuersturms (67)
# feet=,id=36380,bonus_id=1692/3840,drop_level=70,context=28
#
# Schienbeinschützer des uralten Bösen (95)
# feet=,id=37618,bonus_id=4111,drop_level=75,context=1
#
# Keleseths Siegelring (58)
# finger1=,id=38672
#
# Spitzhacke (4)
# main_hand=,id=2901,context=14

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by scamille** [comment] 2020-09-13 14:50
Ok that is a different error now.

As a warning beforehand, simulating a low level character is not fully supported and you might get wildly different results, depending on how well the class/spec you are trying to simulate supports low levels. In most cases at least the Action Priority List is in no way optimized for it.

@navv1234 The problem here is the download of https://www.wowhead.com/item=35924/arcanum-bound-bracers . What is our answer here why the download does not work from alternative item sources? (We probably do not have it in our local item database, otherwise I assume it would work )

**Comment by scamille** [comment] 2020-09-13 14:55
Please try again with the latest http://downloads.simulationcraft.org/?C=M;O=D simc-830-02-win64-2e438b4513.7z
Seems to be fixed for me.

**Comment by scamille** [comment] 2020-09-14 06:33
To add some more info to this:
- Item downloads from blizzard can sometimes fail sporadically
- Time walking gear is known for causing those failures
- The latest nightly seems to get it working for me, and in any case might handle it more gracefully.

**Comment by scamille** [comment] 2020-09-23 16:23
Closing as Duplicate of #5278

**Closed as completed by scamille** 2020-09-23 16:23 UTC
Labels: GUI, Item, LowLevel, Battle for Azeroth
