### ISSUE TITLE
Simulation Setup Error

### ISSUE THREAD

**Issue by Fokusrite** [simulationcraft/simc#4035] opened 2017-09-19 18:43 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Fokusrite** [comment] 2017-09-19 18:45
I keep getting this error no matter what gear i put on my mage. it started to happen couple of days ago. or even yesterday, can't be sure.

**Comment by Fokusrite** [comment] 2017-09-19 18:47
SimulationCraft encountered an error!

Simulation setup error:
Unknown option 'crucible' with value '1739:1780/1739/1739'

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'crucible' with value '1739:1780/1739/1739'

## All options used for simulation:
``` ini
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=0
override.bleeding=1
override.mortal_wounds=1
threads=6
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
mage="Kabel"
level=110
race=troll
region=eu
server=dentarg
role=spell
professions=herbalism=214/skinning=800
talents=2133121
spec=frost
artifact=53:0:0:0:0:783:1:784:4:785:4:786:4:787:4:788:4:789:4:790:4:791:4:792:4:793:1:794:1:795:1:796:1:797:1:798:1:1296:1:1373:1:1537:4:1538:1:1539:1:1540:10:1641:1
crucible=1739:1780/1739/1739

head=,id=147147,bonus_id=3564/1467/3528
neck=,id=149627,enchant_id=5439,bonus_id=3573/1572/3528
shoulder=,id=139129,bonus_id=1824/1552/3337
back=,id=152778,enchant_id=5436,bonus_id=1690/3629/1477/3336
chest=,id=134395,gem_id=130220,bonus_id=3573/1808/1572/3528
shirt=,id=89194
tabard=,id=45583
wrist=,id=134222,bonus_id=3573/1572/3528
hands=,id=137506,gem_id=130220,bonus_id=3415/1808/1557/3528
waist=,id=134171,bonus_id=3573/1587/3337
legs=,id=150986,bonus_id=3395/1547/3528
feet=,id=152774,bonus_id=1677/3629/1472/3528
finger1=,id=151642,enchant_id=5428,gem_id=130220,bonus_id=3459/3570
finger2=,id=134367,enchant_id=5428,bonus_id=3573/1572/3528
trinket1=,id=144259,bonus_id=1811/3570
trinket2=,id=134248,bonus_id=3573/607/1572/3528
main_hand=,id=128862,gem_id=147095/147077/151010,bonus_id=731,relic_id=3564:1482:3336/3564:1487:3337/3397:3174:3528

### Gear from Bags
#
# Azurelight Sage's Cap of the Peerless (880)
# head=,id=152770,bonus_id=1683/3629/1472/3528
#
# Firehawk Hood (378)
# head=,id=71287
#
# Mantle of the Arcane Tempest (885)
# shoulder=,id=147150,bonus_id=3564/1467/3528
#
# Firehawk Mantle (378)
# shoulder=,id=71290
#
# Drape of the Arcane Tempest (915)
# back=,id=147145,enchant_id=5436,bonus_id=3564/1497/3337
#
# Cloak of Coordination (60)
# back=,id=65274
#
# Soul-Stitched Robes (915)
# chest=,id=133611,bonus_id=3412/1567/3337
#
# Robes of the Arcane Tempest (885)
# chest=,id=147149,bonus_id=3564/1467/3528
#
# Firehawk Robes (378)
# chest=,id=71289
#
# Thunder Bluff Tabard (1)
# tabard=,id=45584
#
# Gloves of the Arcane Tempest (895)
# hands=,id=147146,bonus_id=3564/1477/3336
#
# Firehawk Gloves (378)
# hands=,id=71286
#
# Leggings of Countless Worlds (910)
# legs=,id=142151,bonus_id=3573/1522/3528
#
# Firehawk Leggings (378)
# legs=,id=71288
#
# Astonishingly Scarlet Slippers (880)
# feet=,id=142298,bonus_id=3410/1497/3336
#
# Arcane Singed Slippers (885)
# feet=,id=134352,bonus_id=1825/1547/3336
#
# Doomsinger Slippers (910)
# feet=,id=150984,bonus_id=3573/1572/3528
#
# Band of Rescinded Truths (910)
# finger1=,id=147194,bonus_id=3573/1492/3528
#
# Fierce Gladiator's Signet (910)
# finger1=,id=148072,bonus_id=3573/1808/1542/3528
#
# Theck's Emberseal (378)
# finger1=,id=71367
#
# Charm of the Rising Tide (885)
# trinket1=,id=147002,bonus_id=3564/42/1467/3528
#
# Fierce Combatant's Insignia of Dominance (910)
# trinket1=,id=149713,bonus_id=3573/1572/3528
#
# Unblemished Sigil of Argus (880)
# trinket1=,id=152781,bonus_id=3629/1472/3528
#
# Tome of Unraveling Sanity (895)
# trinket1=,id=147019,bonus_id=3564/1477/3528
#
# Spire of Scarlet Pain (378)
# main_hand=,id=71360
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```


DPS Ranking:
 854309 100.0%  Raid
 854309  100.0%  Kabel

HPS Ranking:
      0 100.0%  Raid

Player: Kabel troll mage frost 110
  DPS: 854308.9  DPS-Error=794.0/0.093%  DPS-Range=150879/17.7%  DPS-Convergence=67.0%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=64.5  RPS-Out=13194.4 RPS-In=13194.4  Resource=(mana) Waiting=0.0 ApM=50.9
  Talents: 2133121
  Artifact: 53:0:0:0:0:783:1:784:4:785:4:786:4:787:4:788:4:789:4:790:4:791:4:792:4:793:1:794:1:795:1:796:1:797:1:798:1:1296:1:1373:1:1537:4:1538:1:1539:1:1540:6:1641:1
  Core Stats:    strength=4876|4551(4551)  agility=6579|6254(6254)  stamina=62795|62795(39575)  intellect=50326|48620(46671)  spirit=1|1(1)  health=3767700|3767700  mana=1100000|1100000
  Generic Stats: mastery=52.58%|52.58%(6146)  versatility=10.58%|9.58%(4549)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=50326|48620(0)  hit=15.00%|15.00%(0)  crit=17.00%|17.00%(4801)  haste=20.07%|20.07%(7528)  speed=20.07%|20.07%  manareg=16500|16500(0)
  Attack Stats:  power=0|0(0)  hit=7.50%|7.50%(0)  crit=17.00%|17.00%(4801)  expertise=7.50%|7.50%(0)  haste=20.07%|20.07%(7528)  speed=20.07%|20.07%
  Defense Stats: armor=1940|1940(1940) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=0.00%|0.00%(0)  block=0.00%|0.00%(0) crit=0.00%|0.00%  versatility=5.29%|4.79%(4549)
  Priorities (actions.precombat):
    flask/food/augmentation/water_elemental/snapshot_stats/mirror_image/potion/frostbolt
  Priorities:
    call_action_list,name=variables/counterspell,if=target.debuff.casting.react
    ice_lance,if=variable.fof_react=0&prev_gcd.1.flurry
    time_warp,if=buff.bloodlust.down&(buff.exhaustion.down|equipped.shard_of_the_exodar)&(time=0|cooldown.icy_veins.remains<1|target.time_to_die<50)
    use_item,name=kiljaedens_burning_wish/call_action_list,name=movement
    call_action_list,name=cooldowns/call_action_list,name=aoe,if=active_enemies>=4
    call_action_list,name=single
  Priorities (actions.single):
    ice_nova,if=debuff.winters_chill.up/frozen_orb,if=set_bonus.tier20_2pc
    frostbolt,if=prev_off_gcd.water_jet
    water_jet,if=prev_gcd.1.frostbolt&buff.fingers_of_frost.stack<(2+artifact.icy_hand.enabled)&buff.brain_freeze.react=0
    ray_of_frost,if=buff.icy_veins.up|(cooldown.icy_veins.remains>action.ray_of_frost.cooldown&buff.rune_of_power.down)
    flurry,if=prev_gcd.1.ebonbolt|buff.brain_freeze.react&(!talent.glacial_spike.enabled&prev_gcd.1.frostbolt|talent.glacial_spike.enabled&(prev_gcd.1.glacial_spike|prev_gcd.1.frostbolt&(buff.icicles.stack<=3|cooldown.frozen_orb.remains<=10&set_bonus.tier20_2pc)))
    blizzard,if=cast_time=0&active_enemies>1&variable.fof_react<3
    frost_bomb,if=debuff.frost_bomb.remains<action.ice_lance.travel_time&variable.fof_react>0
    ice_lance,if=variable.fof_react>0&cooldown.icy_veins.remains>10|variable.fof_react>2
    ebonbolt/frozen_orb/ice_nova/comet_storm
    blizzard,if=active_enemies>2|active_enemies>1&!(talent.glacial_spike.enabled&talent.splitting_ice.enabled)|(buff.zannesu_journey.stack=5&buff.zannesu_journey.remains>cast_time)
    frostbolt,if=buff.frozen_mass.remains>execute_time+action.glacial_spike.execute_time+action.glacial_spike.travel_time&buff.brain_freeze.react=0&talent.glacial_spike.enabled
    glacial_spike,if=cooldown.frozen_orb.remains>10|!set_bonus.tier20_2pc/frostbolt
    blizzard,if=cast_time=0/ice_lance
  Priorities (actions.cooldowns):
    rune_of_power,if=cooldown.icy_veins.remains<cast_time|charges_fractional>1.9&cooldown.icy_veins.remains>10|buff.icy_veins.up|target.time_to_die.remains+5<charges_fractional*10
    potion,if=cooldown.icy_veins.remains<1/icy_veins,if=buff.icy_veins.down
    mirror_image/use_items/blood_fury/berserking/arcane_torrent
  Actions:
    berserking                Count=  2.1|180.54sec  DPE=      0| 0%  DPET=      0  DPR=  0.0  pDPS=     0
    ebonbolt                  Count=  6.7| 48.61sec  DPE=2832298| 5%  DPET=1302265  DPR=  0.0  pDPS= 42413  Miss=0.00%
    flurry                    Count= 34.6|  8.70sec  DPE=1590784| 0%  DPET=1492755  DPR=144.6  pDPS=     0
    flurry_bolt               Count=103.6|  2.86sec  DPE= 531956|22%  DPET=      0  DPR=  0.0  pDPS=185325  Miss=0.00%
    frostbolt                 Count=123.4|  2.38sec  DPE= 666247|17%  DPET= 477433  DPR= 30.0  pDPS=148960  Miss=0.00%
    frozen_orb                Count=  5.5| 60.55sec  DPE= 927103| 0%  DPET= 896213  DPR= 84.3  pDPS=     0
    frozen_orb_bolt           Count=106.4|  2.64sec  DPE=  47616| 2%  DPET=      0  DPR=  0.0  pDPS= 16981  Miss=0.00%
    glacial_eruption          Count=  6.5| 48.62sec  DPE= 953418| 2%  DPET=      0  DPR=  0.0  pDPS= 20906  Miss=0.00%
    ice_lance                 Count= 65.8|  4.54sec  DPE=1280430|33%  DPET=1209560  DPR=116.4  pDPS=282912  Miss=0.00%
    icicle                    Count=141.5|  2.11sec  DPE= 235624|13%  DPET=      0  DPR=  0.0  pDPS=111763  Miss=0.00%
    icy_veins                 Count=  3.3|110.16sec  DPE=      0| 0%  DPET=      0  DPR=  0.0  pDPS=     0
    insidious_corruption      Count=  5.5| 60.53sec  DPE= 678697| 1%  DPET=      0  DPR=  0.0  pDPS= 12452  TickCount=52  MissTick=0.0%  Tick=58663|3002|66290  CritTick=135882|2415|159096|17.0%  UpTime=21.3%
    kiljaedens_burning_wish   Count=  4.5| 75.59sec  DPE=1175904| 2%  DPET=      0  DPR=  0.0  pDPS= 17689  Miss=0.00%
    potion                    Count=  2.0|  0.00sec  DPE=      0| 0%  DPET=      0  DPR=  0.0  pDPS=     0
    unstable_magic_explosion  Count= 24.8| 11.62sec  DPE= 178908| 2%  DPET=      0  DPR=  0.0  pDPS= 14907  Miss=0.00%
  Constant Buffs: defiled_augmentation/flask_of_the_whispered_pact/incanters_flow/lemon_herb_filet
  Dynamic Buffs:
    berserking                    : start= 2.1 refresh=  0.0 interval=180.7 trigger=180.5 uptime= 6.93%  benefit=10%
    bloodlust                     : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.64%  benefit=14%
    brain_freeze                  : start=34.9 refresh=  0.4 interval=  8.6 trigger=  8.6 uptime=23.74%
    chain_reaction                : start=16.0 refresh= 43.7 interval= 18.7 trigger=  4.9 uptime=77.32%  benefit=77%
    chilled_to_the_core           : start= 3.3 refresh=  0.0 interval=107.1 trigger=110.0 uptime=21.86%  benefit=22%
    concordance_of_the_legionfall : start= 8.4 refresh=  3.0 interval= 35.1 trigger= 25.0 uptime=32.56%  benefit=33%
    extracted_sanity              : start= 5.5 refresh=  0.0 interval= 60.2 trigger= 60.2 uptime=20.47%  benefit=20%
    fingers_of_frost              : start=30.2 refresh= 14.1 interval=  9.9 trigger=  6.7 uptime=21.44%  benefit=66%
    freezing_rain                 : start= 5.5 refresh=  0.0 interval= 60.6 trigger= 60.6 uptime=18.00%  benefit=18%
    frozen_mass                   : start= 5.5 refresh=  0.0 interval= 60.6 trigger= 60.6 uptime=17.92%  benefit=18%
    icicles                       : start=34.2 refresh=108.9 interval=  8.8 trigger=  2.1 uptime=72.76%  benefit=73%
    icy_veins                     : start= 3.3 refresh=  0.0 interval=107.1 trigger=110.0 uptime=42.60%  benefit=43%
    potion_of_prolonged_power     : start= 2.0 refresh=  0.0 interval=102.7 trigger=  0.0 uptime=40.23%  benefit=40%
  Benefits:
     20.3% : Incanter's Flow Incanter's Flow 1
     19.6% : Incanter's Flow Incanter's Flow 2
     20.2% : Incanter's Flow Incanter's Flow 3
     19.6% : Incanter's Flow Incanter's Flow 4
     20.3% : Incanter's Flow Incanter's Flow 5
     47.1% : Fingers of Frost from Frostbolt
     12.5% : Fingers of Frost from Frozen Orb Initial Impact
     40.4% : Fingers of Frost from Frozen Orb Tick
  Up-Times:
      7.3% : Mana Cap                      
  Gains:
    3930501.6 : mp5_regen (mana)  (overflow=20.3%)
  Scale Factors:
    Weights :  Int=15.97(0.86)  SP=0.00(0.00)  Crit=21.31(0.87)  Haste=17.06(0.87)  Mastery=11.57(0.86)  Vers=15.73(0.87)
    Wowhead : 
  Waiting: 0.00%

 *** Targets *** 


Target: Fluffy_Pillow humanoid enemy unknown 113
  DPS: 0.0  DPS-Error=0.0/0.000%  DPS-Range=0/0.0%  DPS-Convergence=0.0%
  HPS: 0.0 HPS-Error=0.0/0.0%
  DPR=0.0  RPS-Out=849502.9 RPS-In=849502.9  Resource=(health) Waiting=0.0 ApM=0.0
  Talents: 0000000
  Core Stats:    strength=0|0(0)  agility=0|0(0)  stamina=0|0(0)  intellect=0|0(0)  spirit=0|0(0)  health=0|204064720  mana=0|0
  Generic Stats: mastery=0.00%|0.00%(0)  versatility=0.00%|0.00%(0)  leech=0.00%|0.00%(0)  runspeed=7.00%|7.00%(0)
  Spell Stats:   power=0|0(0)  hit=0.00%|0.00%(0)  crit=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%  manareg=0|0(0)
  Attack Stats:  power=0|0(0)  hit=0.00%|0.00%(0)  crit=5.00%|5.00%(0)  expertise=0.00%|0.00%(0)  haste=0.00%|0.00%(0)  speed=0.00%|0.00%
  Defense Stats: armor=3474|3474(3474) miss=3.00%|3.00%  dodge=3.00%|3.00%(0)  parry=3.00%|3.00%(0)  block=3.00%|3.00%(0) crit=0.00%|0.00%  versatility=0.00%|0.00%(0)
  Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.89%  benefit=11%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.11%  benefit=11%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.95%  benefit=11%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.30%  benefit=11%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.55%  benefit=11%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.65%  benefit=10%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.47%  benefit=11%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.87%  benefit=11%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 8.25%  benefit= 8%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 4.97%  benefit= 5%
    winters_chill            : start=34.6 refresh= 69.0 interval=  8.7 trigger=  2.9 uptime=18.01%  benefit=18%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Waiting:
    All players active 100% of the time.

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 10005 (1675, 1688, 1680, 1650, 1642, 1670)
  TotalEvents   = 23744713
  MaxEventQueue = 42
  TargetHealth  = 204064721
  SimSeconds    = 2992161
  CpuSeconds    = 18.923
  WallSeconds   = 3.246
  SpeedUp       = 158124
  EndTime       = 2017-09-11 09:15:38+0200 (1505114138)


Scale Factors:
  Kabel  Int=15.97(0.86)  SP=0.00(0.00)  Crit=21.31(0.87)  Haste=17.06(0.87)  Mastery=11.57(0.86)  Vers=15.73(0.87)

**Comment by seriallos** [comment] 2017-09-19 18:48
Duplicate of #4000 

Follow the instructions there to resolve the issue

**Closed as completed by seriallos** 2017-09-19 18:48 UTC

**Comment by Fokusrite** [comment] 2017-09-19 18:50
Thanks.

**Comment by Fokusrite** [comment] 2017-09-19 18:55
:) Will let you know if it works. downloading at 10KB/s now lol. it was never this slow.

**Comment by Fokusrite** [comment] 2017-09-19 19:17
Works. Thanks again.

**Comment by Fokusrite** [comment] 2017-09-19 19:22
Guys, just download newest simulationcraft version on their site and it should work good again.
