### ISSUE TITLE
Lady and The Child Moonfire spam glitch

### ISSUE THREAD

**Issue by CidiusV** [simulationcraft/simc#3595] opened 2017-02-26 19:00 UTC
First time here so let me know if there's anything else I need to include or if this was already resolved and I'm just using an out of date SimC.

The Version 715-02

Situation: Simulating AoE on my Balance druid. Equipping 'Lady and the Child' and simulating a multitarget fight appears to cause the program to spend nearly all of its time casting moonfire. This did not occur on my single target simulation.

I put on my AoE gear for my toon (Lunaidus aman'thul) to simulate 3 target dps with my new legendary. "Lady and the Child". important talent options were: Starlord, soul of the forest, shooting stars, stellar drift.
Options in SimC were default aside from some basic stat scaling and I had 3 targets enabled. My dps came up as under 400k (my dps prior to equipping the legendary was 1.2mil). I looked at the cast log and it was SPAMMING moonfire on the third target. It had Got all prepped as usual and then it just...spammed the fuck out of moonfire outside of casting moon abilities. It also did the occasional other cast but 90% of time spent was casting moonfire.

**Comment by Abso1** [comment] 2017-03-03 00:35
Confirmed, same here. My char is abso from tyrande.

**Comment by Collisionc** [comment] 2017-03-12 06:29
Can you upload the profile you were using? (just copy/paste the entire simulate tab) I'm having trouble reproducing this, and it's probably because you're not wearing the same gear in your armory at the moment.

**Comment by Abso1** [comment] 2017-03-13 00:01
druid="Abso"
origin="https://eu.api.battle.net/wow/character/tyrande/abso/advanced"
thumbnail="http://eu.battle.net/static-render/eu/tyrande/27/38595867-avatar.jpg"
level=110
race=night_elf
timeofday=day
role=spell
position=back
professions=tailoring=800/engineering=800
talents=http://eu.battle.net/wow/en/tool/talent-calculator#Ua!2101121
artifact=59:0:0:0:0:1034:3:1035:3:1036:3:1037:3:1038:3:1039:3:1040:3:1041:3:1042:3:1043:1:1044:1:1045:1:1046:1:1047:1:1048:1:1049:1:1294:1:1364:20
spec=balance

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=flask_of_the_whispered_pact
actions.precombat+=/food,type=azshari_salad
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/moonkin_form
actions.precombat+=/blessing_of_elune
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/new_moon

# Executed every time the actor is available.
actions=potion,name=deadly_grace,if=buff.celestial_alignment.up|buff.incarnation.up
actions+=/blessing_of_elune,if=active_enemies<=2&talent.blessing_of_the_ancients.enabled&buff.blessing_of_elune.down
actions+=/blessing_of_elune,if=active_enemies>=3&talent.blessing_of_the_ancients.enabled&buff.blessing_of_anshe.down
actions+=/blood_fury,if=buff.celestial_alignment.up|buff.incarnation.up
actions+=/berserking,if=buff.celestial_alignment.up|buff.incarnation.up
actions+=/arcane_torrent,if=buff.celestial_alignment.up|buff.incarnation.up
actions+=/call_action_list,name=fury_of_elune,if=talent.fury_of_elune.enabled&cooldown.fury_of_elue.remains<target.time_to_die
actions+=/call_action_list,name=ed,if=equipped.the_emerald_dreamcatcher&active_enemies<=2
actions+=/new_moon,if=(charges=2&recharge_time<5)|charges=3
actions+=/half_moon,if=(charges=2&recharge_time<5)|charges=3|(target.time_to_die<15&charges=2)
actions+=/full_moon,if=(charges=2&recharge_time<5)|charges=3|target.time_to_die<15
actions+=/stellar_flare,cycle_targets=1,max_cycle_targets=4,if=active_enemies<4&remains<7.2&astral_power>=15
actions+=/moonfire,cycle_targets=1,if=(talent.natures_balance.enabled&remains<3)|(remains<6.6&!talent.natures_balance.enabled)
actions+=/sunfire,if=(talent.natures_balance.enabled&remains<3)|(remains<5.4&!talent.natures_balance.enabled)
actions+=/astral_communion,if=astral_power.deficit>=75
actions+=/incarnation,if=astral_power>=40
actions+=/celestial_alignment,if=astral_power>=40
actions+=/starfall,if=buff.oneths_overconfidence.up
actions+=/solar_wrath,if=buff.solar_empowerment.stack=3
actions+=/lunar_strike,if=buff.lunar_empowerment.stack=3
actions+=/call_action_list,name=celestial_alignment_phase,if=buff.celestial_alignment.up|buff.incarnation.up
actions+=/call_action_list,name=single_target

actions.celestial_alignment_phase=starfall,if=((active_enemies>=2&talent.stellar_drift.enabled)|active_enemies>=3)
actions.celestial_alignment_phase+=/starsurge,if=active_enemies<=2
actions.celestial_alignment_phase+=/warrior_of_elune
actions.celestial_alignment_phase+=/lunar_strike,if=buff.warrior_of_elune.up
actions.celestial_alignment_phase+=/solar_wrath,if=buff.solar_empowerment.up
actions.celestial_alignment_phase+=/lunar_strike,if=buff.lunar_empowerment.up
actions.celestial_alignment_phase+=/solar_wrath,if=talent.natures_balance.enabled&dot.sunfire_dmg.remains<5&cast_time<dot.sunfire_dmg.remains
actions.celestial_alignment_phase+=/lunar_strike,if=(talent.natures_balance.enabled&dot.moonfire_dmg.remains<5&cast_time<dot.moonfire_dmg.remains)|active_enemies>=2
actions.celestial_alignment_phase+=/solar_wrath

actions.ed=astral_communion,if=astral_power.deficit>=75&buff.the_emerald_dreamcatcher.up
actions.ed+=/incarnation,if=astral_power>=85&!buff.the_emerald_dreamcatcher.up|buff.bloodlust.up
actions.ed+=/celestial_alignment,if=astral_power>=85&!buff.the_emerald_dreamcatcher.up
actions.ed+=/starsurge,if=(buff.celestial_alignment.up&buff.celestial_alignment.remains<(10))|(buff.incarnation.up&buff.incarnation.remains<(3*execute_time)&astral_power>78)|(buff.incarnation.up&buff.incarnation.remains<(2*execute_time)&astral_power>52)|(buff.incarnation.up&buff.incarnation.remains<execute_time&astral_power>26)
actions.ed+=/stellar_flare,cycle_targets=1,max_cycle_targets=4,if=active_enemies<4&remains<7.2&astral_power>=15
actions.ed+=/moonfire,if=((talent.natures_balance.enabled&remains<3)|(remains<6.6&!talent.natures_balance.enabled))&(buff.the_emerald_dreamcatcher.remains>gcd.max|!buff.the_emerald_dreamcatcher.up)
actions.ed+=/sunfire,if=((talent.natures_balance.enabled&remains<3)|(remains<5.4&!talent.natures_balance.enabled))&(buff.the_emerald_dreamcatcher.remains>gcd.max|!buff.the_emerald_dreamcatcher.up)
actions.ed+=/starfall,if=buff.oneths_overconfidence.up&buff.the_emerald_dreamcatcher.remains>execute_time&remains<2
actions.ed+=/half_moon,if=astral_power<=80&buff.the_emerald_dreamcatcher.remains>execute_time&astral_power>=6
actions.ed+=/full_moon,if=astral_power<=60&buff.the_emerald_dreamcatcher.remains>execute_time
actions.ed+=/solar_wrath,if=buff.solar_empowerment.stack>1&buff.the_emerald_dreamcatcher.remains>2*execute_time&astral_power>=6&(dot.moonfire.remains>5|(dot.sunfire.remains<5.4&dot.moonfire.remains>6.6))&(!(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=90|(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=85)
actions.ed+=/lunar_strike,if=buff.lunar_empowerment.up&buff.the_emerald_dreamcatcher.remains>execute_time&astral_power>=11&(!(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=85|(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=77.5)
actions.ed+=/solar_wrath,if=buff.solar_empowerment.up&buff.the_emerald_dreamcatcher.remains>execute_time&astral_power>=16&(!(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=90|(buff.celestial_alignment.up|buff.incarnation.up)&astral_power<=85)
actions.ed+=/starsurge,if=(buff.the_emerald_dreamcatcher.up&buff.the_emerald_dreamcatcher.remains<gcd.max)|astral_power>90|((buff.celestial_alignment.up|buff.incarnation.up)&astral_power>=85)|(buff.the_emerald_dreamcatcher.up&astral_power>=77.5&(buff.celestial_alignment.up|buff.incarnation.up))
actions.ed+=/starfall,if=buff.oneths_overconfidence.up&remains<2
actions.ed+=/new_moon,if=astral_power<=90
actions.ed+=/half_moon,if=astral_power<=80
actions.ed+=/full_moon,if=astral_power<=60&((cooldown.incarnation.remains>65&cooldown.full_moon.charges>0)|(cooldown.incarnation.remains>50&cooldown.full_moon.charges>1)|(cooldown.incarnation.remains>25&cooldown.full_moon.charges>2))
actions.ed+=/solar_wrath,if=buff.solar_empowerment.up
actions.ed+=/lunar_strike,if=buff.lunar_empowerment.up
actions.ed+=/solar_wrath

actions.fury_of_elune=incarnation,if=astral_power>=95&cooldown.fury_of_elune.remains<=gcd
actions.fury_of_elune+=/fury_of_elune,if=astral_power>=95
actions.fury_of_elune+=/new_moon,if=((charges=2&recharge_time<5)|charges=3)&&(buff.fury_of_elune_up.up|(cooldown.fury_of_elune.remains>gcd*3&astral_power<=90))
actions.fury_of_elune+=/half_moon,if=((charges=2&recharge_time<5)|charges=3)&&(buff.fury_of_elune_up.up|(cooldown.fury_of_elune.remains>gcd*3&astral_power<=80))
actions.fury_of_elune+=/full_moon,if=((charges=2&recharge_time<5)|charges=3)&&(buff.fury_of_elune_up.up|(cooldown.fury_of_elune.remains>gcd*3&astral_power<=60))
actions.fury_of_elune+=/astral_communion,if=buff.fury_of_elune_up.up&astral_power<=25
actions.fury_of_elune+=/warrior_of_elune,if=buff.fury_of_elune_up.up|(cooldown.fury_of_elune.remains>=35&buff.lunar_empowerment.up)
actions.fury_of_elune+=/lunar_strike,if=buff.warrior_of_elune.up&(astral_power<=90|(astral_power<=85&buff.incarnation.up))
actions.fury_of_elune+=/new_moon,if=astral_power<=90&buff.fury_of_elune_up.up
actions.fury_of_elune+=/half_moon,if=astral_power<=80&buff.fury_of_elune_up.up&astral_power>cast_time*12
actions.fury_of_elune+=/full_moon,if=astral_power<=60&buff.fury_of_elune_up.up&astral_power>cast_time*12
actions.fury_of_elune+=/moonfire,if=buff.fury_of_elune_up.down&remains<=6.6
actions.fury_of_elune+=/sunfire,if=buff.fury_of_elune_up.down&remains<5.4
actions.fury_of_elune+=/stellar_flare,if=remains<7.2&active_enemies=1
actions.fury_of_elune+=/starfall,if=(active_enemies>=2&talent.stellar_flare.enabled|active_enemies>=3)&buff.fury_of_elune_up.down&cooldown.fury_of_elune.remains>10
actions.fury_of_elune+=/starsurge,if=active_enemies<=2&buff.fury_of_elune_up.down&cooldown.fury_of_elune.remains>7
actions.fury_of_elune+=/starsurge,if=buff.fury_of_elune_up.down&((astral_power>=92&cooldown.fury_of_elune.remains>gcd*3)|(cooldown.warrior_of_elune.remains<=5&cooldown.fury_of_elune.remains>=35&buff.lunar_empowerment.stack<2))
actions.fury_of_elune+=/solar_wrath,if=buff.solar_empowerment.up
actions.fury_of_elune+=/lunar_strike,if=buff.lunar_empowerment.stack=3|(buff.lunar_empowerment.remains<5&buff.lunar_empowerment.up)|active_enemies>=2
actions.fury_of_elune+=/solar_wrath

actions.single_target=new_moon,if=astral_power<=90
actions.single_target+=/half_moon,if=astral_power<=80
actions.single_target+=/full_moon,if=astral_power<=60
actions.single_target+=/starfall,if=((active_enemies>=2&talent.stellar_drift.enabled)|active_enemies>=3)
actions.single_target+=/starsurge,if=active_enemies<=2
actions.single_target+=/warrior_of_elune
actions.single_target+=/lunar_strike,if=buff.warrior_of_elune.up
actions.single_target+=/solar_wrath,if=buff.solar_empowerment.up
actions.single_target+=/lunar_strike,if=buff.lunar_empowerment.up
actions.single_target+=/solar_wrath,if=talent.natures_balance.enabled&dot.sunfire_dmg.remains<5&cast_time<dot.sunfire_dmg.remains
actions.single_target+=/lunar_strike,if=(talent.natures_balance.enabled&dot.moonfire_dmg.remains<5&cast_time<dot.moonfire_dmg.remains)|active_enemies>=2
actions.single_target+=/solar_wrath

head=hood_of_the_astral_warden,id=138330,bonus_id=3516/1487/1813
neck=radiant_string_of_scorpid_eyes,id=140898,bonus_id=3445/1502/3336,enchant=mark_of_the_claw
shoulders=lady_and_the_child,id=144295,bonus_id=3529/3530
back=cloak_of_the_astral_warden,id=138366,bonus_id=3516/1507/3337,enchant=200int
chest=robe_of_the_astral_warden,id=138324,bonus_id=3516/1507/3337
wrists=oneths_intuition,id=137092,bonus_id=3458/3455
hands=gloves_of_the_astral_warden,id=138327,bonus_id=3516/1487/1813
waist=blightbile_waistband,id=137435,bonus_id=3536/1808/1552/3337,gems=150haste
legs=repulsive_leathery_pants,id=139203,bonus_id=1806/1512/3336
feet=stutterstep_treads,id=140860,bonus_id=3444/1497/3337
finger1=mindrend_band,id=138220,bonus_id=1806/1517/3337,enchant=200haste
finger2=ring_of_the_scoured_clan,id=140897,bonus_id=3517/1497/3336,enchant=200haste
trinket1=erratic_metronome,id=140792,bonus_id=3444/1492/3336
trinket2=whispers_in_the_dark,id=140809,bonus_id=3517/1492/1813
main_hand=scythe_of_elune,id=128858,bonus_id=722,gem_id=140813/140839/140827/0,relic_id=3516:1487:1813/3516:1487:1813/3445:1502:3336/0

# Gear Summary
# gear_ilvl=905.27
# gear_stamina=34204
# gear_intellect=37404
# gear_crit_rating=5367
# gear_haste_rating=8261
# gear_mastery_rating=7531
# gear_versatility_rating=2015
# gear_armor=2445
# set_bonus=tier19_2pc=1
# set_bonus=tier19_4pc=1

**Comment by Abso1** [comment] 2017-03-13 00:02
Num enemies was set to 3

**Comment by Abso1** [comment] 2017-03-13 00:04
rest of options was set Default.

**Comment by Abso1** [comment] 2017-03-13 00:07
thanks in advance :)

**Comment by navv1234** [comment] 2017-07-12 14:19
This seems to have been resolved. Closing.

**Closed as completed by navv1234** 2017-07-12 14:19 UTC
