### ISSUE TITLE
Simulation runtime error:

### ISSUE THREAD

**Issue by Smoothz624** [simulationcraft/simc#4636] opened 2018-12-15 23:52 UTC
I encounter this error when I try to sim my DK I'm 8.1 Live Tried updating both addon and App

> SimulationCraft encountered an error!
> 
> Simulation runtime error:
> Initializing: Actor 'Cmooth': Item 'inactive' Slot 'head': Cannot parse option from ',id=161396,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=194/21/85/13': Unexpected parameter 'context'.
> 
> If you think this is a bug, please open a ticket, copying the detailed text below.
> It contains all the input options of the last simulation and helps us reproduce the issue.
> 
> # SimulationCraft encountered an error!
> * Category: Simulation runtime error
> * Error: Initializing: Actor 'Cmooth': Item 'inactive' Slot 'head': Cannot parse option from ',id=161396,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=194/21/85/13': Unexpected parameter 'context'.
> 
> ## All options used for simulation:
> ``` ini
> ### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
> ### Using QT 5.10.1 with WebEngine ###
> 
> ### Begin GUI options ###
> item_db_source=local/bcpapi/wowhead/bfahead
> target_error=0
> iterations=25000
> default_world_lag=0.1
> max_time=300
> vary_combat_length=0.2
> fight_style=Patchwerk
> show_etmi=1
> tmi_window_global=6
> target_level+=3
> target_race=Humanoid
> optimal_raid=0
> override.bloodlust=0
> override.arcane_intellect=0
> override.power_word_fortitude=0
> override.battle_shout=0
> override.bleeding=0
> override.mortal_wounds=0
> override.chaos_brand=0
> override.mystic_touch=0
> threads=4
> process_priority=Normal
> calculate_scale_factors=1
> scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
> scale_over=DPS
> dps_plot_stat=str,agi,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor
> dps_plot_points=20
> dps_plot_step=150
> dps_plot_target_error=0.5
> dps_plot_iterations=0
> statistics_level=1
> ### End GUI options ###
> ### Begin simulateText ###
> # Profile will be downloaded into a new tab.
> #
> # Clicking Simulate will create a simc_gui.simc profile for review.
> # SimC Addon 1.10.8
> deathknight="Cmooth"
> level=120
> race=orc
> region=us
> server=tichondrius
> role=attack
> professions=alchemy=32/herbalism=108
> talents=2233312
> spec=unholy
> 
> head=,id=161396,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=194/21/85/13
> neck=,id=158075,bonus_id=4933/4936/4929/1532,context=11,azerite_level=31
> shoulder=,id=157964,enchant_id=5440,bonus_id=1547/5140/5379/4775,context=28,azerite_powers=482/31/85/13
> back=,id=155884,gem_id=154127,bonus_id=5007/4802/1532/4786,context=16
> chest=,id=161634,bonus_id=5450/5128/1547/4786/5395/4775,context=25,azerite_powers=199/459/465/13
> shirt=,id=3428,context=14
> tabard=,id=69210,context=14
> wrist=,id=163307,bonus_id=5126/1587/4784,context=6
> hands=,id=155890,enchant_id=5932,bonus_id=5007/4802/1537/4783,context=16
> waist=,id=161765,bonus_id=5065/5128/1547/4786,context=56
> legs=,id=163455,bonus_id=5125/4802/1562/4783,context=29
> feet=,id=161371,bonus_id=4798/40/1477/4786,context=3
> finger1=,id=158314,enchant_id=5939,bonus_id=5002/1532/4783,context=35
> finger2=,id=161359,enchant_id=5939,bonus_id=4798/1477/4786,context=3
> trinket1=,id=161376,bonus_id=4798/42/1477/4786,context=3
> trinket2=,id=161419,bonus_id=4798/1477/4786,context=3
> main_hand=,id=163967,enchant_id=3368,gem_id=153707,bonus_id=40/4802/1472/4786,context=54
> 
> ### Gear from Bags
> #
> # Petrified Ironbark Crown (390)
> # head=,id=166696,bonus_id=5478/1502/4786/5402/4775,context=3,azerite_powers=244/31/14/13
> #
> # Weather-Beaten Fishing Hat (10)
> # head=,id=33820,context=11
> #
> # Wrap of Unity (35)
> # back=,id=63207,context=14
> #
> # Shroud of Cooperation (35)
> # back=,id=63353,context=14
> #
> # Cloak of Coordination (58)
> # back=,id=65274,context=14
> #
> # Honorbound Centurion's Long Cloak (370)
> # back=,id=163368,bonus_id=5126/1562/4786,context=6
> #
> # Breastplate of Rezan's Bladeguard (325)
> # chest=,id=157926,bonus_id=1517/4785/5389,context=27,azerite_powers=
> #
> # Bilgewater Cartel Tabard (1)
> # tabard=,id=64884,context=14
> #
> # Orgrimmar Tabard (1)
> # tabard=,id=45581,context=14
> #
> # Darkspear Tabard (1)
> # tabard=,id=45582,context=14
> #
> # Dread Aspirant's Plate Armguards (330)
> # wrist=,id=162960,bonus_id=1522/4785,context=47
> #
> # Sandswept Legionnaire's Legplates (355)
> # legs=,id=161408,bonus_id=4798/1477/4786,context=3
> #
> # Lord Waycrest's Signet (350)
> # finger1=,id=158362,bonus_id=5002/1522/4786,context=16
> #
> # Glompmaw's Ring (273)
> # finger1=,id=160985,bonus_id=4776,drop_level=112,context=17
> #
> # Siren's Alchemist Stone (225)
> # trinket1=,id=152637,bonus_id=4927,context=13
> #
> # Zem'lan Hacker (330)
> # main_hand=,id=158109,bonus_id=4803/1522/4785,context=27
> #
> # Strong Fishing Pole (10)
> # main_hand=,id=6365,context=14
> #
> # Zem'lan Hacker (325)
> # main_hand=,id=158109,bonus_id=4803/1517/4785,context=26
> 
> # Stacks of reorigination array based on hidden quest completion
> # bfa.reorigination_array_stacks=3
> 
> ### End simulateText ###
> desired_targets=1
> ### Begin overrides ###
> # User-specified persistent global and player parameters will be set here.
> 
> ### End overrides ###
> ### Begin final options ###
> ### End final options ###
> ### END ###
> 
> 
> 
>

**Comment by AlexanderKenny** [comment] 2018-12-16 01:05
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

I know you mentioned updating but please use a nightly as the main release is quite old

**Closed as completed by AlexanderKenny** 2018-12-16 01:05 UTC
