### ISSUE TITLE
Crucible line not working from simc addon

### ISSUE THREAD

**Issue by Cheesiercake** [simulationcraft/simc#4070] opened 2017-10-04 08:06 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version 
730-01

#### simc_gui.simc file or contents
Player Cheesypuns invalid crucible rank '1782/1739/1739' for power '1739', expected a number > 0 && <= 255
#### Reproduction Steps:
druid="Cheesypuns"
level=110
race=night_elf
region=us
server=frostmourne
role=spell
professions=herbalism=799/mining=766
talents=3221233
spec=balance
artifact=59:0:0:0:0:1034:4:1035:4:1036:4:1037:4:1038:4:1039:4:1040:4:1041:4:1042:4:1043:1:1044:1:1045:1:1046:1:1047:1:1048:1:1049:1:1294:1:1364:1:1501:4:1502:1:1503:1:1504:11:1632:1
crucible=1739:1782/1739/1739

head=,id=137062,bonus_id=3529/3459/3570
neck=,id=142207,enchant_id=5890,bonus_id=3418/42/1517/3337
shoulder=,id=138336,bonus_id=3516/41/1487/3528
back=,id=147134,enchant_id=5436,bonus_id=3561/1492/3336
chest=,id=138324,bonus_id=3516/1487/1813
tabard=,id=64882
wrist=,id=137092,bonus_id=3529/3459/3570
hands=,id=140863,bonus_id=3443/1487/3337
waist=,id=147347,bonus_id=3573/1492/3528
legs=,id=147137,bonus_id=3562/1497/3528
feet=,id=134429,bonus_id=3417/1562/3528
finger1=,id=152779,enchant_id=5428,bonus_id=1757/3573/1507/3336
finger2=,id=142173,enchant_id=5428,gem_id=151583,bonus_id=3573/1808/1522/3528
trinket1=,id=147002,bonus_id=3561/1482/3528
trinket2=,id=134336,bonus_id=3573/603/1572/3528
main_hand=,id=128858,gem_id=147078/151012/151006,bonus_id=722,relic_id=3562:1497:3528/3396:3184:3337/3397:3189:3337

### Gear from Bags
#
# Arinor Keeper's Headgear of the Feverflare (895)
# head=,id=152759,bonus_id=1703/3629/1487/3337
#
# Mantle of the Dark Sea (885)
# shoulder=,id=137332,bonus_id=1727/1537/3528
#
# Lady and the Child (970)
# shoulder=,id=144295,bonus_id=1811/3570
#
# Cloak of the Astral Warden (885)
# back=,id=138366,enchant_id=5436,bonus_id=3514/1482/3336
#
# Cloak of Stifling Brimstone (915)
# back=,id=146984,enchant_id=5436,bonus_id=3562/1497/3528
#
# Spirebreaker Harness (905)
# chest=,id=147027,bonus_id=3561/1487/3336
#
# Swordsinger's Wristguards (900)
# wrist=,id=134280,bonus_id=1727/1562/3337
#
# Brinewashed Leather Grips (895)
# hands=,id=134239,bonus_id=3411/1557/3528
#
# Cinidaria, the Symbiote (970)
# waist=,id=133976,bonus_id=3529/3459/3570
#
# Biornskin Belt (885)
# waist=,id=134199,bonus_id=1727/1547/3528
#
# D-Lux Slipstream Pants (935)
# legs=,id=134450,bonus_id=3418/42/1587/3337
#
# Leggings of the Astral Warden (890)
# legs=,id=138333,bonus_id=3516/1487/3528
#
# Fierce Combatant's Ring (910)
# finger1=,id=149664,bonus_id=3573/1572/3528
#
# Rough-Hammered Silver Ring (910)
# finger1=,id=134191,bonus_id=3573/1572/3528
#
# Fierce Gladiator's Ring (910)
# finger1=,id=148067,bonus_id=3573/1542/3528
#
# Loop of Eightfold Eyes (910)
# finger1=,id=134527,gem_id=151583,bonus_id=3573/1808/40/1562/3528
#
# Ring of Twisted Webbing (895)
# finger1=,id=134540,bonus_id=1727/1547/3336
#
# Aran's Relaxing Ruby (905)
# trinket1=,id=142157,bonus_id=3418/1517/3337
#
# Pharamere's Forbidden Grimoire (880)
# trinket1=,id=140800,bonus_id=3514/1477/3336
#
# Venerable Triad Statuette (895)
# trinket1=,id=152782,bonus_id=3629/1487/3337
#
# Perfect Dreamgrove Blossom (810)
# trinket1=,id=140400
#
# Kil'jaeden's Burning Wish (970)
# trinket1=,id=144259,bonus_id=1811/3570
#
# Amalgam's Seventh Spine (870)
# trinket1=,id=136714,bonus_id=3510/41/1522/1813
#
# Icon of Rot (900)
# trinket1=,id=140798,bonus_id=3516/1497/3336
#
# Ethereal Urn (875)
# trinket1=,id=142166,bonus_id=41/3454/1472
#
# Erratic Metronome (885)
# trinket1=,id=140792,bonus_id=3444/1482/3528
#
# Eye of Skovald (910)
# trinket1=,id=133641,bonus_id=3573/1562/3528
#
# Mining Pick (4)
# main_hand=,id=2901
#
# Fishing Pole (1)
# main_hand=,id=6256
#

**Comment by Melekus** [comment] 2017-10-04 10:08
Duplicate of https://github.com/simulationcraft/simc/issues/4000-

**Closed as completed by Melekus** 2017-10-04 10:08 UTC
