### ISSUE TITLE
Demon Hunter head piece throwing an error?

### ISSUE THREAD

**Issue by omgitsagirl** [simulationcraft/simc#4644] opened 2018-12-17 04:25 UTC
I use the SimC addon and when I plug it in the Simulation Craft it throws me this error. Help please, I have reinstalled both the SimC addon and Sim Craft desktop app.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Omgitsagirl': Item 'inactive' Slot 'head': Cannot parse option from ',id=163435,bonus_id=5125/1562/5136/5381/4775,context=28,azerite_powers=221/461/85/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,sta,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
demonhunter="Omgitsagirl"
level=120
race=blood_elf
region=us
server=firetree
role=tank
professions=alchemy=87/enchanting=142
talents=1213321
spec=vengeance

head=,id=163435,bonus_id=5125/1562/5136/5381/4775,context=28,azerite_powers=221/461/85/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=160620,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=354/43/202/13
back=,id=160642,bonus_id=4799/1507/4784,context=5
chest=,id=160619,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/21/83/13
tabard=,id=69210,context=14
wrist=,id=163309,bonus_id=5126/1577/4784,context=6
hands=,id=160618,gem_id=154126,bonus_id=4800/1808/1512/4783,context=6
waist=,id=160622,bonus_id=4799/1512/4784,context=5
legs=,id=160625,bonus_id=4799/1497/4783,context=5
feet=,id=159336,bonus_id=5007/1557/4784,context=16
finger1=,id=160647,enchant_id=5943,bonus_id=4799/1492/4786,context=5
finger2=,id=160645,enchant_id=5943,bonus_id=4799/1507/4784,context=5
trinket1=,id=160652,bonus_id=4799/1492/4786,context=5
trinket2=,id=159614,bonus_id=5008/1542/4783,context=35
main_hand=,id=160693,enchant_id=5963,bonus_id=4799/1492/4786,context=5
off_hand=,id=160681,enchant_id=5966,bonus_id=4799/1492/4786,context=5

### Gear from Bags
#
# Honorbound Outrider's Headpiece (370)
# head=,id=163435,bonus_id=5126/1562/4786/5399,context=6,azerite_powers=
#
# Evergreen Vinewrap Drape (180)
# back=,id=139248,bonus_id=1806/1484/3528,context=6
#
# Wrap of Unity (35)
# back=,id=63207,context=14
#
# Honorbound Outrider's Drape (340)
# back=,id=163360,bonus_id=5124/1532/4786,context=3
#
# Blood Bog Wraps (325)
# chest=,id=157878,bonus_id=1517/4785/5389,context=26,azerite_powers=
#
# Waterfall Robe of the Feverflare (115)
# chest=,id=82253,bonus_id=1698,context=6
#
# Lifeless Buckled Girdle (185)
# waist=,id=139197,bonus_id=1806/1489/3336,context=6
#
# Dread Aspirant's Leather Legguards (330)
# legs=,id=162951,bonus_id=1522/4785,context=47
#
# Splotched Bloodfur Leggings (180)
# legs=,id=139201,bonus_id=1806/1484/3528,context=6
#
# Unbridled Fury (180)
# trinket1=,id=139327,bonus_id=1806/41/1484/3528,context=6
#
# Deathbringer's Will (102)
# trinket1=,id=50363
#
# Fishing Pole (1)
# main_hand=,id=6256,context=14
#
# Glaive of the Keepers (355)
# main_hand=,id=160681,bonus_id=4798/1808/1477/4786,context=3
#
# Glaive of the Keepers (355)
# off_hand=,id=160681,bonus_id=4798/1808/1477/4786,context=3

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-17 05:43
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-17 05:43 UTC

**Comment by omgitsagirl** [comment] 2018-12-17 06:05
> Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

How would i do that?

**Comment by AlexanderKenny** [comment] 2018-12-17 06:19
For windows either grab the .exe (installer) or .7z (zip file) from the link I provided. For MacOS grab the .dmg.

Grab whichever version is most recent (new builds are posted roughly daily to that link between major releases).
