### ISSUE TITLE
sim not working

### ISSUE THREAD

**Issue by Huggepung** [simulationcraft/simc#4018] opened 2017-09-15 19:35 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

#### # SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Huggepung invalid crucible rank '1774/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
paladin="Huggepung"
level=110
race=human
region=eu
server=outland
role=attack
professions=enchanting=60/
talents=1113212
spec=retribution
artifact=2:0:0:0:0:40:1:41:4:42:4:43:4:44:4:47:4:49:1:50:4:51:4:52:4:53:4:54:1:350:1:351:1:352:1:353:1:1118:1:1275:1:1561:4:1562:1:1563:1:1564:12:1647:1
crucible=1739:1774/1739/1739

head=,id=142126,bonus_id=3418/1522/3337
neck=,id=147013,bonus_id=3561/1482/3528
shoulder=,id=138362,enchant_id=5900,bonus_id=3516/1512/3337
back=,id=137020,enchant_id=5434,bonus_id=3529/3459/3570
chest=,id=147157,bonus_id=3561/1487/3336
shirt=,id=151116
tabard=,id=69210
wrist=,id=134362,bonus_id=3534/1582/3337
hands=,id=147159,bonus_id=3562/1497/3528
waist=,id=147071,bonus_id=3561/1502/3337
legs=,id=138359,bonus_id=3516/1487/3528
feet=,id=139241,bonus_id=3418/1557/3337
finger1=,id=137048,enchant_id=5427,gem_id=130221,bonus_id=1811/3570
finger2=,id=134490,enchant_id=5430,bonus_id=3534/1572/3337
trinket1=,id=140806,gem_id=130221,bonus_id=3516/1808/1487/3528
trinket2=,id=147009,bonus_id=3562/1502/3336
main_hand=,id=120978,gem_id=147096/140835/140843,bonus_id=737,relic_id=3562:1497:3528/3573:1532:3337/3444:1482:3528

### Gear from Bags
#
# Radiant Lightbringer Crown (925)
# head=,id=147160,bonus_id=3562/1808/1507/3336
#
# Garothi Helmet (895)
# head=,id=150957,bonus_id=3397/1808/1557/3528
#
# Erratically Ticking Talisman (910)
# neck=,id=137418,bonus_id=3573/1562/3528
#
# Cloak of Coordination (60)
# back=,id=65360
#
# Shroud of Cooperation (35)
# back=,id=63352
#
# Wrap of Unity (35)
# back=,id=63206
#
# Cape of Mindless Fury (915)
# back=,id=147193,enchant_id=5310,bonus_id=3562/1497/3528
#
# Radiant Lightbringer Cape (925)
# back=,id=147158,bonus_id=3562/41/1507/3336
#
# Cloak of Sweltering Flame (935)
# back=,id=142206,bonus_id=3418/1552/3337
#
# Wave-Hammered Breastplate (905)
# chest=,id=147067,bonus_id=3561/42/1487/3336
#
# Thornscar Wristguards (925)
# wrist=,id=134520,bonus_id=3417/1577/3337
#
# Bonemeal-Crusted Armplates (920)
# wrist=,id=147073,bonus_id=3562/1502/3336
#
# Shadowed Grips of the Nathrezim (920)
# hands=,id=144502,bonus_id=3534/1572/3337
#
# Waistguard of Fel Magics (930)
# waist=,id=152380,bonus_id=3614/1472/3528
#
# Praetorium Guard's Waistplate of the Decimator (880)
# waist=,id=152749,bonus_id=1718/3629/1472/3528
#
# Radiant Lightbringer Greaves (915)
# legs=,id=147161,bonus_id=3562/1497/3528
#
# Lava-Slough Legguards (915)
# legs=,id=147065,bonus_id=3562/1497/3528
#
# Aggramar's Stride (970)
# feet=,id=132443,bonus_id=1811/3570
#
# Rockbound Sabatons (905)
# feet=,id=134141,bonus_id=3418/1567/3337
#
# Yathae's Thumb Ring (915)
# finger1=,id=147021,enchant_id=5427,bonus_id=3562/42/1497/3528
#
# Ring of Collapsing Futures (935)
# finger1=,id=142173,bonus_id=3416/1547/3337
#
# Sephuz's Secret (970)
# finger1=,id=132452,enchant_id=5427,gem_id=130219,bonus_id=3529/3459/3570
#
# Kil'jaeden's Burning Wish (970)
# trinket1=,id=144259,bonus_id=3459/3570
#
# Hunger of the Pack (885)
# trinket1=,id=136975,bonus_id=3573/1537/3336
#
# Runeblade of Baron Rivendare (53)
# main_hand=,id=13505
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

#### simc_gui.simc file or contents
paladin="Huggepung"
level=110
race=human
region=eu
server=outland
role=attack
professions=enchanting=60/
talents=1113212
spec=retribution
artifact=2:0:0:0:0:40:1:41:4:42:4:43:4:44:4:47:4:49:1:50:4:51:4:52:4:53:4:54:1:350:1:351:1:352:1:353:1:1118:1:1275:1:1561:4:1562:1:1563:1:1564:12:1647:1
crucible=1739:1774/1739/1739

head=,id=142126,bonus_id=3418/1522/3337
neck=,id=147013,bonus_id=3561/1482/3528
shoulder=,id=138362,enchant_id=5900,bonus_id=3516/1512/3337
back=,id=137020,enchant_id=5434,bonus_id=3529/3459/3570
chest=,id=147157,bonus_id=3561/1487/3336
shirt=,id=151116
tabard=,id=69210
wrist=,id=134362,bonus_id=3534/1582/3337
hands=,id=147159,bonus_id=3562/1497/3528
waist=,id=147071,bonus_id=3561/1502/3337
legs=,id=138359,bonus_id=3516/1487/3528
feet=,id=139241,bonus_id=3418/1557/3337
finger1=,id=137048,enchant_id=5427,gem_id=130221,bonus_id=1811/3570
finger2=,id=134490,enchant_id=5430,bonus_id=3534/1572/3337
trinket1=,id=140806,gem_id=130221,bonus_id=3516/1808/1487/3528
trinket2=,id=147009,bonus_id=3562/1502/3336
main_hand=,id=120978,gem_id=147096/140835/140843,bonus_id=737,relic_id=3562:1497:3528/3573:1532:3337/3444:1482:3528

### Gear from Bags
#
# Radiant Lightbringer Crown (925)
# head=,id=147160,bonus_id=3562/1808/1507/3336
#
# Garothi Helmet (895)
# head=,id=150957,bonus_id=3397/1808/1557/3528
#
# Erratically Ticking Talisman (910)
# neck=,id=137418,bonus_id=3573/1562/3528
#
# Cloak of Coordination (60)
# back=,id=65360
#
# Shroud of Cooperation (35)
# back=,id=63352
#
# Wrap of Unity (35)
# back=,id=63206
#
# Cape of Mindless Fury (915)
# back=,id=147193,enchant_id=5310,bonus_id=3562/1497/3528
#
# Radiant Lightbringer Cape (925)
# back=,id=147158,bonus_id=3562/41/1507/3336
#
# Cloak of Sweltering Flame (935)
# back=,id=142206,bonus_id=3418/1552/3337
#
# Wave-Hammered Breastplate (905)
# chest=,id=147067,bonus_id=3561/42/1487/3336
#
# Thornscar Wristguards (925)
# wrist=,id=134520,bonus_id=3417/1577/3337
#
# Bonemeal-Crusted Armplates (920)
# wrist=,id=147073,bonus_id=3562/1502/3336
#
# Shadowed Grips of the Nathrezim (920)
# hands=,id=144502,bonus_id=3534/1572/3337
#
# Waistguard of Fel Magics (930)
# waist=,id=152380,bonus_id=3614/1472/3528
#
# Praetorium Guard's Waistplate of the Decimator (880)
# waist=,id=152749,bonus_id=1718/3629/1472/3528
#
# Radiant Lightbringer Greaves (915)
# legs=,id=147161,bonus_id=3562/1497/3528
#
# Lava-Slough Legguards (915)
# legs=,id=147065,bonus_id=3562/1497/3528
#
# Aggramar's Stride (970)
# feet=,id=132443,bonus_id=1811/3570
#
# Rockbound Sabatons (905)
# feet=,id=134141,bonus_id=3418/1567/3337
#
# Yathae's Thumb Ring (915)
# finger1=,id=147021,enchant_id=5427,bonus_id=3562/42/1497/3528
#
# Ring of Collapsing Futures (935)
# finger1=,id=142173,bonus_id=3416/1547/3337
#
# Sephuz's Secret (970)
# finger1=,id=132452,enchant_id=5427,gem_id=130219,bonus_id=3529/3459/3570
#
# Kil'jaeden's Burning Wish (970)
# trinket1=,id=144259,bonus_id=3459/3570
#
# Hunger of the Pack (885)
# trinket1=,id=136975,bonus_id=3573/1537/3336
#
# Runeblade of Baron Rivendare (53)
# main_hand=,id=13505
#

**Comment by vituscze** [comment] 2017-09-15 19:38
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-15 19:38 UTC
