### ISSUE TITLE
Crashes at results tab

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2614] opened 2015-08-13 19:58 UTC
Originally reported on Google Code with ID 2615
```
hunter="Goldrisen_Active"
origin="https://us.api.battle.net/wow/character/alexstrasza/Goldrisen/advanced"
thumbnail="http://us.battle.net/static-render/us/alexstrasza/192/138893248-avatar.jpg"
level=100
race=pandaren_alliance
role=attack
position=ranged_back
professions=engineering=700/alchemy=700
talents=http://us.battle.net/wow/en/tool/talent-calculator#YZ!2002222
glyphs=chimaera_shot/deterrence/misdirection/revive_pet/stampede/aspect_of_the_cheetah
spec=marksmanship

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely
highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action
lists.

# Executed before combat begins. Accepts non-harmful actions only.

actions.precombat=flask,type=greater_draenic_agility_flask
actions.precombat+=/food,type=salty_squid_roll
actions.precombat+=/summon_pet
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/exotic_munitions,ammo_type=poisoned,if=spell_targets.multi_shot<3
actions.precombat+=/exotic_munitions,ammo_type=incendiary,if=spell_targets.multi_shot>=3
actions.precombat+=/potion,name=draenic_agility
actions.precombat+=/glaive_toss
actions.precombat+=/focusing_shot

# Executed every time the actor is available.

actions=auto_shot
actions+=/use_item,name=wayfaring_belt
actions+=/use_item,name=mirror_of_the_blademaster
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/potion,name=draenic_agility,if=((buff.rapid_fire.up|buff.bloodlust.up)&(cooldown.stampede.remains<1))|target.time_to_die<=25
actions+=/chimaera_shot
actions+=/kill_shot
actions+=/rapid_fire
actions+=/stampede,if=buff.rapid_fire.up|buff.bloodlust.up|target.time_to_die<=25
actions+=/call_action_list,name=careful_aim,if=buff.careful_aim.up
actions+=/explosive_trap,if=spell_targets.explosive_trap_tick>1
actions+=/a_murder_of_crows
actions+=/dire_beast,if=cast_regen+action.aimed_shot.cast_regen<focus.deficit
actions+=/glaive_toss
actions+=/powershot,if=cast_regen<focus.deficit
actions+=/barrage
# Pool max focus for rapid fire so we can spam AimedShot with Careful Aim buff
actions+=/steady_shot,if=focus.deficit*cast_time%(14+cast_regen)>cooldown.rapid_fire.remains
actions+=/focusing_shot,if=focus.deficit*cast_time%(50+cast_regen)>cooldown.rapid_fire.remains&focus<100
# Cast a second shot for steady focus if that won't cap us.
actions+=/steady_shot,if=buff.pre_steady_focus.up&(14+cast_regen+action.aimed_shot.cast_regen)<=focus.deficit
actions+=/multishot,if=spell_targets.multi_shot>6
actions+=/aimed_shot,if=talent.focusing_shot.enabled
actions+=/aimed_shot,if=focus+cast_regen>=85
actions+=/aimed_shot,if=buff.thrill_of_the_hunt.react&focus+cast_regen>=65
# Allow FS to over-cap by 10 if we have nothing else to do
actions+=/focusing_shot,if=50+cast_regen-10<focus.deficit
actions+=/steady_shot

actions.careful_aim=glaive_toss,if=active_enemies>2
actions.careful_aim+=/powershot,if=spell_targets.powershot>1&cast_regen<focus.deficit
actions.careful_aim+=/barrage,if=spell_targets.barrage>1
actions.careful_aim+=/aimed_shot
actions.careful_aim+=/focusing_shot,if=50+cast_regen<focus.deficit
actions.careful_aim+=/steady_shot

head=hood_of_the_savage_hunt,id=124296
neck=faulty_detonator_cord,id=124207,bonus_id=561/566,enchant=75crit
shoulders=rylakstalkers_spaulders,id=115547
back=marshwater_cape,id=124613,bonus_id=107/648/652,enchant=gift_of_critical_strike
chest=rylakstalkers_tunic,id=115548,bonus_id=563,gems=50crit
wrists=chain_wristguards_of_the_stricken,id=124313,bonus_id=564/566,gems=50crit
hands=axeclaw_gauntlets,id=124577,bonus_id=76/648/653
waist=wayfaring_belt,id=116194,bonus_id=70/535/618,addon=nitro_boosts
legs=leggings_of_the_savage_hunt,id=124301,bonus_id=560
feet=diecast_ringmail_sabatons,id=124285,bonus_id=561/566
finger1=cinderwolf_signet,id=113917,bonus_id=562/567,enchant=50crit
finger2=spellbound_runic_band_of_unrelenting_slaughter,id=118307,enchant=50crit
trinket1=chipped_soul_prism,id=124545
trinket2=mirror_of_the_blademaster,id=124224
main_hand=shredirons_shredder,id=109168,bonus_id=84/531/620,enchant=oglethorpes_missile_splitter

# Gear Summary
# gear_ilvl=699.60
# gear_agility=3491
# gear_stamina=4696
# gear_intellect=187
# gear_crit_rating=2108
# gear_haste_rating=360
# gear_mastery_rating=589
# gear_multistrike_rating=1623
# gear_versatility_rating=729
# gear_armor=1458
# set_bonus=tier17_2pc=1
# set_bonus=tier18_2pc=1
summon_pet=cat

What steps will reproduce the problem?
1. Run a simulation, as soon as the simulation finishes and it goes to the "results"
tab, the program locks up.

What is the expected output? What do you see instead?
     Results, instead the program locks up.

What version of the product are you using? On what operating system?
     SimulationCraft 620-01, Windows 10 x64

Please provide any additional information below.


```

Reported by `Baer.Brandon` on 2015-08-05 22:55:52

**Comment by Fredyy90** [comment] 2015-09-02 13:39
I sometimes experience the same problem when wow is running in the background it locks up after the simulation, before showing the results.
If i only run simc it works flawless.

If i only run simc it works

**Comment by Collisionc** [comment] 2015-09-06 16:14
Try the 622-01 version I have uploaded here - http://downloads.simulationcraft.org/?C=M;O=D
It uses a newer version of QT 5.5.1, which is known to fix these issues. It might not fix them all, but hopefully enough.

**Comment by Fredyy90** [comment] 2015-09-06 16:35
Unfortunalty this doens't fix the problem.
Simc still crashes after the simulation, while wow is running.

![2015-09-06_1834](https://cloud.githubusercontent.com/assets/1572327/9705470/fc52f816-54c5-11e5-99c8-99d27b9eb20f.png)

**Comment by Fredyy90** [comment] 2015-09-07 07:15
Is there any way to get a debug version, so i can post you a stacktrace were it crashes?

**Comment by scamille** [comment] 2015-09-09 07:07
Duplicate of #2613

**Closed by scamille** 2015-09-09 07:07 UTC
Labels: bug, GUI, WebEngine
