### ISSUE TITLE
Havok DH simprobs

### ISSUE THREAD

**Issue by Abramelech** [simulationcraft/simc#4010] opened 2017-09-15 02:04 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Abramelech invalid crucible rank '1770/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=HelterSkelter
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
center_scale_delta=1
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
demonhunter="Abramelech"
level=110
race=night_elf
region=eu
server=malygos
role=attack
professions=mining=627/jewelcrafting=800
talents=2221311
spec=havoc
artifact=3:0:0:0:0:1000:4:1001:4:1002:4:1003:4:1004:4:1005:4:1006:4:1007:4:1008:4:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:1:1493:4:1494:1:1495:1:1496:10:1630:1
crucible=1739:1770/1739/1739

head=,id=147130,bonus_id=3561/1492/3336
neck=,id=149626,enchant_id=5437,gem_id=151580,bonus_id=3573/1808/1577/3336
shoulder=,id=136744,bonus_id=3573/1572/3528
back=,id=150988,bonus_id=3396/1572/3337
chest=,id=147027,bonus_id=3561/1487/3336
wrist=,id=137512,bonus_id=3573/1562/3528
hands=,id=147032,bonus_id=3561/1487/3336
waist=,id=133976,bonus_id=1811/3570
legs=,id=147131,bonus_id=3561/1482/3528
feet=,id=152359,bonus_id=3614/1482/3336
finger1=,id=134191,enchant_id=5423,bonus_id=3573/1572/3528
finger2=,id=139103,enchant_id=5423,gem_id=151580,bonus_id=3394/1808/1542/3528
trinket1=,id=153172,bonus_id=3573/1502/3528
trinket2=,id=151190,bonus_id=3561/1492/3528
main_hand=,id=127829,gem_id=141255/147108/151008,bonus_id=719,relic_id=3573:1577:3336/3561:1492:3336/3397:3194:3337
off_hand=,id=127830

### Gear from Bags
#
# Kapuze des Schattenpirschers (870)
# head=,id=136742,bonus_id=1824/1808/42/1532/3528
#
# Ausgelaugter Manakristallanhänger (870)
# neck=,id=134319,bonus_id=1824/1532/3528
#
# Mantel des aufstrebenden Zauberriesen (860)
# shoulder=,id=141445,bonus_id=3466/1472/3528
#
# Schleier des Dämonenbanns (900)
# back=,id=147128,enchant_id=5432,bonus_id=3561/1482/3528
#
# Harnisch des Dämonenbanns (885)
# chest=,id=147127,bonus_id=3564/41/1467/3528
#
# Nietenhandschutz des Glevenmeisters (915)
# hands=,id=137509,bonus_id=3573/1567/3336
#
# Gürtel des Netherscheusals (900)
# waist=,id=146775,bonus_id=3394/1562/3337
#
# Teufelshautstiefel des stürmischen Gladiators (890)
# feet=,id=147951,bonus_id=3579/1710/42/1522/3528
#
# Wächterinnenband (915)
# finger1=,id=136737,enchant_id=5423,bonus_id=3573/1577/3336
#
# Stachelbesetztes Gegengewicht (885)
# trinket1=,id=136715,bonus_id=1727/41/1537/3528
#
# Dreizehige Hasenpfote (870)
# trinket1=,id=134203,bonus_id=1824/605/1532/3528
#
# Kriegsgleve von Azzinoth (156)
# main_hand=,id=32837
#
# Spitzhacke (4)
# main_hand=,id=2901
#
# Krokulspitzhacke (800)
# main_hand=,id=153290
#
# Schmiedehammer (1)
# main_hand=,id=5956
#
# Kürschnermesser (4)
# main_hand=,id=7005
#
# Kriegsgleve von Azzinoth (156)
# off_hand=,id=32838
#
# Kürschnermesser (4)
# off_hand=,id=7005
#
# Krokulspitzhacke (800)
# off_hand=,id=153290
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-15 11:38
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-15 11:38 UTC
Labels: duplicate
