### ISSUE TITLE
SimulationCraft encountered an error!

### ISSUE THREAD

**Issue by graset** [simulationcraft/simc#4049] opened 2017-09-21 18:28 UTC
#### simc_gui.simc file or contents
https://pastebin.com/DjCyu8hx

dont relly know how to do this. it told me to post a ticket so I did it

**Comment by vituscze** [comment] 2017-09-21 22:15
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-21 22:15 UTC
Labels: duplicate
