### ISSUE TITLE
Warlock Sim Bug

### ISSUE THREAD

**Issue by Biscia15** [simulationcraft/simc#4632] opened 2018-12-15 15:57 UTC
### Describe the bug
I tried to sim my affliction warlock during this week, but I found an error that does not allow me to simulate my character.
I use simulationcraft addon to recover my character's string, then I paste it into the simulationcraft program, but when i try to star the simulation an error comes out (Simulation runtime error)
### Additional information
* SimulationCraft Version 8.01-01
* Simulationcraft AddonVersion 1.10.8

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Krodont': Item 'inactive' Slot 'head': Cannot parse option from ',id=160616,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/14/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=bfahead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=0
override.power_word_fortitude=0
override.battle_shout=0
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=0
override.mystic_touch=0
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
# SimC Addon 1.10.8
warlock="Krodont"
level=120
race=undead
region=eu
server=pozzo_delleternità
role=spell
professions=alchemy=150/herbalism=150
talents=3322323
spec=affliction

head=,id=160616,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/14/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=157875,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=442/30/15/13
back=,id=159288,bonus_id=5010/40/1552/4783,context=35
chest=,id=166684,bonus_id=5478/1502/4786/5401/4775,context=3,azerite_powers=425/30/15/13
tabard=,id=35280,context=11
wrist=,id=160617,enchant_id=5971,bonus_id=4799/1492/4786,context=5
hands=,id=160612,enchant_id=5932,bonus_id=4800/1507/4786,context=6
waist=,id=160734,bonus_id=4799/1492/4786,context=5
legs=,id=159285,bonus_id=5010/1557/4784,context=35
feet=,id=160714,bonus_id=4799/1808/1492/4786,context=5
finger1=,id=160646,enchant_id=5944,bonus_id=4798/1497/4784,context=3
finger2=,id=158314,enchant_id=5944,bonus_id=5009/1552/4784,context=35
trinket1=,id=160651,bonus_id=4800/1507/4786,context=6
trinket2=,id=166793,bonus_id=5479/1502/4786,context=3
main_hand=,id=160680,enchant_id=5964,bonus_id=4800/1512/4783,context=6
off_hand=,id=159668,bonus_id=5010/1557/4784,context=35

### Gear from Bags

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-15 15:58
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-15 15:58 UTC
