### ISSUE TITLE
# SimulationCraft encountered an error!

### ISSUE THREAD

**Issue by Soulhavester** [simulationcraft/simc#4045] opened 2017-09-20 23:19 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Soulhavester invalid crucible rank '1778/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Soulhavester invalid crucible rank '1778/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers,wdps,wohdps
statistics_level=1
### End GUI options ###
### Begin simulateText ###
warlock="Soulhavester"
level=110
race=orc
region=us
server=terenas
role=spell
professions=enchanting=800/jewelcrafting=800
talents=3111113
spec=affliction
artifact=39:0:0:0:0:915:4:916:4:917:4:918:4:919:4:920:4:921:4:922:4:923:4:924:1:925:1:926:1:927:1:928:1:929:1:999:1:1353:1:1390:1:1601:4:1602:1:1603:1:1604:11:1711:1
crucible=1739:1778/1739/1739

head=,id=132394,bonus_id=3459/3570
neck=,id=133633,bonus_id=3418/1587/3337
shoulder=,id=147186,bonus_id=3561/43/1492/3336
back=,id=147181,enchant_id=5436,bonus_id=3562/1497/3528
chest=,id=147185,bonus_id=3561/43/1497/3337
shirt=,id=89192
wrist=,id=139130,bonus_id=3418/1612/3337
hands=,id=147182,gem_id=151584,bonus_id=3561/1808/1502/3337
waist=,id=132457,bonus_id=1811/3570
legs=,id=146992,bonus_id=3562/1522/3337
feet=,id=152349,bonus_id=3614/1477/3336
finger1=,id=147195,enchant_id=5429,bonus_id=3561/1507/3337
finger2=,id=147020,enchant_id=5429,bonus_id=3562/1497/3528
trinket1=,id=147019,bonus_id=3561/1502/3336
trinket2=,id=147017,bonus_id=3562/1497/3528
main_hand=,id=128942,gem_id=147108/151189/136719,bonus_id=747,relic_id=3562:1497:3528/3562:1497:3528/3573:1577:3337

### Gear from Bags
#
# Hood of Indignation (905)
# head=,id=137502,bonus_id=3418/1557/3337
#
# Diabolic Helm (905)
# head=,id=147183,bonus_id=3561/1487/3336
#
# Blackened Mask of Disgrace (900)
# head=,id=146991,bonus_id=3561/1482/3528
#
# Cowl of Plumbed Depths (910)
# head=,id=147731,bonus_id=3572/1492/3336
#
# Hundred-Fathom Veil (925)
# head=,id=146990,bonus_id=3562/1507/3336
#
# String of Extracted Incisors (930)
# neck=,id=147013,enchant_id=5437,bonus_id=3562/1512/3337
#
# Locket of Splintered Souls (925)
# neck=,id=147014,enchant_id=5890,bonus_id=3562/1507/3336
#
# Prydaz, Xavaric's Magnum Opus (970)
# neck=,id=132444,enchant_id=5437,gem_id=151584,bonus_id=1811/3570
#
# Shoulderpads of Whispering Twilight (925)
# shoulder=,id=146997,bonus_id=3562/1507/3336
#
# Amice of the Unfurling Tempest (930)
# shoulder=,id=134432,enchant_id=5931,bonus_id=3536/1582/3337
#
# Cape of Mindless Fury (915)
# back=,id=147193,bonus_id=3562/1497/3528
#
# Reap and Sow (970)
# back=,id=144364,bonus_id=3459/3570
#
# Cloak of Stifling Brimstone (920)
# back=,id=146984,enchant_id=5436,gem_id=130222,bonus_id=3562/1808/1502/3336
#
# Shroud of the Drowned Adherent (920)
# back=,id=146985,bonus_id=3562/1502/3336
#
# Iceblood Shroud (900)
# back=,id=134411,bonus_id=3417/1808/1552/3337
#
# Cloak of Fading Echoes (910)
# back=,id=134405,bonus_id=3418/1562/3337
#
# Robe of Aqueous Command (915)
# chest=,id=146994,bonus_id=3562/1497/3528
#
# The Master Harvester (970)
# chest=,id=151821,bonus_id=3459/3570
#
# Ravenous Devotee's Bracelets (915)
# wrist=,id=147000,bonus_id=3562/1497/3528
#
# Gloves of Furtive Oppression (915)
# hands=,id=146988,bonus_id=3561/1497/3336
#
# Waistband of Spiritual Doom (915)
# waist=,id=137507,bonus_id=3573/41/1567/3336
#
# Cord of Unraveling Reality (910)
# waist=,id=151302,bonus_id=3573/1562/3528
#
# Diabolic Leggings (915)
# legs=,id=147184,bonus_id=3562/1497/3528
#
# Emberscatter Treads (915)
# feet=,id=146986,gem_id=151584,bonus_id=3562/1808/1497/3528
#
# Acolyte's Abandoned Footwraps (920)
# feet=,id=147422,bonus_id=3562/1502/3336
#
# Slippers of Enduring Vigilance (915)
# feet=,id=146987,bonus_id=3562/1497/3528
#
# Sacrolash's Dark Strike (970)
# finger1=,id=132378,enchant_id=5429,gem_id=151584,bonus_id=3459/3570
#
# Sephuz's Secret (970)
# finger1=,id=132452,enchant_id=5428,gem_id=130220,bonus_id=3459/3570
#
# Band of Rescinded Truths (915)
# finger1=,id=147194,bonus_id=3562/1497/3528
#
# Yathae's Thumb Ring (920)
# finger1=,id=147021,enchant_id=5429,gem_id=151584,bonus_id=3562/1808/1502/3336
#
# Charm of the Rising Tide (915)
# trinket1=,id=147002,bonus_id=3562/1497/3528
#
# Kil'jaeden's Burning Wish (970)
# trinket1=,id=144259,bonus_id=3529/3459/3570
#
# Time-Lost Artifact (496)
# trinket1=,id=103678
#
# Whispers in the Dark (900)
# trinket1=,id=140809,bonus_id=3517/1497/3336
#
# Big Iron Fishing Pole (30)
# main_hand=,id=6367,enchant_id=5357
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by seriallos** [comment] 2017-09-20 23:24
Duplicate of #4000

**Closed as completed by seriallos** 2017-09-20 23:24 UTC
Labels: duplicate
