### ISSUE TITLE
SimulationCraft encountered an error!  Item 'inactive' Slot

### ISSUE THREAD

**Issue by randompsique** [simulationcraft/simc#4618] opened 2018-12-11 22:50 UTC
Hello, I'm having troubles running simulations on my character. I don't know what happened it was working great and I didn't change anything. 

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Cryptic': Item 'inactive' Slot 'head': Cannot parse option from ',id=159374,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=196/30/83/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
hunter="Cryptic"
level=120
race=blood_elf
region=us
server=quelthalas
role=attack
professions=leatherworking=150/skinning=150
talents=1323211
spec=beast_mastery

head=,id=159374,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=196/30/83/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=160731,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/30/14/13
back=,id=159292,gem_id=154126,bonus_id=5010/4802/1552/4786,context=35
chest=,id=160627,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/31/15/13
shirt=,id=18231,context=7
tabard=,id=5976,context=14
wrist=,id=159380,bonus_id=5010/41/1552/4783,context=35
hands=,id=159399,enchant_id=5934,bonus_id=5010/1557/4784,context=35
waist=,id=159369,bonus_id=5010/1557/4784,context=16
legs=,id=160631,bonus_id=4800/1517/4783,context=6
feet=,id=162472,bonus_id=1704,context=13
finger1=,id=160645,enchant_id=5942,gem_id=153708,bonus_id=4799/1808/1497/4783,context=5
finger2=,id=159461,enchant_id=5942,gem_id=154126,bonus_id=5010/4802/42/1547/4783,context=16
trinket1=,id=161462,bonus_id=5119/1492/4786,context=3
trinket2=,id=160648,gem_id=154126,bonus_id=4799/1808/1492/4786,context=5
main_hand=,id=160678,enchant_id=5957,bonus_id=4799/1492/4786,context=5

### Gear from Bags

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-11 22:51
Duplicate of #4613 update your local simc version as it's months out of date.

**Closed as completed by AlexanderKenny** 2018-12-11 22:51 UTC
