### ISSUE TITLE
Error from helm

### ISSUE THREAD

**Issue by SirBatsheep** [simulationcraft/simc#4733] opened 2019-02-09 03:49 UTC
When I go to sim my character I get a "Initializing: Actor 'Tokahli': Item 'inactive' Slot 'head': Cannot parse option from ',id=157889,bonus_id=1577/4786/5414,context=28,azerite_powers=137/416/22': Unexpected parameter 'context'."

I have no idea what the issue is

[log.txt](https://github.com/simulationcraft/simc/files/2847475/log.txt)

**Comment by vituscze** [comment] 2019-02-14 17:44
Duplicate of #4613

**Comment by vituscze** [comment] 2019-02-14 17:44
Please update your simc.

**Closed as completed by vituscze** 2019-02-14 17:44 UTC
