### ISSUE TITLE
No mountable file systems OSX nightly builds

### ISSUE THREAD

**Issue by Tenwatts** [simulationcraft/simc#4114] opened 2017-10-30 08:08 UTC
I can't mount any of the later nightly builds. I tried re-downloading many times but I get the message "No mountable file systems". The september 14, 7.3.0 r2 works like a charm though.

I'm running OSX Sierra, 10.12.3 (16D30) on a 2017 MacBook pro touch 15.

**Comment by navv1234** [comment] 2017-10-30 09:26
They open fine on a high sierra machine, not sure what is going on here. Quick googling around talks about various kernel extensions / software packages that may cause the issue.

EDIT: Scratch that. I know what the issue is .. need to figure how to fix it.

**Comment by navv1234** [comment] 2017-10-30 09:36
Right, should be fixed now.

**Closed as completed by navv1234** 2017-10-30 09:36 UTC

**Comment by Tenwatts** [comment] 2017-10-30 18:35
Thanks man! Now it works!:))
