### ISSUE TITLE
assassin rogue helm wont sim

### ISSUE THREAD

**Issue by stabghost** [simulationcraft/simc#4620] opened 2018-12-13 02:10 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Sologhost': Item 'inactive' Slot 'head': Cannot parse option from ',id=159318,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=196/30/83/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=100
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Undead
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
rogue="Sologhost"
level=120
race=blood_elf
region=us
server=tichondrius
role=attack
professions=alchemy=150/herbalism=150
talents=2212221
spec=assassination

head=,id=159318,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=196/30/83/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=159331,bonus_id=5064/1542/4786/4775,context=35,azerite_powers=407/22/548/13
back=,id=163360,gem_id=154127,bonus_id=5126/4802/1562/4786,context=6
chest=,id=160619,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/31/15/13
tabard=,id=160544,context=14
wrist=,id=163309,bonus_id=5126/1562/4786,context=6
hands=,id=159305,enchant_id=5932,bonus_id=5010/1552/4783,context=35
waist=,id=159325,bonus_id=5007/1542/4783,context=35
legs=,id=160625,bonus_id=4800/1517/4783,context=6
feet=,id=159295,bonus_id=5010/1542/4786,context=16
finger1=,id=158314,enchant_id=5943,bonus_id=5008/1537/4786,context=16
finger2=,id=160645,enchant_id=5943,bonus_id=4799/1492/4786,context=5
trinket1=,id=166794,bonus_id=5479/1512/4783,context=3
trinket2=,id=160652,bonus_id=4800/1507/4786,context=6
main_hand=,id=160683,enchant_id=5963,bonus_id=4799/1492/4786,context=5
off_hand=,id=160683,enchant_id=5965,gem_id=153708,bonus_id=4799/1808/40/1492/4786,context=5

### Gear from Bags
#
# Gonk Outrunner Mask (375)
# head=,id=157913,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=136/459/84/13
#
# Irontide Captain's Hat (360)
# head=,id=155888,bonus_id=5047/1527/4786/4775,context=35,azerite_powers=479/30/44/13
#
# Honorbound Outrider's Headpiece (370)
# head=,id=163435,bonus_id=5125/1562/5136/5381,context=28,azerite_powers=
#
# Usurper's Bloodcaked Spaulders (360)
# shoulder=,id=160620,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=483/30/217/13
#
# Gonk Outrunner Shoulderguards (375)
# shoulder=,id=157915,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=408/30/473/13
#
# Tentacle-Laced Spaulders (370)
# shoulder=,id=159307,bonus_id=5060/1542/4786,context=35,azerite_powers=
#
# Wrap of Unity (35)
# back=,id=63207,context=14
#
# Cloak of Coordination (58)
# back=,id=65274,context=14
#
# Shroud of Cooperation (35)
# back=,id=63353,context=14
#
# Tunic of the Sanguine Deity (360)
# chest=,id=160728,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=485/22/87/13
#
# Spymaster's Wrap (340)
# chest=,id=155860,bonus_id=4819/1512/4786/5392,context=23,azerite_powers=
#
# Deathsnap Jerkin (375)
# chest=,id=157942,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=408/22/15/13
#
# Wharf Warden's Gloves (370)
# hands=,id=159328,enchant_id=5932,bonus_id=5007/1542/4783,context=35
#
# Silver-Trimmed Breeches (370)
# legs=,id=159297,gem_id=154127,bonus_id=5008/4802/1542/4783,context=16
#
# Gonk Outrunner Striders (325)
# feet=,id=157911,bonus_id=4803/1517/4785,context=26
#
# Seal of the City Watch (365)
# finger1=,id=162542,bonus_id=5009/1537/4786,context=16
#
# Loop of Pulsing Veins (365)
# finger1=,id=159463,bonus_id=5008/41/1537/4786,context=16
#
# Darkmoon Deck: Fathoms (355)
# trinket1=,id=159125,context=13
#
# Galecaller's Boon (355)
# trinket1=,id=159614,bonus_id=5006/1527/4786,context=16
#
# Plume of the Seaborne Avian (365)
# trinket1=,id=161378,bonus_id=4798/41/1487/4783,context=3
#
# Permafrost-Encrusted Heart (355)
# trinket1=,id=161381,bonus_id=4798/1808/1477/4786,context=3
#
# Pursax, the Backborer (375)
# main_hand=,id=160684,enchant_id=5963,bonus_id=4799/1497/4783,context=5
#
# Deep Fathom's Bite (370)
# main_hand=,id=159135,bonus_id=5008/1542/4783,context=16
#
# Pursax, the Backborer (375)
# off_hand=,id=160684,enchant_id=5963,bonus_id=4799/1497/4783,context=5
#
# Deep Fathom's Bite (370)
# off_hand=,id=159135,bonus_id=5008/1542/4783,context=16

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=8

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-13 02:13
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-13 02:13 UTC
