### ISSUE TITLE
[Death Knight] Seal of Necrofantasia

### ISSUE THREAD

**Issue by Demei** [simulationcraft/simc#3615] opened 2017-03-09 01:53 UTC
Build 715-02 22bf567

Is the death knight class module handling Seal of Necrofantasia correctly? The implementation appears to be multiplying the cooldown by (1 - the spelldata modifier), but the modifier is a negative number.  Wouldn't this result in the cooldown being increased rather than decreased by 10%? Running sims with no actions in the APL other than HRW and with Seal of Necrofantasia equipped and unequipped suggest that this is the case.

**Comment by lgkern** [comment] 2017-03-09 16:33
Thanks for the report, fixed on https://github.com/simulationcraft/simc/commit/cae5feccf20423988426ab2bfa2822bffccdd9ac

**Closed as completed by lgkern** 2017-03-09 16:33 UTC

**Comment by Sundava** [comment] 2017-03-09 16:40
The issue is fixed for Empower Rune Weapon, but the same line is present for Hungering Rune Weapon [on line 4886](https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_death_knight.cpp#L4886) and is still the same as before :
`      ( 1.0 - p() -> legendary.seal_of_necrofantasia -> effectN( 2 ).percent() );
`

**Comment by lgkern** [comment] 2017-03-09 16:44
Ops, fixed on https://github.com/simulationcraft/simc/commit/f9752bca3d5bc649cf9a0adc314a21b1d8b611ef
Also double checked for other mentions of the legendary.

**Comment by navv1234** [comment] 2017-03-09 17:46
Oops, should not fix things at work.
