### ISSUE TITLE
Can't simulate.

### ISSUE THREAD

**Issue by Shoka222** [simulationcraft/simc#4652] opened 2018-12-19 11:13 UTC
### Describe the bug
I can't start tbe simulation of my character.

### Expected behavior
I expected it to simulate as normal.

### To Reproduce
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Akohs': Item 'inactive' Slot 'head': Cannot parse option from ',id=159279,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=381/22/468/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
# SimC Addon 1.10.8
mage="Akohs"
level=120
race=pandaren
region=eu
server=stormscale
role=spell
professions=herbalism=150/mining=150
talents=1213123
spec=frost

head=,id=159279,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=381/22/468/13
neck=,id=158075,bonus_id=4936/4929/4930/1540,context=11,azerite_level=35
shoulder=,id=158344,bonus_id=5063/1557/4786/4775,context=35,azerite_powers=381/22/205/13
back=,id=160644,bonus_id=4799/1517/4784,context=5
chest=,id=163280,bonus_id=5125/1562/5138/5383/4775,context=28,azerite_powers=170/30/468/13
tabard=,id=43348
wrist=,id=160617,bonus_id=4799/1502/4783,context=5
hands=,id=159253,bonus_id=5010/1552/4783,context=35
waist=,id=159226,gem_id=154126,bonus_id=5010/4802/1552/4783,context=35
legs=,id=160615,bonus_id=4800/42/1507/4786,context=6
feet=,id=160714,bonus_id=4800/1507/4786,context=6
finger1=,id=160645,enchant_id=5942,bonus_id=4799/1492/4786,context=5
finger2=,id=160647,enchant_id=5942,bonus_id=4799/1502/4783,context=5
trinket1=,id=159624,bonus_id=5010/1552/4786,context=35
trinket2=,id=160651,gem_id=153709,bonus_id=4800/1808/1512/4783,context=6
main_hand=,id=160680,enchant_id=5949,gem_id=154126,bonus_id=4800/1808/1507/4786,context=6
off_hand=,id=160695,bonus_id=4800/1517/4783,context=6

### Gear from Bags
#
# Mantle of Contained Corruption (375)
# shoulder=,id=160613,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/31/15/13
#
# Sandspinner Vestments (375)
# chest=,id=157962,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=379/22/15/13
#
# Shadra Silk Robes (375)
# chest=,id=157930,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=132/22/44/13
#
# Fen Spirit Wraps (375)
# chest=,id=157898,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=225/31/85/13
#
# Honorbound Artificer's Cuffs (375)
# wrist=,id=163306,bonus_id=5126/1567/4783,context=6
#
# Ouroborial Sash (380)
# waist=,id=159255,bonus_id=5010/1552/4783,context=35
#
# Ivus' Tanglemoss Waistcord (385)
# waist=,id=166685,bonus_id=5479/1502/4786,context=3
#
# Rowdy Reveler's Legwraps (370)
# legs=,id=158350,bonus_id=5010/1542/4786,context=16
#
# Band of Certain Annihilation (370)
# finger1=,id=160646,enchant_id=5942,bonus_id=4799/1492/4786,context=5
#
# Loop of Pulsing Veins (380)
# finger1=,id=159463,enchant_id=5942,bonus_id=5010/1552/4783,context=35
#
# Ignition Mage's Fuse (375)
# trinket1=,id=159615,bonus_id=5009/1547/4783,context=35

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

### Additional information
SimulationCraft 801-01 WebEngine

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by AlexanderKenny** [comment] 2018-12-19 13:08
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-19 13:08 UTC
