### ISSUE TITLE
Simulation Runtime Error - Crucible

### ISSUE THREAD

**Issue by A11ectis** [simulationcraft/simc#4009] opened 2017-09-15 00:43 UTC
#### Simulationcraft Version
730-01
1.8.2 Add-on

#### simc_gui.simc file or contents
https://pastebin.com/1aNMq12V

#### Reproduction Steps:

Use /simc in-game when Crucible is unlocked, and trying to sim.

**Comment by AlexanderKenny** [comment] 2017-09-15 00:45
Duplicate of #4000 read the comments on that issue for how to fix

**Closed as completed by AlexanderKenny** 2017-09-15 00:45 UTC
