### ISSUE TITLE
Not sure how to open a ticket, but this is what I got from SimulationCraft

### ISSUE THREAD

**Issue by doutrnz** [simulationcraft/simc#4790] opened 2019-04-09 18:13 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Dysonshock item 'inactive': Unable to parse item options str ',id=26004,bonus_id=3635,drop_level=13,context=11': : Unexpected parameter 'context'.
Unable to parse item 'inactive' options on player 'Dysonshock'
Simulation has been canceled during player setup! (thread=0)                     
Dysonshock item 'inactive': Unable to parse item options str ',id=26004,bonus_id=3635,drop_level=13,context=11': : Unexpected parameter 'context'.
Unable to parse item 'inactive' options on player 'Dysonshock'
Simulation has been canceled during player setup! (thread=0)                     
Dysonshock item 'inactive': Unable to parse item options str ',id=26004,bonus_id=3635,drop_level=13,context=11': : Unexpected parameter 'context'.
Unable to parse item 'inactive' options on player 'Dysonshock'
Simulation has been canceled during player setup! (thread=0)                     

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
mage="Dysonshock"
level=20
race=draenei
region=us
server=stormrage
role=spell
professions=herbalism=82/skinning=95
talents=2000000
spec=frost

back=,id=24104,bonus_id=3799,drop_level=8,context=11
chest=,id=26004,bonus_id=3635,drop_level=13,context=11
shirt=,id=23473
wrist=,id=3603,context=14
hands=,id=26009,bonus_id=3635,drop_level=16,context=11
waist=,id=56673,bonus_id=3643,drop_level=18,context=11
legs=,id=14119,bonus_id=1678/3829,drop_level=15,context=26
feet=,id=24112,bonus_id=3674/5619,drop_level=12,context=11
main_hand=,id=24342,bonus_id=3635,drop_level=14,context=11
off_hand=,id=27398,bonus_id=3635,drop_level=15,context=11

### Gear from Bags
#
# Candlewax Streaked Robe (20)
# chest=,id=57398,bonus_id=3796,drop_level=20,context=11
#
# Crime Scene Tape (20)
# waist=,id=58907,bonus_id=3637,drop_level=20,context=11
#
# Staats' Fishing Pole (10)
# main_hand=,id=46337,context=11

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2019-04-10 04:44
Duplicate of #4613

**Closed as completed by vituscze** 2019-04-10 04:44 UTC
