### ISSUE TITLE
Deteriorated Construct Core From Karazhan Doesnt work in Sim

### ISSUE THREAD

**Issue by Schichtkohl** [simulationcraft/simc#3122] opened 2016-11-06 15:14 UTC
Simulatet multiple fights with this trinket and it just not shows in the DMG. 
Are the Trinkets from Karazhan already able to be simulated?

**Comment by kenthklui** [comment] 2016-11-08 20:53
Construt core should be added as of 6 days ago: https://github.com/simulationcraft/simc/commit/b3d36f68849217bacd0dd705938bb10c2a1974c3

Please check that you are using the nightly or wait for next release.

**Comment by kenthklui** [comment] 2016-11-08 20:54
Closing as a duplicate of #3100

**Closed as completed by kenthklui** 2016-11-08 20:54 UTC
