### ISSUE TITLE
Runtime Error Sin Rogue

### ISSUE THREAD

**Issue by Ghoster1211** [simulationcraft/simc#4013] opened 2017-09-15 10:52 UTC
# SimulationCraft encountered an error (Version 730-01)
* Category: Simulation runtime error
* Error: Player Wishper invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
rogue="Wishper"
level=110
race=human
region=us
server=frostmourne
role=attack

talents=1133111
spec=assassination
artifact=43:0:0:0:0:323:4:324:4:325:4:326:4:327:4:328:4:329:4:330:4:331:4:332:1:333:1:334:1:335:1:337:1:346:1:347:1:1276:1:1384:1:1577:4:1578:1:1579:1:1580:8:1651:1
crucible=1739/1739/1739

head=,id=152759,bonus_id=1678/3629/1492/3337
neck=,id=147014,bonus_id=3564/1467/3528
shoulder=,id=137455,bonus_id=3573/1567/3336
back=,id=152400
chest=,id=152358,bonus_id=3614/1472/3528
wrist=,id=134280,bonus_id=3573/1577/3336
hands=,id=134444,bonus_id=3412/1567/3337
waist=,id=152364,bonus_id=3614/1472/3528
legs=,id=137069,bonus_id=3459/3570
feet=,id=137030,bonus_id=1811/3570
finger1=,id=147020,bonus_id=3564/1477/3336
finger2=,id=148071,bonus_id=3579/1522/3528
trinket1=,id=142164,bonus_id=3573/1552/3337
trinket2=,id=147009,bonus_id=3561/1482/3528
main_hand=,id=128870,gem_id=147109/151011/151189,bonus_id=741,relic_id=3561:1487:3336/3397:3174:3528/3564:1482:3337
off_hand=,id=128869

### Gear from Bags
#
# Fierce Gladiator's Pendant (910)
# neck=,id=148031,bonus_id=3573/1542/3528
#
# Clasp of Burning Demise (920)
# neck=,id=147765,bonus_id=3573/1502/3336
#
# Footpads of the Swift Balestra (920)
# feet=,id=137497,bonus_id=3573/1572/3336
#
# Eternal Groom's Wedding Band (660)
# finger1=,id=141882,bonus_id=1794,drop_level=110
#
# Ring of the Dread Pirate Bob (660)
# finger1=,id=129070,bonus_id=1794,drop_level=110
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-15 11:32
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-15 11:32 UTC
Labels: duplicate
