### ISSUE TITLE
as the software suggetsts

### ISSUE THREAD

**Issue by Blondysinger** [simulationcraft/simc#4024] opened 2017-09-16 18:42 UTC
SimulationCraft encountered an error!

Simulation runtime error:
Player Takaya invalid crucible format, expected: power_id:rank[:power_id:rank...] Player Takaya invalid crucible format, expected: power_id:rank[:power_id:rank...] Player Takaya invalid crucible format, expected: power_id:rank[:power_id:rank...]

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Takaya invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Takaya invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Takaya invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
druid="Takaya"
level=110
race=night_elf
region=eu
server=pozzo_delleternit
role=spell
professions=tailoring=790/enchanting=770
talents=3213233
spec=balance
artifact=59:0:0:0:0:1034:4:1035:4:1036:4:1037:4:1038:4:1039:4:1040:4:1041:4:1042:4:1043:1:1044:1:1045:1:1046:1:1047:1:1048:1:1049:1:1294:1:1364:1:1501:4:1502:1:1503:1:1504:12:1632:1
crucible=1739:1781/1739:1781/1739

head=,id=137062,bonus_id=1811/3570
neck=,id=134529,enchant_id=5890,bonus_id=3418/41/1587/3337
shoulder=,id=147138,enchant_id=5931,bonus_id=3561/1497/3337
back=,id=147134,enchant_id=5436,bonus_id=3562/1502/3336
chest=,id=147133,bonus_id=3561/1482/3528
tabard=,id=69210
wrist=,id=134280,bonus_id=3573/1577/3336
hands=,id=151318,bonus_id=3417/1597/3337
waist=,id=147347,bonus_id=3561/1497/3336
legs=,id=147137,bonus_id=3564/1467/3528
feet=,id=137023,bonus_id=3459/3570
finger1=,id=134279,enchant_id=5428,bonus_id=3573/1577/3336
finger2=,id=134531,enchant_id=5428,bonus_id=3418/1577/3336
trinket1=,id=147017,bonus_id=3561/1487/3336
trinket2=,id=147019,bonus_id=3564/1517/3337
main_hand=,id=128858,gem_id=139269/137381/147076,bonus_id=722,relic_id=3573:1532:3528/3573:1562:3528/3562:1497:3528

### Gear from Bags
#
# Cappuccio di Cuor Tempesta (900)
# head=,id=147136,bonus_id=3561/1482/3528
#
# Copricapo Foderato di Cuoio di Vilpipistrello (910)
# head=,id=134372,bonus_id=3573/42/1572/3528
#
# Copritesta Segnato dall'Ombra (895)
# head=,id=147034,bonus_id=3564/1477/3528
#
# Cappuccio del Bosco dei Sogni (840)
# head=,id=139726,bonus_id=3385/3384
#
# Pendente del Gladiatore Feroce (885)
# neck=,id=145498,enchant_id=5897,bonus_id=3567/1517/3336
#
# Antico Pendente degli Augari della Folgore (910)
# neck=,id=152780,enchant_id=5439,bonus_id=1762/3573/1502/3528
#
# Medaglione delle Anime Scheggiate (905)
# neck=,id=147014,enchant_id=5439,bonus_id=3561/1487/3336
#
# Collana del Gladiatore Violento (910)
# neck=,id=148029,bonus_id=3573/1542/3528
#
# Coprispalle del Demonio Fatuo (900)
# shoulder=,id=146774,bonus_id=3394/1562/3337
#
# Mantello dello Zolfo Soffocante (905)
# back=,id=146984,enchant_id=5436,bonus_id=3561/1487/3336
#
# Mantello dell'Unità (35)
# back=,id=63206
#
# Drappo di Cuor Tempesta (890)
# back=,id=147134,enchant_id=5436,bonus_id=3564/1472/3336
#
# Manto della Cooperazione (35)
# back=,id=63352
#
# Vestito Semplice Nero (1)
# chest=,id=10053
#
# Giubba del Supervisore degli Imp (945)
# chest=,id=152358,bonus_id=3614/1487/3337
#
# Insegna della Crociata d'Argento (1)
# tabard=,id=46874
#
# Polsiere Foderate del Cantalame (900)
# wrist=,id=134280,bonus_id=3414/41/1562/3528
#
# Guanti delle Pulsioni Ribelli (900)
# hands=,id=147032,bonus_id=3561/1482/3528
#
# Pantaloni Borchiati d'Ossa (900)
# legs=,id=147035,bonus_id=3561/1482/3528
#
# Gambiere dei Graffiasangue (915)
# legs=,id=134449,bonus_id=3418/1567/3528
#
# Calzature di Cuoio del Terrore della Bramosia (900)
# feet=,id=128885,bonus_id=689/1700/3408/601/679
#
# Anello con Sigillo dell'Impero di Nazjatar (900)
# finger1=,id=134525,enchant_id=5429,gem_id=130218,bonus_id=3417/1808/1552/3337
#
# Vera a Scaglie della Servitù (900)
# finger1=,id=147020,enchant_id=5428,bonus_id=3561/1482/3528
#
# Segreto di Sephuz (970)
# finger1=,id=132452,enchant_id=5428,gem_id=130248,bonus_id=3459/3570
#
# Generatore di Bombe Scoiattolo d'Elementio (935)
# trinket1=,id=137446,bonus_id=3418/1587/3337
#
# Urna Eterea (885)
# trinket1=,id=142166,bonus_id=40/3573/1482/3336
#
# Terrore dagli Abissi (900)
# trinket1=,id=147016,bonus_id=3561/1808/1482/3528
#
# Turibolo Spettrale (925)
# trinket1=,id=147018,bonus_id=3561/1507/3337
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2017-09-16 18:45
Duplicate of #4000 

Read the comments there on how to resolve this.

**Closed as completed by AlexanderKenny** 2017-09-16 18:45 UTC
