### ISSUE TITLE
The desktop app doesn't work + bug at simulation

### ISSUE THREAD

**Issue by dralsoM** [simulationcraft/simc#4645] opened 2018-12-17 17:50 UTC
The application does not work 2 times out of 3 and when I can do a simulation there is an error.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Dralsom': Item 'inactive' Slot 'head': Cannot parse option from ',id=127548,bonus_id=5130,drop_level=108,context=22': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=bfahead/local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers,wdps,wohdps
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
# SimC Addon 1.10.8
rogue="Dralsom"
level=111
race=undead
region=eu
server=hyjal
role=attack
professions=herbalism=6/mining=19
talents=2212221
spec=assassination

head=,id=127548,bonus_id=5130,drop_level=108,context=22
neck=,id=158075,bonus_id=4932/4933/4935/1474,context=11,azerite_level=2
shoulder=,id=160919,context=11,azerite_powers=82/87
back=,id=159292,bonus_id=4776/40,drop_level=111,context=17
chest=,id=127593,bonus_id=5130/5131,drop_level=104,context=22
shirt=,id=11840,context=1
wrist=,id=129228,bonus_id=768/1739,drop_level=108,context=11
hands=,id=130292,bonus_id=767,drop_level=110,context=11
waist=,id=133490,bonus_id=5130,drop_level=105,context=22
legs=,id=121184,bonus_id=1812/1695,drop_level=101
feet=,id=121659,bonus_id=767/1734,drop_level=109,context=11
finger1=,id=129239,bonus_id=768,drop_level=106,context=11
finger2=,id=141294,context=11
trinket1=,id=129318,bonus_id=664,drop_level=100,context=11
trinket2=,id=158374,gem_id=153714,bonus_id=4776/4802,drop_level=110,context=17
main_hand=,id=163525,context=11
off_hand=,id=133491,bonus_id=5130/5131,drop_level=104,context=22

### Gear from Bags
#
# Grande cape de la cité d’or (222)
# back=,id=155305,bonus_id=4790/4791,drop_level=110,context=11


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-17 17:51
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-17 17:51 UTC
