### ISSUE TITLE
Unable to make simulations

### ISSUE THREAD

**Issue by mattewho** [simulationcraft/simc#4709] opened 2019-01-23 22:54 UTC
### Describe the bug
when i try to make simulations, appear a little window with a message. i try to unistall and install again..but nothing happen.

### Additional information
last version.

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  # SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Paparedlock': Item 'inactive' Slot 'head': Cannot parse option from ',id=158315,bonus_id=5448/1557/4786/5402/4775,context=35,azerite_powers=183/30/85/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.10
warlock="Paparedlock"
level=120
race=nightborne
region=eu
server=pozzo_delleternità
role=spell
professions=tailoring=150/enchanting=85
talents=3312323
spec=affliction

head=,id=158315,bonus_id=5448/1557/4786/5402/4775,context=35,azerite_powers=183/30/85/13
neck=,id=158075,bonus_id=4936/4929/4930/1544,context=11,azerite_level=37
shoulder=,id=166554,bonus_id=5126/1502/4786/5403/4775,context=6,azerite_powers=442/22/85/13
back=,id=160643,bonus_id=4799/1492/4786,context=5
chest=,id=159233,bonus_id=5448/1557/4786/5401/4775,context=35,azerite_powers=123/22/208/13
tabard=,id=160545,context=14
wrist=,id=160617,bonus_id=4799/40/1517/4784,context=5
hands=,id=163428,bonus_id=5125/1577/4784,context=29
waist=,id=157908,bonus_id=4803/1562/4786,context=28
legs=,id=160615,bonus_id=4799/1492/4786,context=5
feet=,id=165465,bonus_id=5126/1502/4786,context=6
finger1=,id=160646,enchant_id=5944,bonus_id=4799/1492/4786,context=5
finger2=,id=162542,enchant_id=5940,bonus_id=5010/42/1542/4786,context=16
trinket1=,id=166793,bonus_id=5479/1512/4783,context=3
trinket2=,id=159631,bonus_id=5010/1557/4783,context=35
main_hand=,id=158321,enchant_id=5963,bonus_id=5010/1542/4786,context=16
off_hand=,id=165582,bonus_id=4798/1507/4786,context=3

### Gear from Bags
#
# Maschera dell'Ingegnere della Brigata dell'Onore (375)
# head=,id=163426,bonus_id=5125/1562/4786/5399/4775,context=28,azerite_powers=429/22/15/13
#
# Vesti dell'Ingegnere della Brigata dell'Onore (375)
# chest=,id=163280,bonus_id=5125/1562/5138/5383/4775,context=28,azerite_powers=458/30/14/13
#
# Vera degli Assalti Multidirezionali (390)
# finger1=,id=165565,bonus_id=4798/1512/4783,context=3
#
# Anello Adornato di Elun'dris (370)
# finger1=,id=165679,enchant_id=5939,bonus_id=4803/1562/4786,context=28
#
# Vera dell'Antico Dragatore (385)
# finger1=,id=159461,enchant_id=5943,bonus_id=5010/4802/1557/4783,context=35

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2019-01-23 23:04
Duplicate of #4613

**Closed as completed by vituscze** 2019-01-23 23:04 UTC
