### ISSUE TITLE
Sim Error - new Leather Helm 

### ISSUE THREAD

**Issue by Sicsixsicks** [simulationcraft/simc#4658] opened 2018-12-20 21:32 UTC
SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Sicsixsicks': Item 'inactive' Slot 'head': Cannot parse option from ',id=166688,bonus_id=5478/1502/4786/5402,context=3,azerite_powers=245/31/87': Unexpected parameter 'context'.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Sicsixsicks': Item 'inactive' Slot 'head': Cannot parse option from ',id=166688,bonus_id=5478/1502/4786/5402,context=3,azerite_powers=245/31/87': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
demonhunter="Sicsixsicks"
level=120
race=blood_elf
region=us
server=area_52
role=attack
professions=alchemy=140/herbalism=150
talents=1313231
spec=havoc

head=,id=166688,bonus_id=5478/1502/4786/5402,context=3,azerite_powers=245/31/87
neck=,id=158075,bonus_id=4936/4929/4930/1530,context=11,azerite_level=30
shoulder=,id=157883,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=245/459/15/13
back=,id=159289,bonus_id=5010/1552/4786,context=35
chest=,id=160619,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/31/15/13
wrist=,id=160621,bonus_id=4799/1497/4783,context=5
hands=,id=155889,bonus_id=5010/1567/4784,context=16
waist=,id=160717,bonus_id=4800/1507/4786,context=6
legs=,id=159345,gem_id=154127,bonus_id=5009/4802/1562/4784,context=35
feet=,id=160624,bonus_id=4800/1507/4786,context=6
finger1=,id=160645,enchant_id=5943,gem_id=153708,bonus_id=4800/1808/1512/4783,context=6
finger2=,id=159461,bonus_id=5009/1537/4786,context=16
trinket1=,id=160648,bonus_id=4799/1497/4783,context=5
trinket2=,id=159623,bonus_id=5009/1537/4786,context=16
main_hand=,id=160681,enchant_id=5962,gem_id=154127,bonus_id=4800/1808/1512/4783,context=6
off_hand=,id=160681,enchant_id=5963,bonus_id=4800/1507/4786,context=6

### Gear from Bags
#
# Finely-Tailored Red Holiday Hat (1)
# head=,id=139299,context=5
#
# Gonk Outrunner Mask (375)
# head=,id=157913,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=160/101/84/13
#
# Gonk Outrunner Shoulderguards (360)
# shoulder=,id=157915,bonus_id=1547/5140/5379/4775,context=28,azerite_powers=353/30/15/13
#
# Jerkin of the Aberrant Chimera (375)
# chest=,id=160619,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=246/89/15/13
#
# Blood Bog Wraps (375)
# chest=,id=157878,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=194/98/85/13

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

Log saved to: C:\Simulationcraft(x64)\simc-801-01-win64\simc-801-01-win64\log.txt

**Comment by vituscze** [comment] 2018-12-20 21:38
Duplicate of #4613 

Please update your simc to 810-01 or use one of the recent nightly builds.

**Closed as completed by vituscze** 2018-12-20 21:38 UTC
