### ISSUE TITLE
rogue problem

### ISSUE THREAD

**Issue by gelfb** [simulationcraft/simc#4752] opened 2019-03-02 18:23 UTC
SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Chichera': Item 'inactive' Slot 'head': Cannot parse option from ',id=166563,bonus_id=5126/1517/4786/5417,context=6,azerite_powers=249/136/30/15': Unexpected parameter 'context'.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Chichera': Item 'inactive' Slot 'head': Cannot parse option from ',id=166563,bonus_id=5126/1517/4786/5417,context=6,azerite_powers=249/136/30/15': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.11
rogue="Chichera"
level=120
race=blood_elf
region=eu
server=sanguino
role=attack
professions=mining=150/engineering=126
talents=2211221
spec=assassination

head=,id=166563,bonus_id=5126/1517/4786/5417,context=6,azerite_powers=249/136/30/15
neck=,id=158075,bonus_id=4936/4929/4930/1550,context=11,azerite_level=40
shoulder=,id=159339,bonus_id=5448/1587/4786/5421,context=35,azerite_powers=408/193/30
back=,id=159289,bonus_id=5007/1577/4784,context=35
chest=,id=165515,bonus_id=4823/1522/4786/5416,context=5,azerite_powers=408/406/461/548
wrist=,id=165524,bonus_id=4799/1808/1522/4786,context=5
hands=,id=163437,gem_id=154127,bonus_id=5125/4802/1572/4783,context=29
waist=,id=159325,gem_id=154127,bonus_id=5008/4802/1572/4783,context=35
legs=,id=165528,bonus_id=4799/1522/4786,context=5
feet=,id=159343,bonus_id=5010/1572/4786,context=16
finger1=,id=166559,enchant_id=5943,context=14
finger2=,id=162542,enchant_id=5943,bonus_id=5009/41/1577/4783,context=35
trinket1=,id=165572,bonus_id=4798/1507/4786,context=3
trinket2=,id=165568,gem_id=154127,bonus_id=4799/1808/1522/4786,context=5
main_hand=,id=165593,enchant_id=5965,bonus_id=4798/1507/4786,context=3
off_hand=,id=158114,enchant_id=5962,bonus_id=4803/1577/4786,context=28

### Gear from Bags
#
# Collar de mortacechador (400)
# head=,id=165475,bonus_id=5126/1517/4786/5417,context=6,azerite_powers=
#
# Broche de perfume dulce (365)
# neck=,id=143909,bonus_id=5472,drop_level=120
#
# Guiño de amor (365)
# neck=,id=143905,bonus_id=5472,drop_level=120
#
# Gargantilla de miseria de Beleron (190)
# neck=,id=140899,bonus_id=3518/40/1484/3528,context=6
#
# Sobrehombros de acechador fantasmal (390)
# shoulder=,id=165523,bonus_id=4822/1507/4786/5415/4775,context=3,azerite_powers=407/181/30/15/13
#
# Capa de la Compañía Gobernalle de la navaja (266)
# back=,id=159230,bonus_id=4796/1679,drop_level=120
#
# Mantón del vasallo leal (395)
# back=,id=158375,bonus_id=5008/1567/4786,context=16
#
# Mantón de escolta de los Defensores del Honor (370)
# back=,id=163360,bonus_id=5125/1562/4786,context=29
#
# Jubón del Aullido de Fatalidad (370)
# chest=,id=161456,bonus_id=5120/1492/4786/5398,context=3,azerite_powers=
#
# Toga de erudito temporal de la navaja (158)
# chest=,id=121052,bonus_id=1812/1678,drop_level=120
#
# Jubón de avanzado de Gonk (385)
# chest=,id=157910,bonus_id=1577/4786/5413,context=28,azerite_powers=
#
# Guardabrazos de chascamuerte (355)
# wrist=,id=157949,bonus_id=4803/4802/1547/4785,context=26
#
# Brazales de escolta de los Defensores del Honor (375)
# wrist=,id=163309,bonus_id=5125/1567/4783,context=29
#
# Guardamuñecas de nadaarenas (395)
# wrist=,id=159332,bonus_id=5008/1567/4786,context=16
#
# Ataduras de cuero de aspirante siniestro (360)
# wrist=,id=165076,bonus_id=1502/4785,context=47
#
# Guantes de cuero de Gladiador siniestro (385)
# hands=,id=164789,bonus_id=5173/5142/1497/4786,context=56
#
# Cincho de pellejo de bestia de guerra (400)
# waist=,id=165518,bonus_id=4799/1522/4786,context=5
#
# Cinturón de cuero de aspirante siniestro (365)
# waist=,id=165075,bonus_id=1507/4781,context=47
#
# Faja de chascamuerte (400)
# waist=,id=157948,bonus_id=4803/1592/4784,context=28
#
# Hebilla de escolta de los Defensores del Honor (370)
# waist=,id=163439,bonus_id=5125/1562/4786,context=29
#
# Musleras de cuero de aspirante siniestro (360)
# legs=,id=165073,bonus_id=1502/4785,context=47
#
# Pantalones de escolta de los Defensores del Honor (370)
# legs=,id=163298,bonus_id=5125/1562/4786,context=29
#
# Musleras de cuero de Gladiador siniestro (385)
# legs=,id=164791,bonus_id=5252/5141/1497/4786,context=25
#
# Grebas con cordones de algas (370)
# legs=,id=165528,bonus_id=4801/1492/4786,context=4
#
# Musleras de cuero de aspirante siniestro (360)
# legs=,id=165073,bonus_id=1502/4785,context=47
#
# Botines de mortacechador (355)
# feet=,id=165473,bonus_id=5124/4802/1472/4785,context=3
#
# Sandalias de Vallecánido del destello (266)
# feet=,id=159188,bonus_id=4796/1691,drop_level=120
#
# Zancos de avanzado de Gonk (390)
# feet=,id=157911,bonus_id=4803/1582/4784,context=28
#
# Zarpa cortante de Kimbul (385)
# trinket1=,id=165579,bonus_id=4798/1507/4786,context=3
#
# Martillo de guerra de los Defensores del Honor (370)
# main_hand=,id=166337,bonus_id=5125/43/1562/4786,context=29
#
# Caña de pescar fuerte (10)
# main_hand=,id=6365,context=14
#
# Quiebracalaveras de los Defensores del Honor (380)
# main_hand=,id=163866,bonus_id=5125/1572/4783,context=29
#
# Daga de los Defensores del Honor (370)
# main_hand=,id=163868,bonus_id=5125/1562/4786,context=29
#
# Faca de aspirante siniestro (360)
# main_hand=,id=165194,bonus_id=1502/4785,context=47
#
# Pico de minero (4)
# main_hand=,id=2901,context=14
#
# Daga de los Defensores del Honor (340)
# main_hand=,id=163868,bonus_id=5125/1532/4786,context=5
#
# Martillo de guerra de los Defensores del Honor (370)
# off_hand=,id=166337,bonus_id=5125/43/1562/4786,context=29
#
# Quiebracalaveras de los Defensores del Honor (380)
# off_hand=,id=163866,bonus_id=5125/1572/4783,context=29
#
# Daga de los Defensores del Honor (370)
# off_hand=,id=163868,bonus_id=5125/1562/4786,context=29
#
# Daga de los Defensores del Honor (340)
# off_hand=,id=163868,bonus_id=5125/1532/4786,context=5
#
# Faca de aspirante siniestro (360)
# off_hand=,id=165194,bonus_id=1502/4785,context=47

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=3


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###

**Comment by Mystler** [comment] 2019-03-02 18:42
You are using an outdated version of SimC. I recommend getting a nightly build or using raidbots.com.

**Comment by vituscze** [comment] 2019-03-02 19:57
Duplicate of #4613

**Closed as completed by vituscze** 2019-03-02 19:57 UTC
