### ISSUE TITLE
[Closed][Duplicate][#4613] Simc Wow Addon returns an error when using pasted text in tool

### ISSUE THREAD

**Issue by grimuletz** [simulationcraft/simc#4640] opened 2018-12-16 13:00 UTC
### Describe the bug
After using "/simc" command in WoW, on main character, copying and pasting the text in the tool returns this error:
"Initializing: Actor 'Slynk': Item 'inactive' Slot 'head': Cannot parse option from ',id=163435,bonus_id=5125/1547/4786/5396/4775,context=29,azerite_powers=239/30/83/13': Unexpected parameter 'context'."

### Expected behavior
Profile should be loaded correctly

### To Reproduce
Download WoW Addons via Twitch: Simulationcraft,Stat Weight Score,Pawn
Download Simulationcraft Program
Opens tool, launches WoW
Types /simc in chat
Copies text and pastes to Sim tool
Attempts to simulate

### Additional information
* SimulationCraft Version ( SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) 
Using QT 5.10.1 with WebEngine

* **simc_gui.simc** file or contents: https://pastebin.com/b6qPz30G
  [log.txt](https://github.com/simulationcraft/simc/files/2683555/log.txt)

**Comment by AlexanderKenny** [comment] 2018-12-16 14:02
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-16 14:02 UTC

**Comment by grimuletz** [comment] 2018-12-16 14:19
I've updated to the lastest version, using the link you've provided, AlexanderKenny.
Thanks for the help and sorry for the duplicate, I'm learning as I go.

Have a nice day!
