### ISSUE TITLE
[DH] Blade Dance false positives with imperfect skill

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#2879] opened 2016-09-23 21:02 UTC
Simming with a lower "player skill" then "Elite" results in Blade Dance being utilized on Patchwerk Sims which is wrong. 

`demonhunter="DB CB PVP"
level=110
race=night_elf
region=eu
server=malganis
role=attack
professions=mining=479/engineering=669
talents=1233111
spec=havoc
artifact=3:0:0:0:0:1001:3:1002:3:1003:3:1005:3:1006:3:1010:1:1011:1:1012:1:1013:1:1015:1:1016:1:1330:1

head=,id=134196,bonus_id=1727/1507/3336
neck=,id=121193,bonus_id=1727/1745/1632/1813
shoulder=,id=136284,enchant_id=5882,bonus_id=3428/1715/1477/3336
back=,id=134405,enchant_id=5432,bonus_id=1727/1808/1492/1813,gem_id=130219
chest=,id=134197,bonus_id=3432/1512/3337
wrist=,id=133621,bonus_id=1727/1808/1497/3336,gem_id=130219
hands=,id=136741,bonus_id=1727/1502/1813
waist=,id=139243,bonus_id=1727/1502/3336
legs=,id=134448,bonus_id=1727/1492/1813
feet=,id=139716,bonus_id=3385/3384
finger1=,id=139236,bonus_id=1805/1487
finger2=,id=135682,bonus_id=3428/1477/3336
trinket1=,id=135693,bonus_id=3428/1477/3336
trinket2=,id=139113,bonus_id=3397/607/1512/3337
main_hand=,id=127829,bonus_id=719,relic_id=3432:1507:3336/1807:1472/3428:1642:3336,gem_id=141255/138226/140427/0
off_hand=,id=127830,relic_id=0/0,gem_id=0/0/0/0
`

Sim 10.000 iterations, 300 seconds, 10% varying time

Elite -> No Blade dance (right)
Good -> Blade Dance

**Comment by Collisionc** [comment] 2016-09-29 21:43
I can set blade dance to not roll a "false positive", aka using the ability when you shouldn't.  Lowering player skill basically tells the action list to occasionally ignore the conditions set for the spell to be used. Is blade dance something that tanks would never use by accident?

**Comment by aggixx** [comment] 2016-10-01 01:17
As collision said, this is essentially working as intended. Having less than elite skill means (among other things) that you will use abilities when they shouldn't normally be used.

@Collisionc Its not a tank ability, but it is somewhat reasonable that you wouldn't accidentally use an AoE ability on single target. Not sure if thats enough to justify disabling false positives.

**Comment by ghost** [comment] 2016-10-01 09:26
hey guys!

Blade Dance is not used in Single Target scenarios at all, so even a player
who is not "elite" will not use it by accident in my opinion. The only
reason to dump fury into BD would be that you are capped and out of range
by a few meters. But even there it would be a waste and you should wait the
millisecond to use a chaos strike.

On Patchwerk it should be disabled (false positive?) for sure, unless the
person runs First Blood in the 3rd Tier instead of Bloodlet or Felblade.

**Comment by Collisionc** [comment] 2016-10-09 07:22
Fair enough, I'll set it to not roll false positives.

**Comment by Collisionc** [comment] 2016-10-09 07:25
Ok, fixed in next release.

**Closed as completed** 2016-10-11 04:39 UTC
Labels: Fixed
