### ISSUE TITLE
64bit version hangs when it attempts to open the Results page 

### ISSUE THREAD

**Issue by fateswarm** [simulationcraft/simc#2625] opened 2015-09-07 20:00 UTC
Let me know if you need any further info. It works normally until after the simulation is done it tries to show the Results page. It's blank, it only renders the "Results 1" tab text and it hangs the program requiring an exit. 

It feels like an eternal loop is going on.

**Comment by fateswarm** [comment] 2015-09-07 20:01
PS. No issues on the 32bit version. Also the 64bit version rarely works normally.

**Comment by skules** [comment] 2015-09-07 20:21
Bump, can confirm. 64 bit version hangs when trying to display result

**Comment by navv1234** [comment] 2015-09-07 20:22
I uploaded an experimental release at http://downloads.simulationcraft.org/reia/simc-release.zip that you can try.

**Comment by skules** [comment] 2015-09-07 20:27
Still freezes navv

**Comment by navv1234** [comment] 2015-09-07 20:31
Are you using highcharts or google charts in the option?

**Comment by navv1234** [comment] 2015-09-07 20:32
This may be related: https://bugreports.qt.io/browse/QTBUG-47018

**Comment by skules** [comment] 2015-09-07 20:39
Apparently i'm using google charts. I don't see the option to turn it off however, only google or high charts. I'll check out your link

**Comment by navv1234** [comment] 2015-09-07 20:44
Yeah, it's likely that issue from Qt. I'm not using HiDPI windows (only full-hd) so can't really test this.

**Comment by skules** [comment] 2015-09-07 20:48
Is there a fix for it? I can only see a way to reproduce the bug, but i'm using 100% on windows 7. not windows 8 and 150%+

**Comment by navv1234** [comment] 2015-09-07 20:50
The fix is that we swap to webkit for the time being. Up to @Collisionc really, but I would very much recommend it, until Qt people get the fix in.

**Comment by skules** [comment] 2015-09-07 21:21
Just a heads up aswell. I get "ordinal 3906 in dynamic library not found" thing when using the 622-01 32 bit version.

620-02 32bit works fine.

**Comment by fateswarm** [comment] 2015-09-08 08:18
Changing to Highcharts does not alter the behavior.

**Comment by scamille** [comment] 2015-09-09 07:07
Duplicate of #2613

**Closed by scamille** 2015-09-09 07:07 UTC

**Comment by fateswarm** [comment] 2015-10-16 13:51
I managed to reproduce this hang here on a msvc debug build after a couple of simulations (it occasionally doesn't hang). (I assume the default 64bit 7zip is on Webkit now, because I couldn't reproduce it there). 

Since it only hangs, doesn't crash, I can only break. It complains that it doesn't have the symbols of Qt5WebEngineCored.dll :

http://i.imgur.com/8pAzKEj.png

**Comment by fateswarm** [comment] 2015-10-16 20:37
OK, I'm getting somewhere. --disable-gpu appears to avoid the hang. Inspiration from https://bugreports.qt.io/browse/QTBUG-48276
