### ISSUE TITLE
SimulationCraft encountered an error!

### ISSUE THREAD

**Issue by eldoranstars** [simulationcraft/simc#4617] opened 2018-12-11 20:05 UTC
Simulation runtime error:
Initializing: Actor 'Скилнакд': Item 'inactive' Slot 'head': Cannot parse option from ',id=160634,bonus_id=4824/1507/4786/4775,context=6,azerite_powers=483/31/15/13': Unexpected parameter 'context'.

[log.txt](https://github.com/simulationcraft/simc/files/2669184/log.txt)

**Comment by eldoranstars** [comment] 2018-12-11 20:06
I have windows 7 before. And everything is work. But now I have windows 10. And I have a problem with simulation....

**Comment by seriallos** [comment] 2018-12-11 20:13
Duplicate of #4613 

Update your local SimC program, grab one of the recent nightly SimC builds from http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by seriallos** 2018-12-11 20:13 UTC
Labels: duplicate

**Comment by eldoranstars** [comment] 2018-12-12 16:50
TY! it help!
