### ISSUE TITLE
DH bug with azerit traits

### ISSUE THREAD

**Issue by Canabel** [simulationcraft/simc#4623] opened 2018-12-13 07:10 UTC
SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Canabelle': Item 'inactive' Slot 'head': Cannot parse option from ',id=160623,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=352/31/15/13': Unexpected parameter 'context'.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Canabelle': Item 'inactive' Slot 'head': Cannot parse option from ',id=160623,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=352/31/15/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=100000
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=6
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
demonhunter="Canabelle"
level=120
race=blood_elf
region=eu
server=hyjal
role=attack
professions=herbalism=150/enchanting=77
talents=1331212
spec=havoc

head=,id=160623,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=352/31/15/13
neck=,id=158075,bonus_id=4933/4936/4929/1532,context=11,azerite_level=31
shoulder=,id=159331,bonus_id=5054/1542/4786/4775,context=35,azerite_powers=352/31/564/13
back=,id=159287,bonus_id=5008/41/1542/4786,context=35
chest=,id=163283,bonus_id=5126/1562/4786/4775,context=6,azerite_powers=126/31/15/13
wrist=,id=163309,enchant_id=5971,bonus_id=5126/1562/4786,context=6
hands=,id=160618,enchant_id=5932,bonus_id=4799/1492/4786,context=5
waist=,id=160622,bonus_id=4799/1497/4783,context=5
legs=,id=159329,bonus_id=5008/1547/4783,context=35
feet=,id=159336,gem_id=154128,bonus_id=5005/4802/1532/4783,context=16
finger1=,id=160645,enchant_id=5939,bonus_id=4798/1477/4786,context=3
finger2=,id=158314,enchant_id=5941,bonus_id=5005/1527/4786,context=16
trinket1=,id=160652,bonus_id=4798/1477/4786,context=3
trinket2=,id=160648,gem_id=154127,bonus_id=4798/1808/1477/4786,context=3
main_hand=,id=160681,enchant_id=5963,bonus_id=4799/1492/4786,context=5
off_hand=,id=163866,enchant_id=5962,gem_id=154128,bonus_id=5124/4802/1537/4783,context=3

### Gear from Bags
#
# Chapel du voltigeur honorable (375)
# head=,id=163435,bonus_id=5125/1562/4786/5399/4775,context=29,azerite_powers=221/101/83/13
#
# Chaperon claquemort (375)
# head=,id=157945,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=355/99/44/13
#
# Bassinet de Tourbesang (375)
# head=,id=157881,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=480/22/83/13
#
# Chapeau de capitaine bleu pillé (1)
# head=,id=164367,context=11
#
# Spallières couvertes de sang de l’usurpateur (360)
# shoulder=,id=160620,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=483/43/202/13
#
# Protège-épaules de Tourbesang (375)
# shoulder=,id=157883,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=221/89/15/13
#
# Garde-épaules d’estafette de Gonk (375)
# shoulder=,id=157915,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=134/20/15/13
#
# Cape enchevêtrée d’horreur fétide (370)
# back=,id=160643,bonus_id=4799/1492/4786,context=5
#
# Cape en peau de dragon vert (350)
# back=,id=150411,bonus_id=5384,drop_level=120,context=3
#
# Tunique du voltigeur honorable (370)
# chest=,id=163283,bonus_id=5125/1562/4786/5398,context=29,azerite_powers=
#
# Pourpoint de la chimère absurde (360)
# chest=,id=160619,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=483/89/83/13
#
# Pourpoint de la chimère absurde (375)
# chest=,id=160619,bonus_id=4823/1492/4786/5398/4775,context=5,azerite_powers=483/89/83/13
#
# Gants de folie approchante (355)
# hands=,id=160618,enchant_id=5932,bonus_id=4798/40/1477/4786,context=3
#
# Ceinture de détermination resplendissante (360)
# waist=,id=158306,bonus_id=5007/42/1532/4786,context=16
#
# Chevalière du seigneur Malvoie (350)
# finger1=,id=158362,enchant_id=5939,bonus_id=5002/1522/4786,context=16
#
# Anneau de championnat de footbombe (370)
# finger1=,id=159462,enchant_id=5941,bonus_id=5006/1542/4784,context=16
#
# Bague d’annihilation certaine (355)
# finger1=,id=160646,enchant_id=5939,bonus_id=4801/40/1477/4784,context=4
#
# Cœur résonnant d’Azerokk (360)
# trinket1=,id=159612,bonus_id=5006/1532/4783,context=16
#
# Longue-vue d’œil-mort (360)
# trinket1=,id=159623,bonus_id=5006/42/1532/4783,context=16
#
# Faveur de mande-trombe (355)
# trinket1=,id=159614,bonus_id=5005/40/1527/4786,context=16
#
# Figurine de Loa dorée (345)
# trinket1=,id=158153,bonus_id=4803/1537/4783,context=28
#
# Sillage du malheur (370)
# trinket1=,id=161462,bonus_id=5119/1492/4786,context=3
#
# Lame de cauchemar (350)
# main_hand=,id=150393,enchant_id=5966,bonus_id=5384,drop_level=120,context=3
#
# Griffe trancheuse d’âme (355)
# main_hand=,id=160269,enchant_id=5963,bonus_id=5006/42/1527/4786,context=16
#
# Lame de cauchemar (350)
# off_hand=,id=150393,enchant_id=5966,bonus_id=5384,drop_level=120,context=3
#
# Griffe trancheuse d’âme (355)
# off_hand=,id=160269,enchant_id=5963,bonus_id=5006/42/1527/4786,context=16

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=7


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-13 07:11
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-13 07:11 UTC
