### ISSUE TITLE
Sim aint running, encountering this issue.

### ISSUE THREAD

**Issue by Niunka** [simulationcraft/simc#4267] opened 2018-02-03 18:35 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Niunka invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.9.1

paladin="Niunka"
level=110
race=human
region=eu
server=the_maelstrom
role=attack
professions=blacksmithing=47/mining=237
talents=1332212
spec=retribution
artifact=2:0:0:0:0:350:1:351:1:352:1:353:1:1118:1:1275:1:1561:4:1562:1:1563:1:1564:25:1647:1:40:1:41:4:42:4:43:4:49:1:54:1:47:4:44:4:53:4:52:4:51:4:50:4
crucible=1739:1779:1561/1739:1774:53/1739:1778:42

head=,id=152013,bonus_id=3611/41/1487/3528
neck=,id=151965,enchant_id=5890,bonus_id=3611/1487/3528
shoulder=,id=152153,enchant_id=5929,bonus_id=3610/1482/3336
back=,id=137020,enchant_id=5434,bonus_id=3459/3630
chest=,id=152148,gem_id=151583,bonus_id=3611/1808/1492/3336
wrist=,id=134520,bonus_id=3536/1612/3337
hands=,id=152150,bonus_id=3611/1487/3528
waist=,id=152020,gem_id=151585,bonus_id=3611/1808/1487/3528
legs=,id=152152,bonus_id=3611/1507/3337
feet=,id=152011,bonus_id=3612/1512/3336
finger1=,id=151644,enchant_id=5428,gem_id=151583,bonus_id=1811/3630
finger2=,id=152688,enchant_id=5428,bonus_id=3610/1482/3336
trinket1=,id=151964,bonus_id=3611/1487/3528
trinket2=,id=154176,bonus_id=3985/3989
main_hand=,id=120978,gem_id=152043/152036/152046,bonus_id=737,relic_id=3610:1472:3528/3611:1487:3528/3611:1492:3336

### Gear from Bags
#
# Light's Vanguard Helm (915)
# head=,id=152151,bonus_id=3613/1457/3528
#
# The Topless Tower (1000)
# head=,id=151782,bonus_id=1811/3630
#
# Helmet of Reverent Loyalty (940)
# head=,id=134513,bonus_id=3536/1592/3528
#
# Crown of Burning Resolve (930)
# head=,id=152376,bonus_id=3614/41/1472/3528
#
# Titan-Subjugator's Visage (930)
# head=,id=152014,bonus_id=3610/1808/1472/3528
#
# Justice Gaze (1000)
# head=,id=137065,bonus_id=3459/3630
#
# Chain of the Unmaker (940)
# neck=,id=152283,enchant_id=5890,bonus_id=3610/1472/3528
#
# Man'ari Training Amulet (800)
# neck=,id=153130
#
# Shoulderguards of Indomitable Purpose (945)
# shoulder=,id=152416,bonus_id=3611/40/1487/3528
#
# Pauldrons of the All-Father (940)
# shoulder=,id=133631,enchant_id=5929,bonus_id=3509/1592/3337
#
# Seacursed Wrap (960)
# back=,id=133771,bonus_id=3535/1612/3337
#
# Maraad's Dying Breath (1000)
# back=,id=144273,bonus_id=3459/3630
#
# Light's Vanguard Greatcloak (945)
# back=,id=152149,enchant_id=5436,bonus_id=3611/1487/3528
#
# Soul-Tempered Chestplate (945)
# chest=,id=152017,bonus_id=3611/40/1487/3528
#
# Stormwind Tabard (1)
# tabard=,id=45574
#
# Uther's Guard (1000)
# wrist=,id=137105,bonus_id=3459/3630
#
# Portalguard Gauntlets (955)
# hands=,id=134356,bonus_id=3535/1617/3337
#
# Light's Vanguard Gauntlets (930)
# hands=,id=152150,bonus_id=3610/1472/3528
#
# Molten Bite Handguards (960)
# hands=,id=152012,bonus_id=3612/41/1502/3528
#
# Chain of Thrayn (1000)
# waist=,id=137086,bonus_id=3459/3630
#
# Flamelicked Girdle (945)
# waist=,id=152021,bonus_id=3611/1487/3528
#
# World-Defiler's Tuille of the Peerless (880)
# legs=,id=152945,bonus_id=1685/1472/3528
#
# Cosmos-Culling Legplates (955)
# legs=,id=152016,bonus_id=3611/1487/3528
#
# Aggramar's Stride (1000)
# feet=,id=132443,bonus_id=1811/3630
#
# Insignia of the Grand Army (1000)
# finger1=,id=152626,enchant_id=5427,gem_id=151580,bonus_id=1811/3630
#
# Sephuz's Secret (1000)
# finger1=,id=132452,bonus_id=3459/3630
#
# Seal of the Portalmaster (945)
# finger1=,id=152063,enchant_id=5428,bonus_id=3611/1487/3528
#
# Seal of the Second Duumvirate (930)
# finger1=,id=147195,enchant_id=5429,bonus_id=3562/1512/3336
#
# Tarratus Keystone (960)
# trinket1=,id=151958,bonus_id=3610/1502/3337
#
# Aggramar's Conviction (960)
# trinket1=,id=154173,bonus_id=3984/3989
#
# Memento of Angerboda (960)
# trinket1=,id=133644,bonus_id=3536/1612/3337
#
# Orb of Torment (955)
# trinket1=,id=137538,bonus_id=3535/1607/3337
#
# Forgefiend's Fabricator (940)
# trinket1=,id=151963,bonus_id=3610/1482/3336
#
# Garothi Feedback Conduit (960)
# trinket1=,id=151956,bonus_id=3612/1502/3528
#
# Giant Ornamental Pearl (935)
# trinket1=,id=137369,bonus_id=3535/1587/3528
#
# Writhing Heart of Darkness (910)
# trinket1=,id=137315,gem_id=151583,bonus_id=3416/1808/1562/3528
#
# Vitality Resonator (945)
# trinket1=,id=151970,bonus_id=3611/1487/3528
#
# Fel-Oiled Infernal Machine (930)
# trinket1=,id=144482,bonus_id=3417/1582/3337
#
# Krokul Mining Pick (800)
# main_hand=,id=153290
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2018-02-03 19:06
Duplicate of #4000

**Closed as completed by vituscze** 2018-02-03 19:06 UTC
