### ISSUE TITLE
Simulation runtime error

### ISSUE THREAD

**Issue by silodin** [simulationcraft/simc#4017] opened 2017-09-15 18:48 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Notacaster invalid crucible rank '1777/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Notacaster invalid crucible rank '1777/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Notacaster invalid crucible rank '1777/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=100000
default_world_lag=0.025
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Normal
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
scale_over=DPS
dps_plot_stat=str,sta,crit,haste,mastery,vers
dps_plot_points=20
dps_plot_step=150
dps_plot_target_error=0.5
dps_plot_iterations=0
statistics_level=1
### End GUI options ###
### Begin simulateText ###
warrior="Notacaster"
level=110
race=orc
region=eu
server=draenor
role=attack
professions=blacksmithing=762/herbalism=252
talents=3312322
spec=arms
artifact=36:0:0:0:0:1136:1:1137:1:1138:1:1139:1:1140:1:1141:1:1142:1:1143:4:1144:4:1145:4:1146:4:1147:4:1148:4:1149:4:1150:4:1151:4:1356:1:1393:1:1613:4:1614:1:1615:1:1616:10:1714:1
crucible=1739:1777/1739/1739

head=,id=142126,bonus_id=3573/1527/3528
neck=,id=147014,enchant_id=5439,gem_id=151584,bonus_id=3561/1808/1482/3528
shoulder=,id=147192,bonus_id=3564/1467/3528
back=,id=147932,enchant_id=5434,bonus_id=3573/1706/1542/3528
chest=,id=152378,bonus_id=3614/1472/3528
shirt=,id=4344
tabard=,id=45581
wrist=,id=134522,bonus_id=3410/1562/3337
hands=,id=152751,bonus_id=1698/3629/1482/3336
waist=,id=134137,bonus_id=3573/42/1572/3528
legs=,id=121280,bonus_id=1825/1572/3337
feet=,id=147059,bonus_id=3561/1487/3336
finger1=,id=137052,enchant_id=5429,gem_id=151584,bonus_id=1811/3570
finger2=,id=134191,enchant_id=5429,gem_id=151584,bonus_id=3573/1808/1572/3528
trinket1=,id=147278,bonus_id=607/42/3573/3159/3528
trinket2=,id=144259,bonus_id=3459/3570
main_hand=,id=128910,gem_id=150293/144466/151013,bonus_id=750,relic_id=3579:3139:3528/3410:1562:3337/3397:3189:3337

### Gear from Bags
#
# Skoldiir Helm (910)
# head=,id=134182,bonus_id=3573/1808/1572/3528
#
# Fierce Combatant's Plate Shoulders (915)
# shoulder=,id=149747,bonus_id=3573/1679/1577/3336
#
# Titanic Onslaught Greaves (890)
# legs=,id=147191,bonus_id=3564/1472/3336
#
# Aggramar's Stride (970)
# feet=,id=132443,bonus_id=1811/3570
#
# Coral Band of the Abyss (900)
# finger1=,id=147767,enchant_id=5429,bonus_id=3572/1482/3528
#
# Ironrune Charm (890)
# trinket1=,id=134190,bonus_id=3394/604/1552/3336
#
# Toe Knee's Promise (920)
# trinket1=,id=142164,bonus_id=3573/1537/3336
#
# An'she's Invigoring Charm (910)
# trinket1=,id=139102,bonus_id=3573/607/1572/3528
#
# Claw of the Crystalline Scorpid (910)
# trinket1=,id=140790,bonus_id=3573/42/1507/3528
#
# Brumdysla, Hammer of Vrorsk (1)
# main_hand=,id=136350
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by vituscze** [comment] 2017-09-15 19:38
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-15 19:38 UTC
Labels: duplicate
