### ISSUE TITLE
Havoc DH Problems 7.3

### ISSUE THREAD

**Issue by Vaados** [simulationcraft/simc#4020] opened 2017-09-15 21:23 UTC
Hello, my simcraft doesn't work, need a fix or somebody who can tell me how to fix that?

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Vaados invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
demonhunter="Vaados"
level=110
race=blood_elf
region=eu
server=malganis
role=attack
professions=leatherworking=800/skinning=800
talents=2221311
spec=havoc
artifact=3:0:0:0:0:1000:4:1001:4:1002:4:1003:4:1004:4:1005:4:1006:4:1007:4:1008:4:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:1:1493:4:1494:1:1495:1:1496:12:1630:1
crucible=0/0/0

head=,id=147130,bonus_id=3561/1507/3337
neck=,id=137461,enchant_id=5437,bonus_id=3536/1582/3337
shoulder=,id=144279,enchant_id=5883,bonus_id=3459/3570
back=,id=147128,bonus_id=3562/1497/3528
chest=,id=137336,bonus_id=3536/1582/3337
tabard=,id=31780
wrist=,id=133621,bonus_id=3573/1562/3528
hands=,id=147129,enchant_id=5446,bonus_id=3562/40/1497/3528
waist=,id=136776,bonus_id=3536/1582/3337
legs=,id=147131,bonus_id=3562/1497/3528
feet=,id=147030,bonus_id=3562/1507/3336
finger1=,id=137038,enchant_id=5427,bonus_id=1811/3570
finger2=,id=134489,enchant_id=5427,bonus_id=3536/1582/3337
trinket1=,id=151190,bonus_id=3562/1808/1507/3528
trinket2=,id=147009,bonus_id=3562/1808/1497/3528
main_hand=,id=127829,bonus_id=719,relic_id=3536:1542:3337/3561:1502:3336/3517:1507:3337
off_hand=,id=127830

### Gear from Bags
#
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-15 22:22
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-15 22:22 UTC
Labels: duplicate
