### ISSUE TITLE
Invalid crucible format

### ISSUE THREAD

**Issue by Majei** [simulationcraft/simc#4002] opened 2017-09-14 14:39 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Majei invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Majei invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Majei invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Majei invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
mage="Majei"
level=110
race=human
region=eu
server=silvermoon
role=spell
professions=tailoring=743/jewelcrafting=800
talents=3133123
spec=fire
artifact=54:0:0:0:0:748:1:749:3:750:3:751:3:752:3:753:3:754:3:755:3:756:3:757:3:758:1:759:1:760:1:761:1:762:1:763:1:1340:1:1372:1
crucible=0/0/0

head=,id=147147,bonus_id=3562/1497/3528
neck=,id=132444,enchant_id=5439,gem_id=130248,bonus_id=1811/3570
shoulder=,id=134177,bonus_id=3418/1587/3336
back=,id=134406,enchant_id=5436,bonus_id=3535/1602/3337
chest=,id=147149,bonus_id=3561/1497/3337
shirt=,id=18231
tabard=,id=52252
wrist=,id=134398,bonus_id=3536/1592/3337
hands=,id=147146,bonus_id=3561/1492/3336
waist=,id=134423,gem_id=130220,bonus_id=3418/1808/1587/3337
legs=,id=147148,bonus_id=3562/1497/3528
feet=,id=146987,bonus_id=3562/1497/3528
finger1=,id=147194,bonus_id=3561/1492/3336
finger2=,id=147195,enchant_id=5428,bonus_id=3562/1507/3528
trinket1=,id=147017,bonus_id=3562/1497/3528
trinket2=,id=147016,bonus_id=3562/1497/3528
main_hand=,id=128820,gem_id=151009/151006/151009,bonus_id=730,relic_id=3397:3189:3337/3397:3184:3336/3397:3184:3336
off_hand=,id=133959

### Gear from Bags
#
# Collar of Raking Claws (930)
# head=,id=134426,bonus_id=3536/1582/3337
#
# Understone Gorget (915)
# neck=,id=134491,enchant_id=5439,bonus_id=3510/1567/3337
#
# Mantle of the Arcane Tempest (910)
# shoulder=,id=147150,bonus_id=3561/1492/3336
#
# Shoulderpads of Whispering Twilight (915)
# shoulder=,id=146997,bonus_id=3562/1497/3528
#
# Shoulderpads of Whispering Twilight (900)
# shoulder=,id=146997,bonus_id=3561/42/1482/3528
#
# Ice Time (970)
# shoulder=,id=144260,enchant_id=5931,bonus_id=1811/3570
#
# Shroud of the Drowned Adherent (920)
# back=,id=146985,bonus_id=3562/1502/3336
#
# Drape of the Arcane Tempest (905)
# back=,id=147145,bonus_id=3561/1808/1487/3336
#
# Belo'vir's Final Stand (970)
# chest=,id=133977,bonus_id=1811/3570
#
# Tunic of Smoldering Ire (925)
# chest=,id=137352,bonus_id=3536/1808/1577/3337
#
# Ooze-Soaked Shirt (1)
# shirt=,id=98084
#
# Magtheridon's Banished Bracers (970)
# wrist=,id=138140,bonus_id=3459/3570
#
# Fel-Flecked Grips (915)
# hands=,id=146989,bonus_id=3562/1497/3528
#
# Fel-Flecked Grips (915)
# hands=,id=146989,bonus_id=3562/1497/3528
#
# Fel-Flecked Grips (915)
# hands=,id=146989,bonus_id=3562/1497/3528
#
# Zann'esu Journey (970)
# waist=,id=133970,bonus_id=1811/3570
#
# Braided Torture Lash (920)
# waist=,id=146998,bonus_id=3562/40/1502/3336
#
# Leggings of Divine Portents (930)
# legs=,id=146993,bonus_id=3562/1512/3337
#
# Azurelight Sage's Leggings of the Feverflare (885)
# legs=,id=152776,bonus_id=1698/1808/3629/1477/3336
#
# Oakheart's Trunkwarmers (915)
# legs=,id=137304,bonus_id=3535/1567/3336
#
# Terrorweave Leggings (930)
# legs=,id=121326,bonus_id=3536/1592/3337
#
# Leggings of the Arcane Tempest (900)
# legs=,id=147148,bonus_id=3561/1482/3528
#
# Legwraps of Fused Loathing (900)
# legs=,id=146992,bonus_id=3561/1482/3528
#
# Shard of the Exodar (970)
# finger1=,id=132410,enchant_id=5428,gem_id=151583,bonus_id=1811/3570
#
# Soul of the Archmage (970)
# finger1=,id=151642,enchant_id=5427,gem_id=130219,bonus_id=1811/3570
#
# Band of the Wyrm Matron (915)
# finger1=,id=134524,enchant_id=5428,gem_id=151583,bonus_id=3535/1808/1567/3336
#
# Nightmare Loop (910)
# finger1=,id=121288,enchant_id=5428,gem_id=151583,bonus_id=3573/1808/41/1572/3528
#
# Band of Fused Coral (910)
# finger1=,id=134532,bonus_id=3573/1562/3528
#
# Leycoral Shard (910)
# trinket1=,id=134248,bonus_id=3573/604/1572/3337
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-14 15:00
Duplicate of #4000 

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-14 15:00 UTC
Labels: duplicate
