### ISSUE TITLE
Simulationcraft doesn't start 

### ISSUE THREAD

**Issue by st0neface97** [simulationcraft/simc#3715] opened 2017-04-20 21:45 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

simc 720 01 64 bit doesn't start after updating to windows 10 creators update

[DxDiag.txt](https://github.com/simulationcraft/simc/files/945550/DxDiag.txt)

Any way to get it to work?

**Comment by nuoHep** [comment] 2017-04-21 17:29
Duplicate of #3706

**Closed as completed** 2017-09-26 23:51 UTC
Labels: duplicate
