### ISSUE TITLE
umbral moonglaves

### ISSUE THREAD

**Issue by Fyshtank** [simulationcraft/simc#4240] opened 2018-01-18 08:48 UTC
getting spammed with
unknown spell with ID umbral_moonglaves used in PreviousOFFGCDSpell(umbral_moonglaves)

**Comment by vituscze** [comment] 2018-01-18 11:59
Can you provide steps to reproduce this? Simc input perhaps?

**Comment by Fyshtank** [comment] 2018-01-18 12:38
Here is the simc input data that I have generated from my character.
Hope this help
Thanks Fýshtank

**Comment by vituscze** [comment] 2018-01-23 02:07
Looks like this is related to Ovale and not simc itself, closing.

**Closed as completed by vituscze** 2018-01-23 02:07 UTC
