### ISSUE TITLE
hello cant sim my char

### ISSUE THREAD

**Issue by Yodacream** [simulationcraft/simc#4003] opened 2017-09-14 15:31 UTC
SimulationCraft encountered an error!

Simulation runtime error:
Player Yodacream invalid crucible format, expected: power_id:rank[:power_id:rank...] Player Yodacream invalid crucible format, expected: power_id:rank[:power_id:rank...]

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Yodacream invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Yodacream invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=25000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
demonhunter="Yodacream"
level=110
race=blood_elf
region=eu
server=skullcrusher
role=attack

talents=2221311
spec=havoc
artifact=3:0:0:0:0:1000:4:1001:4:1002:4:1003:4:1004:4:1005:4:1006:4:1007:4:1008:4:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:1:1493:4:1494:1:1495:1:1496:8:1630:1
crucible=1739/1739/1739

head=,id=147130,bonus_id=3561/43/1482/3528
neck=,id=132444,enchant_id=5437,gem_id=151580,bonus_id=3459/3570
shoulder=,id=144279,bonus_id=3529/3459/3570
back=,id=147128,enchant_id=5435,bonus_id=3561/1502/3337
chest=,id=137336,bonus_id=3510/1567/3337
wrist=,id=147042,bonus_id=3562/1497/3528
hands=,id=147129,bonus_id=3562/1507/3336
waist=,id=147425,bonus_id=3562/1517/3337
legs=,id=147131,bonus_id=3562/1497/3528
feet=,id=139105,bonus_id=3418/41/1602/3337
finger1=,id=147021,enchant_id=5427,bonus_id=3562/1497/3528
finger2=,id=142172,enchant_id=5427,bonus_id=3418/1527/3528
trinket1=,id=147009,bonus_id=3562/1497/3528
trinket2=,id=142506,gem_id=151580,bonus_id=3573/1808/41/604/1537/3336
main_hand=,id=127829,gem_id=144459/142310/147086,bonus_id=719,relic_id=3418:1587:3337/3416:1522:3528/3562:1497:3528
off_hand=,id=127830

### Gear from Bags
#
# Empyrial Deep Crown of the Fireflash (885)
# head=,id=151588,bonus_id=601/1690/3408/3598/3609
#
# Raddon's Cascading Eyes (970)
# head=,id=137061,bonus_id=1811/3570
#
# Lunar-Wrath Headgear (920)
# head=,id=147033,bonus_id=3562/1502/3336
#
# Brysngamen, Torc of Helheim (925)
# neck=,id=133636,bonus_id=3418/1577/3336
#
# Locket of Splintered Souls (905)
# neck=,id=147014,bonus_id=3561/1487/3336
#
# Pendant of the Stormforger (895)
# neck=,id=133767,enchant_id=5437,bonus_id=3416/1547/3336
#
# Shredded Felbroken Shawl (110)
# back=,id=152862
#
# Demonbane Shroud (915)
# back=,id=147128,bonus_id=3562/1497/3528
#
# Cape of Mindless Fury (905)
# back=,id=147193,enchant_id=5435,gem_id=130219,bonus_id=3561/1808/1487/3336
#
# Sinew-Stitched Wristguards (915)
# wrist=,id=147041,bonus_id=3562/1497/3528
#
# Gloves of Wayward Compulsions (915)
# hands=,id=147032,gem_id=130219,bonus_id=3562/1808/1497/3528
#
# Cinidaria, the Symbiote (970)
# waist=,id=133976,bonus_id=1811/3570
#
# Prophetic Band of the Fireflash (900)
# finger1=,id=130229,enchant_id=5427,gem_id=151580,bonus_id=3350/689/600/679
#
# Band of the Wyrm Matron (915)
# finger1=,id=134524,enchant_id=5427,bonus_id=3573/1567/3336
#
# Jeweled Signet of Melandrus (900)
# finger1=,id=134542,enchant_id=5427,bonus_id=3510/1552/3336
#
# Engine of Eradication (920)
# trinket1=,id=147015,bonus_id=3562/1502/3336
#
# Mark of Dargrul (935)
# trinket1=,id=137357,bonus_id=3418/1587/3337
#
# Umbral Moonglaives (900)
# trinket1=,id=147012,bonus_id=3561/1482/3528
#
# Cradle of Anguish (915)
# trinket1=,id=147010,bonus_id=3562/1497/3528
#
# Spiked Counterweight (910)
# trinket1=,id=136715,bonus_id=3415/1562/3337
#
# Vial of Ceaseless Toxins (915)
# trinket1=,id=147011,bonus_id=3562/1497/3528
#
# Darkmoon Deck: Dominion (900)
# trinket1=,id=128705,bonus_id=689/600/679
#
# Tirathon's Betrayal (930)
# trinket1=,id=137537,bonus_id=3573/1582/3337
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-14 15:38
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-14 15:38 UTC
Labels: duplicate
