### ISSUE TITLE
Cannot Simulate, Works for Frost and Blood but not Unholy spec

### ISSUE THREAD

**Issue by Cursdblood** [simulationcraft/simc#5097] opened 2020-05-02 12:50 UTC
# Cursdblood - Unholy - 2020-05-02 14:46 - EU/Kazzak
# SimC Addon 1.12.5
# Requires SimulationCraft 820-01 or newer

deathknight="Cursdblood"
level=71
race=undead
region=eu
server=kazzak
role=attack

talents=3233000
spec=unholy

head=,id=122263,bonus_id=3592
neck=,id=122662,bonus_id=582
shoulder=,id=122372,bonus_id=3592
back=,id=122266,bonus_id=582
chest=,id=122387,bonus_id=3592
tabard=,id=45583,context=14
wrist=,id=39680,bonus_id=4139/5569,drop_level=66,context=11
hands=,id=113692,bonus_id=4242/24,drop_level=66,context=1
waist=,id=43168,bonus_id=4117,drop_level=68,context=11
legs=,id=122264,bonus_id=3592
feet=,id=39098,bonus_id=3688,drop_level=69,context=11
finger1=,id=38218,bonus_id=4139,drop_level=66,context=11
finger2=,id=43178,bonus_id=4117,drop_level=68,context=11
trinket1=,id=122361,bonus_id=582
trinket2=,id=38761,bonus_id=3688,drop_level=70,context=11
main_hand=,id=122365,enchant_id=3368,bonus_id=583

### Gear from Bags
#
# Eternal Emberfury Talisman (85)
# neck=,id=122667,bonus_id=582
#
# Obsidian Citadel Necklace of the Fireflash (79)
# neck=,id=113688,bonus_id=4242/23,drop_level=68,context=1
#
# Blood-Tempered Spaulders (81)
# shoulder=,id=37783,context=1
#
# Orca Spaulders of the Aurora (67)
# shoulder=,id=36217,bonus_id=1709/3840,drop_level=70,context=28
#
# Worn Stoneskin Gargoyle Cape (85)
# back=,id=122260,bonus_id=583
#
# Syreian's Leggings of the Aurora (84)
# legs=,id=44676,bonus_id=1705/3767,drop_level=70
#
# Inherited Mark of Tyranny (85)
# trinket1=,id=122530,bonus_id=582
#
# Inherited Insignia of the Horde (85)
# trinket1=,id=122370
#
# Swift Hand of Justice (85)
# trinket1=,id=122361,bonus_id=582
#
# Bloodsoaked Skullforge Reaver (85)
# main_hand=,id=122389,enchant_id=3370,bonus_id=582
#
# Battleworn Thrash Blade (85)
# main_hand=,id=122369,enchant_id=3368,bonus_id=582
#
# Reforged Truesilver Champion (85)
# main_hand=,id=122365,enchant_id=3847,bonus_id=583
#
# Abandoned Greatsword (58)
# main_hand=,id=33430,bonus_id=3890,drop_level=70,context=28

**Comment by Melekus** [comment] 2020-05-04 17:00
Duplicate of #5098

**Closed as completed by Melekus** 2020-05-04 17:00 UTC
