### ISSUE TITLE
771 legendary ring simming lower than 668 ring

### ISSUE THREAD

**Issue by rmstep** [simulationcraft/simc#2675] opened 2016-01-13 16:19 UTC
This is simming my character in SimulationCraft 623-01 (build level 20726)

I was testing the scaling of the legendary ring with upgrades, and I noticed the 771 ilevel ring data is way out of wack.

Here's my numbers with the delta in the right column (25,000 iterations, 300 second fight duration, all other settings on defaults)
![image](https://cloud.githubusercontent.com/assets/4852030/12299533/302ace14-b9e5-11e5-9aab-55d7ef62e910.png)

I ran it with 10k iterations a few times with 450 second fight length, and I've double checked my inputs. It looks like BOS damage is low on the 771 ring (it's the biggest single ability dps delta in the data).

I've attached my sim results here at the end (the results_html.txt is html version)
[results_html.txt](https://github.com/simulationcraft/simc/files/89136/results_html.txt)
[results_text.txt](https://github.com/simulationcraft/simc/files/89139/results_text.txt)

EDIT: Also, I did try running the nightly build to see if it was still an issue in the recent builds, but it didn't run, just crashed immediately (no window even pops up)

**Comment by mrdmnd** [comment] 2016-01-13 18:42
Goodness, that does seem.. very broken.

**Comment by mrdmnd** [comment] 2016-01-13 18:42
Is this reproducible on the build from the master branch?

**Comment by jordantoine** [comment] 2016-01-13 19:00
seems likely to be a weird stat threshold thing than anything with that specific version of the ring. Here's another DK with 771 ring being higher dps than 768.

[results_text.txt](https://github.com/simulationcraft/simc/files/89361/results_text.txt)

**Comment by navv1234** [comment] 2016-01-13 20:21
Yeah, it seems like a weird local thing due to the way default APL handles BoS. The peculiar thing is that the three DPS stats that change have no effect on anything that I can think of that would relate to BoS uptime, or indeed actor behavior with BoS.

**Comment by rmstep** [comment] 2016-01-13 20:59
Didn't even think to try other spec/talents... When I use NP + UB talents on a UH DK, it appears to sim properly (25k iterations) 

768 = 73127 DPS
771 = 73548 DPS

**Comment by navv1234** [comment] 2016-01-13 21:01
Yeah, what exactly goes wrong is somewhat unknown at the moment, though. You could try to see if adjusting that magical 75 runic power requirement for BoS gets you anywhere.

**Comment by mrdmnd** [comment] 2016-01-13 21:07
I am working on the default APLs this week, hopefully this will be resolved
when I put in the "pool for BoS when it's nearly off CD" logic.

**Comment by navv1234** [comment] 2016-01-13 21:08
Perhaps. Debugging that requires some additional code, probably. If I have the motivation, I'll try to take a look during the weekend. Need slight inspiration on what I need to look for first, though.

**Comment by rmstep** [comment] 2016-01-14 22:36
So I tested with some other UH DKs and I don't see this same problem. Must be something buzzards with my character's stat breakpoints. I'll run a few more sims changing some things and see if I can narrow it dow.

**Comment by mrdmnd** [comment] 2016-01-24 21:43
Going to close this as unreproducible; if you've managed to find a way to repro this bug, please feel free to re-open.

**Closed by mrdmnd** 2016-01-24 21:43 UTC
