### ISSUE TITLE
Sim Error -

### ISSUE THREAD

**Issue by minion1390** [simulationcraft/simc#4050] opened 2017-09-22 03:29 UTC
# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'crucible' with value '1739/1739/1739'

## All options used for simulation:
``` ini
### Begin GUI options ###
ptr=0
item_db_source=ptrhead/local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
warrior="Miníon"
level=110
race=tauren
region=us
server=thrall
role=attack
professions=blacksmithing=800/alchemy=800
talents=1332232
spec=fury
artifact=35:0:0:0:0:980:1:981:1:982:1:984:1:985:1:986:1:987:1:988:4:989:4:990:4:991:4:992:4:993:4:994:4:995:4:996:4:1357:1:1394:1:1617:4:1618:1:1619:1:1620:7:1715:1
crucible=1739/1739/1739

head=,id=147190,bonus_id=3561/1482/3528
neck=,id=147013,enchant_id=5439,bonus_id=3562/1497/3528
shoulder=,id=147192,gem_id=151583,bonus_id=3561/1808/1482/3528
back=,id=137053,enchant_id=5434,bonus_id=3529/3459/3570
chest=,id=147187,gem_id=151583,bonus_id=3562/1808/1502/3336
shirt=,id=14617
wrist=,id=147073,bonus_id=3562/1507/3336
hands=,id=147189,bonus_id=3562/1507/3336
waist=,id=150494,gem_id=130220,bonus_id=3589/3590/1808/41,drop_level=110
legs=,id=151824,bonus_id=3459/3570
feet=,id=139241,bonus_id=3418/1592/3337
finger1=,id=147020,enchant_id=5428,bonus_id=3562/1502/3336
finger2=,id=134525,enchant_id=5428,gem_id=151583,bonus_id=3418/1808/1567/3528
trinket1=,id=147010,bonus_id=3562/1502/3336
trinket2=,id=147012,bonus_id=3562/1507/3336
main_hand=,id=128908,gem_id=147088/151523/147101,bonus_id=751,relic_id=3562:1497:3528/3567:3149:3337/3561:1492:3336
off_hand=,id=134553

### Gear from Bags
#
# Armet of the Rotten Mind (915)
# head=,id=147063,bonus_id=3564/1497/3337
#
# Weather-Beaten Fishing Hat (10)
# head=,id=33820,enchant_id=2543
#
# Ceann-Ar Charger (970)
# head=,id=137088,bonus_id=1811/3570
#
# Storm-Tempered Greathelm of the Savant (885)
# head=,id=147244,bonus_id=1721/3573/3134/3336
#
# Helmet of Reverent Loyalty (915)
# head=,id=134513,bonus_id=3573/1567/3336
#
# Brysngamen, Torc of Helheim (910)
# neck=,id=133636,bonus_id=3415/1562/3336
#
# Prydaz, Xavaric's Magnum Opus (970)
# neck=,id=132444,enchant_id=5889,gem_id=130220,bonus_id=3459/3570
#
# Locket of Splintered Souls (940)
# neck=,id=147014,enchant_id=5889,bonus_id=3562/1522/3337
#
# Dread Commander's Pauldrons (925)
# shoulder=,id=144501,enchant_id=5883,gem_id=130246,bonus_id=3535/1808/1577/3337
#
# Shoulderplates of Crackling Flame (915)
# shoulder=,id=147069,bonus_id=3562/1497/3528
#
# Ley-Scarred Pauldrons (855)
# shoulder=,id=134316,enchant_id=5883,gem_id=130222,bonus_id=1824/1808/42/1517/3528
#
# Timeless Stratagem (970)
# shoulder=,id=143728,bonus_id=3459/3570
#
# Cloak of Unwavering Loyalty (945)
# back=,id=134412,enchant_id=5434,bonus_id=3418/1597/3337
#
# Drape of the Raven Lord (875)
# back=,id=136770,bonus_id=3413/42/1527/3528
#
# Cloak of Stifling Brimstone (915)
# back=,id=146984,enchant_id=5434,bonus_id=3562/1497/3528
#
# Cloak of Coordination (60)
# back=,id=65274
#
# Arcane Defender's Breastplate (855)
# chest=,id=134267,bonus_id=1824/42/1517/3528
#
# Titanic Onslaught Breastplate (915)
# chest=,id=147187,bonus_id=3562/43/1497/3528
#
# Argent Crusader's Tabard (1)
# tabard=,id=46874
#
# Mannoroth's Bloodletting Manacles (970)
# wrist=,id=137107,bonus_id=3459/3570
#
# Inordinately Wondrous Wristguards (865)
# wrist=,id=142198,bonus_id=1727/1808/42/1482/3528
#
# Arcane Defender's Gauntlets (915)
# hands=,id=134268,bonus_id=3510/1577/3337
#
# Skoldiir Gauntlets (865)
# hands=,id=134180,bonus_id=1727/42/1527/3528
#
# Groundshatter Gauntlets (920)
# hands=,id=147062,bonus_id=3562/1502/3336
#
# Fierce Combatant's Plate Gauntlets (915)
# hands=,id=149741,bonus_id=3573/1704/1577/3336
#
# Waistguard of Fel Magics (935)
# waist=,id=152380,bonus_id=3614/1477/3336
#
# Skoldiir Waistplate (870)
# waist=,id=134181,gem_id=130222,bonus_id=1824/1808/42/1532/3528
#
# Thundergod's Vigor (970)
# waist=,id=137089,bonus_id=1811/3570
#
# Naj'entus's Vertebrae (970)
# waist=,id=137087,bonus_id=1811/3570
#
# Lava-Slough Legguards (935)
# legs=,id=147065,bonus_id=3562/1517/3337
#
# Arcane Defender's Pants (910)
# legs=,id=134271,bonus_id=3509/1572/3337
#
# Titanic Onslaught Greaves (915)
# legs=,id=147191,gem_id=151583,bonus_id=3562/1808/1497/3528
#
# Titanic Onslaught Greaves (900)
# legs=,id=147191,bonus_id=3561/1482/3528
#
# Arcane Defender's Pants (890)
# legs=,id=134271,bonus_id=3417/42/1552/3336
#
# Aggramar's Stride (970)
# feet=,id=132443,bonus_id=1811/3570
#
# Boots of the Bay (1)
# feet=,id=50287
#
# Ayala's Stone Heart (970)
# finger1=,id=137052,enchant_id=5428,gem_id=130220,bonus_id=1811/3570
#
# Ring of Contempt (895)
# finger1=,id=134490,enchant_id=5428,bonus_id=3416/1547/3336
#
# Cruel Gladiator's Band (905)
# finger1=,id=144695,enchant_id=5428,bonus_id=3568/1537/3337
#
# Ring of the Kirin Tor (200)
# finger1=,id=44935
#
# Band of Rescinded Truths (915)
# finger1=,id=147194,enchant_id=5428,bonus_id=3562/1497/3528
#
# Nazjatar Manapearl Ring (855)
# finger1=,id=134245,bonus_id=1825/42/1517/3528
#
# Sephuz's Secret (970)
# finger1=,id=132452,bonus_id=3459/3570
#
# Ring of Minute Mirrors (915)
# finger1=,id=137533,enchant_id=5428,bonus_id=3536/1567/3336
#
# Reliquary of the Damned (900)
# trinket1=,id=147024,bonus_id=3561/1482/3528
#
# Shifting Cosmic Sliver (910)
# trinket1=,id=147026,bonus_id=3561/1492/3528
#
# Ember of Nullification (915)
# trinket1=,id=136978,bonus_id=3510/1567/3337
#
# Darkmoon Deck: Immortality (900)
# trinket1=,id=128711,bonus_id=689/601/679
#
# Leviathan's Hunger (915)
# trinket1=,id=147023,bonus_id=3562/1497/3528
#
# Draenic Philosopher's Stone (620)
# trinket1=,id=109262
#
# Umbral Moonglaives (915)
# trinket1=,id=147012,bonus_id=3562/42/1497/3528
#
# Specter of Betrayal (925)
# trinket1=,id=151190,bonus_id=3562/1507/3528
#
# Fluctuating Arc Capacitor (885)
# trinket1=,id=140035,bonus_id=3394/1808/1547/3336
#
# Feverish Carapace (915)
# trinket1=,id=147022,bonus_id=3562/1497/3528
#
# Kil'jaeden's Burning Wish (970)
# trinket1=,id=144259,bonus_id=3529/3459/3570
#
# Brumdysla, Hammer of Vrorsk (1)
# main_hand=,id=136350
#
# Mastercraft Kalu'ak Fishing Pole (200)
# main_hand=,id=44050,enchant_id=5357
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by seriallos** [comment] 2017-09-22 06:00
Duplicate of #4000

**Closed as completed by seriallos** 2017-09-22 06:00 UTC
Labels: duplicate
