### ISSUE TITLE
Ret Paladin simulation runtime error - invalid crucible rank

### ISSUE THREAD

**Issue by Funkybundy** [simulationcraft/simc#4032] opened 2017-09-18 12:38 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Funkmeister invalid crucible rank '1774/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Funkmeister invalid crucible rank '1774/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0.03
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.1
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=0
override.mortal_wounds=0
threads=8
process_priority=Normal
statistics_level=1
### End GUI options ###
### Begin simulateText ###
paladin="Funkmeister"
level=110
race=human
region=us
server=malfurion
role=attack
professions=blacksmithing=800/mining=800
talents=2212312
spec=retribution
artifact=2:0:0:0:0:40:1:41:4:42:4:43:4:44:4:47:4:49:1:50:4:51:4:52:4:53:4:54:1:350:1:351:1:352:1:353:1:1118:1:1275:1:1561:4:1562:1:1563:1:1564:11:1647:1
crucible=1739:1774/1739/1739

head=,id=147160,bonus_id=3562/1512/3337
neck=,id=147013,enchant_id=5439,gem_id=130219,bonus_id=3562/1808/1497/3528
shoulder=,id=147162,bonus_id=3562/1502/3336
back=,id=138369,enchant_id=5434,bonus_id=3516/1502/3337
chest=,id=147157,gem_id=130219,bonus_id=3562/1808/1502/3336
shirt=,id=98083
wrist=,id=147073,bonus_id=3562/1502/3336
hands=,id=147159,enchant_id=5445,bonus_id=3562/1507/3336
waist=,id=137086,bonus_id=3459/3570
legs=,id=138359,bonus_id=3516/1497/3336
feet=,id=147060,bonus_id=3562/1502/3336
finger1=,id=137048,enchant_id=5427,gem_id=130246,bonus_id=3459/3570
finger2=,id=151308,enchant_id=5427,bonus_id=3418/1587/3337
trinket1=,id=147009,bonus_id=3562/1497/3528
trinket2=,id=147011,gem_id=130219,bonus_id=3562/1808/1502/3336
main_hand=,id=120978,gem_id=147097/137375/147099,bonus_id=737,relic_id=3562:1497:3528/3418:1602:3337/3561:1497:3336

### Gear from Bags
#
# Storm-Tempered Greathelm of the Harmonious (860)
# head=,id=147244,bonus_id=1713/42/3574/1652/3336
#
# Saruan's Resolve (970)
# head=,id=144275,bonus_id=3459/3570
#
# Nat's Drinking Hat (10)
# head=,id=117405
#
# String of Extracted Incisors (915)
# neck=,id=147013,enchant_id=5897,bonus_id=3562/42/1497/3528
#
# Prydaz, Xavaric's Magnum Opus (970)
# neck=,id=132444,enchant_id=5437,gem_id=130219,bonus_id=3459/3570
#
# Shoulderplates of Crackling Flame (930)
# shoulder=,id=147069,enchant_id=5883,bonus_id=3562/1512/3337
#
# Radiant Lightbringer Shoulderguards (900)
# shoulder=,id=147162,bonus_id=3561/1482/3528
#
# Radiant Lightbringer Cape (900)
# back=,id=147158,enchant_id=5434,bonus_id=3561/1482/3528
#
# Astromancer's Greatcloak (895)
# back=,id=140909,enchant_id=5311,bonus_id=3516/42/1492/3336
#
# Cloak of Coordination (60)
# back=,id=65360,enchant_id=5311
#
# Wave-Hammered Breastplate (940)
# chest=,id=147067,bonus_id=3562/1522/3337
#
# Dusk-Crusher Handguards (900)
# hands=,id=147061,bonus_id=3561/42/1482/3528
#
# Reaver's Rattling Girdle (900)
# waist=,id=147753,bonus_id=3572/1482/3528
#
# Rethu's Incessant Courage (970)
# waist=,id=146667,gem_id=130220/130220/130220,bonus_id=1811/3570
#
# Radiant Lightbringer Greaves (915)
# legs=,id=147161,bonus_id=3562/1497/3528
#
# Aggramar's Stride (970)
# feet=,id=132443,bonus_id=3529/3459/3570
#
# Ring of Braided Stems (915)
# finger1=,id=140896,enchant_id=5428,bonus_id=3516/1512/3337
#
# Ilterendi, Crown Jewel of Silvermoon (970)
# finger1=,id=137046,enchant_id=5427,gem_id=130248,bonus_id=1811/3570
#
# Band of Dark Millennia (900)
# finger1=,id=147766,enchant_id=5428,bonus_id=3572/1482/3528
#
# Royal Dagger Haft (870)
# trinket1=,id=140791,bonus_id=3443/42/1467/1813
#
# Memento of Angerboda (920)
# trinket1=,id=133644,bonus_id=3534/1572/3337
#
# Specter of Betrayal (910)
# trinket1=,id=151190,bonus_id=3561/1492/3528
#
# Velen's Future Sight (970)
# trinket1=,id=144258,bonus_id=3459/3570
#
# Naglfar Fare (890)
# trinket1=,id=133645,bonus_id=3410/1542/3337
#
# Umbral Moonglaives (915)
# trinket1=,id=147012,bonus_id=3562/1497/3528
#
# Resilient Heart of the Forest (910)
# trinket1=,id=139064,bonus_id=3573/1808/607/1572/3528
#
# Feverish Carapace (890)
# trinket1=,id=147022,bonus_id=3564/1472/3336
#
# Bottled Hurricane (865)
# trinket1=,id=137378,bonus_id=3418/42/1517/1813
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2017-09-18 14:09
Duplicate of #4000 

Read the comments there for options to resolve.

**Closed as completed by AlexanderKenny** 2017-09-18 14:09 UTC
