### ISSUE TITLE
SimC crashing when simulating new Battle for Azeroth gear patch 8.1

### ISSUE THREAD

**Issue by BlackKnight1984** [simulationcraft/simc#4622] opened 2018-12-13 06:32 UTC
### Describe the bug
I get this message when I run the simulator: 

Initializing: Actor 'Virabhadrasa': Item 'inactive' Slot 'head': Cannot parse option from ',id=165443,bonus_id=5126/1502/4786/5402/4775,context=6,azerite_powers=352/30/83/13': Unexpected parameter 'context'.

This is a new headpiece from the Battle for Darkshore warfront released in 8.1

### Expected behavior
The text copied from simc in game to be simulated to help me optimise my world of warcraft character's gear. 

### To Reproduce
I copy and paste the text from simc in wow into my simc desktop app and select simulate.

### Additional information
* SimulationCraft Version (required) - Version 801 - 01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
See below: 

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Virabhadrasa': Item 'inactive' Slot 'head': Cannot parse option from ',id=165443,bonus_id=5126/1502/4786/5402/4775,context=6,azerite_powers=352/30/83/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
demonhunter="Virabhadrasa"
level=120
race=night_elf
region=us
server=frostmourne
role=attack
professions=alchemy=150/herbalism=150
talents=1311221
spec=havoc

head=,id=165443,bonus_id=5126/1502/4786/5402/4775,context=6,azerite_powers=352/30/83/13
neck=,id=158075,bonus_id=4936/4929/4930/1536,context=11,azerite_level=33
shoulder=,id=161468,bonus_id=5120/1492/4786/4775,context=3,azerite_powers=245/22/84/13
back=,id=158375,gem_id=154128,bonus_id=5009/4802/1542/4783,context=16
chest=,id=159330,bonus_id=5061/1557/4786/4775,context=35,azerite_powers=194/22/83/13
shirt=,id=6795
tabard=,id=152399,context=14
wrist=,id=158305,bonus_id=5010/1542/4786,context=16
hands=,id=160618,enchant_id=5932,bonus_id=4800/1507/4786,context=6
waist=,id=160622,gem_id=153708,bonus_id=4799/1808/1497/4783,context=5
legs=,id=163266,bonus_id=5126/43/1562/4786,context=6
feet=,id=155862,gem_id=154128,bonus_id=5010/4802/1542/4786,context=16
finger1=,id=160645,enchant_id=5943,bonus_id=4799/1507/4784,context=5
finger2=,id=158362,enchant_id=5943,gem_id=154126,bonus_id=5009/4802/1547/4783,context=35
trinket1=,id=160652,bonus_id=4799/1492/4786,context=5
trinket2=,id=160648,gem_id=154128,bonus_id=4799/1808/1492/4786,context=5
main_hand=,id=160110,enchant_id=5962,bonus_id=5010/1552/4786,context=35
off_hand=,id=160693,enchant_id=5963,bonus_id=4799/1497/4783,context=5

### Gear from Bags
#
# Cowl of Dark Portents (375)
# head=,id=163596,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/461/466/13
#
# Cloak of the Restless Tribes (375)
# back=,id=159288,bonus_id=5009/40/1547/4783,context=35
#
# Fetid Horror's Tanglecloak (375)
# back=,id=160643,bonus_id=4799/1497/4783,context=5
#
# Cloak of Rippling Whispers (370)
# back=,id=160642,bonus_id=4799/40/1492/4786,context=5
#
# Cloak of Coordination (58)
# back=,id=65360,context=14
#
# Raiment of the Blighted Tribe (375)
# chest=,id=159335,bonus_id=5052/1542/4786/4775,context=35,azerite_powers=352/31/44/13
#
# Splatterguards (370)
# wrist=,id=161072,bonus_id=4799/1492/4786,context=5
#
# Venerated Raptorhide Bindings (370)
# wrist=,id=160214,bonus_id=5010/43/1542/4786,context=16
#
# Grips of Electrified Defense (380)
# hands=,id=159337,enchant_id=5932,bonus_id=5010/1552/4783,context=35
#
# Replicated Chitin Cord (370)
# waist=,id=160717,gem_id=153708,bonus_id=4799/1808/1492/4786,context=5
#
# Seawalker's Pantaloons (370)
# legs=,id=159322,bonus_id=5010/1542/4786,context=16
#
# Pathogenic Legwraps (370)
# legs=,id=160625,bonus_id=4799/41/1492/4786,context=5
#
# Striders of the Putrescent Path (370)
# feet=,id=160729,bonus_id=4799/1492/4786,context=5
#
# Quarantine Protocol Treads (370)
# feet=,id=160624,bonus_id=4799/1492/4786,context=5
#
# Footpads of the Serene Wake (370)
# feet=,id=159295,bonus_id=5010/1542/4786,context=16
#
# Ritual Binder's Ring (380)
# finger1=,id=159459,enchant_id=5943,bonus_id=5008/1552/4784,context=35
#
# Azerokk's Resonating Heart (380)
# trinket1=,id=159612,bonus_id=5010/1552/4783,context=16
#
# Glaive of the Keepers (370)
# main_hand=,id=160681,enchant_id=5962,bonus_id=4799/1492/4786,context=5
#
# Dragon Fishing Pole (20)
# main_hand=,id=84661,context=14
#
# Glaive of the Keepers (370)
# main_hand=,id=160681,enchant_id=5963,bonus_id=4799/1492/4786,context=5
#
# Glaive of the Keepers (370)
# off_hand=,id=160681,enchant_id=5963,bonus_id=4799/1492/4786,context=5
#
# Glaive of the Keepers (370)
# off_hand=,id=160681,enchant_id=5962,bonus_id=4799/1492/4786,context=5

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-13 07:02
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-13 07:02 UTC

**Comment by BlackKnight1984** [comment] 2018-12-13 07:12
Thanks Alex, I just checked the main website http://www.simulationcraft.org/download.html and the old version 801-01 is listed as the latest download. This was the source of my initial confusion ergo why I posted here. 

The link you have provided contained the version you recommended for OSX - I use Win 64. The latest files in that link for Win 64 is for my current version. 

Are you or someone else able to assist in guiding me to the latest version for Windows 10 64?

**Comment by AlexanderKenny** [comment] 2018-12-13 08:03
There has not been a build flagged for release in a while so they contain the same version number as the one on the main site. That said if you check the got hashes (the random letters and numbers at the end) you'll see they correspond to significantly more recent versions.

Simply grab the latest .exe or .7z from that link and your issue should resolve.

**Comment by AlexanderKenny** [comment] 2018-12-13 23:50
It's planned but no e.t.a as a volunteer project it could be a while before
people have time to implement. In the meantime your best bet is to update
every once and a while from the link provided (more frequently near
patches)

**Comment by BlackKnight1984** [comment] 2018-12-14 01:56
Perfect, thanks Alex. Really appreciate your time - great customer service. I have the latest version now and everything is working well. :)
