### ISSUE TITLE
Invalid crucible format

### ISSUE THREAD

**Issue by joppepoppe** [simulationcraft/simc#4033] opened 2017-09-18 14:06 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Dikkon invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Dikkon invalid crucible format, expected: power_id:rank[:power_id:rank...]
Player Dikkon invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=HeavyMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
priest="Dikkon"
level=110
race=blood_elf
region=eu
server=stormreaver
role=spell
professions=herbalism=177/
talents=1211231
spec=shadow
artifact=47:0:0:0:0:764:1:765:1:766:1:767:4:768:1:769:1:770:1:771:4:772:4:773:4:774:4:775:4:776:4:777:4:778:4:779:1:1347:1:1381:1:1573:4:1574:1:1575:1:1576:12:1650:1
crucible=1739:1777/1739:1778/1739

head=,id=148056,bonus_id=3579/1708/1542/3528
neck=,id=148032,bonus_id=3579/41/1522/3528
shoulder=,id=152354,bonus_id=3614/1472/3528
back=,id=144438,enchant_id=5436,bonus_id=3459/3570
chest=,id=134415,bonus_id=3418/1567/3528
tabard=,id=5976
wrist=,id=147001,bonus_id=3562/1497/3528
hands=,id=148054,bonus_id=1715/1542/3336
waist=,id=148064,bonus_id=1719/1537/3528
legs=,id=145525,gem_id=130220,bonus_id=3567/1708/1808/1557/3337
feet=,id=132455,bonus_id=3459/3570
finger1=,id=148068,bonus_id=3579/1522/3528
finger2=,id=133637,bonus_id=3417/1562/3528
trinket1=,id=139114,bonus_id=3573/1808/607/1572/3528
trinket2=,id=134248,bonus_id=3573/607/1572/3528
main_hand=,id=128827,gem_id=137317/147082/133684,bonus_id=740,relic_id=3417:1582:3337/3573:1492:3528/3418:1597:3337
off_hand=,id=133958

### Gear from Bags
#
# Hood of Blind Absolution (885)
# head=,id=147165,bonus_id=3564/1467/3528
#
# Blackened Mask of Disgrace (885)
# head=,id=146991,bonus_id=3564/1467/3528
#
# Chain of Scorched Bones (910)
# neck=,id=134529,enchant_id=5437,bonus_id=3417/40/1562/3528
#
# Fierce Gladiator's Choker (895)
# neck=,id=148034,bonus_id=3579/1808/1527/3336
#
# Stormcharged Choker (915)
# neck=,id=134497,enchant_id=5437,bonus_id=3418/1567/3528
#
# Radiant String of Scorpid Eyes (885)
# neck=,id=140898,bonus_id=3444/1482/3528
#
# Slipstream Shoulderpads (900)
# shoulder=,id=137309,bonus_id=3413/1552/3528
#
# Amice of the Unfurling Tempest (870)
# shoulder=,id=134432,bonus_id=1726/1522/3336
#
# Inner Hallation (970)
# shoulder=,id=151786,bonus_id=3459/3570
#
# Drape of Shame (900)
# back=,id=142170,bonus_id=3413/1517/3528
#
# Fierce Gladiator's Satin Bracers (890)
# wrist=,id=148066,bonus_id=3579/1708/1522/3528
#
# Doomsinger Gloves (895)
# hands=,id=150981,bonus_id=3397/1557/3528
#
# Ashen Worldscorcher Gloves (900)
# hands=,id=147730,bonus_id=3572/1482/3528
#
# Gloves of Arcane Confluence (885)
# hands=,id=142149,bonus_id=1727/1808/1497/3528
#
# Gloves of Blind Absolution (885)
# hands=,id=147164,bonus_id=3564/1467/3528
#
# Sunfrost Waistcord (885)
# waist=,id=139123,bonus_id=1824/1547/3337
#
# Cord of the Penitent (910)
# waist=,id=142153,bonus_id=3417/1527/3528
#
# Fierce Combatant's Satin Cord (910)
# waist=,id=149661,bonus_id=3573/1715/1572/3528
#
# Fierce Gladiator's Satin Treads (925)
# feet=,id=148052,bonus_id=3579/1682/1557/3337
#
# Treads of Light (930)
# feet=,id=139280,bonus_id=3573/1582/3337
#
# Grasping Tentacle Loop (920)
# finger1=,id=133634,enchant_id=5424,bonus_id=3414/1572/3337
#
# Loop of Vitriolic Intent (910)
# finger1=,id=134530,enchant_id=5424,bonus_id=3417/1562/3528
#
# Oakheart's Gnarled Root (910)
# trinket1=,id=137306,bonus_id=3573/41/1562/3528
#
# Infernal Writ (915)
# trinket1=,id=137485,bonus_id=3573/1567/3336
#
# Naglfar Fare (865)
# trinket1=,id=133645,bonus_id=1726/1517/3528
#
# Touch of the Void (1)
# trinket1=,id=128318
#
# Tome of Unraveling Sanity (910)
# trinket1=,id=147019,bonus_id=3564/1492/3337
#
# Ferocious Gladiator's Badge of Dominance (895)
# trinket1=,id=145579,bonus_id=3567/1527/3528
#
# Figurehead of the Naglfar (915)
# trinket1=,id=137329,bonus_id=3573/42/1567/3336
#
# Terror From Below (910)
# trinket1=,id=147016,bonus_id=3573/1492/3528
#
# Unblemished Sigil of Argus (910)
# trinket1=,id=152781,bonus_id=1808/42/3573/1502/3528
#
# Fishing Pole (1)
# main_hand=,id=6256
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2017-09-18 14:08
Duplicate of #4000 

Read the comments there for options to resolve.

**Closed as completed by AlexanderKenny** 2017-09-18 14:08 UTC
