### ISSUE TITLE
SimulationCraft will not start

### ISSUE THREAD

**Issue by Wolf-DK** [simulationcraft/simc#8021] opened 2023-08-29 10:58 UTC
### Describe the bug
SimulationCraft will not start

### Expected behavior
Start up and allow me to Sim.

I am aware this is not a general issue impacting many, but I am unable to figure out a solution to my issue myself.

### To Reproduce
Been trying nightly builds.
To reset I have deleted folders for SimulationCraft in %%APPDATA%%\local and \roaming
When I Start the program I get info that it has reset configuration and then the program stops working.

I can see the 2 APPDATA folders are created and that Local\simulationcraft includes \cache\simc_webcache_qt6.4\ data8 and prepared with some subdfolders.

I just see a black background with a header with SimulationCraft 1015-01 WebEngine.
After a short time it says not working (if I interact with it).

I have attached DxDiag and report.wer.

### SimulationCraft Version (required)
Version: 1015-01 (simc-1015.01.7da2ab5-win64)
Also tried odler versions: 
simc-1015.01.43c2569-win64
simc-1015.01.0318665-win64
simc-1015.01.a83acaf-win64

And latest version: simc-1015.01.b0b4e38-win64

* **simc_gui.simc** file or contents
This file is not created as the program is not starting properly.

--------------- 
I have run SimC recently with successful reports and good scales, but suddenly I am completely unable to run the program.
I have deleted those folders so cannot show reports or simc file.

Anything I need to install? or Remove to get this to work again.

I run SimC from c:\progs\simc\simulationcraft.exe
I unzip new version with the version name then rename folder.

I prefer running my own sims so I can get my own scales :D

Thanks for maintaining this program it is greatly appreciated.

Regards
Wolf

[DxDiag.txt](https://github.com/simulationcraft/simc/files/12463712/DxDiag.txt)
[Report.wer.txt](https://github.com/simulationcraft/simc/files/12463715/Report.wer.txt)

**Comment by seanpeters86** [comment] 2024-04-22 20:00
@Wolf-DK since we arent able to reproduce going to close this as there isnt much for us to do here. Maybe future updates of dependencies on your side (or ours) over time will resolve this. Feel free to reopen

**Closed as completed by seanpeters86** 2024-04-22 20:00 UTC
