### ISSUE TITLE
Rezan's fury azerite not working.

### ISSUE THREAD

**Issue by Maggiiee** [simulationcraft/simc#4650] opened 2018-12-18 17:44 UTC
### Describe the bug

I get a error code when i try to sim my character from world of warcraft. The code says that the head peice is missing. 

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Here is the full version of the error report.** 

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Maggïe': Item 'inactive' Slot 'head': Cannot parse option from ',id=159236,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=157/30/15/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=25000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=HecticAddCleave
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=0
override.arcane_intellect=0
override.power_word_fortitude=0
override.battle_shout=0
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_lag=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
mage="Maggïe"
level=120
race=gnome
region=eu
server=silvermoon
role=spell
professions=herbalism=150/tailoring=150
talents=1213323
spec=frost

head=,id=159236,bonus_id=5062/1557/4786/4775,context=35,azerite_powers=157/30/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1540,context=11,azerite_level=35
shoulder=,id=159273,bonus_id=5063/1557/4786/4775,context=35,azerite_powers=380/30/83/13
back=,id=163246,enchant_id=6087,gem_id=154126,bonus_id=5126/4802/1567/4783,context=6
chest=,id=159257,bonus_id=5061/1557/4786/4775,context=35,azerite_powers=225/30/85/13
wrist=,id=161071,gem_id=153709,bonus_id=4799/1808/1502/4783,context=5
hands=,id=162479,bonus_id=1704,context=13
waist=,id=165438,bonus_id=5126/1507/4783,context=6
legs=,id=162480,bonus_id=1706,context=13
feet=,id=160714,bonus_id=4800/1517/4783,context=6
finger1=,id=160645,enchant_id=5942,bonus_id=4800/1507/4786,context=6
finger2=,id=158362,enchant_id=5942,bonus_id=5006/1527/4786,context=16
trinket1=,id=160656,bonus_id=4799/40/1497/4783,context=5
trinket2=,id=160651,bonus_id=4800/1507/4786,context=6
main_hand=,id=158321,enchant_id=5949,bonus_id=5010/40/1557/4783,context=35
off_hand=,id=160695,bonus_id=4800/1507/4786,context=6

### Gear from Bags
#
# Sagehold Mantle of the Quickblade (266)
# shoulder=,id=159222,bonus_id=4796/1677,drop_level=120
#
# Amice of Corrupting Horror (375)
# shoulder=,id=160726,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/461/468/13
#
# Forest Grace Mantle (158)
# shoulder=,id=56636,bonus_id=3643,drop_level=60,context=11
#
# Mantle of Contained Corruption (375)
# shoulder=,id=160613,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/22/15/13
#
# Mantle of Ceremonial Ascension (390)
# shoulder=,id=158344,bonus_id=5063/1557/4786/4775,context=35,azerite_powers=381/22/205/13
#
# Void-Drenched Cape (390)
# back=,id=159289,enchant_id=6087,bonus_id=5007/1562/4784,context=35
#
# Squallshaper Vestments (370)
# chest=,id=158058,bonus_id=1562/5138/5383,context=28,azerite_powers=
#
# Ruffled Poet Blouse (370)
# chest=,id=158301,bonus_id=5055/1542/4786,context=35,azerite_powers=
#
# Squallshaper Vestments (375)
# chest=,id=158058,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=478/31/14/13
#
# Robes of the Unraveler (375)
# chest=,id=160614,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/22/205/13
#
# Ouroborial Sash (370)
# waist=,id=159255,bonus_id=5010/1542/4786,context=16
#
# Cord of Animated Contagion (370)
# waist=,id=160734,bonus_id=4799/42/1492/4786,context=5
#
# Aqu'sirr's Swirling Sash (360)
# waist=,id=159239,gem_id=154126,bonus_id=5005/4802/1532/4783,context=35
#
# Ring of the Infinite Void (370)
# finger1=,id=160647,enchant_id=5942,bonus_id=4799/1492/4786,context=5
#
# Spearfisher's Band (350)
# finger1=,id=158161,enchant_id=5942,gem_id=154126,bonus_id=4803/4802/1542/4784,context=27
#
# Footbomb Championship Ring (365)
# finger1=,id=159462,bonus_id=5008/1537/4786,context=16
#
# Murky Cerulean Signet (360)
# finger1=,id=158318,enchant_id=5942,bonus_id=5007/1532/4786,context=16
#
# Overseer's Lost Seal (350)
# finger1=,id=159460,enchant_id=5942,gem_id=154126,bonus_id=4946/4802/1522/4783,context=16
#
# Lady Waycrest's Music Box (370)
# trinket1=,id=159631,gem_id=154126,bonus_id=5010/4802/1542/4786,context=16
#
# Leyshock's Grand Compilation (350)
# trinket1=,id=163937,bonus_id=1472/4786,context=54
#
# Hadal's Nautilus (370)
# trinket1=,id=159622,bonus_id=5010/1542/4786,context=16
#
# Lion's Grace (370)
# trinket1=,id=161472,gem_id=154127,bonus_id=5119/1808/1492/4786,context=3
#
# First Mate's Spyglass (350)
# trinket1=,id=158163,bonus_id=4803/1542/4784,context=27
#
# Ignition Mage's Fuse (385)
# trinket1=,id=159615,bonus_id=5010/1557/4784,context=35
#
# Rotcrusted Voodoo Doll (380)
# trinket1=,id=159624,bonus_id=5010/1552/4783,context=35
#
# T'zane's Barkspines (355)
# trinket1=,id=161411,bonus_id=4798/1477/4786,context=3
#
# Balefire Branch (365)
# trinket1=,id=159630,bonus_id=5008/1537/4786,context=16
#
# Rivermarsh Machete of the Harmonious (266)
# main_hand=,id=159596,bonus_id=4796/1714,drop_level=120
#
# Titanspark Animator (390)
# main_hand=,id=160680,enchant_id=5949,bonus_id=4800/1512/4783,context=6
#
# Bleached Bone Staff of the Peerless (266)
# main_hand=,id=159573,bonus_id=4796/1689,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

### Additional information
* SimulationCraft Version (required) 801-01 WebEngine

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by seriallos** [comment] 2018-12-18 18:13
Duplicate of #4613 

You have a very old version of the SimulationCraft program. Grab a recent Nightly version from http://downloads.simulationcraft.org/?C=M;O=D (not the release version from the downloads page, it must be a nightly version right now).

**Closed as completed by seriallos** 2018-12-18 18:13 UTC
Labels: duplicate
