### ISSUE TITLE
Asked to open ticket, invalid artifact power from addon

### ISSUE THREAD

**Issue by liliburnett** [simulationcraft/simc#4054] opened 2017-09-24 21:30 UTC
I get a message about invalid artifact power when copying and pasting from addon.

#### Simulationcraft Version
730
#### simc_gui.simc file or contents
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Isatap invalid crucible rank '1774/1739' for power '1739', expected a number > 0 && <= 255
Player Isatap invalid crucible rank '1774/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Demon
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
demonhunter="Isatap"
level=110
race=blood_elf
region=us
server=thrall
role=attack
professions=leatherworking=792/skinning=755
talents=2221311
spec=havoc
artifact=3:0:0:0:0:1000:4:1001:4:1002:4:1003:4:1004:4:1005:4:1006:4:1007:4:1008:4:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:1:1493:4:1494:1:1495:1:1496:16:1630:1
crucible=1739:1774/1739:1778/1739:1778

head=,id=147130,bonus_id=3562/1512/3337
neck=,id=137536,enchant_id=5437,bonus_id=3510/1582/3337
shoulder=,id=144279,enchant_id=5931,bonus_id=1811/3570
back=,id=147128,enchant_id=5435,bonus_id=3562/1497/3528
chest=,id=142139,bonus_id=3417/42/1562/3337
wrist=,id=134192,bonus_id=3573/1572/3528
hands=,id=147129,enchant_id=5446,bonus_id=3562/1502/3336
waist=,id=142196,bonus_id=3536/1547/3337
legs=,id=147131,bonus_id=3562/42/1507/3336
feet=,id=139105,bonus_id=3536/1592/3337
finger1=,id=137038,enchant_id=5427,gem_id=151580,bonus_id=1811/3570
finger2=,id=134528,enchant_id=5427,gem_id=151580,bonus_id=3573/1808/1562/3528
trinket1=,id=147009,gem_id=151580,bonus_id=3562/1808/1502/3336
trinket2=,id=151190,bonus_id=3562/1507/3528
main_hand=,id=127829,gem_id=140826/141282/147086,bonus_id=719,relic_id=3573:1517:3336/3573:1572:3528/3562:1497:3528
off_hand=,id=127830

### Gear from Bags
#
# Raddon's Cascading Eyes (970)
# head=,id=137061,bonus_id=1811/3570
#
# Shadoweave Mask (49)
# head=,id=10025
#
# Strand of the Stars (925)
# neck=,id=137487,enchant_id=5889,bonus_id=3534/1577/3337
#
# Demonbane Shoulderpads (900)
# shoulder=,id=147132,enchant_id=5443,gem_id=130219,bonus_id=3561/1808/1482/3528
#
# Fiendish Shoulderguards of the Fireflash (935)
# shoulder=,id=151577,bonus_id=1694/3408/3609/600/3608
#
# Chaos Theory (970)
# back=,id=151798,enchant_id=5435,bonus_id=3459/3570
#
# Shroud of the Drowned Adherent (930)
# back=,id=146985,enchant_id=5435,bonus_id=3562/1512/3337
#
# Cloak of Fel Flames (970)
# back=,id=137066,enchant_id=5314,bonus_id=3459/3570
#
# Shredded Felbroken Shawl (110)
# back=,id=152862
#
# Spirebreaker Harness (920)
# chest=,id=147027,bonus_id=3561/1502/3337
#
# Demonbane Harness (915)
# chest=,id=147127,bonus_id=3562/1497/3528
#
# Hide of the Abyssal Behemoth (915)
# chest=,id=147028,bonus_id=3562/43/1497/3528
#
# Gloves of Barbarous Feats (930)
# hands=,id=152360,enchant_id=5446,bonus_id=3614/1472/3528
#
# Custodian's Soothing Touch (920)
# hands=,id=142141,enchant_id=5446,bonus_id=3534/1532/3337
#
# Cinidaria, the Symbiote (970)
# waist=,id=133976,bonus_id=3459/3570
#
# Biornskin Leggings (940)
# legs=,id=134194,bonus_id=3418/1602/3337
#
# Grasping Tentacle Loop (910)
# finger1=,id=133634,bonus_id=3573/1562/3528
#
# Ferocious Gladiator's Signet (925)
# finger1=,id=145539,enchant_id=5430,bonus_id=3567/1557/3337
#
# Band of Rescinded Truths (910)
# finger1=,id=147194,enchant_id=5430,bonus_id=3561/1492/3336
#
# Jeweled Signet of Melandrus (915)
# finger1=,id=134542,enchant_id=5427,bonus_id=3418/1567/3528
#
# Vial of Ceaseless Toxins (905)
# trinket1=,id=147011,bonus_id=3561/1487/3336
#
# Leviathan's Hunger (900)
# trinket1=,id=147023,bonus_id=3561/1482/3528
#
# Giant Ornamental Pearl (910)
# trinket1=,id=137369,gem_id=130221,bonus_id=3536/1808/1562/3528
#
# Eye of Command (910)
# trinket1=,id=142167,bonus_id=3535/1522/3336
#
# Umbral Moonglaives (915)
# trinket1=,id=147012,bonus_id=3562/1497/3528
#
# Shifting Cosmic Sliver (955)
# trinket1=,id=147026,bonus_id=3562/1537/3337
#
# Skinning Knife (4)
# main_hand=,id=7005
#
# Skinning Knife (4)
# off_hand=,id=7005
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

#### Reproduction Steps:

type /simc, copy and paste into program, run simulate

**Comment by seriallos** [comment] 2017-09-24 21:41
Duplicate of #4000

**Closed as completed by seriallos** 2017-09-24 21:41 UTC
Labels: duplicate
