### ISSUE TITLE
SC doesn't start at all on any latest build type on this system.

### ISSUE THREAD

**Issue by fateswarm** [simulationcraft/simc#2636] opened 2015-10-05 11:59 UTC
After searching old issues, it might be related to the GPU, it's on a  Radeon HD 5000 driver. I tried both webkit and normal versions on both 32bit and 64bit. They both just exit without any error, the .exe is run and then it just does nothing, nothing is hang on taskmanager either. Windows 10 64.

QT standandalone versions do not exist in the system or are uninstalled.

AppCrashView does not show reports though it had a few related to Qt5core before.

**Comment by fateswarm** [comment] 2015-10-05 12:05
I have seen it start before, so it seems like a misconfiguration, rather that a true inability of the libraries.

Is there a way to do a full reset of simcraft files config? I do not see anything in c:/users about it.

**Comment by fateswarm** [comment] 2015-10-05 12:10
Oh, I can see AppCrashView reports: e.g. the latest:

Version=1
EventType=APPCRASH
EventTime=130885205793139376
ReportType=2
Consent=1
UploadTime=130885205806271867
ReportIdentifier=f34c48bd-6b59-11e5-bfe6-78acc051385a
IntegratorReportIdentifier=39377761-b44f-4ad1-9b6d-0584d5b85f6a
WOW64=1
NsAppName=SimulationCraft.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=SimulationCraft.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=56107e5d
Sig[3].Name=Fault Module Name
Sig[3].Value=Qt5Core.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=5.5.1.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=560848b2
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0007a9d6
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10240.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1032
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=bdcb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=bdcb33e65a9843796b7ec31cc25bda3b
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=689d
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=689d12abf00dd47c453b5e1a156c0fa3
UI[2]=C:\games\World of Warcraft\_simc-622-01-win32\SimulationCraft.exe
UI[3]=SimulationCraft.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\games\World of Warcraft\_simc-622-01-win32\SimulationCraft.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\SYSTEM32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\SHELL32.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\msvcrt.dll
LoadedModule[6]=C:\WINDOWS\SYSTEM32\WININET.dll
LoadedModule[7]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Network.dll
LoadedModule[8]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[9]=C:\WINDOWS\SYSTEM32\combase.dll
LoadedModule[10]=C:\WINDOWS\SYSTEM32\RPCRT4.dll
LoadedModule[11]=C:\WINDOWS\SYSTEM32\advapi32.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\sechost.dll
LoadedModule[14]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
LoadedModule[16]=C:\WINDOWS\SYSTEM32\shlwapi.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\GDI32.dll
LoadedModule[18]=C:\WINDOWS\SYSTEM32\USER32.dll
LoadedModule[19]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Gui.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\WS2_32.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\shcore.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\NSI.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[25]=C:\WINDOWS\SYSTEM32\CRYPT32.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[27]=C:\WINDOWS\SYSTEM32\MSASN1.dll
LoadedModule[28]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Core.dll
LoadedModule[29]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5WebKit.dll
LoadedModule[30]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5WebKitWidgets.dll
LoadedModule[31]=C:\WINDOWS\SYSTEM32\ole32.dll
LoadedModule[32]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Widgets.dll
LoadedModule[33]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[34]=C:\games\World of Warcraft\_simc-622-01-win32\MSVCP120.dll
LoadedModule[35]=C:\games\World of Warcraft\_simc-622-01-win32\MSVCR120.dll
LoadedModule[36]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Sensors.dll
LoadedModule[37]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5MultimediaWidgets.dll
LoadedModule[38]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[39]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Multimedia.dll
LoadedModule[40]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5PrintSupport.dll
LoadedModule[41]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5OpenGL.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\COMDLG32.dll
LoadedModule[43]=C:\games\World of Warcraft\_simc-622-01-win32\icuin54.dll
LoadedModule[44]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[45]=C:\games\World of Warcraft\_simc-622-01-win32\icuuc54.dll
LoadedModule[46]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[47]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Positioning.dll
LoadedModule[48]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Quick.dll
LoadedModule[49]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Qml.dll
LoadedModule[50]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5WebChannel.dll
LoadedModule[51]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Sql.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[53]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.10240.16384_none_49c02355cf03478c\COMCTL32.dll
LoadedModule[54]=C:\games\World of Warcraft\_simc-622-01-win32\icudt54.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\cfgmgr32.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\IMM32.DLL
LoadedModule[60]=C:\WINDOWS\SYSTEM32\MSCTF.dll
LoadedModule[61]=C:\games\World of Warcraft\_simc-622-01-win32\platforms\qwindows.dll
LoadedModule[62]=C:\WINDOWS\SYSTEM32\OLEAUT32.dll
LoadedModule[63]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[64]=C:\WINDOWS\system32\dwmapi.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=SimulationCraft.exe
AppPath=C:\games\World of Warcraft\_simc-622-01-win32\SimulationCraft.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=9605365AC722B48F7AF55ECA996DE938

**Comment by fateswarm** [comment] 2015-10-08 10:06
Same on latest nightly 32bit build.

Version=1
EventType=APPCRASH
EventTime=130887722986619919
ReportType=2
Consent=1
UploadTime=130887723000945183
ReportIdentifier=07b8956c-6da4-11e5-bfe6-78acc051385a
IntegratorReportIdentifier=a762a6dc-e9fd-4e13-bde3-bced12f1c1b3
WOW64=1
NsAppName=SimulationCraft.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=SimulationCraft.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=56146cbc
Sig[3].Name=Fault Module Name
Sig[3].Value=Qt5Core.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=5.5.1.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=560848b2
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0007a9d6
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10240.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1032
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=bdcb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=bdcb33e65a9843796b7ec31cc25bda3b
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=689d
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=689d12abf00dd47c453b5e1a156c0fa3
UI[2]=C:\games\World of Warcraft\_simc-622-01-win32\SimulationCraft.exe
UI[3]=SimulationCraft.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\games\World of Warcraft\_simc-622-01-win32\SimulationCraft.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\SYSTEM32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\SHELL32.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\msvcrt.dll
LoadedModule[6]=C:\WINDOWS\SYSTEM32\WININET.dll
LoadedModule[7]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Network.dll
LoadedModule[8]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Gui.dll
LoadedModule[9]=C:\WINDOWS\SYSTEM32\combase.dll
LoadedModule[10]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[11]=C:\WINDOWS\SYSTEM32\RPCRT4.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\advapi32.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[14]=C:\WINDOWS\SYSTEM32\sechost.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[16]=C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\shlwapi.dll
LoadedModule[18]=C:\WINDOWS\SYSTEM32\GDI32.dll
LoadedModule[19]=C:\WINDOWS\SYSTEM32\USER32.dll
LoadedModule[20]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Core.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\shcore.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[25]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5WebKit.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\WS2_32.dll
LoadedModule[27]=C:\WINDOWS\SYSTEM32\NSI.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\CRYPT32.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\MSASN1.dll
LoadedModule[30]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5WebKitWidgets.dll
LoadedModule[31]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Widgets.dll
LoadedModule[32]=C:\WINDOWS\SYSTEM32\ole32.dll
LoadedModule[33]=C:\games\World of Warcraft\_simc-622-01-win32\MSVCP120.dll
LoadedModule[34]=C:\games\World of Warcraft\_simc-622-01-win32\MSVCR120.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[36]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Sensors.dll
LoadedModule[37]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5MultimediaWidgets.dll
LoadedModule[38]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Multimedia.dll
LoadedModule[39]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5PrintSupport.dll
LoadedModule[40]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5OpenGL.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\COMDLG32.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[44]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.10240.16384_none_49c02355cf03478c\COMCTL32.dll
LoadedModule[45]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[46]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[47]=C:\games\World of Warcraft\_simc-622-01-win32\icuuc54.dll
LoadedModule[48]=C:\games\World of Warcraft\_simc-622-01-win32\icuin54.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[50]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Positioning.dll
LoadedModule[51]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Quick.dll
LoadedModule[52]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Qml.dll
LoadedModule[53]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5WebChannel.dll
LoadedModule[54]=C:\games\World of Warcraft\_simc-622-01-win32\Qt5Sql.dll
LoadedModule[55]=C:\games\World of Warcraft\_simc-622-01-win32\icudt54.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\cfgmgr32.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\IMM32.DLL
LoadedModule[60]=C:\WINDOWS\SYSTEM32\MSCTF.dll
LoadedModule[61]=C:\games\World of Warcraft\_simc-622-01-win32\platforms\qwindows.dll
LoadedModule[62]=C:\WINDOWS\SYSTEM32\OLEAUT32.dll
LoadedModule[63]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[64]=C:\WINDOWS\system32\dwmapi.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=SimulationCraft.exe
AppPath=C:\games\World of Warcraft\_simc-622-01-win32\SimulationCraft.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=7A5922A12BB291C1C7BC5E1D3FD4019D

**Comment by fateswarm** [comment] 2015-10-08 10:11
Wow, I a few times and it started once. That's the weirdest thing ever. Then after being closed it doesn't start again.

+ And it started again. If I keep hitting <enter> on the .exe in explorer for instance, 1 out of 20 times will start it.

**Comment by navv1234** [comment] 2015-10-08 10:56
The Crash is in the Qt core library packaged with the simulator. Have you tried earlier releases (620-2 for example) if they exhibit the same behaviour?

**Comment by fateswarm** [comment] 2015-10-08 22:11
Yes. Yes. I find it weird that it actually starts one of ~20 tries, I've never seen that again.

I'll look at even older versions maybe later, it's not on this PC, it's an older one.

**Comment by fateswarm** [comment] 2015-10-09 08:04
620-2 from front page has the same behavior. It starts rarely, crashes usually. 610-7 from downloads index also similar.

I may check on a guest account.

**Comment by fateswarm** [comment] 2015-10-09 08:16
OK it always starts reliably on a new Windows account so it appears purely a configuration issue at the user level. I'll have to find first where the user files are for this software..

OK deleting Roaming/SimulationCraft/ does not fix it.

Does it keep files anywhere else? registry?

**Comment by navv1234** [comment] 2015-10-09 08:35
I'm not sure, @collisionc might know better about the specifics of the windows version and where it keeps files.

**Comment by fateswarm** [comment] 2015-10-09 08:36
I'm doing a full clean with adwcleaner, malwarebytes and ccleaner just in case but I doubt it'll do anything.

**Comment by navv1234** [comment] 2015-10-09 08:37
I think it's more likely that qt is in some fit of rage and crashes because of it, would not be the first time.

**Comment by fateswarm** [comment] 2015-10-09 10:00
Clean did nothing. Dunno what else to do. I lied, I could debug it but I never coded in QT and I don't want to get into all those installations.

**Comment by scamille** [comment] 2015-10-09 14:39
SimC should not keep any files except for the .ini file in Roaming/SimulationCraft/. You could check the registry, but hopefully you won't find anything.

Unfortunately, QT debug libraries are very large, so I'm not sure if it would be possible for Collision to build such a release.

Maybe I'll find the time to compile a MinGW release at some point, as a third option for people to try out.

**Comment by Collisionc** [comment] 2015-10-10 12:58
I think that we save simulationcraft stuff in appdata\roaming\simulationcraft, and QT saves QT crap in appdata\local\Simulationcraft

Try nuking the \local\ and see if that works as well.

**Comment by navv1234** [comment] 2015-10-10 13:10
appdata\local\simulationcraft contains the various caches the binary uses on windows.

**Comment by fateswarm** [comment] 2015-10-13 10:13
Hrm. Nope. Deleting both keeps the same behavior.

I'll start killing processes now that may not exist on a new user account. If something positive happens, I'll report.

**Comment by fateswarm** [comment] 2015-10-13 13:55
I debugged it and solved it. 

main.cpp, line 67

Change from:

    lang = QLocale::system().name().split('_').at(1).toLower();

to:

    lang = QLocale::system().name().split('_').value(1).toLower();

Inspiration from a forum thread I googled:

https://forum.qt.io/topic/2007/index-out-of-range-when-using-qlist/17

Apparently they are telling him the problem is not that exactly, but others parts of the code, etc.

In this case it's most probably related to Language settings. I'm in a multilanguage setup.

**Comment by fateswarm** [comment] 2015-10-13 13:58
The initial error was a window: 

http://i.imgur.com/xrSx4I5.png

A break into that point mentioned on the error window, could trace to the line changed above (it was the previous step in the trace).

**Comment by navv1234** [comment] 2015-10-13 14:00
Interesting .. Yeah, the issue is obvious now. Can you check what the list contains (in essence the Locale::system().name()" method call)?

**Comment by fateswarm** [comment] 2015-10-13 14:06
Erm, how do I do that? I can see http://i.imgur.com/xEC2E5W.png

**Comment by navv1234** [comment] 2015-10-13 14:09
Add something like `QString langStr = QLocale::system().name();` above the crashing line. When it crashes, you should have a local `langStr` in the sub-window that contains the language string.

**Comment by fateswarm** [comment] 2015-10-13 14:15
I don't know if that helps or if there's another way to look at that data http://i.imgur.com/AjXH3ZS.png

**Comment by navv1234** [comment] 2015-10-13 14:16
Yeah helps, it's returning something irrelevant. I'll fix it when I get home.

**Comment by fateswarm** [comment] 2015-10-13 14:16
Oh. Alright. Thanks.

**Comment by navv1234** [comment] 2015-10-13 17:35
Right, hopefully fixed with 6d268ce.

**Comment by fateswarm** [comment] 2015-10-14 09:03
This change works well here, on the original PC that had the problem. Hrm, did you fix the Webengine 64bit results page hang? It used to hang there in most tries,but now it looks fine in several tries, unless it's mere luck.

**Comment by navv1234** [comment] 2015-10-14 09:17
> Hrm, did you fix the Webengine 64bit results page hang? It used to hang there in most tries,but now it looks fine in several tries, unless it's mere luck.

Nothing has been done for that as far as I know, mostly because it has not been reproducible by anyone on the team. I think it's rather improbable that fixing the obvious access violation in this issue also fixed that, but you never know...

**Comment by fateswarm** [comment] 2015-10-14 11:41
I didn't think it's related, just mentioning a "by the way". But let me try just in case ... ............ hrm, nope, it still gives results fine here without this bug fixed (after I manage to run it after 30 crashes). I guess it's something with the browser rendering. The HTML/XML looks fine in the file system. Maybe I'll see on my main PC if it can be somehow debugged there.

**Comment by navv1234** [comment] 2015-10-14 11:49
Did you use the webengine or the webkit version? I know Qt's webengine has had some issues (perhaps not related to rendering), and that we have gone back to webkit as the in-gui browser in (windows) releases.

**Comment by fateswarm** [comment] 2015-10-14 14:20
Webengine. Webkit works fine, yeah. I may look into debugging that on my other PC (unrelated to this here bug) because I may only see the 64bit results hang there if I'm not mistaken.

**Comment by fateswarm** [comment] 2015-10-16 06:27
Hrm. I can't replicate that results hang on any of my PC now. I wonder if Windows updates their Internet Explorer API or something.

**Comment by fateswarm** [comment] 2015-10-16 20:40
More info added about the hang issue here: https://github.com/simulationcraft/simc/issues/2625

**Comment by Collisionc** [comment] 2015-11-23 18:06
Sorry for not seeing this, my github notifications are so spammy, I need to turn off all the non-important ones. For the time being I am exclusively building webkit until webengine gets it's act together.

Closing for now.

**Closed by Collisionc** 2015-11-23 18:06 UTC
Labels: GUI, OpSys-Windows
