### ISSUE TITLE
Failure to  Sim it

### ISSUE THREAD

**Issue by Drakendar** [simulationcraft/simc#4629] opened 2018-12-14 21:05 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Drakendar': Item 'inactive' Slot 'head': Cannot parse option from ',id=163380,bonus_id=5126/1562/4786,context=6,azerite_powers=173/461/85': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=6
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
druid="Drakendar"
level=120
race=worgen
region=eu
server=blackmoore
role=spell
professions=alchemy=100/enchanting=99
talents=2123221
spec=balance

head=,id=163380,bonus_id=5126/1562/4786,context=6,azerite_powers=173/461/85
neck=,id=158075,bonus_id=4936/4929/4930/1522,context=11,azerite_level=26
shoulder=,id=158043,bonus_id=1532/5140,context=28,azerite_powers=478/459/15
back=,id=160643,gem_id=154127,bonus_id=4798/1808/1477/4786,context=3
chest=,id=158006,bonus_id=1547/4786/5395/4775,context=28,azerite_powers=156/31/44/13
wrist=,id=160720,bonus_id=4798/1477/4786,context=3
hands=,id=165442,bonus_id=5126/1502/4786,context=6
waist=,id=127578,bonus_id=5130/5131,drop_level=120,context=22
legs=,id=165444,bonus_id=5124/1457/4786,context=3
feet=,id=160624,bonus_id=4798/1808/43/1487/4783,context=3
finger1=,id=160645,enchant_id=5939,bonus_id=4798/1477/4786,context=3
finger2=,id=127570,enchant_id=5939,bonus_id=5130,drop_level=120,context=22
trinket1=,id=160651,bonus_id=4798/1477/4786,context=3
trinket2=,id=158164,bonus_id=4803/1522/4785,context=27
main_hand=,id=133485,enchant_id=5963,bonus_id=5130,drop_level=120,context=22

### Gear from Bags
#
# Langer Umhang der 7. Legion (340)
# back=,id=163347,bonus_id=5124/1532/4786,context=3
#
# Berster der Flussmarschen des Hitzeschocks (266)
# main_hand=,id=159546,bonus_id=4796/1702,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=2

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-15 01:43
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-15 01:43 UTC
