### ISSUE TITLE
Error: Player invalid crucible format, expected: power_id:rank[:power_id:rank...]

### ISSUE THREAD

**Issue by Lonyara** [simulationcraft/simc#4027] opened 2017-09-17 10:42 UTC
SimulationCraft 730-01
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Ãsunà invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=12
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
demonhunter="Ãsunà"
level=110
race=blood_elf
region=eu
server=hyjal
role=attack
professions=tailoring=800/enchanting=810
talents=2221311
spec=havoc
artifact=3:0:0:0:0:1000:4:1001:4:1002:4:1003:4:1004:4:1005:4:1006:4:1007:4:1008:4:1010:1:1011:1:1012:1:1013:1:1014:1:1015:1:1016:1:1330:1:1362:1:1493:4:1494:1:1495:1:1496:12:1630:1
crucible=1739:1780/1739:1782/0

head=,id=147130,bonus_id=3561/1482/3528
neck=,id=142174,enchant_id=5437,gem_id=151580,bonus_id=3414/1808/1522/3336
shoulder=,id=144279,enchant_id=5931,bonus_id=3459/3570
back=,id=147128,enchant_id=5435,bonus_id=3561/1487/3336
chest=,id=128884,bonus_id=689/1691/3408/601/679
wrist=,id=128891,bonus_id=689/1690/3408/601/679
hands=,id=147129,bonus_id=3561/1482/3528
waist=,id=128890,bonus_id=689/1691/3408/601/679
legs=,id=147131,bonus_id=3561/1482/3528
feet=,id=147738,bonus_id=3572/42/1482/3528
finger1=,id=132452,enchant_id=5427,gem_id=130247,bonus_id=3459/3570
finger2=,id=134530,enchant_id=5427,bonus_id=3418/1587/3337
trinket1=,id=147009,bonus_id=3562/1502/3336
trinket2=,id=142159,bonus_id=3573/1522/3337
main_hand=,id=127829,gem_id=147087/147110/147086,bonus_id=719,relic_id=3562:1507:3528/3561:1492:3336/3561:1482:3528
off_hand=,id=127830

### Gear from Bags
#
# Fermoir de la mort ardente (900)
# neck=,id=147765,bonus_id=3572/1482/3528
#
# Chapelet d'incisives arrachées (905)
# neck=,id=147013,enchant_id=5889,bonus_id=3561/42/1487/3336
#
# Harnais du fléau des démons (900)
# chest=,id=147127,bonus_id=3561/1482/3528
#
# Gilet en peau de biorn (895)
# chest=,id=134197,bonus_id=3410/1557/3337
#
# Garde-poignets cousus de tendon (920)
# wrist=,id=147041,bonus_id=3561/41/1502/3337
#
# Cordelière de chair crépitante (885)
# waist=,id=147039,bonus_id=3564/43/1467/3528
#
# Jambières du fléau des démons (900)
# legs=,id=147131,bonus_id=3561/1482/3528
#
# Jambières du fléau des démons (885)
# legs=,id=147131,bonus_id=3564/1467/3528
#
# Bottines d'assombrisseur du bosquet (900)
# feet=,id=134429,bonus_id=3417/1552/3337
#
# Brodequins du glacier (900)
# feet=,id=147029,bonus_id=3561/43/1482/3528
#
# Bague du Kirin Tor (200)
# finger1=,id=40586
#
# Bague des vérités invalidées (900)
# finger1=,id=147194,enchant_id=5430,bonus_id=3561/1482/3528
#
# Tome de la raison déclinante (910)
# trinket1=,id=147019,bonus_id=3564/1492/3337
#
# Perle ornementale géante (895)
# trinket1=,id=137369,bonus_id=3411/1547/3528
#
# Médaillon de Parjesh (870)
# trinket1=,id=137362,bonus_id=1727/1522/3336
#
# Canne à pêche solide (10)
# main_hand=,id=6365
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by Lonyara** [comment] 2017-09-17 10:43
Addon Simc : v1.8.3

**Comment by AlexanderKenny** [comment] 2017-09-17 11:01
Duplicate of #4000 

Read the comments there for solutions.

**Closed as completed by AlexanderKenny** 2017-09-17 11:01 UTC
