### ISSUE TITLE
Reporting error

### ISSUE THREAD

**Issue by Vakz** [simulationcraft/simc#4015] opened 2017-09-15 15:13 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version 730-01

Just posting a link to an error as requested per the tool could not see how to make a ticket.

Error code was as follows : 

> Player Vák invalid crucible format, expected: power_id:rank[:power_id:rank...]

**Comment by vituscze** [comment] 2017-09-15 15:30
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-15 15:30 UTC
Labels: duplicate
