### ISSUE TITLE
seed_of_creation causing simc to crash

### ISSUE THREAD

**Issue by qlesz** [simulationcraft/simc#2622] opened 2015-09-05 12:55 UTC
Every time i try to simulate my char with seed_of_creation trinket, program is crashing. If i remove it or put any other trink it's fine (i've tried desecrated_shadowmoon_insignia, unblinking_gaze_of_sethe and darmacs_unstable_talisman) i've tried two different versions of seed_of_creation (ilvl 705 and ilvl 720) both caused program to crash. My simcraft version is 620-02 64bit, working on win10. I've tried with win7 on my old pc (also 64bit) and it seem to be ok.

**Comment by scamille** [comment] 2015-09-05 14:03
Can you please copy-paste the content of simc_gui.simc file, which you can find in your SimulationCraft folder. It contains the full settings used for the last simulation you start. Makes it easier for us to debug the problem.

**Comment by navv1234** [comment] 2015-09-05 18:04
Presumably this means a Balance Druid. I cannot reproduce it directly by adding Seed of Creation to the sample Balance profile, so as stated above, we'll need a sim configuration to attempt to reproduce the issue.

**Comment by qlesz** [comment] 2015-09-06 09:01
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=450
vary_combat_length=0.2
fight_style=Ultraxion
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.attack_power_multiplier=1
override.spell_power_multiplier=1
override.critical_strike=1
override.haste=1
override.multistrike=1
override.mastery=1
override.stamina=1
override.str_agi_int=1
override.versatility=1
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
thread_priority=Lowest
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

druid=sineaterr
origin="http://www.askmrrobot.com/wow/player/eu/burning_legion/sineaterr"
level=100
race=night_elf
role=spell
spec=balance
professions=Jewelcrafting=700/Enchanting=700
talents=1132231
glyphs=54733/54760/59219/114295/114301/146655

head=oathclaw_helm,id=124261,bonus_id=561/566
neck=necklace_of_endless_shadow,id=109956,bonus_id=642/643,enchant_id=5319
shoulders=oathclaw_mantle,id=124272,bonus_id=566
chest=vest_of_forceful_fury,id=113870,bonus_id=41/567
waist=waistwrap_of_banishment,id=124276,bonus_id=564/566,gem_id=127762
legs=oathclaw_leggings,id=124267,bonus_id=566
feet=spiked_irontoe_slippers,id=124249,bonus_id=566
wrists=manacles_of_the_multitudes,id=124280,bonus_id=566
hands=oathclaw_gauntlets,id=124255,bonus_id=566
finger1=nithramus_the_allseer,id=124635,bonus_id=622/649,enchant_id=5326
finger2=loathful_encrusted_band,id=124192,bonus_id=561/566,enchant_id=5326
trinket1=seed_of_creation,id=124514,bonus_id=564/566,gem_id=127762
trinket2=goren_soul_repository,id=119194,bonus_id=565/567,gem_id=127762
back=cloak_of_hideous_unity,id=124138,enchant_id=5300
main_hand=warhammer_of_arrogance,id=124376,bonus_id=566,enchant_id=5384



### End simulateText ###
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin command line ###

### End command line ###
### Begin final options ###
### End final options ###
### END ###

W dniu 05.09.2015 o 15:03, Serge Camille pisze:

**Comment by scamille** [comment] 2015-09-09 07:16
Fixed in 445bf6b85eae2ca6cb9f04ac126e4d7a78118fc1

**Closed by scamille** 2015-09-09 07:16 UTC
Labels: bug, Druid
