### ISSUE TITLE
cant sim character since 8.1

### ISSUE THREAD

**Issue by cacosaurus** [simulationcraft/simc#4635] opened 2018-12-15 21:39 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Itscac': Item 'inactive' Slot 'head': Cannot parse option from ',id=163435,bonus_id=5125/1562/5136/5381/4775,context=28,azerite_powers=159/30/85/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=agi,ap,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Post your Simc Addon Export text here.
# SimC Addon 1.10.8
demonhunter="Itscac"
level=120
race=blood_elf
region=us
server=bleeding_hollow
role=attack
professions=alchemy=150/herbalism=150
talents=1311211
spec=havoc

head=,id=163435,bonus_id=5125/1562/5136/5381/4775,context=28,azerite_powers=159/30/85/13
neck=,id=158075,bonus_id=4936/4929/4930/1536,context=11,azerite_level=33
shoulder=,id=159307,bonus_id=5064/1542/4786/4775,context=35,azerite_powers=126/21/466/13
back=,id=160642,bonus_id=4799/1492/4786,context=5
chest=,id=163283,bonus_id=5125/1562/5138/5383/4775,context=28,azerite_powers=126/31/15/13
wrist=,id=163309,bonus_id=5126/1567/4783,context=6
hands=,id=159321,enchant_id=5932,gem_id=154128,bonus_id=5010/4802/1552/4783,context=35
waist=,id=159341,gem_id=153708,bonus_id=5010/4802/1552/4783,context=35
legs=,id=159345,bonus_id=5010/1547/4783,context=16
feet=,id=159304,bonus_id=5010/43/1552/4783,context=35
finger1=,id=160645,enchant_id=5945,bonus_id=4799/1492/4786,context=5
finger2=,id=158314,enchant_id=5945,bonus_id=5008/1537/4786,context=16
trinket1=,id=155881,bonus_id=5010/1542/4786,context=16
trinket2=,id=159125,context=13
main_hand=,id=159651,enchant_id=5962,bonus_id=5010/1557/4784,context=35
off_hand=,id=160681,enchant_id=5965,bonus_id=4799/1492/4786,context=5

### Gear from Bags
#
# Warring Ancient's Crown (390)
# head=,id=166688,bonus_id=5478/1502/4786/5402/4775,context=3,azerite_powers=245/31/14/13
#
# Cowl of Dark Portents (375)
# head=,id=163596,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/462/85/13
#
# Hood of Pestilent Ichor (375)
# head=,id=160623,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=352/31/15/13
#
# Usurper's Bloodcaked Spaulders (375)
# shoulder=,id=160620,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/44/13
#
# Doom's Wake (370)
# trinket1=,id=161462,bonus_id=5119/1492/4786,context=3
#
# Frenetic Corpuscle (370)
# trinket1=,id=160648,bonus_id=4799/1492/4786,context=5
#
# Honorbound Warglaive (370)
# main_hand=,id=163877,enchant_id=5965,gem_id=154128,bonus_id=5125/4802/1562/4786,context=29
#
# Fishing Pole (1)
# main_hand=,id=6256,context=14
#
# Honorbound Warglaive (370)
# off_hand=,id=163877,enchant_id=5965,gem_id=154128,bonus_id=5125/4802/1562/4786,context=29

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=8

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-15 22:53
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-15 22:53 UTC
