### ISSUE TITLE
Affliction Warlock 6+ targets bug

### ISSUE THREAD

**Issue by NickTheGeek88** [simulationcraft/simc#2701] opened 2016-04-10 11:53 UTC
Hello.

So, i was running some sims as Affliction Warlock with sb:Haunt and GoSup to see how sb:haunt scales with targets. The thing is when i set it to 6 targets, the results start making no sense.

First, Haunt's DPET is 6.8 million, which isnt reachable in any way. Secondly, the total damage is about 172k while in 5 targets is 180k, so why not to damage only the 5 targets instead of damaging all?

Here's a printsreen:
http://imgur.com/dpR5HAH

Some more info about the fight:
Duration: 240 secs / Targets: 6, non-demon / Fight style: patchwerk / Iterations: 10.000

Thanks for reading.

**Comment by scamille** [comment] 2016-04-16 07:40
Thanks for your ticket.

Can you please add the [simc_gui.simc](https://github.com/simulationcraft/simc/wiki/simc_gui.simc) file which contains all the settings used for your last simulation. This makes it much easier for us to replicate the problem.

@tjc12821 Can you take a look at this?

**Comment by tjc12821** [comment] 2016-04-16 18:17
So the first issue is that the APL for affliction just doesn't handle target numbers over 4 very well. It's setup so it always prioritizes keeping DoTs up on as many targets as possible. On 6 targets, particularly with class trinket, the duration of the DoTs is short enough that the sim will spend 100% of it's time trying to maintain DoTs on every target. There's likely a point at which DoTing more targets is worth less than just using Drain Soul on a single target.

It's not a bug, the APL is just doing something that probably isn't optimal. Most of my focus is currently on alpha, so I probably won't be fixing this anytime before legion, when all of the warlock APLs will get full rewrites. Sorry for the inconvenience.

As for the haunt DPET...I think it's something to do with their only being one execute per sim on 6 targets. Not entirely sure, asking around the irc about it.

**Comment by NickTheGeek88** [comment] 2016-04-18 10:04
Good morning.

I checked the results again and in 6 targets, in the column "execute", Haunt has the number 1 which probably means it is executed only once per fight (probably on pull; only once during the precombat actions).

I also noticed that in 5 targets, Haunting Spirits has a 68% uptime while in 6 targets its only 12.5%. Thats probably the main reason, damage in 5 targets is higher than damage in 6. Maybe sim tries to keep the dots up, without refreshing Haunting Spirits. Shouldnt Haunting Spirits have priority over dots? A soulburn:Haunt cast will give you 20% damage increase for each set of dots on each target for the next 30 secs, while a single dot cast will give you some raw dmg but it cant be higher than the one SB:Haunt gave you indirectly through the 20% dmg multiplier, overall.

**Comment by Frostedmages** [comment] 2016-04-18 14:52
If Haunt is only used once, and is being used during the "precombat" phase, then that is why the DPET looks so large. Something with how we're treating pre-combat actions, and is known already.

Look at the sample action list readout following the DPS report and see if the one execute comes from the "actions.precombat+=/haunt" line.

**Comment by NickTheGeek88** [comment] 2016-04-19 11:20
Yup you are right. Haunt is casted only once during the precombat actions, i just checked the "sample sequence" table.

**Comment by Collisionc** [comment] 2016-07-09 23:40
Closing as it should be fixed in legion branch.

**Closed by Collisionc** 2016-07-09 23:40 UTC
Labels: Warlock
