### ISSUE TITLE
Error during import 

### ISSUE THREAD

**Issue by Lugburz78** [simulationcraft/simc#4657] opened 2018-12-20 14:55 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Lûgburz': Item 'inactive' Slot 'head': Cannot parse option from ',id=160719,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/31/15/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=int,sp,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
warlock="Lûgburz"
level=120
race=orc
region=eu
server=cthun
role=spell
professions=alchemy=150/herbalism=150
talents=2113312
spec=destruction

head=,id=160719,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/31/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=161454,bonus_id=5120/1492/4786/4775,context=3,azerite_powers=444/22/83/13
back=,id=160642,gem_id=153709,bonus_id=4799/1808/1492/4786,context=5
chest=,id=160614,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/44/13
shirt=,id=85508,context=14
wrist=,id=160617,bonus_id=4799/1492/4786,context=5
hands=,id=160715,enchant_id=5932,bonus_id=4799/1492/4786,context=5
waist=,id=160734,bonus_id=4799/1492/4786,context=5
legs=,id=160615,gem_id=154127,bonus_id=4800/1808/42/1507/4786,context=6
feet=,id=160714,bonus_id=4800/1507/4786,context=6
finger1=,id=160647,enchant_id=5943,bonus_id=4800/1507/4786,context=6
finger2=,id=160645,enchant_id=5943,bonus_id=4800/1507/4786,context=6
trinket1=,id=160651,bonus_id=4800/1507/4786,context=6
trinket2=,id=165664,bonus_id=4803/1562/4786,context=28
main_hand=,id=160680,enchant_id=5963,bonus_id=4800/1507/4786,context=6
off_hand=,id=160695,bonus_id=4800/1507/4786,context=6

### Gear from Bags
#
# Sombrero para pescar deteriorado por el tiempo (10)
# head=,id=33820,context=11
#
# Dije de buscador de tesoros verdadero (58)
# neck=,id=27944,context=14
#
# Collar de plata reluciente (1)
# neck=,id=141322
#
# Amito de artificiero de los Defensores del Honor (370)
# shoulder=,id=163424,bonus_id=5125/1562/4786/5400,context=28,azerite_powers=
#
# Manto de tejearena (370)
# shoulder=,id=157939,bonus_id=1562/4786/5400,context=28,azerite_powers=
#
# Amito de artificiero de los Defensores del Honor (370)
# shoulder=,id=163424,bonus_id=5125/1562/4786/5400,context=29,azerite_powers=
#
# Toga de artificiero de los Defensores del Honor (370)
# chest=,id=163280,bonus_id=5125/1562/4786/5398,context=29,azerite_powers=
#
# Sobrevesta de espíritu de pantano (370)
# chest=,id=157898,bonus_id=1562/4786/5398,context=28,azerite_powers=
#
# Tabardo de los Voldunai (120)
# tabard=,id=160548,context=14
#
# Tabardo de los Buscadores Tortolianos (120)
# tabard=,id=160543,context=14
#
# Cubremuñecas de vinculación de hechizos (350)
# wrist=,id=161503,context=14
#
# Guantes del devoto escamado (350)
# hands=,id=165235,context=14
#
# Manijas del clamavientos (370)
# hands=,id=161350,bonus_id=4798/1492/4784,context=3
#
# Fajín espiritual de Zo'bal (350)
# waist=,id=165237,context=14
#
# Cordón de artificiero de los Defensores del Honor (370)
# waist=,id=163430,bonus_id=5126/1562/4786,context=6
#
# Sortija Cinérea de destrucción (100)
# finger1=,id=50377,context=11
#
# Sortija de aniquilación cierta (370)
# finger1=,id=160646,enchant_id=5943,bonus_id=4799/1492/4786,context=5
#
# Anillo de rastreo de podredumbre (370)
# finger1=,id=160645,enchant_id=5943,bonus_id=4799/1492/4786,context=5
#
# Odio de fatalidad (370)
# trinket1=,id=161461,bonus_id=5119/1492/4786,context=3
#
# Piedra de alquimista astral (192)
# trinket1=,id=151607,bonus_id=3609/601/3603,context=13
#
# Garrocha hundebarcos del destello (266)
# main_hand=,id=159566,bonus_id=4796/1691,drop_level=120
#
# Caña de pescar fuerte (10)
# main_hand=,id=6365,context=14

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-20 15:17
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-20 15:17 UTC
