### ISSUE TITLE
Simulationcraft error crucible weight

### ISSUE THREAD

**Issue by Morideth** [simulationcraft/simc#4175] opened 2017-11-30 00:04 UTC
SimulationCraft encountered an error!

Simulation runtime error:
Player Nocommands invalid crucible rank '1778' for power '1739', expected a number > 0 && 

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Nocommands invalid crucible rank '1778' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.20
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Normal
calculate_scale_factors=1
scale_only=agi,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
rogue="Nocommands"
level=110
race=blood_elf
region=us
server=darkspear
role=attack
professions=blacksmithing=800/enchanting=250
talents=1113113
spec=subtlety
artifact=17:0:0:0:0:851:1:852:4:853:4:854:4:855:4:856:4:857:4:858:4:859:4:860:4:861:1:862:1:863:1:864:1:865:1:866:1:1349:1:1386:1:1585:4:1586:1:1587:1:1588:23:1653:1
crucible=1739:1778:854/1739:1778:857/1739:1782

head=,id=147172,bonus_id=3561/1492/3336
neck=,id=137311,enchant_id=5890,gem_id=151584,bonus_id=3418/1808/1587/3337
shoulder=,id=144236,enchant_id=5883,bonus_id=1811/3570
back=,id=147170,enchant_id=5435,gem_id=130222,bonus_id=3561/1808/1487/3336
chest=,id=147169,bonus_id=3561/1482/3528
shirt=,id=42360
tabard=,id=35221
wrist=,id=147041,bonus_id=3561/1507/3337
hands=,id=151818,enchant_id=5445,bonus_id=3459/3570
waist=,id=151990,bonus_id=3611/1497/3336
legs=,id=147173,bonus_id=3562/1507/3336
feet=,id=134193,bonus_id=3418/1612/3337
finger1=,id=142171,enchant_id=5429,bonus_id=3418/1532/3528
finger2=,id=147194,enchant_id=5429,bonus_id=3562/1497/3528
trinket1=,id=147010,bonus_id=3562/1532/3337
trinket2=,id=142167,bonus_id=3573/1537/3337
main_hand=,id=128476,gem_id=152031/137347/142181,bonus_id=743,relic_id=3611:1487:3528/3573:1582:3337/3418:1552:3337
off_hand=,id=128479

### Gear from Bags
#
# Adorno das Espinheiras Vivas (930)
# head=,id=152681,gem_id=151585,bonus_id=3610/1808/1472/3528
#
# Capuz com Chifres da Retaliação (930)
# head=,id=152361,bonus_id=3614/1472/3528
#
# Gargantilha Rebitada do Delírio (930)
# neck=,id=151966,enchant_id=5439,gem_id=151585,bonus_id=3610/1808/1472/3528
#
# Prydaz, Obra Magna de Xavaric (970)
# neck=,id=132444,bonus_id=3459/3570
#
# Ombreiras do Matador das Presas (900)
# shoulder=,id=147174,enchant_id=5883,bonus_id=3561/1482/3528
#
# Manto do Biltre Ousado (935)
# back=,id=152161,enchant_id=5435,bonus_id=3610/1808/1477/3336
#
# A Trapaça do Senhor do Medo (970)
# back=,id=137021,enchant_id=5432,bonus_id=3459/3570
#
# Clâmide da Caçada Espiritual (945)
# back=,id=151938,bonus_id=3611/1487/3528
#
# Colete do Galho Tranquilo (935)
# chest=,id=139071,bonus_id=3418/1597/3337
#
# Negação dos Meio-gigantes (970)
# wrist=,id=137100,bonus_id=3459/3570
#
# Protetores de Mão do Matador das Presas (915)
# hands=,id=147171,bonus_id=3562/1497/3528
#
# Luvas das Compulsões Extravagantes (900)
# hands=,id=147032,bonus_id=3561/1482/3528
#
# Protetores de Mão do Intruso Atinado (935)
# hands=,id=137480,bonus_id=3418/1587/3337
#
# Simetria de Shivarra (1000)
# hands=,id=141321,bonus_id=1811/3630
#
# Luvas das Compulsões Extravagantes (920)
# hands=,id=147032,bonus_id=3562/1502/3336
#
# Cintel de Osso Gravado (925)
# waist=,id=147040,bonus_id=3561/1507/3337
#
# Cilha de Carne Fervilhante (930)
# waist=,id=147039,bonus_id=3562/1512/3337
#
# Cinidária, a Simbionte (970)
# waist=,id=133976,bonus_id=1811/3570
#
# Cinto da Sanidade Fraturada (930)
# waist=,id=151991,bonus_id=3610/42/1472/3528
#
# Cilha da Perspicácia Detestável (930)
# waist=,id=152364,bonus_id=3614/1472/3528
#
# Vontade de Valira (970)
# legs=,id=137069,bonus_id=1811/3570
#
# Calças do Biltre Ousado (930)
# legs=,id=152164,gem_id=151585,bonus_id=3610/1808/1472/3528
#
# Botinas do Bosque Obscurecente (940)
# feet=,id=134429,bonus_id=3418/1592/3337
#
# Botinas Travessas de Thraxi (1000)
# feet=,id=137031,bonus_id=3459/3630
#
# Desbravadores do Alastramento Vil (920)
# feet=,id=147030,bonus_id=3562/1808/1502/3336
#
# Alma do Umbralâmina (970)
# finger1=,id=150936,enchant_id=5429,gem_id=130222,bonus_id=1811/3570
#
# Insígnia do Grande Exército (1000)
# finger1=,id=152626,enchant_id=5430,gem_id=151585,bonus_id=3459/3630
#
# Insígnia dos Corvoforte (1000)
# finger1=,id=137049,enchant_id=5430,gem_id=151585,bonus_id=3459/3630
#
# Engenho da Erradicação (910)
# trinket1=,id=147015,bonus_id=3573/1492/3528
#
# Glaives Lunares do Umbral (915)
# trinket1=,id=147012,bonus_id=3562/1497/3528
#
# Tragada das Almas (895)
# trinket1=,id=140808,bonus_id=3517/1492/3528
#
# Contrato de Espreitador do Caos (915)
# trinket1=,id=151307,bonus_id=3417/1567/3336
#
# Espectro da Traição (895)
# trinket1=,id=151190,bonus_id=3564/1477/3528
#
# Convergência de Destinos (915)
# trinket1=,id=140806,bonus_id=3573/1512/3336
#
# Pedra-ume Cortavento (935)
# trinket1=,id=137486,bonus_id=3418/1587/3337
#
# Distintivo da Conquista do Gladiador Dominador (910)
# trinket1=,id=148599,bonus_id=3573/1542/3528
#
# Martelo de Ferreiro (1)
# main_hand=,id=5956
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by Melekus** [comment] 2017-11-30 01:01
Make sure your simcraft version is updated with the latest nightly build.
Duplicate of #4000

**Closed as completed by Melekus** 2017-11-30 01:01 UTC
