### ISSUE TITLE
Unknown option 'crucible' with value '0/0/0'

### ISSUE THREAD

**Issue by savilla0628** [simulationcraft/simc#4048] opened 2017-09-21 15:14 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

I am operating on Version 730-02 

I keep getting this error:  Unknown option 'crucible' with value '0/0/0'

Here is the log:

Priorities (actions.precombat):
    snapshot_stats
  Priorities:

  Actions:
  Constant Buffs: bleeding/mortal_wounds
  Dynamic Buffs:
    Health Decade (0 - 10)   : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.27%  benefit=11%
    Health Decade (10 - 20)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=10.85%  benefit=11%
    Health Decade (20 - 30)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.38%  benefit=11%
    Health Decade (30 - 40)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=11.52%  benefit=12%
    Health Decade (40 - 50)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 8.77%  benefit= 9%
    Health Decade (50 - 60)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 9.31%  benefit= 9%
    Health Decade (60 - 70)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=13.23%  benefit=13%
    Health Decade (70 - 80)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime=12.29%  benefit=12%
    Health Decade (80 - 90)  : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 5.76%  benefit= 6%
    Health Decade (90 - 100) : start= 1.0 refresh=  0.0 interval=  0.0 trigger=  0.0 uptime= 5.62%  benefit= 6%
    judgment                 : start=25.8 refresh= 48.2 interval= 12.0 trigger=  4.1 uptime=89.92%  benefit=95%
  Scale Factors:
    Weights :
    Wowhead : 
  Waiting: 0.00%
Waiting:
     4.1% : Rbjësus

Baseline Performance:
  RNG Engine    = sse2-sfmt
  Iterations    = 18833 (3185, 3112, 3137, 3108, 3137, 3154)
  TotalEvents   = 100108644
  MaxEventQueue = 34
  TargetHealth  = 236308557
  SimSeconds    = 5727391
  CpuSeconds    = 44.828
  WallSeconds   = 7.544
  SpeedUp       = 127763
  EndTime       = 2017-08-09 23:18:37-0700 (1502345917)

Scale Factors:
  Rbjësus  Str=16.53(0.54)  AP=0.00(0.00)  Crit=19.12(0.54)  Haste=15.14(0.54)  Mastery=14.71(0.54)  Vers=18.50(0.54)  Wdps=0.00(0.00)

Please help.  I have no idea what is going on

**Comment by savilla0628** [comment] 2017-09-21 15:19
Not sure what is going on here :(

**Comment by vituscze** [comment] 2017-09-21 16:51
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-21 16:51 UTC
Labels: duplicate
