### ISSUE TITLE
Simulation error 

### ISSUE THREAD

**Issue by Rhodewald** [simulationcraft/simc#4616] opened 2018-12-11 15:33 UTC

**Comment by Rhodewald** [comment] 2018-12-11 15:34
SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Fríedrich': Item 'inactive' Slot 'head': Cannot parse option from ',id=163596,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=485/21/473/13': Unexpected parameter 'context'.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Fríedrich': Item 'inactive' Slot 'head': Cannot parse option from ',id=163596,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=485/21/473/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
rogue="Fríedrich"
level=120
race=worgen
region=eu
server=die_aldor
role=attack

talents=2212231
spec=assassination

head=,id=163596,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=485/21/473/13
neck=,id=158075,bonus_id=4932/4933/4936/1526,context=11,azerite_level=28
shoulder=,id=160620,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=483/30/217/13
back=,id=158375,bonus_id=5007/1547/4784,context=16
chest=,id=160728,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=485/30/14/13
wrist=,id=160621,gem_id=154127,bonus_id=4798/1808/1477/4786,context=3
hands=,id=163256,bonus_id=5126/1562/4786,context=6
waist=,id=159333,bonus_id=5005/1532/4783,context=35
legs=,id=160625,gem_id=154127,bonus_id=4798/1808/1477/4786,context=3
feet=,id=163383,bonus_id=5126/1567/4783,context=6
finger1=,id=159463,gem_id=154127,bonus_id=5010/4802/1542/4786,context=16
finger2=,id=160646,bonus_id=4798/1477/4786,context=3
trinket1=,id=160652,bonus_id=4798/1482/4783,context=3
trinket2=,id=159623,bonus_id=4780/41/1522/4783,context=16
main_hand=,id=160683,bonus_id=4799/1492/4786,context=5
off_hand=,id=159132,bonus_id=5009/1542/4783,context=16

### Gear from Bags
#
# Anomalus' Helm (335)
# head=,id=127586,bonus_id=5130,drop_level=120,context=22
#
# Wildevarhose der Aurora (89)
# legs=,id=36096,bonus_id=1706/3850,drop_level=120,context=36
#
# Ring der pulsierenden Venen (350)
# finger1=,id=159463,bonus_id=5002/1522/4786,context=16
#
# Meteoritenschleifstein (335)
# trinket1=,id=127493,bonus_id=5130,drop_level=120,context=22
#
# Angelrute (1)
# main_hand=,id=6256,context=14

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=2

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by seriallos** [comment] 2018-12-11 17:52
Duplicate of #4613 

Update your local SimulationCraft version to a recent nightly build

**Closed as completed by seriallos** 2018-12-11 17:52 UTC
Labels: duplicate
