### ISSUE TITLE
Failure when i try to sim my Pala

### ISSUE THREAD

**Issue by Siiuox** [simulationcraft/simc#4634] opened 2018-12-15 19:38 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Siiuox': Item 'inactive' Slot 'head': Cannot parse option from ',id=166696,bonus_id=5478/1502/4786/5402/4775,context=3,azerite_powers=523/31/14/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.025
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=12
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Post your Simc Addon Export text here.
# SimC Addon 1.10.8
paladin="Siiuox"
level=120
race=blood_elf
region=eu
server=blackmoore
role=attack
professions=herbalism=52/enchanting=14
talents=2213213
spec=retribution

head=,id=166696,bonus_id=5478/1502/4786/5402/4775,context=3,azerite_powers=523/31/14/13
neck=,id=158075,bonus_id=4933/4936/4929/1532,context=11,azerite_level=31
shoulder=,id=157932,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=154/30/15/13
back=,id=160643,bonus_id=4799/1492/4786,context=5
chest=,id=157926,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=125/31/44/13
wrist=,id=160637,bonus_id=4800/1507/4786,context=6
hands=,id=163458,bonus_id=5126/1562/4786,context=6
waist=,id=159426,bonus_id=5005/1532/4783,context=35
legs=,id=160639,bonus_id=4799/1492/4786,context=5
feet=,id=163460,bonus_id=5126/1562/4786,context=6
finger1=,id=165680,bonus_id=4803/1562/4786,context=28
finger2=,id=160645,bonus_id=4799/1492/4786,context=5
trinket1=,id=161376,bonus_id=4798/1477/4786,context=3
trinket2=,id=161463,gem_id=154127,bonus_id=5119/1808/1492/4786,context=3
main_hand=,id=160679,enchant_id=5963,bonus_id=4798/1487/4783,context=3

### Gear from Bags
#
# Tristwaldschulterstücke (325)
# shoulder=,id=158028,bonus_id=1517/4785/5391,context=27,azerite_powers=
#
# Rotbrauner Gürtel (37)
# waist=,id=3593,context=14
#
# Grabhügelhüftgurt des Hitzeschocks (266)
# waist=,id=154858,bonus_id=4796/4802/1699,drop_level=120
#
# Ring der unendlichen Leere (355)
# finger1=,id=160647,enchant_id=5943,gem_id=154127,bonus_id=4798/1808/1477/4786,context=3
#
# Ausgeblichener Knochenentersäbel des Harmonischen (266)
# main_hand=,id=159595,bonus_id=4796/1714,drop_level=120
#
# Verteidiger der Flussmarschen des Feuersturms (266)
# off_hand=,id=159809,bonus_id=4796/1696,drop_level=120
#
# Rundschild von Zem'lan der Aurora (266)
# off_hand=,id=159807,bonus_id=4796/1709,drop_level=120
#
# Eisenwogenlaterne der Aurora (266)
# off_hand=,id=159820,bonus_id=4796/1706,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=8

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by Pewtro** [comment] 2018-12-15 20:18
Download a new build of SimulationCraft from here: http://downloads.simulationcraft.org/?C=M;O=D
Yours is several months old. 

Duplicate of #4613

**Comment by seriallos** [comment] 2018-12-15 20:18
Duplicate of #4613 - Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed** 2018-12-15 20:18 UTC
Labels: duplicate
