### ISSUE TITLE
asked to make a ticket

### ISSUE THREAD

**Issue by Sabe2** [simulationcraft/simc#4219] opened 2018-01-01 19:19 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Sabellayia invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
hunter="Sabellayia"
level=110
race=night_elf
region=us
server=sargeras
role=attack
professions=mining=800/jewelcrafting=800
talents=2111113
spec=beast_mastery
artifact=56:0:0:0:0:868:4:869:4:870:4:871:4:872:4:873:4:874:4:875:4:876:1:877:1:878:1:879:1:880:1:881:1:882:1:1095:4:1336:1:1368:1:1517:4:1518:1:1519:1:1520:25:1636:1
crucible=1739:1782:1517/1739:1777:1095/1739:1771:1517

head=,id=152423,bonus_id=3611/1487/3528
neck=,id=151973,enchant_id=5437,bonus_id=3611/1507/3337
shoulder=,id=147144,enchant_id=5929,bonus_id=3562/1512/3337
back=,id=152131,enchant_id=5435,bonus_id=3611/1497/3336
chest=,id=133622,bonus_id=3535/1607/3337
wrist=,id=152280,bonus_id=3610/1502/3337
hands=,id=147141,enchant_id=5445,gem_id=151580,bonus_id=3562/1808/1497/3528
waist=,id=137080,bonus_id=1811/3630
legs=,id=152134,bonus_id=3610/1482/3336
feet=,id=137227,bonus_id=3459/3630
finger1=,id=134489,enchant_id=5427,bonus_id=3418/1587/3337
finger2=,id=134528,enchant_id=5427,bonus_id=3418/1587/3337
trinket1=,id=154174,bonus_id=3984/3989
trinket2=,id=147010,bonus_id=3573/1507/3337
main_hand=,id=128861,gem_id=152059/152344/155855,bonus_id=726,relic_id=3610:1472:3528/3614:1487:3337/3611:1507:3336

### Gear from Bags
#
# Wildstalker Helmet (915)
# head=,id=147142,bonus_id=3562/1497/3528
#
# Chain of the Underking (940)
# neck=,id=134495,bonus_id=3535/1592/3336
#
# Prydaz, Xavaric's Magnum Opus (1000)
# neck=,id=132444,enchant_id=5437,gem_id=151584,bonus_id=3459/3630
#
# Riveted Choker of Delirium (930)
# neck=,id=151966,bonus_id=3610/1472/3528
#
# Serpentstalker Mantle (930)
# shoulder=,id=152135,enchant_id=5929,bonus_id=3610/1472/3528
#
# Pauldrons of the Soulburner (950)
# shoulder=,id=152004,bonus_id=3611/1492/3336
#
# Shoulderguards of Bane (930)
# shoulder=,id=133625,bonus_id=3534/1582/3528
#
# Cloak of the Burning Vanguard (955)
# back=,id=151937,enchant_id=5435,bonus_id=3611/1497/3336
#
# Wildstalker Cape (920)
# back=,id=147140,enchant_id=5435,gem_id=151584,bonus_id=3562/1808/1502/3336
#
# Serpentstalker Tunic (930)
# chest=,id=152130,bonus_id=3610/1472/3528
#
# Parsel's Tongue (1000)
# chest=,id=151805,bonus_id=3459/3630
#
# Chestguard of Ravaged Chitin (955)
# chest=,id=137428,bonus_id=3535/1607/3337
#
# Luminous Bladesworn Hauberk (960)
# chest=,id=137498,bonus_id=3536/1612/3337
#
# Wildstalker Chestguard (915)
# chest=,id=147139,bonus_id=3562/1497/3528
#
# Enthralling Chain Armor (930)
# chest=,id=152366,bonus_id=3614/1472/3528
#
# Scalding Shatterguards (930)
# wrist=,id=152280,bonus_id=3610/1472/3528
#
# Tideskorn Gauntlets (940)
# hands=,id=134209,bonus_id=3536/1602/3528
#
# Gauntlets of Spiteful Haunting (915)
# hands=,id=147047,bonus_id=3562/1497/3528
#
# Vigilance Perch (1000)
# hands=,id=146668,enchant_id=5445,gem_id=130222/130222/130222,bonus_id=1811/3630
#
# Tideskorn Cinch (940)
# waist=,id=134207,bonus_id=3536/1602/3528
#
# War Belt of the Sentinel Army (1000)
# waist=,id=137081,bonus_id=1811/3630
#
# Dominant Combatant's Chain Clasp (870)
# waist=,id=149840,bonus_id=3582/1678/1532/3528
#
# Roots of Shaladrassil (1000)
# legs=,id=132466,bonus_id=3529/1811/3630
#
# Legguards of Doomed Chattel (930)
# legs=,id=152370,bonus_id=3614/1808/1472/3528
#
# Wildstalker Leggings (915)
# legs=,id=147143,gem_id=130247,bonus_id=3562/1808/1497/3528
#
# Legguards of Countless Hours (960)
# legs=,id=142135,bonus_id=3536/1572/3337
#
# Ullr's Feather Snowshoes (1000)
# feet=,id=137033,bonus_id=1811/3630
#
# Sabatons of Ceaseless Assault (930)
# feet=,id=152367,bonus_id=3614/1472/3528
#
# Whelp Handler's Lined Boots (925)
# feet=,id=134464,bonus_id=3418/1577/3336
#
# Scaled Band of Servitude (915)
# finger1=,id=147020,enchant_id=5429,bonus_id=3562/40/1497/3528
#
# Violet Seal of the Grand Magus (875)
# finger1=,id=142469
#
# Dominant Combatant's Signet (875)
# finger1=,id=149918,bonus_id=3582/1808/41/1537/3336
#
# Ring of Fel Domination (940)
# finger1=,id=144481,enchant_id=5429,bonus_id=3418/1592/3337
#
# Band of the Sargerite Smith (930)
# finger1=,id=152064,bonus_id=3610/1808/1472/3528
#
# Engine of Eradication (930)
# trinket1=,id=147015,bonus_id=3562/1512/3337
#
# Tarnished Sentinel Medallion (915)
# trinket1=,id=147017,bonus_id=3562/41/1497/3528
#
# Convergence of Fates (910)
# trinket1=,id=140806,bonus_id=3573/40/1507/3528
#
# Infernal Bloodstone Shard (920)
# trinket1=,id=134379,bonus_id=3573/604/1582/3336
#
# Mark of the Sentinel (915)
# trinket1=,id=136749,bonus_id=3573/603/1577/3336
#
# Stormsinger Fulmination Charge (935)
# trinket1=,id=137367,bonus_id=3534/1587/3336
#
# Eye of Skovald (935)
# trinket1=,id=133641,bonus_id=3418/1587/3337
#
# Krokul Mining Pick (800)
# main_hand=,id=153290
#
# Surface-to-Infernal Rocket Launcher (700)
# main_hand=,id=136631,bonus_id=1717
#
# Krokul Mining Pick (800)
# off_hand=,id=153290
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2018-01-02 13:14
Duplicate of #4000

**Closed as completed by vituscze** 2018-01-02 13:14 UTC
