### ISSUE TITLE
Simulationcraft V1.82 breaks 730-01 webengine

### ISSUE THREAD

**Issue by Maxhawkgt** [simulationcraft/simc#4007] opened 2017-09-14 20:18 UTC
I downloaded 730-01 to update simulationcraft64 on my PC so it would work with the new crucible relics. Later my simulationcraft addon was updated to V1.82 and now I get an error: https://pastebin.com/HaupZZCj

Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
1.82, webengine 730-1

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - 
n/a

#### simc_gui.simc file or contents
https://pastebin.com/Zb21PcvG

#### Reproduction Steps:
Run simulate on webengine after copying and pasting info from /simc

**Comment by vituscze** [comment] 2017-09-14 22:35
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-14 22:35 UTC
Labels: duplicate
