### ISSUE TITLE
Simulate error

### ISSUE THREAD

**Issue by Penushead** [simulationcraft/simc#4659] opened 2018-12-20 22:14 UTC
**SimulationCraft encountered an error!
Category: Simulation runtime error
Error: Initializing: Actor 'Penushead': Item 'inactive' Slot 'head': Cannot parse option from ',id=160634,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/31/15/13': Unexpected parameter 'context'.
All options used for simulation:
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers
statistics_level=1
### Begin simulateText ###
# SimC Addon 1.10.8
warrior="Penushead"
level=120
race=undead
region=eu
server=draenor
role=attack
professions=blacksmithing=121/mining=49
talents=3112211
spec=arms

head=,id=160634,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/31/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=161460,bonus_id=5120/1492/4786/4775,context=3,azerite_powers=433/22/83/13
back=,id=159287,bonus_id=5007/1552/4784,context=16
chest=,id=163459,bonus_id=5125/1562/5138/5383/4775,context=28,azerite_powers=121/31/15/13
wrist=,id=158311,bonus_id=5005/1552/4784,context=35
hands=,id=160635,gem_id=154127,bonus_id=4799/1808/43/1492/4786,context=5
waist=,id=163461,bonus_id=5126/1567/4783,context=6
legs=,id=163455,bonus_id=5126/1567/4783,context=6
feet=,id=159412,bonus_id=5007/1542/4783,context=35
finger1=,id=160645,enchant_id=5939,gem_id=154127,bonus_id=4799/1808/1492/4786,context=5
finger2=,id=159458,enchant_id=5939,bonus_id=5009/1547/4786,context=35
trinket1=,id=160655,bonus_id=4799/1492/4786,context=5
trinket2=,id=160650,bonus_id=4799/1492/4786,context=5
main_hand=,id=163870,enchant_id=5950,gem_id=154127,bonus_id=5126/4802/1562/4786,context=6

**Comment by vituscze** [comment] 2018-12-20 22:26
Looks like your report is missing the actual error that occured.

**Comment by Penushead** [comment] 2018-12-21 08:10
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Penushead': Item 'inactive' Slot 'head': Cannot parse option from ',id=160634,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/31/15/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
warrior="Penushead"
level=120
race=undead
region=eu
server=draenor
role=attack
professions=blacksmithing=121/mining=49
talents=3112211
spec=arms

head=,id=160634,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/31/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=161460,bonus_id=5120/1492/4786/4775,context=3,azerite_powers=433/22/83/13
back=,id=159287,bonus_id=5007/1552/4784,context=16
chest=,id=163459,bonus_id=5125/1562/5138/5383/4775,context=28,azerite_powers=121/31/15/13
wrist=,id=158311,bonus_id=5005/1552/4784,context=35
hands=,id=160635,gem_id=154127,bonus_id=4799/1808/43/1492/4786,context=5
waist=,id=163461,bonus_id=5126/1567/4783,context=6
legs=,id=163455,bonus_id=5126/1567/4783,context=6
feet=,id=159412,bonus_id=5007/1542/4783,context=35
finger1=,id=160645,enchant_id=5939,gem_id=154127,bonus_id=4799/1808/1492/4786,context=5
finger2=,id=159458,enchant_id=5939,bonus_id=5009/1547/4786,context=35
trinket1=,id=160655,bonus_id=4799/1492/4786,context=5
trinket2=,id=160650,bonus_id=4799/1492/4786,context=5
main_hand=,id=163870,enchant_id=5950,gem_id=154127,bonus_id=5126/4802/1562/4786,context=6

### Gear from Bags
#
# Petrified Ironbark Crown (390)
# head=,id=166696,bonus_id=5478/1502/4786/5402/4775,context=3,azerite_powers=433/31/14/13
#
# Brutohide Vest of the Fireflash (266)
# chest=,id=160133,bonus_id=4796/1695,drop_level=120
#
# Chestplate of Apocalyptic Machinations (375)
# chest=,id=160722,bonus_id=4823/1492/4786/5398/4775,context=5,azerite_powers=485/461/477/13
#
# Deathguard's Gauntlets (340)
# hands=,id=165490,bonus_id=5124/1457/4786,context=3
#
# Sharktooth-Knuckled Grips (370)
# hands=,id=155890,bonus_id=5010/1542/4786,context=16
#
# Gauntlets of the Avian Sentinel (360)
# hands=,id=159413,bonus_id=5007/4802/1532/4786,context=16
#
# Girdle of Pestilent Purification (365)
# waist=,id=159418,bonus_id=5009/4802/1537/4786,context=16
#
# Deathguard's Waistplate (385)
# waist=,id=165495,bonus_id=5126/1502/4786,context=6
#
# Legplates of Beaten Gold (355)
# legs=,id=158313,bonus_id=5006/1527/4786,context=16
#
# Honorbound Centurion's Greaves (340)
# feet=,id=163460,bonus_id=5124/1532/4786,context=3
#
# Honorbound Centurion's Greaves (370)
# feet=,id=163460,bonus_id=5126/1562/4786,context=6
#
# Thornwoven Band (375)
# finger1=,id=162548,bonus_id=5009/1547/4786,context=35
#
# Stormsteel Saber of the Fireflash (300)
# main_hand=,id=162665,bonus_id=1691/4927,context=13
#
# Blacksmith Hammer (1)
# main_hand=,id=5956,context=14
#
# Voror, Gleaming Blade of the Stalwart (370)
# main_hand=,id=160686,bonus_id=4799/1492/4786,context=5
#
# Mining Pick (4)
# main_hand=,id=2901,context=14
#
# Honorable Combatant's Shield of the Quickblade (300)
# off_hand=,id=159851,bonus_id=1680/4927,context=13

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2018-12-21 11:55
Duplicate of #4613

Please update your simc to 810-01 or use one of the recent nightly builds.

**Closed as completed by vituscze** 2018-12-21 11:55 UTC
