### ISSUE TITLE
Can't find slot helm

### ISSUE THREAD

**Issue by Meladron** [simulationcraft/simc#4647] opened 2018-12-18 03:40 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Expira': Item 'inactive' Slot 'head': Cannot parse option from ',id=160910,bonus_id=4775,context=11,azerite_powers=82/44/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
deathknight="Expira"
level=114
race=blood_elf
region=us
server=wyrmrest_accord
role=attack
professions=blacksmithing=8/mining=32
talents=3113233
spec=frost

head=,id=160910,bonus_id=4775,context=11,azerite_powers=82/44/13
neck=,id=158075,bonus_id=4932/4933/4935/1484,context=11,azerite_level=7
shoulder=,id=155260,bonus_id=1452/4785,context=25,azerite_powers=346/83
back=,id=151298,bonus_id=3573/1476/3528,context=43
chest=,id=163675,bonus_id=1472/4785,context=25,azerite_powers=242/15
tabard=,id=5976,context=14
wrist=,id=152809,bonus_id=1688/4927,context=13
hands=,id=161042,bonus_id=4776/4802,drop_level=113,context=17
waist=,id=146667,gem_id=130246/130219/130219,bonus_id=1811/3570,context=13
legs=,id=158399,bonus_id=4790,drop_level=113,context=11
feet=,id=159150,bonus_id=4790,drop_level=112,context=11
finger1=,id=155304,bonus_id=4787,drop_level=113,context=11
finger2=,id=161139,bonus_id=4787,drop_level=112,context=11
trinket1=,id=161125,bonus_id=4776,drop_level=112,context=17
trinket2=,id=159763,bonus_id=4787,drop_level=112,context=11
main_hand=,id=159119,bonus_id=4813,drop_level=112,context=11
off_hand=,id=159110,bonus_id=4793,drop_level=113,context=11

### Gear from Bags
#
# Monel-Hardened Armguards of the Aurora (225)
# wrist=,id=152809,bonus_id=1707/4927,context=13
#
# Monel-Hardened Armguards of the Aurora (225)
# wrist=,id=152809,bonus_id=1709/4927,context=13
#
# Monel-Hardened Armguards of the Peerless (225)
# wrist=,id=152809,bonus_id=1689/4927,context=13
#
# Monel-Hardened Armguards of the Feverflare (225)
# wrist=,id=152809,bonus_id=1699/4927,context=13
#
# Rastari Battlegloves (236)
# hands=,id=158424,bonus_id=4787,drop_level=112,context=11
#
# Relentless Hydra Legguards (238)
# legs=,id=161043,bonus_id=4776/40,drop_level=112,context=17
#
# Rastari Warboots (241)
# feet=,id=155242,bonus_id=4790,drop_level=113,context=11
#
# Ruptured Plate Stompers (108)
# feet=,id=154779
#
# Dread Aspirant's Signet (238)
# finger1=,id=162964,bonus_id=4990,drop_level=110,context=7
#
# Blacksmith Hammer (1)
# main_hand=,id=5956,context=14
#
# Mining Pick (4)
# main_hand=,id=2901,context=14
#
# Crimson Cultist Pummeler (241)
# main_hand=,id=159104,bonus_id=4790,drop_level=110,context=11
#
# Crimson Cultist Pummeler (241)
# off_hand=,id=159104,bonus_id=4790,drop_level=110,context=11

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-18 03:41
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-18 03:41 UTC
