### ISSUE TITLE
Resto Shaman... just doing what the program told me to

### ISSUE THREAD

**Issue by brat4300** [simulationcraft/simc#4373] opened 2018-07-21 00:23 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Chrystiana's role (hybrid) or spec(Restoration Shaman) isn't supported yet.
No active players in sim!

## All options used for simulation:
``` ini
### SimulationCraft 735-01 for World of Warcraft 7.3.5 Live (wow build 25901) ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
scale_over=HPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.1

shaman="Chrystiana"
level=110
race=draenei
region=us
server=draenor
role=heal
professions=mining=44/jewelcrafting=11
talents=2312113
spec=restoration
artifact=42:0:0:0:0:1117:1:1600:9:1102:1:1103:4:1104:4:1105:4:1106:4:1107:4:1108:4:1109:4:1110:4:1111:4:1112:1:1113:1:1114:1:1115:1:1116:1:1599:1:1598:1:1597:4:1693:1:1352:1:1389:1
crucible=0/0/0

head=,id=134471,bonus_id=1727/1498/3337
neck=,id=133633,bonus_id=1826/1476/3528
shoulder=,id=134345,bonus_id=3394/1491/3528
back=,id=134334,bonus_id=1824/1481/3528
chest=,id=152768,bonus_id=1692/3629/1472/3528
wrist=,id=147747,bonus_id=3572/1480/3336
hands=,id=137058,bonus_id=3459/3570
waist=,id=152767,bonus_id=1688/3629/1472/3528
legs=,id=147247,bonus_id=1690/3574/1504/3528
feet=,id=147744,bonus_id=3572/1476/3528
finger1=,id=147257,bonus_id=3404/3574/1504/3528
finger2=,id=134532,bonus_id=1727/1494/3336
trinket1=,id=147276,bonus_id=607/3574/1504/3528
trinket2=,id=134292,bonus_id=1825/605/1479/3528
main_hand=,id=128911,gem_id=137381/141274/142062,bonus_id=746/1482/1482/1480,relic_id=1826:1478:3336/1825:1479:3336
off_hand=,id=128934

### Gear from Bags
#
# Bronze-Tinted Sunglasses (1)
# head=,id=147885
#
# Oronaar Disciple's Coif of the Feverflare (180)
# head=,id=152765,bonus_id=1699/3629/1472/3528
#
# Oronaar Disciple's Coif of the Harmonious (180)
# head=,id=152765,bonus_id=1714/3629/1472/3528
#
# Hatecoil Commander's Amulet (174)
# neck=,id=134492,bonus_id=1826/1484/3337
#
# Galvanized Stormscale Chestguard of the Fireflash (172)
# chest=,id=147230,bonus_id=1692/3574/1506/3336
#
# Smoldering Heart (240)
# hands=,id=151819,bonus_id=1811/3570
#
# Farseer's Belt (165)
# waist=,id=139704,bonus_id=3385/3384
#
# Oronaar Disciple's Girdle of the Aurora (180)
# waist=,id=152767,bonus_id=1709/3629/1472/3528
#
# Oronaar Disciple's Girdle of the Quickblade (185)
# waist=,id=152767,bonus_id=1679/3629/1477/3336
#
# Oronaar Disciple's Legguards of the Peerless (180)
# legs=,id=152764,bonus_id=1687/3629/41/1472/3528
#
# Oronaar Disciple's Boots of the Aurora (180)
# feet=,id=152766,bonus_id=1706/3629/41/1472/3528
#
# Oronaar Disciple's Boots of the Feverflare (180)
# feet=,id=152766,bonus_id=1700/3629/1472/3528
#
# Seal of the Nazjatar Empire (166)
# finger1=,id=134525,bonus_id=1826/1476/3528
#
# Silent Seashell (166)
# trinket1=,id=134247,bonus_id=1825/41/605/1477/3528
#
# Beguiler's Talisman (172)
# trinket1=,id=147275,bonus_id=605/3574/1506/3336
#
# Mining Pick (4)
# main_hand=,id=2901
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by scamille** [comment] 2018-07-21 06:59
It might be a bit of a inappropriate message in the GUI, but opening a ticket for this will not bring a functioning restoration into existence.

If you want to contribute to healing spec development in simc or know someone else, do not hesitate to join us on Discord.

Duplicate of #2775

**Closed as completed by scamille** 2018-07-21 06:59 UTC
