### ISSUE TITLE
Sim Error

### ISSUE THREAD

**Issue by ManekNZ** [simulationcraft/simc#4627] opened 2018-12-14 19:14 UTC
Getting the below error on all characters, wont sim.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Manek': Item 'inactive' Slot 'head': Cannot parse option from ',id=160616,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/14/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=12
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
warlock="Manek"
level=120
race=undead
region=us
server=amanthul
role=spell
professions=tailoring=135/enchanting=81
talents=3222223
spec=affliction

head=,id=160616,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/14/13
neck=,id=158075,bonus_id=4936/4929/4930/1530,context=11,azerite_level=30
shoulder=,id=163424,bonus_id=5126/1562/4786/4775,context=6,azerite_powers=183/31/83/13
back=,id=160644,bonus_id=4799/1502/4783,context=5
chest=,id=157930,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=123/31/44/13
shirt=,id=2576
tabard=,id=63378
wrist=,id=160617,bonus_id=4799/1492/4786,context=5
hands=,id=160715,enchant_id=5937,bonus_id=4799/1492/4786,context=5
waist=,id=160734,bonus_id=4799/1497/4783,context=5
legs=,id=159277,bonus_id=5010/1552/4786,context=35
feet=,id=160714,bonus_id=4800/1507/4786,context=6
finger1=,id=158314,enchant_id=5944,bonus_id=5010/1542/4786,context=16
finger2=,id=160646,enchant_id=5944,gem_id=154127,bonus_id=4799/1808/1497/4783,context=5
trinket1=,id=160651,bonus_id=4799/1492/4786,context=5
trinket2=,id=159630,bonus_id=5008/1537/4786,context=16
main_hand=,id=160691,enchant_id=5964,gem_id=154127,bonus_id=4799/1808/1492/4786,context=5
off_hand=,id=160696,bonus_id=4799/1492/4786,context=5

### Gear from Bags
#
# Fen Spirit Headdress (370)
# head=,id=157873,bonus_id=1562/5136/5381,context=28,azerite_powers=
#
# Honorbound Artificer's Guise (370)
# head=,id=163426,bonus_id=5126/1562/4786,context=6,azerite_powers=
#
# Mantle of Contained Corruption (370)
# shoulder=,id=160613,bonus_id=4823/1492/4786,context=5,azerite_powers=483/31/475
#
# Honorbound Artificer's Amice (370)
# shoulder=,id=163424,bonus_id=5125/1562/5140/5382,context=28,azerite_powers=
#
# Shadra Silk Mantle (370)
# shoulder=,id=157907,bonus_id=1562/5140/5382,context=28,azerite_powers=
#
# Amice of Corrupting Horror (370)
# shoulder=,id=160726,bonus_id=4823/1492/4786/5400,context=5,azerite_powers=
#
# Fetid Horror's Tanglecloak (375)
# back=,id=160643,enchant_id=6089,bonus_id=4799/1497/4783,context=5
#
# Honorbound Artificer's Robes (370)
# chest=,id=163280,bonus_id=5125/1562/5138/5383,context=28,azerite_powers=123/30/475
#
# Robes of the Unraveler (370)
# chest=,id=160614,bonus_id=4823/1492/4786,context=5,azerite_powers=483/30/208
#
# Honorbound Artificer's Cuffs (370)
# wrist=,id=163306,enchant_id=5971,bonus_id=5126/1562/4786,context=6
#
# Leggings of the Drowned Lord (380)
# legs=,id=159242,bonus_id=5010/1552/4783,context=35
#
# Ring of the Infinite Void (370)
# finger1=,id=160647,enchant_id=5940,bonus_id=4799/1492/4786,context=5
#
# Titanspark Animator (370)
# main_hand=,id=160680,enchant_id=5964,bonus_id=4799/1492/4786,context=5
#
# Jeweled Fishing Pole (15)
# main_hand=,id=45992,context=11
#
# Uldir Subject Manifest (370)
# off_hand=,id=160695,bonus_id=4799/1492/4786,context=5

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=6

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-14 19:17
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-14 19:17 UTC
