### ISSUE TITLE
Program crash when I select Ultraxion fight style.

### ISSUE THREAD

**Issue by Rollkey** [simulationcraft/simc#2676] opened 2016-01-16 04:00 UTC
Only when I select the ultraxion fight style then simulate, the program pop-up "stop working" and ask me want to debug or just stop it. I tried other options, and all the other fight style work.

**Comment by mrdmnd** [comment] 2016-01-24 21:51
I cannot reproduce - can you provide an exact .simc input that leads to the crash? Can you be more specific about what options lead to the crash?

**Comment by Rollkey** [comment] 2016-01-25 03:14
I didn't change anything after I installed SimC. I only changed fight style to Ultraxion with all the other options are reseted. Import is loaded from Battle.net. Character: Bullon - Ner'zhul
It seems only druid could cause this problem. I tried my hunter, warrior, paladin. All works with same options. Also, I tried import from Sample Profiles. No matter feral druid or balance druid, with Ultraxion fight style, the program stop working.

**Comment by Rollkey** [comment] 2016-01-25 03:16
I attatch a few screenshots here.
![reset](https://cloud.githubusercontent.com/assets/10136217/12541678/e03f2c86-c2ce-11e5-9d8d-587171eddad0.PNG)
![ultraxion](https://cloud.githubusercontent.com/assets/10136217/12541669/c250f24a-c2ce-11e5-8808-a6b0858ad84e.PNG)
![import from sample profiles](https://cloud.githubusercontent.com/assets/10136217/12541671/cc0ac9d2-c2ce-11e5-8614-d1482fa7c296.PNG)
![stop working 1](https://cloud.githubusercontent.com/assets/10136217/12541672/cf802850-c2ce-11e5-9882-66bfd78dc601.PNG)
![stop working 2](https://cloud.githubusercontent.com/assets/10136217/12541674/d80be43c-c2ce-11e5-9aed-e4742b85ddd0.PNG)

**Comment by scamille** [comment] 2016-01-25 09:14
Ultraxion fight often exposes buggy implementations in class modules, because it adds movement/stun/etc.

Please attach the simc_gui.simc file you can find in your SimulationCraft installation folder, after you tried to run such a buggy simulation. It contains ALL the settings & profile you used for the last simulation.  This will make it much easier for us to reproduce the problem.

**Comment by scamille** [comment] 2016-01-25 13:39
https://github.com/simulationcraft/simc/wiki/simc_gui.simc

**Comment by navv1234** [comment] 2016-01-25 13:52
Should be fixed now.

**Comment by mrdmnd** [comment] 2016-01-25 18:34
Looks fixed to me too.

**Closed by mrdmnd** 2016-01-25 18:34 UTC
