### ISSUE TITLE
请问这是一个什么错误

### ISSUE THREAD

**Issue by hope-han** [simulationcraft/simc#4236] opened 2018-01-16 06:26 UTC
SimulationCraft encountered an error!

Simulation runtime error:
Unknown option 'level' with value '110' Player 爆炸骑士 invalid crucible rank '1770' for power '1739', expected a number > 0 && 0 && 0 && 0 && 0 && 0 && 0 && 0 && 

Please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

**Comment by vituscze** [comment] 2018-01-19 16:17
Duplicate of #4000

**Closed as completed by vituscze** 2018-01-19 16:17 UTC
