### ISSUE TITLE
CAnt Simulate

### ISSUE THREAD

**Issue by Cursdblood** [simulationcraft/simc#5095] opened 2020-05-01 11:10 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Cursdblood': Action 'berserking': Cannot parse expression from 'buff.unholy_frenzy.up|pet.gargoyle.active|(talent.army_of_the_damned.enabled&pet.apoc_ghoul.active)': Cannot find pet or pet spawner 'apoc_ghoul'.

## All options used for simulation:
``` ini
### SimulationCraft 830-01 for World of Warcraft 8.3.0 Live (wow build 33051) ###
### Using QT 5.12.6 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
scale_over=DPS
dps_plot_stat=str,agi,sta,ap,crit,haste,mastery,vers,wdps,wohdps,armor
dps_plot_points=20
dps_plot_step=150
dps_plot_target_error=0.5
dps_plot_iterations=0
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.# Cursdblood - Unholy - 2020-05-01 13:08 - EU/Kazzak
# SimC Addon 1.12.5
# Requires SimulationCraft 820-01 or newer

deathknight="Cursdblood"
level=68
race=undead
region=eu
server=kazzak
role=attack

talents=3233000
spec=unholy

head=,id=122263,bonus_id=3592
neck=,id=122667,bonus_id=582
shoulder=,id=122372,bonus_id=3592
back=,id=122266,bonus_id=582
chest=,id=122387,bonus_id=3592
tabard=,id=45583,context=14
wrist=,id=39680,bonus_id=4139/5569,drop_level=66,context=11
hands=,id=113692,bonus_id=4242/24,drop_level=66,context=1
waist=,id=43168,bonus_id=4117,drop_level=68,context=11
legs=,id=122264,bonus_id=3592
feet=,id=43176,bonus_id=4117,drop_level=68,context=11
finger1=,id=38218,bonus_id=4139,drop_level=66,context=11
finger2=,id=43178,bonus_id=4117,drop_level=68,context=11
trinket1=,id=122361,bonus_id=582
trinket2=,id=122361,bonus_id=582
main_hand=,id=122365,enchant_id=3368,bonus_id=583

### Gear from Bags
#
# Eternal Talisman of Evasion (77)
# neck=,id=122662,bonus_id=582
#
# Obsidian Citadel Necklace of the Fireflash (79)
# neck=,id=113688,bonus_id=4242/23,drop_level=68,context=1
#
# Snake Den Spaulders (77)
# shoulder=,id=37627,bonus_id=4117,drop_level=67,context=1
#
# Pauldrons of the Colossus (77)
# shoulder=,id=37635,bonus_id=4117,drop_level=67,context=1
#
# Worn Stoneskin Gargoyle Cape (77)
# back=,id=122260,bonus_id=583
#
# Ice-Bound Plate Chestpiece (58)
# chest=,id=33407,bonus_id=3819,drop_level=68,context=28
#
# The Plaguebringer's Girdle (58)
# waist=,id=38668,context=11
#
# Greaves of the Slaughter (58)
# feet=,id=38670,context=11
#
# Gemstone Ring of the Fireflash (58)
# finger1=,id=36420,bonus_id=1693/3839,drop_level=65,context=27
#
# Gal'darah's Signet (79)
# finger1=,id=43306,bonus_id=4117,drop_level=68,context=1
#
# Inherited Insignia of the Horde (77)
# trinket1=,id=122370
#
# Inherited Mark of Tyranny (77)
# trinket1=,id=122530,bonus_id=582
#
# Reforged Truesilver Champion (77)
# main_hand=,id=122365,enchant_id=3847,bonus_id=583
#
# Battleworn Thrash Blade (77)
# main_hand=,id=122369,enchant_id=3368,bonus_id=582
#
# Bloodsoaked Skullforge Reaver (77)
# main_hand=,id=122389,enchant_id=3370,bonus_id=582


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Melekus** [comment] 2020-05-04 17:01
Duplicate of #5098

**Closed as completed by Melekus** 2020-05-04 17:01 UTC
