### ISSUE TITLE
Frost mage - import error msg

### ISSUE THREAD

**Issue by rharlos2** [simulationcraft/simc#4806] opened 2019-06-10 20:03 UTC
### Describe the bug

Attempted to import us-zuluhed-wyntyr via the win-64 client and received the following error information in the "Import Failed" tab:

# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
# Unable to generate profile from: 
# Actor 'Wyntyr': Action 'ray_of_frost': Cannot parse expression from '!action.frozen_orb.in_flight&ground_aoe.frozen_orb.remains=0': No expression found.

### Expected behavior
Expected to successfully import the profile.

### To Reproduce
From the Win-64 client, under the "Import" tab, select "US", then "Zuluhed", then "Wyntyr", then click the button to import.

### Additional information
* SimulationCraft Version (required)
815-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files
SC is not crashing.

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

Error resulted in no file created beyond what I pasted above.

**Comment by vituscze** [comment] 2019-06-10 22:04
Duplicate of #4514

**Comment by vituscze** [comment] 2019-06-10 22:04
We generally do not support low level characters, but you can check the linked thread for workaround.

**Closed as completed by vituscze** 2019-06-10 22:04 UTC
