### ISSUE TITLE
Invalid Crucible Rank

### ISSUE THREAD

**Issue by barleyj** [simulationcraft/simc#4030] opened 2017-09-17 22:49 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
730-02

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Igrief invalid crucible rank '1774/1739/1739' for power '1739', expected a number > 0 && <= 255
Player igrief_test invalid crucible rank '1774/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=100
default_world_lag=0.1
max_time=300
vary_combat_length=0.5
fight_style=Patchwerk
tmi_window_global=6
optimal_raid=0
override.bloodlust=0
override.bleeding=0
override.mortal_wounds=0
threads=4
process_priority=Normal
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
deathknight="Igrief"
level=110
race=blood_elf
region=us
server=illidan
role=attack
professions=mining=783/engineering=773
talents=3221232
spec=unholy
artifact=16:0:0:0:0:149:1:150:1:151:1:152:1:153:1:154:1:156:4:157:4:158:4:262:4:263:1:264:4:265:4:266:4:267:4:1119:4:1333:1:1361:1:1489:4:1490:1:1491:1:1492:11:1629:1
crucible=1739:1774/1739/1739

head=,id=134182,bonus_id=3418/1577/3528
neck=,id=147014,enchant_id=5890,bonus_id=3562/1502/3336
shoulder=,id=137075,enchant_id=5899,bonus_id=3459/3570
back=,id=134408,enchant_id=5434,bonus_id=3536/1582/3337
chest=,id=147068,bonus_id=3562/1497/3528
shirt=,id=98091
tabard=,id=69210
wrist=,id=134230,gem_id=130222,bonus_id=3535/1808/1582/3337
hands=,id=147123,enchant_id=5445,bonus_id=3562/1517/3337
waist=,id=147753,bonus_id=3572/1502/3337
legs=,id=134514,bonus_id=3536/1582/3337
feet=,id=137529,bonus_id=3573/1562/3528
finger1=,id=134526,enchant_id=5429,bonus_id=3416/1562/3337
finger2=,id=151640,enchant_id=5429,gem_id=130246,bonus_id=3459/3570
trinket1=,id=133644,gem_id=130222,bonus_id=3416/1808/1567/3337
trinket2=,id=147010,bonus_id=3562/1507/3336
main_hand=,id=128403,enchant_id=3368,gem_id=137316/144464/137350,bonus_id=718,relic_id=3418:1567:3528/3536:1582:3337/3536:1582:3337

### Gear from Bags
#
# Polished Felfury Helmet (900)
# head=,id=147749,bonus_id=3572/1482/3528
#
# String of Extracted Incisors (900)
# neck=,id=147013,bonus_id=3561/1482/3528
#
# Choker of Barbed Reins (890)
# neck=,id=142174,bonus_id=3573/1507/3336
#
# Breathless Choker (945)
# neck=,id=137461,bonus_id=3418/1597/3337
#
# Understone Gorget (890)
# neck=,id=134491,bonus_id=3418/1542/3528
#
# Pauldrons of Encroaching Limits (915)
# shoulder=,id=142128,enchant_id=5899,gem_id=130222,bonus_id=3510/1808/41/1527/3337
#
# Frozen Pendulum Shoulderguards (890)
# shoulder=,id=134518,bonus_id=3418/1542/3528
#
# Drape of Shame (905)
# back=,id=142170,bonus_id=3418/1522/3337
#
# Acherus Drapes (970)
# back=,id=132376,bonus_id=1811/3570
#
# Cloak of the Unending Assault (910)
# back=,id=144476,enchant_id=5434,bonus_id=3509/1562/3337
#
# Cloak of Growing Mistrust (920)
# back=,id=147764,bonus_id=3572/1502/3337
#
# Crackling Overcharge Chestguard (910)
# chest=,id=134501,bonus_id=3536/1562/3528
#
# Inferno Breastplate (895)
# chest=,id=134503,bonus_id=3416/1547/3336
#
# Storm-Tempered Bracers of the Quickblade (880)
# wrist=,id=147228,bonus_id=1679/42/3573/1672/3528
#
# Duskwatch Plate Bracers (890)
# wrist=,id=140878,bonus_id=3516/43/1487/3528
#
# Wristclamps of Mad Dreams (900)
# wrist=,id=139235,bonus_id=3573/1808/1522/3337
#
# Thornscar Wristguards (890)
# wrist=,id=134520,bonus_id=3509/1542/3528
#
# Wristclamps of Mad Dreams (895)
# wrist=,id=139235,bonus_id=3573/43/1517/3337
#
# Moonshatter Vambraces (885)
# wrist=,id=146856,bonus_id=3573/43/1547/3336
#
# Repurposed Golem Grips (930)
# hands=,id=142125,bonus_id=3536/1542/3337
#
# Rumblestone Gauntlets (890)
# hands=,id=137355,bonus_id=3418/1542/3528
#
# Draugr, Girdle of the Everlasting King (970)
# waist=,id=132441,bonus_id=1811/3570
#
# Malicious Zealot's Legplates (905)
# legs=,id=147750,bonus_id=3572/1487/3336
#
# Portalguard Legplates (910)
# legs=,id=134359,bonus_id=3536/1808/1572/3528
#
# Duskwatch Guard's Boots (910)
# feet=,id=137482,bonus_id=3573/1562/3528
#
# Trampling Warboots (910)
# feet=,id=139234,bonus_id=3573/1532/3528
#
# Aggramar's Stride (970)
# feet=,id=132443,bonus_id=3459/3570
#
# Band of Dark Millennia (925)
# finger1=,id=147766,enchant_id=5425,bonus_id=3572/41/1507/3337
#
# Ring of Braided Stems (890)
# finger1=,id=140896,bonus_id=3516/1487/3528
#
# Ring of Exclusive Servitude (890)
# finger1=,id=140906,enchant_id=5425,bonus_id=3516/41/1487/1813
#
# Ring of Mind-Shielding (905)
# finger1=,id=137432,enchant_id=5429,bonus_id=3418/1557/3337
#
# Ring of the Scoured Clan (880)
# finger1=,id=140897,bonus_id=3515/1477/3528
#
# Seal of Darkshire Nobility (905)
# finger1=,id=142171,enchant_id=5429,bonus_id=3418/1522/3337
#
# Uvanimor, the Unbeautiful (970)
# finger1=,id=137037,enchant_id=5427,gem_id=130219,bonus_id=3459/3570
#
# Talisman of the Cragshaper (890)
# trinket1=,id=137344,bonus_id=3418/1542/3528
#
# Umbral Moonglaives (900)
# trinket1=,id=147012,bonus_id=3561/1482/3528
#
# Kil'jaeden's Burning Wish (970)
# trinket1=,id=144259,bonus_id=1811/3570
#
# Giant Ornamental Pearl (920)
# trinket1=,id=137369,bonus_id=3536/1572/3336
#
# Vial of Ceaseless Toxins (900)
# trinket1=,id=147011,bonus_id=3561/1808/1482/3528
#
# Mining Pick (4)
# main_hand=,id=2901
#
# Krokul Mining Pick (800)
# main_hand=,id=153290
#

copy=igrief_test

### End simulateText ###
desired_targets=5
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-17 22:50
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-17 22:50 UTC
Labels: duplicate
