### ISSUE TITLE
Can't run sim due to error from Helmet(?)

### ISSUE THREAD

**Issue by Thorrenn** [simulationcraft/simc#4625] opened 2018-12-13 07:26 UTC
### Describe the bug
When I import my SimC addon text and try to sim it, it gives a "Simulation runtime error."

### Expected behavior
Expected the sim to run and give simulation report.

### To Reproduce
Helmet is "Deadwash Headguard" ilvl 330 with unlocked Traits: Tidal Surge, Impassive Visage.
Character is lvl 120 Human Male, Survival Hunter

### Additional information
Version 801-1

Error report: 
> https://pastebin.com/Rtwif31E

Error Message: 
> Simulation runtime error:
> Initializing: Actor 'Tennerth': Item 'inactive' Slot 'head': Cannot parse option from ',id=158049,bonus_id=1517/4785/5390/4775,context=25,azerite_powers=478/83/13': Unexpected parameter 'context'.

* **simc_gui.simc** file or contents:
> https://pastebin.com/uCzSpHyL

**Comment by AlexanderKenny** [comment] 2018-12-13 07:26
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-13 07:26 UTC
