### ISSUE TITLE
bug when simulating

### ISSUE THREAD

**Issue by kalfu151** [simulationcraft/simc#4654] opened 2018-12-20 00:42 UTC
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by kalfu151** [comment] 2018-12-20 00:43
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Göttlos': Item 'inactive' Slot 'head': Cannot parse option from ',id=166696,bonus_id=5478/1502/4786/5402,context=3,azerite_powers=108/31': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,ap,crit,haste,mastery,vers,wdps,wohdps
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
deathknight="Göttlos"
level=120
race=orc
region=us
server=area_52
role=attack
professions=herbalism=100/mining=56
talents=3122133
spec=frost

head=,id=166696,bonus_id=5478/1502/4786/5402,context=3,azerite_powers=108/31
neck=,id=158075,bonus_id=4932/4933/4935/1518,context=11,azerite_level=24
shoulder=,id=159415,bonus_id=4819/1512/4786/5394,context=23,azerite_powers=504/31/85
back=,id=160644,bonus_id=4801/1462/4786,context=4
chest=,id=160636,bonus_id=4825/1462/4786/5392,context=4,azerite_powers=483/31/465
shirt=,id=6796
tabard=,id=118372,context=11
wrist=,id=159433,bonus_id=4779/1512/4786,context=23
hands=,id=163458,bonus_id=5126/1562/4786,context=6
waist=,id=165495,bonus_id=5124/1457/4786,context=3
legs=,id=162948,bonus_id=1527/4784,context=47
feet=,id=160640,bonus_id=4801/1467/4783,context=4
finger1=,id=158160,bonus_id=4803/1512/4785,context=25
finger2=,id=159463,bonus_id=4779/1512/4786,context=23
trinket1=,id=165661,bonus_id=4803/1512/4785,context=25
trinket2=,id=159077,bonus_id=4790,drop_level=120,context=11
main_hand=,id=155418,enchant_id=3368,bonus_id=4813/4816,drop_level=118,context=11
off_hand=,id=155369,enchant_id=3368,bonus_id=4811,drop_level=119,context=11

### Gear from Bags
#
# Greathelm of the Putrid Path (340)
# head=,id=159446,bonus_id=4819/1512/4786/5393,context=23,azerite_powers=
#
# Torgashell Helmet of the Peerless (266)
# head=,id=154809,bonus_id=4796/42/1689,drop_level=120
#
# Festerroot Helm of the Quickblade (266)
# head=,id=154819,bonus_id=4796/1680,drop_level=120
#
# Bleakweald Greathelm (325)
# head=,id=158025,bonus_id=1517/4785/5390,context=26,azerite_powers=
#
# Demonic Gladiator's Dreadplate Shoulders (225)
# shoulder=,id=148929,bonus_id=3573/1705/1533/3337,context=43
#
# Harbormaster Pauldrons (315)
# shoulder=,id=157996,bonus_id=1502/4785/5388/4775,context=27,azerite_powers=346/87/13
#
# Dinomancer's Cloak (320)
# back=,id=160530,context=14
#
# Pterroleather Cloak of the Harmonious (266)
# back=,id=160127,bonus_id=4796/4802/1712,drop_level=120
#
# Honorbound Centurion's Long Cloak (340)
# back=,id=163368,bonus_id=5124/1532/4786,context=3
#
# Bloody Warmother's Greatcloak (286)
# back=,id=155383,bonus_id=4790,drop_level=120,context=11
#
# Breastplate of Rezan's Bladeguard (315)
# chest=,id=157926,bonus_id=1502/4785/5386/4775,context=27,azerite_powers=198/44/13
#
# Deathguard's Breastplate (340)
# chest=,id=166574,bonus_id=5124/1457/4786/5392,context=3,azerite_powers=349/101
#
# Shadowshroud Vambraces (340)
# wrist=,id=160212,bonus_id=4779/41/1512/4786,context=23
#
# Geocrag Armplates (310)
# wrist=,id=164426,context=11
#
# Toravon's Whiteout Bindings (265)
# wrist=,id=132458,bonus_id=3459/3630
#
# Nazmani Warplate Bracelets (301)
# wrist=,id=155520,bonus_id=4790/4792,drop_level=119,context=11
#
# Honorbound Centurion's Gauntlets (350)
# hands=,id=163458,bonus_id=5125/1542/4786,context=28
#
# Dread Aspirant's Plate Gauntlets (325)
# hands=,id=162942,bonus_id=1517/4785,context=47
#
# Zalamar Gauntlets of the Feverflare (266)
# hands=,id=154826,bonus_id=4796/1700,drop_level=120
#
# Geocrag Grips (310)
# hands=,id=164420,context=11
#
# Crumbling Chain Belt (108)
# waist=,id=154801
#
# Geocrag Girdle (310)
# waist=,id=164421,context=11
#
# Unraveling Cloth Pants (108)
# legs=,id=154789
#
# Ravascale Legguards of the Quickblade (266)
# legs=,id=160142,bonus_id=4796/1682,drop_level=120
#
# Geocrag Legguards (310)
# legs=,id=164423,context=11
#
# Geocrag Stompers (310)
# feet=,id=164425,context=11
#
# Nazmani Warplate Stompers (290)
# feet=,id=159013,bonus_id=4793,drop_level=120,context=11
#
# Honorbound Centurion's Greaves (330)
# feet=,id=163460,bonus_id=5125/1522/4785,context=29
#
# Amberblaze Loop of the Fireflash (300)
# finger1=,id=153686,bonus_id=4927/3350,context=13
#
# Jin'Tiki's Signet (286)
# finger1=,id=155556,bonus_id=4790,drop_level=119,context=11
#
# Spare Stabilizer Band (298)
# finger1=,id=155382,bonus_id=4793/4794,drop_level=120,context=11
#
# Amberblaze Loop of the Peerless (310)
# finger1=,id=153686,bonus_id=4928/3348,context=13
#
# Dread Aspirant's Band (320)
# finger1=,id=162896,bonus_id=1512/4785,context=47
#
# Golden Empire Signet (325)
# finger1=,id=158152,bonus_id=4803/1517/4785,context=26
#
# Dinobone Charm (300)
# trinket1=,id=158155,bonus_id=4803/1492/4785,context=25
#
# Cracked Crawg Shackles (286)
# trinket1=,id=161182,bonus_id=4790,drop_level=118,context=11
#
# Gilded Loa Figurine (330)
# trinket1=,id=158153,bonus_id=4803/1522/4785,context=27
#
# Mac'Aree Focusing Amethyst (180)
# trinket1=,id=152783,bonus_id=3629/1472/3528
#
# Mining Pick (4)
# main_hand=,id=2901
#
# Bloodhunter Greatblade (286)
# main_hand=,id=159095,bonus_id=4790,drop_level=120,context=11
#
# Sinister Combatant's Deckpounder of the Harmonious (340)
# main_hand=,id=164650,enchant_id=3368,bonus_id=1711,context=13
#
# Warport Handaxe of the Aurora (266)
# main_hand=,id=159482,bonus_id=4796/41/1707,drop_level=120
#
# Blacksmith Hammer (1)
# main_hand=,id=5956
#
# Zem'lan Longsword of the Peerless (266)
# main_hand=,id=159601,bonus_id=4796/1683,drop_level=120
#
# Warport Handaxe of the Aurora (266)
# off_hand=,id=159482,bonus_id=4796/41/1707,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=2

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by kalfu151** [comment] 2018-12-20 00:44
Initializing: Actor 'Göttlos': Item 'inactive' Slot 'head': Cannot parse option from ',id=166696,bonus_id=5478/1502/4786/5402,context=3,azerite_powers=108/31': Unexpected parameter 'context'.

**Comment by Xanzara** [comment] 2018-12-20 01:14
Duplicate of #4613 

Your version of SimC is very out of date, updating to a new version will fix this issue.

**Closed as completed by Xanzara** 2018-12-20 01:14 UTC
