### ISSUE TITLE
GUI load failed because SimulationCraft.ini cannot load with CJK user name

### ISSUE THREAD

**Issue by EKE00372** [simulationcraft/simc#5586] opened 2020-11-30 20:37 UTC
### Describe the bug
GUI load failed because SimulationCraft.ini cannot load with CJK user name

### Expected behavior
When user name was named as CJK character, SimulationCraft.ini will load failed and cause SimGUI won't start/cannot load/crash, it probably treated as an unknow issue (in wiki question 3 and 7 and maybe #5466). Also, this issue feedback from a chinese language user, so i'm not sure it's only happened on chinese Character only, or CJK, or even non-english, but i think CJK is the most likely happened.

Source feedback [here (chinese forum)](https://bbs.nga.cn/read.php?tid=24382103)

### To Reproduce
Create a new user account in PC and name as CJK character.
C:\Users\ **UserName** \AppData\Roaming\SimulationCraft

### Additional information
* SimulationCraft Version (required)
Since version 810
below are able to open.

**Comment by suujonH** [comment] 2020-12-01 07:38
Same problem.
This issue inspired me, so I used [Locale-Emulator](https://github.com/xupefei/Locale-Emulator), set the location to **en-us**, and then successfully started.

**Comment by scamille** [comment] 2020-12-01 08:10
Thanks a lot for the report. That might indeed be the cause of some of the other issues reporting that they can not start the GUI.

How exactly did you determine that the failure is while loading Simulationcraft.ini?

**Comment by EKE00372** [comment] 2020-12-01 13:53
First, he tried compare another PC's file which can run simc normally, and copy it's Simulationcraft.ini to his pc but still crash. and then he started try old version, notice this problem happened since 810 and work fine with 801, but when he edit his ini file and start with upper version, Simulationcraft.ini in AppData didn't have any change, so finally found issue.

I don't have this issue......my user name is english. but as my opinion, CJK support is also a usually problem on program, not only simc.

for example it even happened on WOW client, 6 years ago, WOD beta can crash by this issue, "do not use CJK char on folder path which your client installed" is still in my beta guide until now, although it never happened in later beta again.

**Comment by suujonH** [comment] 2020-12-01 18:29
#5595

**Comment by serrufs** [comment] 2020-12-05 03:51
> Same problem.
> This issue inspired me, so I used [Locale-Emulator](https://github.com/xupefei/Locale-Emulator), set the location to **en-us**, and then successfully started.

Did you download SimulationCraft.exe for Local-Emulator? This Locale-Emulator does not work for SimulationCraft.exe
![Безымянный_cr](https://user-images.githubusercontent.com/15975674/101233055-e2b6fe00-36c6-11eb-844c-b4685feec0fc.png)

possibly this is my problem in Russian
c:\Users\ **Администратор** \AppData\Roaming\SimulationCraft\

**Comment by suujonH** [comment] 2020-12-06 20:22
> > Same problem.
> > This issue inspired me, so I used [Locale-Emulator](https://github.com/xupefei/Locale-Emulator), set the location to **en-us**, and then successfully started.
> 
> Did you download SimulationCraft.exe for Local-Emulator? This Locale-Emulator does not work for SimulationCraft.exe
> ![Безымянный_cr](https://user-images.githubusercontent.com/15975674/101233055-e2b6fe00-36c6-11eb-844c-b4685feec0fc.png)
> 
> possibly this is my problem in Russian
> c:\Users\ **Администратор** \AppData\Roaming\SimulationCraft\

Yes. This is the Chinese environment, It's work.
**Way1:** Use Locale-Emulator and change the location to en-us.
            Use this config to startup the application.
Like this : ![](https://img.nga.178.com/attachments/mon_202012/01/a7Q5-5skdKqT1kS92-8q.jpg)

**Way2:** Use [Beta: Use Unicode UTF-8 for worldwide language support] in control panel.

**Way3:**#5595  fix this issue in my environment(I think is the same issue).
Please try again tomorrow with the next nightly build.

**Comment by serrufs** [comment] 2020-12-07 02:30
> **Way1:** Use Locale-Emulator and change the location to en-us.
you did not understand
![101233055-e2b6fe00-36c6-11eb-844c-b4685feec0fc](https://user-images.githubusercontent.com/15975674/101302608-191e8580-384d-11eb-94fd-9faa6ae5a77d.png)

Locale-Emulator is not listed in the menu for SimulationCraft.exe ...

> Way2: Use [Beta: Use Unicode UTF-8 for worldwide language support] in control panel.

it works for me if I change the language to English (USA), but I have to reboot my PC every time I want to run SimulationCraft.exe
Otherwise, the rest of the programs will also have English (USA) - and this is inconvenient

Thanks anyway - it's better than nothing

**Comment by serrufs** [comment] 2020-12-07 19:47
> **Way3:**#5595 fix this issue in my environment(I think is the same issue).
> Please try again tomorrow with the next nightly build.

thanks, everything works fine
in the new version simc-902-01-win64-bad3400 - the gap is solved!

**Comment by scamille** [comment] 2020-12-08 20:55
Resolved by #5595

**Closed as completed by scamille** 2020-12-08 20:55 UTC
