### ISSUE TITLE
Volitatile soul fragment relic from argus bugs

### ISSUE THREAD

**Issue by EZman1** [simulationcraft/simc#4232] opened 2018-01-10 10:46 UTC
When I want to sim my char with the relic argus drops it ignores that relic.
gem_id: 155852
relic_id: 3610:1482:3528

#### Simulationcraft Version
730-02

#### simc_gui.simc file or contents
https://pastebin.com/DqR144KS

#### Reproduction Steps:
I got the profile from the ingame addon

**Comment by vituscze** [comment] 2018-01-10 10:55
Duplicate of #4228

**Closed as completed by vituscze** 2018-01-10 10:55 UTC
