### ISSUE TITLE
got an error message after new patch while i tried to simulate

### ISSUE THREAD

**Issue by astrixatigma** [simulationcraft/simc#4619] opened 2018-12-12 13:54 UTC
### Describe the bug
SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Oastrix': Item 'inactive' Slot 'head': Cannot parse option from ',id=157961,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=196/21/44/13': Unexpected parameter 'context'.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

### Expected behavior
when i tried to simulate got that error message.

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)
Version 801-01 
* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by AlexanderKenny** [comment] 2018-12-12 14:18
Duplicate of #4613 update your simc version

**Comment by astrixatigma** [comment] 2018-12-12 14:23
i have the latest update of simc  .. theres no more update.

**Comment by AlexanderKenny** [comment] 2018-12-12 14:25
Program not the add-on. That field has been supported for four months: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed** 2018-12-12 14:29 UTC
