### ISSUE TITLE
invalid crucible format

### ISSUE THREAD

**Issue by solidus0079** [simulationcraft/simc#4001] opened 2017-09-14 14:36 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Jarleon haste trink invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
druid="Jarleon haste trink"
level=110
race=worgen
region=us
server=emerald_dream
role=spell
professions=herbalism=800/engineering=800
talents=3221232
spec=balance
artifact=59:0:0:0:0:1034:4:1035:4:1036:4:1037:4:1038:4:1039:4:1040:4:1041:4:1042:4:1043:1:1044:1:1045:1:1046:1:1047:1:1048:1:1049:1:1294:1:1364:1:1501:4:1502:1:1503:1:1504:12:1632:1
crucible=1739:1781/1739:1782/1739

head=,id=147136,bonus_id=3562/41/1497/3528
neck=,id=147013,enchant_id=5890,bonus_id=3562/1502/3336
shoulder=,id=145442,enchant_id=5442,bonus_id=3567/1717/1557/3337
back=,id=147134,enchant_id=5436,bonus_id=3562/1497/3528
chest=,id=147133,bonus_id=3562/1497/3528
shirt=,id=148
tabard=,id=46874
wrist=,id=137092,bonus_id=3459/3570
hands=,id=147969,enchant_id=5444,bonus_id=1716/1562/3337
waist=,id=147347,gem_id=130222,bonus_id=3561/1808/1512/3337
legs=,id=147137,bonus_id=3561/1507/3337
feet=,id=147029,bonus_id=3562/41/1497/3528
finger1=,id=147195,enchant_id=5429,bonus_id=3561/1492/3528
finger2=,id=137039,enchant_id=5326,gem_id=130222,bonus_id=3529/3459/3570
trinket1=,id=147017,bonus_id=3562/1502/3336
trinket2=,id=152783,bonus_id=3573/1517/3337
main_hand=,id=128858,gem_id=147076/137327/142305,bonus_id=722,relic_id=3562:1517:3337/3418:1587:3337/3534:1532:3337

### Gear from Bags
#
# Prydaz, Xavaric's Magnum Opus (970)
# neck=,id=132444,enchant_id=5890,gem_id=130222,bonus_id=1811/3570
#
# Stormheart Mantle (915)
# shoulder=,id=147138,enchant_id=5931,bonus_id=3562/1497/3528
#
# Lady and the Child (970)
# shoulder=,id=144295,enchant_id=5442,bonus_id=1811/3570
#
# Radiant Moonlight (970)
# back=,id=151800,enchant_id=5436,bonus_id=1811/3570
#
# Stormheart Drape (915)
# back=,id=147134,enchant_id=5435,bonus_id=3562/1497/3528
#
# Spirebreaker Harness (915)
# chest=,id=147027,bonus_id=3562/1497/3528
#
# Ekowraith, Creator of Worlds (970)
# chest=,id=137015,bonus_id=3459/3570
#
# Bracers of Rippling Darkness (920)
# wrist=,id=147042,bonus_id=3561/1502/3337
#
# Luffa Wrappings (970)
# wrist=,id=137056,bonus_id=1811/3570
#
# Stormheart Gloves (920)
# hands=,id=147135,enchant_id=5444,bonus_id=3562/42/1502/3336
#
# Cinidaria, the Symbiote (970)
# waist=,id=133976,bonus_id=1811/3570
#
# Yathae's Thumb Ring (925)
# finger1=,id=147021,enchant_id=5429,gem_id=130222,bonus_id=3562/1808/1507/3336
#
# Soul of the Archdruid (970)
# finger1=,id=151636,enchant_id=5429,gem_id=130222,bonus_id=3459/3570
#
# Ring of the Scoured Clan (910)
# finger1=,id=140897,enchant_id=5429,bonus_id=3517/1507/3337
#
# Thunder Totem Band of the Fireflash (680)
# finger1=,id=121082,bonus_id=1812/1757,drop_level=110
#
# Band of Rescinded Truths (915)
# finger1=,id=147194,enchant_id=5429,bonus_id=3562/1497/3528
#
# Umbral Moonglaives (915)
# trinket1=,id=147012,bonus_id=3562/1497/3528
#
# Horn of Valor (920)
# trinket1=,id=133642,bonus_id=3573/1572/3336
#
# Charm of the Rising Tide (915)
# trinket1=,id=147002,bonus_id=3562/1497/3528
#
# Majordomo's Dinner Bell (880)
# trinket1=,id=142168,bonus_id=3573/1497/3528
#
# Terror From Below (915)
# trinket1=,id=147016,bonus_id=3562/42/1497/3528
#
# Animated Exoskeleton (870)
# trinket1=,id=140789,bonus_id=3443/1467/3528
#
# Stormpike Insignia Rank 5 (60)
# trinket1=,id=17903
#
# Archimonde's Hatred Reborn (970)
# trinket1=,id=144249,bonus_id=3529/3459/3570
#
# Ferocious Gladiator's Insignia of Conquest (900)
# trinket1=,id=145576,bonus_id=3567/1532/3337
#
# Feverish Carapace (920)
# trinket1=,id=147022,gem_id=130222,bonus_id=3562/1808/1502/3336
#
# The Devilsaur's Bite (905)
# trinket1=,id=140026,bonus_id=1825/1557/3337
#
# Spectral Thurible (920)
# trinket1=,id=147018,bonus_id=3562/1502/3336
#
# Chrono Shard (880)
# trinket1=,id=137419,bonus_id=3414/1532/3528
#
# Corrupted Starlight (915)
# trinket1=,id=137301,bonus_id=3573/1567/3336
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-14 15:00
Duplicate of #4000 

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-14 15:00 UTC
Labels: duplicate
