### ISSUE TITLE
Crucible relic problem, cant sim

### ISSUE THREAD

**Issue by Rafaker** [simulationcraft/simc#4031] opened 2017-09-17 23:07 UTC
version 730-02, used simc addon to copy my character settings.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Rafaker invalid crucible rank '1780/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
shaman="Rafaker"
level=110
race=pandaren
region=us
server=ragnaros
role=attack
professions=herbalism=800/mining=800
talents=3212111
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:4:906:4:907:4:908:4:909:4:910:4:911:4:912:4:913:4:930:1:1351:1:1388:1:1593:4:1594:1:1595:1:1596:15:1687:1
crucible=1739:1780/1739:1771/1739:1780

head=,id=147178,bonus_id=3562/1497/3528
neck=,id=134488,enchant_id=5439,bonus_id=3536/1582/3337
shoulder=,id=147054,enchant_id=5931,gem_id=151583,bonus_id=3562/1808/1497/3528
back=,id=147176,enchant_id=5435,bonus_id=3562/1497/3528
chest=,id=147175,bonus_id=3562/1507/3336
shirt=,id=151116
tabard=,id=152399
wrist=,id=133626,bonus_id=3536/43/1582/3337
hands=,id=151819,enchant_id=5444,bonus_id=1811/3570
waist=,id=147056,bonus_id=3562/1497/3528
legs=,id=147179,bonus_id=3562/1497/3528
feet=,id=147045,bonus_id=3562/1507/3336
finger1=,id=134539,enchant_id=5428,bonus_id=3536/1582/3337
finger2=,id=137050,enchant_id=5428,gem_id=130247,bonus_id=3459/3570
trinket1=,id=147010,bonus_id=3562/1497/3528
trinket2=,id=151190,gem_id=151583,bonus_id=3561/1808/1497/3336
main_hand=,id=128819,gem_id=142183/142177/147115,bonus_id=745,relic_id=3418:1552:3337/3535:1542:3337/3562:1497:3528
off_hand=,id=128873

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-17 23:07
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-17 23:07 UTC
Labels: duplicate
