### ISSUE TITLE
Simulation Run Time Error

### ISSUE THREAD

**Issue by Vizeryz** [simulationcraft/simc#4648] opened 2018-12-18 10:09 UTC
Trying to run Simulation and I am receiving this error after equipping a new head slot.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Vizeryz': Item 'inactive' Slot 'head': Cannot parse option from ',id=163380,bonus_id=5125/1547/4786/5396/4775,context=28,azerite_powers=159/30/83/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.05
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,ap,crit,haste,mastery,vers,wdps,wohdps
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
# SimC Addon 1.10.8
demonhunter="Vizeryz"
level=120
race=night_elf
region=us
server=lightbringer
role=attack

talents=1311211
spec=havoc

head=,id=163380,bonus_id=5125/1547/4786/5396/4775,context=28,azerite_powers=159/30/83/13
neck=,id=158075,bonus_id=4936/4929/4930/1532,context=11,azerite_level=31
shoulder=,id=160620,bonus_id=4825/1462/4786/4775,context=4,azerite_powers=483/30/44/13
back=,id=163347,bonus_id=5125/1562/4786,context=11
chest=,id=163251,bonus_id=5126/1562/4786/4775,context=6,azerite_powers=126/31/15/13
wrist=,id=163278,gem_id=154127,bonus_id=5124/4802/1537/4783,context=3
hands=,id=163256,bonus_id=5125/1552/4786,context=29
waist=,id=165446,bonus_id=5126/41/1502/4786,context=6
legs=,id=157978,bonus_id=4803/1557/4786,context=28
feet=,id=158039,bonus_id=4803/1557/4786,context=28
finger1=,id=161446,bonus_id=4803/1522/4785,context=27
finger2=,id=161359,enchant_id=5943,bonus_id=4798/1477/4786,context=3
trinket1=,id=158153,bonus_id=4803/1537/4784,context=27
trinket2=,id=159623,bonus_id=4779/1512/4786,context=23
main_hand=,id=163961,enchant_id=5963,bonus_id=1472/4786,context=54
off_hand=,id=164690,enchant_id=5962,bonus_id=1680,context=13

### Gear from Bags
#
# Inherited Cape of the Black Baron (160)
# back=,id=122261,bonus_id=3592
#
# Foxhollow Robes of the Harmonious (266)
# chest=,id=159187,bonus_id=4796/1714,drop_level=120
#
# Tunic of the Pitiless Monstrosity (182)
# chest=,id=134438,bonus_id=1727/1492/3528,context=23
#
# 7th Legionnaire's Boots (365)
# feet=,id=163383,bonus_id=5125/1557/4783,context=29
#
# Wintersail Saber (330)
# main_hand=,id=158103,bonus_id=4803/1522/4781,context=26
#
# Wintersail Saber (330)
# off_hand=,id=158103,bonus_id=4803/1522/4781,context=26

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=2

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-18 11:42
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-18 11:42 UTC
