### ISSUE TITLE
Simulation Setup Error

### ISSUE THREAD

**Issue by Grimmjaw1122** [simulationcraft/simc#4051] opened 2017-09-22 14:01 UTC
# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'crucible' with value '0/0/0'

## All options used for simulation:
``` ini
### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
shaman="Záltana"
level=110
race=troll
region=us
server=bleeding_hollow
role=attack
professions=alchemy=800/herbalism=333
talents=3212133
spec=enhancement
artifact=41:0:0:0:0:899:1:900:1:901:1:902:1:903:1:904:1:905:4:906:4:907:4:908:4:909:4:910:4:911:4:912:4:913:4:930:1:1351:1:1388:1:1593:4:1594:1:1595:1:1596:9:1687:1
crucible=0/0/0

head=,id=147178,bonus_id=3561/1487/3336
neck=,id=147014,enchant_id=5439,bonus_id=3561/1808/1482/3528
shoulder=,id=147180,bonus_id=3561/1487/3336
back=,id=146984,enchant_id=5435,bonus_id=3562/1497/3528
chest=,id=147175,bonus_id=3561/1482/3528
wrist=,id=128907,bonus_id=689/1714/3408/600/679
hands=,id=147177,bonus_id=3562/1502/3336
waist=,id=151326,bonus_id=3416/1577/3337
legs=,id=132466,bonus_id=3459/3570
feet=,id=134477,bonus_id=3573/1562/3528
finger1=,id=137050,enchant_id=5429,bonus_id=1811/3570
finger2=,id=147194,enchant_id=5429,bonus_id=3561/1808/1482/3528
trinket1=,id=151190,bonus_id=3561/1507/3337
trinket2=,id=152782,bonus_id=40/3573/1512/3336
main_hand=,id=128819,bonus_id=745,relic_id=3561:1482:3528/3561:1502:3337/3562:1497:3528
off_hand=,id=128873

### Gear from Bags
#


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-22 16:59
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-22 16:59 UTC
Labels: duplicate
