### ISSUE TITLE
simulation setup error

### ISSUE THREAD

**Issue by theoriginalme** [simulationcraft/simc#4043] opened 2017-09-20 19:31 UTC
Been running it just fine go today to try to simulate and i get this error, nothing has changed exept gear character is using

# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'crucible' with value '0/1739/0'

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,spi,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
druid="Dulwas"
level=110
race=worgen
region=us
server=rexxar
role=spell
professions=herbalism=653/mining=656
talents=3231233
spec=balance
artifact=59:0:0:0:0:1034:4:1035:4:1036:4:1037:4:1038:4:1039:4:1040:4:1041:4:1042:4:1043:1:1044:1:1045:1:1046:1:1047:1:1048:1:1049:1:1294:1:1364:1:1501:4:1502:1:1503:1:1504:7:1632:1
crucible=0/1739/0

head=,id=134152,bonus_id=3411/1562/3336
neck=,id=133633,bonus_id=3412/1547/3528
shoulder=,id=144295,bonus_id=3459/3570
back=,id=142170,bonus_id=3414/1517/3528
chest=,id=142139,bonus_id=3573/1808/1527/3528
wrist=,id=133621,bonus_id=3412/40/1567/3337
hands=,id=134443,bonus_id=3414/1582/3337
waist=,id=142196,bonus_id=3414/1517/3528
legs=,id=144484,bonus_id=3573/1562/3528
feet=,id=142140,bonus_id=3573/1527/3528
finger1=,id=147021,enchant_id=5426,bonus_id=3573/40/1497/3336
finger2=,id=148071,bonus_id=3579/1522/3528
trinket1=,id=136716,bonus_id=3410/1542/3528
trinket2=,id=144259,bonus_id=1811/3570
main_hand=,id=128858,gem_id=151006/151288/152690,bonus_id=722,relic_id=3396:3169:3528/3412:1567:3337

### Gear from Bags
#
# Tranquil Bough Hood (885)
# head=,id=139070,bonus_id=3394/1547/3336
#
# Cape of Mindless Fury (885)
# back=,id=147193,enchant_id=5433,gem_id=130218,bonus_id=3564/1808/1467/3528
#
# Rivermane Gloves (920)
# hands=,id=139107,bonus_id=1825/1582/3337
#
# Cinch of Sizzling Flesh (890)
# waist=,id=147039,bonus_id=3564/1472/3336
#
# Steelgazer Hide Boots (885)
# feet=,id=134149,bonus_id=3394/1547/3336
#
# Rivermane Sandals (895)
# feet=,id=139105,bonus_id=3411/1557/3528
#
# Ring of Twisted Webbing (870)
# finger1=,id=134540,bonus_id=1727/1522/3336
#
# Mining Pick (4)
# main_hand=,id=2901
#
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by seriallos** [comment] 2017-09-20 19:34
Duplicate of #4000

**Closed as completed by seriallos** 2017-09-20 19:34 UTC
Labels: duplicate
