### ISSUE TITLE
Unable to open simcraft

### ISSUE THREAD

**Issue by Garrah** [simulationcraft/simc#3177] opened 2016-11-18 10:54 UTC
When i try to launch the newest version of Simcraft, after launching SimulationCraft.exe it reads "we reset your configuration settings due to major Gui changes" i press ok, then it disappears and nothing shows up. I tried to then run an older version and only 1 seemed to kinda work. the Gui would open i could sim my character but the html page in the results was blacked out, i had to use the text tab to read the results. 
This was working fine on another computer, so not sure if i'm missing a prerequisite or something.
Any insight would be great.   
          - Garrah

**Comment by domstor** [comment] 2016-11-18 15:19
Hi all,

got the exact same problem as the OP.

Tested on win7 SP1: 
SimcSetup-710-02-Win32.exe
SimcSetup-710-03-Win64.exe
simc-710-03-win64-aa39705.7z
simc-710-03-alph-win64-469898a.7z

"we reset your configuration..." but after 1 second "Simulationcraft hast stopped working"
Tested the same version ealier on an other device, also win7 sp1 but without any problems.
Like OP said, any prerequisites that we may missed?

Thanks in advance!
Dom

**Comment by Garrah** [comment] 2016-11-23 18:52
Bump, Still not solved.

**Comment by Talibone** [comment] 2016-11-24 19:14
Hello , here

Same dialog and then simc dont work . Dont have html page

**Comment by Collisionc** [comment] 2016-11-27 05:22
What was the last version to work? 710-01 ?

**Comment by Talibone** [comment] 2016-11-27 08:35
7.0.3  release 2

2016-11-27 6:22 GMT+01:00 Alex <notifications@github.com>:

**Comment by Garrah** [comment] 2016-11-27 16:05
Only version iv had launch and work besides the html/welcome page was simc-703-03-win32 (Also running on a windows 7 64 bit OS) i couldn't get the 64 bit version of that to work also tried to download and test the most recent version simc-710-02-win32 and it wont even launch.

**Comment by Collisionc** [comment] 2016-11-27 23:32
Try this:

Create an environment variable named QT_OPENGL
Instructions for making envrionment variables: https://kb.wisc.edu/cae/page.php?id=24500

Set QT_OPENGL to one of the following - Try software first, then desktop, then angle
software
desktop
angle

Let me know if any of those 3 work.

**Comment by Garrah** [comment] 2016-11-27 23:52
Alright so an update on that, It will now launch but the same html bug accrued, ill supply some screenshots.
Welcome page : https://i.imgur.com/2Pvo6I4.png
After a test sim : https://i.imgur.com/u2s8Fo9.png

**Comment by Collisionc** [comment] 2016-11-27 23:59
Which environment variable did you use with that result?  If it was software, try desktop.

**Comment by Talibone** [comment] 2016-11-28 00:04
Thx Works perfectly now for me with software value .

2016-11-28 0:59 GMT+01:00 Alex <notifications@github.com>:

**Comment by Garrah** [comment] 2016-11-28 00:08
I tried all 3 software and angle did the same thing desktop program just crashed.

**Comment by Garrah** [comment] 2016-11-28 00:08
with desktop*

**Comment by Collisionc** [comment] 2016-11-28 00:10
What video card are you currently using, and are you using a laptop? @Garrah

**Comment by Garrah** [comment] 2016-11-28 00:11
750 ti gtx, and desktop.

**Comment by Collisionc** [comment] 2016-11-28 00:13
Kind of a long shot, but reinstall your videocard drivers

http://www.geforce.com/drivers/results/111034

Make sure to click "Clean install" when doing this. Then set the environment variable to angle, then desktop if that doesn't work.

**Comment by Garrah** [comment] 2016-11-28 00:55
Sorry for the wait, Reinstalled the vc drivers with clean install and tried both software and angle in the environment variable, "desktop" still dosen't work. But the same problems with the welcome page and html results page still persist.

**Comment by Collisionc** [comment] 2016-11-28 01:17
Ok. Let's try different QT versions. (It's what we use to make the GUI because everyone here hates coding guis.)

http://downloads.simulationcraft.org/simc-710-03-win64-eff2d2bQT562.7z

http://downloads.simulationcraft.org/simc-710-03-win64-eff2d2b.7z

Same version, different QT versions. We're using QT 5.6 by default, 5.6.2 in the top download, 5.8 in the bottom. Your antivirus may bitch because 5.8 is a beta build, but just tell it to ignore it.

**Comment by Garrah** [comment] 2016-11-28 01:18
Alright ill give it a shot and let ya know

**Comment by Garrah** [comment] 2016-11-28 01:25
Alright Unfortunately the html pages are still black. If you would like i could turn on a stream so you can see in real time.

**Comment by Collisionc** [comment] 2016-11-28 01:42
That wouldn't help much, this is very likely the same issue that I ran into with https://github.com/simulationcraft/simc/issues/2864 - 

Since you had success with a 32 bit version once , try the QT_OPENGL stuff with this download: 
http://downloads.simulationcraft.org/simc-710-03-win32-eff2d2b.7z

**Comment by Garrah** [comment] 2016-11-28 01:45
The html issue has never worked on this computer. But atleast thus far fixed the crashing. Testing that one now.

**Comment by Garrah** [comment] 2016-11-28 01:47
and no cigar.

**Comment by Collisionc** [comment] 2016-11-28 02:01
http://downloads.simulationcraft.org/simc-710-03-win64-eff2d2b.7z

Disabled the battle.net tab from loading the site in that build.

**Comment by Garrah** [comment] 2016-11-28 02:25
No change.

**Comment by Collisionc** [comment] 2016-11-28 03:21
Ugh. If you have no problems with windows 10, upgrading to 10 would (almost) definitely fix it.  This is a duplicate of the issue I linked above where we could never resolve it on windows 7. :\ 

Basically, QT/chromium just have issues with certain windows 7 setups.  

You can still get the free windows 10 upgrade by downloading the media creation tool, creating the iso, mounting the iso inside windows 7 using http://collision.heroicstrike.org/ISO-Mounter.exe -- and then opening up the magnifier and running setup.exe from the mounted image.

**Comment by Garrah** [comment] 2016-11-28 04:55
no interest in windows 10, but thanks for taking the time to look into it.

**Comment by Collisionc** [comment] 2016-11-29 15:55
Sorry I can't do much for ya here, but if you don't mind learning to use the CLI (simc.exe instead of simulationcraft.exe) you can still use the program. : )

https://github.com/simulationcraft/simc/wiki/StartersGuide - Scroll down to command-line client.

**Closed** 2016-11-30 01:11 UTC
