### ISSUE TITLE
cannot parse expression error

### ISSUE THREAD

**Issue by doutrnz** [simulationcraft/simc#4792] opened 2019-04-17 16:18 UTC
I downloaded the latest release of SimulationCraft, I downloaded the latest add-on version of the mod and still getting this error. 4/17/19.

SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Dysonshock': Action 'ray_of_frost': Cannot parse expression from '!action.frozen_orb.in_flight&ground_aoe.frozen_orb.remains=0': No expression found.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Dysonshock': Action 'ray_of_frost': Cannot parse expression from '!action.frozen_orb.in_flight&ground_aoe.frozen_orb.remains=0': No expression found.

## All options used for simulation:
``` ini
### SimulationCraft 815-01 for World of Warcraft 8.1.5 Live (wow build 29683) ###
### Using QT 5.12.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.11.1
# Requires SimulationCraft 815-01 or newer

mage="Dysonshock"
level=26
race=draenei
region=us
server=stormrage
role=spell
professions=herbalism=108/skinning=118
talents=2000000
spec=frost

shoulder=,id=60941,bonus_id=3644/5646,drop_level=24,context=11
back=,id=60685,bonus_id=3641,drop_level=25,context=11
chest=,id=60899,bonus_id=3644,drop_level=24,context=11
shirt=,id=23473
wrist=,id=60683,bonus_id=3641/5691,drop_level=24,context=11
hands=,id=26009,bonus_id=3635,drop_level=16,context=11
waist=,id=6570,bonus_id=1709/3831,drop_level=22,context=28
legs=,id=14119,bonus_id=1678/3829,drop_level=15,context=26
feet=,id=58915,bonus_id=3637/5739,drop_level=21,context=11
finger1=,id=60895,bonus_id=3644,drop_level=23,context=11
finger2=,id=60910,bonus_id=3644,drop_level=24,context=11
main_hand=,id=60914,bonus_id=3644/5645,drop_level=24,context=11
off_hand=,id=27398,bonus_id=3635,drop_level=15,context=11

### Gear from Bags
#
# Staats' Fishing Pole (10)
# main_hand=,id=46337,context=11

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2019-04-17 17:58
Duplicate of #4514

Check comments on that issue for a workaround; there's currently no good solution to this.

**Closed as completed by vituscze** 2019-04-17 17:58 UTC
