### ISSUE TITLE
Some itens are listed as 'inactive'

### ISSUE THREAD

**Issue by Kugalblitz** [simulationcraft/simc#5451] opened 2020-10-24 00:58 UTC
# SimulationCraft encountered an error!
# SimulationCraft 902-01 for World of Warcraft 9.0.2.36294 shadowlands-BETA (git build shadowlands f1ec3b4)
* Category: Simulation runtime error
* Error: Initializing: Actor *******: Item 'inactive' Slot 'shoulders': Error retrieving item from BCP API: Item JSON data has parse error: The document is empty.

## All options used for simulation:
``` ini
### SimulationCraft 902-01 for World of Warcraft 9.0.2.36294 shadowlands-BETA (wow build 36294, git build shadowlands f1ec3b4)  ###
### Using QT 5.12.9 with WebEngine ###

### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead/shadowlandshead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=6
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers
scale_over=Dps
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Innkalle - Retribution - 2020-10-23 21:53 - US/Thrall
# SimC Addon 9.0.1-02
# Requires SimulationCraft 901-01 or newer

paladin="******"
level=19
race=zandalari_troll
zandalari_loa=paku
region=us
server=thrall
role=attack
professions=engineering=1/
talents=1000000
spec=retribution

head=,id=122263,bonus_id=5805
neck=,id=130275,bonus_id=4811,drop_level=19
shoulder=,id=27844,bonus_id=6710,drop_level=19
back=,id=129090,bonus_id=6691/6703,drop_level=19
chest=,id=130012,enchant_id=2661
shirt=,id=6096
tabard=,id=165001
wrist=,id=121603,bonus_id=4793/4795,drop_level=19
hands=,id=51987,bonus_id=4244/1678,drop_level=19
waist=,id=140622
legs=,id=122264,bonus_id=5805
feet=,id=130013,bonus_id=4811,drop_level=19
finger1=,id=143902,enchant_id=5428,bonus_id=6423,drop_level=19
finger2=,id=121722,bonus_id=3631/6700,drop_level=19
trinket1=,id=138775,bonus_id=6691,drop_level=19
trinket2=,id=131799,bonus_id=6691,drop_level=19
main_hand=,id=120978,enchant_id=1900,gem_id=133029/132319,gem_bonus_id=4790:4791:1452:1809/4790:4792:1454:1809,bonus_id=1483

### Gear from Bags

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

The item i'm having problem with is the gloves and shoulders:
27844 and 51987 at level 19

**Comment by scamille** [comment] 2020-10-25 10:15
Duplicate of #5278 , but thanks for creating this issue and giving some more data on problematic items.
For now please try to simulate without those gear pieces, and we can hopefully have it resolved at some point.

**Comment by navv1234** [comment] 2020-10-30 10:46
We have extended the simulationcraft local item database to contain every single armor and weapon in the client data files. This issue should be resolved now.

**Closed as completed** 2020-11-01 09:06 UTC
Labels: Item, BCP Api
