### ISSUE TITLE
Simulation error

### ISSUE THREAD

**Issue by JediMaDMZ** [simulationcraft/simc#4040] opened 2017-09-20 10:29 UTC
Version 7.30-1

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Jedima invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=LightMovement
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
paladin="Jedima"
level=110
race=human
region=eu
server=eonar
role=attack
professions=herbalism=800/engineering=729
talents=2232222
spec=retribution
artifact=2:0:0:0:0:40:1:41:4:42:4:43:4:44:4:47:4:49:1:50:4:51:4:52:4:53:4:54:1:350:1:351:1:352:1:353:1:1118:1:1275:1:1561:4:1562:1:1563:1:1564:13:1647:1
crucible=1739:1778/1739:1779/1739

head=,id=147063,gem_id=130220,bonus_id=3562/1808/1497/3528
neck=,id=147013,enchant_id=5439,bonus_id=3562/1497/3528
shoulder=,id=147162,enchant_id=5442,bonus_id=3562/1497/3528
back=,id=147158,enchant_id=5434,bonus_id=3562/1497/3528
chest=,id=147067,gem_id=130220,bonus_id=3562/1808/1507/3336
shirt=,id=151116
tabard=,id=52252
wrist=,id=147073,bonus_id=3562/41/1497/3528
hands=,id=147159,gem_id=130220,bonus_id=3562/1808/1497/3528
waist=,id=137086,bonus_id=3459/3570
legs=,id=147161,bonus_id=3562/1497/3528
feet=,id=139241,bonus_id=3510/43/1567/3337
finger1=,id=137048,enchant_id=5428,gem_id=130246,bonus_id=1811/3570
finger2=,id=147195,enchant_id=5428,bonus_id=3561/1492/3528
trinket1=,id=147011,bonus_id=3562/1497/3528
trinket2=,id=147009,gem_id=130220,bonus_id=3562/1808/1497/3528
main_hand=,id=120978,gem_id=147099/147088/137346,bonus_id=737,relic_id=3562:1507:3528/3562:1497:3528/3418:1587:3337

### Gear from Bags
#
# Praetorium Guard's Pauldrons of the Feverflare (910)
# shoulder=,id=152750,bonus_id=1702/1808/3573/1502/3528
#
# Cloak of Coordination (60)
# back=,id=65360
#
# Violet Seal of the Grand Magus (875)
# finger1=,id=142469
#
# Time-Lost Artifact (496)
# trinket1=,id=103678
#
# Eye of Command (905)
# trinket1=,id=142167,bonus_id=3418/1517/3337
#
# Umbral Moonglaives (920)
# trinket1=,id=147012,gem_id=130220,bonus_id=3562/1808/42/1502/3336
#
# Specter of Betrayal (935)
# trinket1=,id=151190,bonus_id=3562/1517/3336
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-20 11:05
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-20 11:05 UTC
Labels: duplicate
