### ISSUE TITLE
Havoc using outdated Demonic mechanics for Eye Beam conditional

### ISSUE THREAD

**Issue by kaedys** [simulationcraft/simc#4621] opened 2018-12-13 03:22 UTC
### Describe the bug
The current Havoc default APL has two specific lines that still assume the old pre-8.0 behavior where Eye Beam with Demonic was only capable of extending Meta once after the cooldown version was cast.  This mechanic was removed with 8.0 (due to the removal of Feast on the Souls and the deprecation of Raddons), and SimC [was updated to reflect this](https://github.com/simulationcraft/simc/commit/357a6ba4d87a020feaa2e3db5289e9ca058a73b3), but the APL was never changed to account for the difference in mechanics.  The APL lines in question are:

[L48](https://github.com/simulationcraft/simc/blob/bfa-dev/profiles/Tier22/T22_Demon_Hunter_Havoc.simc#L48): `actions.cooldown+=/metamorphosis,if=talent.demonic.enabled&buff.metamorphosis.up`
[L59](https://github.com/simulationcraft/simc/blob/bfa-dev/profiles/Tier22/T22_Demon_Hunter_Havoc.simc#L48): `actions.demonic+=/eye_beam,if=!buff.metamorphosis.extended_by_demonic&(raid_event.adds.up|raid_event.adds.in>25)`

### Expected behavior
The APL should be unconditionally casting Eye Beam regardless of whether Meta has been extended or not, and the APL should not be waiting for  Mta to be up via Demonic to cast the cooldown version.

From running the sims with and without those conditions, it looks like SimC is currently coded to always return that Meta has not been extended by Eye Beam, so the DPS impact of fixing the APL should be minimal, but from a cleanliness and correctness standpoint, it should be corrected.

### To Reproduce
N/A, APL issue, not runtime issue

### Additional information
* SimulationCraft Version (required)
Current HEAD of `bfa-dev`

**Comment by EvanMichaels** [comment] 2018-12-13 06:05
This actually doesn't matter because the extended_by_demonic condition no longer returns true as it was internally disabled. We left support for it just in case it makes a return, as it was unclear if this was a bug or not initially during BfA, as this change was never announced or confirmed as intentional.

Probably will remove it since it seems unlikely to change now, but it has zero DPS impact right now. The cooldown condition might have an impact though, so I'll take a look at that.

**Comment by kaedys** [comment] 2018-12-19 02:55
@EvanMichaels ancillary question, why is the default SimC profile for Havoc running Momentum?  I realize it usually sims slightly higher than Demonic, but like 98% of DHs are raiding as Demonic.  Is the goal to represent the purely highest single-target build with no other conditions, or the build that's actually dominant in use?  I believe Momentum being default is also causing sites like Bloodmallet to use Momentum as their baseline, resulting in rather inaccurate weights for Azerite traits and the like.

**Comment by EvanMichaels** [comment] 2018-12-19 03:06
@kaedys Depends on what the goals are, but people should be simming their preferred spec regardless. Momentum is simming quite a bit higher right now with DH-specific talents due to scaling interactions (2%-2.5% higher) so I don't see a specific reason not to have it be the default as the maximum DPS.

But I don't think the differences will be large enough to dramatically skew Bloodmallet and such. The lack of using Momentum was causing HeroDamage, for example, to be quite messy because it was showing the top-simming alternatives for every row (which is basically always Momentum) even though the order did not change in any meaningful way.

Either way, folks should probably be using Raidbots Top Gear tool to sim variants since the large number of talent combos for Havoc makes HeroDamage/Bloodmallet a rough guideline at best.

**Comment by kaedys** [comment] 2018-12-19 06:34
Fair, though there really isn't _that_ much talent variation these days.  The vast vast majority of DHs, even at the tippy-top of the progression scale, are using 1310201, with Trail occasionally swapped for Fel Barrage on fights where it lines up (Zek'voz, Zul, Mythrax, Mother).  I definitely agree that people should be simming gear themselves, but there are a large number of people that use Bloodmallet et al for judging traits at first blush, and it seems...improper to be using a build baseline in SimC that doesn't actually match what the vast majority of DHs are using, even if that build theoretically sims a couple percent higher on a pure single-target fight.

I dunno, as you say, it depends on what the goals are.  The farther SimC's builds diverge from the dominant build, the less SimC's raid profile baseline reflects reality.  We already have to grapple with the issue of Patchwerk fights not really matching the reality of boss fights.  Using a build that's theoretically better for single target, but usually worse in practice (since it has a much higher skill ceiling, and is much more punishing of mistakes, and substantially lacks AoE compared to the dominant build), and as a result is exceedingly uncommon amongst the actual raiding population of DHs, seems like it would do little more than exacerbate that divorcement from reality.

So is the goal for SimC to demonstrate the maximum simming build, regardless of whether anyone uses it or can reliably perform at that level?  Or is it to show the expected maximal output of the dominant builds in use, under ideal boss mechanic situations and player skill, to serve as a reasonable approximation of an objective comparison between classes and specs?  Because the latter seems like a much more _useful_ purpose.  But perhaps that's just me.

**Comment by Spuffeld** [comment] 2018-12-30 23:08
I hope that I am reading the OP bug report correctly. It is stating that as of patch 8.0, eye beam does not need to be cast before metamorphosis?

(Currently Eye Beam will always be cast first before Metamorphosis with Cooldowns enabled)

Assuming I am reading it correctly, there is a separate check that should be in place if the 'bug' is fixed.

Currently, the following azerite trait exists: **Chaotic Transformation (outer ring)**

> "When you enter Metamorphosis, the cooldown of Eye Beam and Blade Dance is immediately reset"

With this trait in mind, if used, it is beneficial to cast Eye Beam before Metamorphosis, and then Eyebeam again after Metamorphosis, as it will extend the duration of Meta twice.

**Comment by EvanMichaels** [comment] 2018-12-31 01:08
The initial bug is just about removing the currently pretty non-functional logic (because of internal changes) about the double extend functionality. Chaotic Transformation issues are already handled in a different set of logic.

**Comment by EvanMichaels** [comment] 2019-01-15 07:10
Have this sorted out now. Wanted to adjust a few more things and had to get my build updated for all the new stuff.. so will check in tomorrow most likely.

**Comment by kaedys** [comment] 2019-01-21 21:17
On that note, I suspect that something is funky in general with the interaction with Chaotic Transformation.  Perhaps your fixes to the APL and code will correct it, but last time I checked Bloodmallet (which uses the default APL and profile), Chaotic Transformation was showing as roughly 100 DPS _less_ on the first stack than the following 2 stacks.  Since the damage add is the same at all stacks, this implies that the reset functionality, only present on the first stack, is somehow evaluating to a DPS _loss_, which should be impossible.  Granted, however, Bloodmallet, using the default profile, is thus using the Momentum build rather than the dominant Demonic build, but I can't see how it would evaluate to a DPS loss even in that situation.

**Comment by EvanMichaels** [comment] 2019-01-21 21:39
Well, I wouldn't say it is "impossible" for it to be a DPS loss vs. less traits. It could be that playing around Chaotic Transformation is a slight relative loss with only one trait because the gain does not offset potentially holding Meta in some situations at fight length thresholds. Not something I was seeing personally though. I'd have to see what options Bloodmallet is using for those sims to know for sure.

Also could depend on target error %. The passive reset functionality is not all that strong given the relative lack of frequency. We saw this with Demon Reborn previously as well.

**Comment by EvanMichaels** [comment] 2019-01-21 21:44
Worth noting that HeroDungeon sims show a pretty obvious difference between the first and additional traits. So it likely is just fight length boundry issues. https://www.herodamage.com/demon-hunter/azerite-stacks/hd-t23-havoc

**Comment by kaedys** [comment] 2019-01-22 17:39
Why would it be holding Meta, though?  Eye Beam is an integer multiple of Meta's CD.  

And it only shows that increase on M+ setting.  It still shows a (minor) DPS loss against a single target, which says to me that the way the APL is using Eye Beam and Meta is wrong.

**Comment by EvanMichaels** [comment] 2019-01-22 19:04
Eye Beam easily gets slightly desynced from Meta due to Fury usage since you can't just use Eye Beam on the pull without pre-pull Fury manipulation.

Using CT disables the precombat Meta cast which could be a DPS loss for certain (random variance) fight lengths. It should generally be correct, but may not be in all cases with only 1 trait, since the gain is marginal.

Feel free to investigate if you find anything wrong, but the logic is quite simple here and there isn't really much to it. Hard to imagine anything too complex going on here.

**Comment by EvanMichaels** [comment] 2019-01-22 19:28
Basically, the short version to this after some quick investigation is that avoiding Meta on prepull is likely not worth it on certain fight lengths despite the reset mechanic. There is some initial lack of synergy due to missed prepot overlap time and if it causes any missed Meta time later in the fight at all (even a few seconds) it's not hard to see how it can happen. But this is likely irrelevant in most real-world situations. Sims can still end up factoring it in due to the 20% default vary length parameter and the long nature of Meta's CD.

**Comment by kaedys** [comment] 2019-01-23 22:25
> Eye Beam easily gets slightly desynced from Meta due to Fury usage since you can't just use Eye Beam on the pull without pre-pull Fury manipulation.

Yes, but this isn't relevant for a CT case, because Meta isn't used on the pull, so the desync would only be relevant if Eye Beam itself is being delayed due to fury deficit.  And I would assume, though I don't have the APL handy atm (at work), that we're pooling a bit in anticipation of Eye Beam so we don't delay it by shorting ourselves of fury immediately before it comes off CD.

That said, and on that note, have we investigated using a pre-combat Immo Aura in the APL to precharge our fury?  To my knowledge, this is considered standard and recommended practice amongst Demonic DHs, though I've not tried adding it to the APL to see if it actually constitutes a DPS gain.

That said, for the fight lengths, I would think the only fight lengths that this would be relevant for would be ones that fall in a very narrow band of times around the 4m mark.  And the default fight length, iirc, is 5m +- 20%, which would only include a very small subset of sims that would fall into that duration band, no?

I'll have to do some more in-depth investigation this weekend when I have some time.

**Comment by EvanMichaels** [comment] 2019-01-24 16:12
> Yes, but this isn't relevant for a CT case, because Meta isn't used on the pull, so the desync would only be relevant if Eye Beam itself is being delayed due to fury deficit.

I think my point here is that if you aren't using Meta on the pull, Meta gets delayed by a few seconds regardless. You have to build Fury, channel Eye Beam, use Blade Dance, then use Meta.

If you think about it this way, it's certainly obvious that 10-15 seconds of Meta at the end of a fight is worth significantly more DPS than 1 CD reset on Eye Beam and Blade Dance. So what can happen here is that different fight boundry lengths can show different results depending on the length variance vs. just using on pull.

Although this would only likely affect a subset of the sample, I'd imagine the DPS delta is enough to easily erase the relatively minor gain from the reset mechanic. The reset mechanic is very weak over the full duration of the Meta cooldown.

But if you do find anything else, let me know. I will be updating the gear profile and some of the APL changes mentioned above over the next few days now that raids are cleared for the week.

**Comment by EvanMichaels** [comment] 2019-01-25 06:14
Main issue should be resolved in https://github.com/simulationcraft/simc/commit/a0a99429128b7224bb127e58f288a1153afff729

Please feel free to get in touch or open another issue if you have any other findings. Thanks!

**Closed as completed by EvanMichaels** 2019-01-25 06:14 UTC
Labels: ActionPriorityList, DemonHunter
