### ISSUE TITLE
Error with simulation for Outlaw Rogue

### ISSUE THREAD

**Issue by sciprox** [simulationcraft/simc#4642] opened 2018-12-16 21:20 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor '': Item 'inactive' Slot 'head': Cannot parse option from ',id=160623,bonus_id=4822/1477/4786/5396/4775,context=3,azerite_powers=483/31/15/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=crit,haste,mastery,vers
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
rogue=""
level=120
race=blood_elf
region=us
server=thrall
role=attack
professions=alchemy=32/herbalism=95
talents=2211122
spec=outlaw

head=,id=160623,bonus_id=4822/1477/4786/5396/4775,context=3,azerite_powers=483/31/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1526,context=11,azerite_level=28
shoulder=,id=163432,bonus_id=5125/1547/4786/5397/4775,context=29,azerite_powers=411/31/14/13
back=,id=160643,bonus_id=4798/1477/4786,context=3
chest=,id=160728,bonus_id=4825/1462/4786/4775,context=4,azerite_powers=485/22/14/13
wrist=,id=163309,bonus_id=5125/1547/4786,context=29
hands=,id=161402,enchant_id=5932,bonus_id=4798/1482/4783,context=3
waist=,id=160622,bonus_id=4798/1477/4786,context=3
legs=,id=160625,bonus_id=4798/41/1487/4783,context=3
feet=,id=163438,bonus_id=5126/1562/4786,context=6
finger1=,id=158151,enchant_id=5939,bonus_id=4803/1537/4783,context=28
finger2=,id=160646,enchant_id=5939,bonus_id=4801/1477/4784,context=4
trinket1=,id=155568,gem_id=153711,bonus_id=4802/4803/1522/4785,context=27
trinket2=,id=159128,context=13
main_hand=,id=163866,bonus_id=5124/1532/4786,context=3
off_hand=,id=163866,bonus_id=5125/1537/4783,context=5

### Gear from Bags
#
# Hood of Pestilent Ichor (345)
# head=,id=160623,bonus_id=4825/1462/4786/4775,context=4,azerite_powers=483/22/15/13
#
# Honorbound Outrider's Shoulderguards (345)
# shoulder=,id=163432,bonus_id=5124/1532/4786/5394/4775,context=3,azerite_powers=411/31/473/13
#
# Drape of the Loyal Vassal (325)
# back=,id=158375,bonus_id=4778/1497/4785,context=2
#
# Plasma-Spattered Greatcloak (340)
# back=,id=160644,gem_id=153711,bonus_id=4801/1808/1462/4786,context=4
#
# Honorbound Outrider's Tunic (340)
# chest=,id=163283,bonus_id=5125/1532/4786,context=5,azerite_powers=410/22/15
#
# Fairweather Tunic (325)
# chest=,id=158038,bonus_id=1517/4785/5389,context=25,azerite_powers=
#
# Splatterguards (350)
# wrist=,id=161072,bonus_id=4801/1472/4783,context=4
#
# Gonk Outrunner Armbands (325)
# wrist=,id=157917,bonus_id=4803/1517/4785,context=26
#
# Fairweather Belt (335)
# waist=,id=158044,gem_id=153711,bonus_id=4803/4802/1527/4783,context=27
#
# Seafarer Breeches (330)
# legs=,id=157978,bonus_id=4803/43/1522/4785,context=27
#
# Lancet of the Deft Hand (340)
# main_hand=,id=160693,bonus_id=4801/1462/4786,context=4
#
# Blacksmith Hammer (1)
# main_hand=,id=5956
#
# Skinning Knife (4)
# main_hand=,id=7005
#
# Honorbound Dagger (340)
# main_hand=,id=163868,bonus_id=5125/1532/4786,context=28
#
# Fishing Pole (1)
# main_hand=,id=6256
#
# Coralshell Hammer of the Feverflare (266)
# main_hand=,id=159540,bonus_id=4796/1701,drop_level=120
#
# Honorbound Dagger (340)
# off_hand=,id=163868,bonus_id=5125/1532/4786,context=28
#
# Skinning Knife (4)
# off_hand=,id=7005
#
# Lancet of the Deft Hand (340)
# off_hand=,id=160693,bonus_id=4801/1462/4786,context=4
#
# Coralshell Hammer of the Feverflare (266)
# off_hand=,id=159540,bonus_id=4796/1701,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=2

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by seriallos** [comment] 2018-12-16 21:24
Duplicate of #4613 Please update your simc program to a recent nightly build as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by seriallos** 2018-12-16 21:24 UTC
Labels: duplicate

**Comment by sciprox** [comment] 2018-12-16 21:25
I updated before posting this bug.  The latest version did not solve the issue.

**Comment by sciprox** [comment] 2018-12-16 21:26
@seriallos I updated before posting this bug. The latest version did not solve the issue.

**Comment by seriallos** [comment] 2018-12-16 21:39
Grab a nightly version from the link in my last comment, not the release version.
