### ISSUE TITLE
crucible format error

### ISSUE THREAD

**Issue by Gerokos** [simulationcraft/simc#4067] opened 2017-10-01 21:21 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Gerokos invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
hunter="Gerokos"
level=110
race=blood_elf
region=us
server=nathrezim
role=attack
professions=mining=743/engineering=745
talents=2111113
spec=beast_mastery
artifact=56:0:0:0:0:868:4:869:4:870:4:871:4:872:4:873:4:874:4:875:4:876:1:877:1:878:1:879:1:880:1:881:1:882:1:1095:4:1336:1:1368:1:1517:4:1518:1:1519:1:1520:14:1636:1
crucible=1739:1781/1739:1781/1739

head=,id=147142,gem_id=151584,bonus_id=3562/1808/1497/3528
neck=,id=147765,enchant_id=5437,bonus_id=3572/1492/3336
shoulder=,id=144326,enchant_id=5883,bonus_id=3459/3570
back=,id=147140,enchant_id=5435,bonus_id=3562/42/1497/3528
chest=,id=147139,bonus_id=3562/1497/3528
shirt=,id=98084
wrist=,id=152373,gem_id=151584,bonus_id=3614/1808/1472/3528
hands=,id=137300,gem_id=130247,bonus_id=3418/1808/1572/3336
waist=,id=137080,bonus_id=3459/3570
legs=,id=147143,bonus_id=3562/1507/3336
feet=,id=147046,bonus_id=3562/1507/3528
finger1=,id=133634,enchant_id=5429,bonus_id=3418/1587/3337
finger2=,id=134540,enchant_id=5429,bonus_id=3418/1567/3528
trinket1=,id=147019,bonus_id=3562/1507/3528
trinket2=,id=142157,bonus_id=3417/1522/3528
main_hand=,id=128861,gem_id=147115/133768/147100,bonus_id=726,relic_id=3562:1502:3336/3416:1577:3337/3562:1502:3336

### Gear from Bags
#
# Synthebrew Goggles (10)
# head=,id=46735
#
# Helm of Shadowy Descent (935)
# head=,id=151324,bonus_id=3418/41/1587/3337
#
# Green Brewfest Hat (1)
# head=,id=33967
#
# Cape of Mindless Fury (915)
# back=,id=147193,bonus_id=3562/1808/1497/3528
#
# Brewfest Dress (1)
# chest=,id=33863
#
# Hauberk of Frozen Mist (915)
# chest=,id=147043,bonus_id=3562/1497/3528
#
# Call of the Wild (970)
# wrist=,id=137101,bonus_id=3529/3459/3570
#
# Ley Dragoon's Wristbraces (935)
# wrist=,id=134296,bonus_id=3418/1597/3337
#
# Wildstalker Gauntlets (915)
# hands=,id=147141,bonus_id=3562/1497/3528
#
# Legguards of Siphoned Power (915)
# legs=,id=147052,bonus_id=3562/1497/3528
#
# Roots of Shaladrassil (970)
# legs=,id=132466,bonus_id=1811/3570
#
# Brewfest Boots (1)
# feet=,id=33868
#
# Qa'pla, Eredun War Order (970)
# feet=,id=137227,bonus_id=3459/3570
#
# An'she's Band (900)
# finger1=,id=139103,enchant_id=5429,gem_id=130247,bonus_id=3573/1808/1562/3337
#
# The Apex Predator's Claw (970)
# finger1=,id=137382,bonus_id=1811/3570
#
# Soul of the Huntmaster (970)
# finger1=,id=151641,bonus_id=1811/3570
#
# Figurehead of the Naglfar (935)
# trinket1=,id=137329,bonus_id=3418/1587/3337
#
# Blacksmith Hammer (1)
# main_hand=,id=5956
#
# Krokul Mining Pick (800)
# main_hand=,id=153290
#
# Krokul Mining Pick (800)
# off_hand=,id=153290
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-10-01 21:22
Duplicate of #4000

**Closed as completed by vituscze** 2017-10-01 21:22 UTC
Labels: duplicate
