### ISSUE TITLE
Sim error crucible 

### ISSUE THREAD

**Issue by Sanjeev2142** [simulationcraft/simc#4036] opened 2017-09-20 01:03 UTC
Please include a brief overview of the issue in the title above, as well as completing the following:
Whenever I try to sim an error message pops up about the crucible.
#### Simulationcraft Version
7.3v2
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Sanelan invalid crucible rank '1778/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Sanelan invalid crucible rank '1778/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.025
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
deathknight="Sanelan"
level=110
race=blood_elf
region=us
server=suramar
role=attack
professions=blacksmithing=795/mining=249
talents=3213331
spec=frost
artifact=12:0:0:0:0:108:4:109:4:110:4:111:4:113:4:114:4:115:4:117:4:119:1:120:1:122:1:123:1:124:1:1090:4:1091:1:1092:1:1332:1:1360:1:1485:4:1486:1:1487:1:1488:9:1628:1
crucible=1739:1778/1739/1739

head=,id=152376,gem_id=130219,bonus_id=3614/1808/1472/3528
neck=,id=137311,enchant_id=5437,bonus_id=3573/1572/3336
shoulder=,id=147126,enchant_id=5883,bonus_id=3562/1517/3337
back=,id=147122,enchant_id=5434,gem_id=151583,bonus_id=3562/1808/1512/3337
chest=,id=151796,bonus_id=3459/3570
tabard=,id=69210
wrist=,id=147073,bonus_id=3562/1507/3336
hands=,id=147123,enchant_id=5445,bonus_id=3562/1497/3528
waist=,id=132366,bonus_id=3459/3570
legs=,id=147125,gem_id=130220,bonus_id=3562/1808/1502/3336
feet=,id=147936,bonus_id=3579/1705/1547/3336
finger1=,id=147020,enchant_id=5428,bonus_id=3562/1502/3336
finger2=,id=134525,enchant_id=5428,bonus_id=3573/1567/3336
trinket1=,id=147015,gem_id=151583,bonus_id=3562/1808/1507/3336
trinket2=,id=147010,bonus_id=3562/1507/3336
main_hand=,id=128292,enchant_id=3370,gem_id=147093/147108/147093,bonus_id=717,relic_id=3562:1497:3528/3562:1497:3528/3561:1497:3337
off_hand=,id=128293,enchant_id=3368

### Gear from Bags
#
# Nullification Greathelm (502)
# head=,id=87024
#
# Gravewarden Visage (915)
# head=,id=147124,gem_id=151585,bonus_id=3562/1808/1497/3528
#
# Perseverance of the Ebon Martyr (970)
# head=,id=132459,bonus_id=3459/3570
#
# Prydaz, Xavaric's Magnum Opus (970)
# neck=,id=132444,enchant_id=5889,gem_id=151583,bonus_id=1811/3570
#
# Dreadfire Drape (391)
# back=,id=71415
#
# Acherus Drapes (970)
# back=,id=132376,enchant_id=5434,bonus_id=3459/3570
#
# Gravewarden Chestplate (910)
# chest=,id=147121,bonus_id=3561/1492/3336
#
# Cuirass of Blinding Dawn (915)
# chest=,id=147068,bonus_id=3562/1497/3528
#
# Gauntlets of Barbaric Cruelty (930)
# hands=,id=152375,bonus_id=3614/1472/3528
#
# Cinch of the Flaming Ember (378)
# waist=,id=71250
#
# Pustulous Girdle (935)
# waist=,id=137436,bonus_id=3418/1587/3337
#
# Consort's Cold Core (970)
# legs=,id=144293,bonus_id=1811/3570
#
# Greaves of Impure Midnight (930)
# legs=,id=147066,gem_id=151583,bonus_id=3562/1808/1512/3336
#
# Leadfoot Earthshakers (915)
# feet=,id=134507,bonus_id=3510/1567/3337
#
# Fierce Combatant's Dreadplate Sabatons (915)
# feet=,id=149532,bonus_id=3573/1711/43/1577/3336
#
# Iron Ballast Sabatons (915)
# feet=,id=147059,gem_id=151583,bonus_id=3562/1808/1497/3528
#
# Seal of Necrofantasia (970)
# finger1=,id=137223,enchant_id=5428,gem_id=130220,bonus_id=1811/3570
#
# Yathae's Thumb Ring (915)
# finger1=,id=147021,enchant_id=5428,bonus_id=3562/1497/3528
#
# Portal Keeper's Seal (910)
# finger1=,id=146767,bonus_id=3573/1572/3528
#
# Ring of Ascended Glory (910)
# finger1=,id=142520,bonus_id=3573/1527/3528
#
# Sephuz's Secret (970)
# finger1=,id=132452,enchant_id=5428,gem_id=130220,bonus_id=3459/3570
#
# Avenging Band of the Feverflare (910)
# finger1=,id=147257,enchant_id=5428,gem_id=151583,bonus_id=1766/1808/40/3573/3159/3528
#
# Kil'jaeden's Burning Wish (970)
# trinket1=,id=144259,bonus_id=3529/3459/3570
#
# Eye of Command (910)
# trinket1=,id=142167,gem_id=130220,bonus_id=3509/1808/1522/3337
#
# Orb of Torment (910)
# trinket1=,id=137538,bonus_id=3573/1562/3528
#
# Convergence of Fates (895)
# trinket1=,id=140806,bonus_id=3516/1492/3336
#
# Resilient Heart of the Forest (910)
# trinket1=,id=139064,bonus_id=3573/607/1572/3528
#
# Specter of Betrayal (925)
# trinket1=,id=151190,bonus_id=3562/40/1507/3528
#
# Bladefist Spear of the Beast (306)
# main_hand=,id=55413,suffix=-41
#

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by seriallos** [comment] 2017-09-20 01:07
Duplicate of #4000

**Closed as completed by seriallos** 2017-09-20 01:07 UTC
