### ISSUE TITLE
Can't simulate my character through armory link, SImulationCraft or /simc addon

### ISSUE THREAD

**Issue by Kliz0** [simulationcraft/simc#4690] opened 2019-01-16 14:00 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Zaridash': Item 'inactive' Slot 'head': Cannot parse option from ',id=166695,bonus_id=5478/1502/4786/5402/4775,context=3,azerite_powers=244/31/14/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=2
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,crit,haste,mastery,vers
center_scale_delta=1
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Post your Simc Addon Export text here.
# SimC Addon 1.10.10
deathknight="Zaridash"
level=120
race=human
region=us
server=earthen_ring
role=attack
professions=blacksmithing=8/herbalism=150
talents=1133312
spec=unholy

head=,id=166695,bonus_id=5478/1502/4786/5402/4775,context=3,azerite_powers=

**Comment by vituscze** [comment] 2019-01-16 16:34
Duplicate of #4613

**Closed as completed by vituscze** 2019-01-16 16:34 UTC
