### ISSUE TITLE
[Shadow] Mind Blast with Maganza's Madness

### ISSUE THREAD

**Issue by lgkern** [simulationcraft/simc#2970] opened 2016-10-11 17:51 UTC
For some reason, profiles aren't using Mind Blast as often as they should during Surrender to Madness when using Maganza's Madness (transforms MB into a 3 charge spell)

For instance, in the attached sims, the Priest_Shadow_T19M_S2MASbelt profile has, at the end of the APL: 
NJSJKJTJKHMDJ
With N being Mind Blast, which isn't casted again after that point while being ready at least at the second J of the extracted expression above, even having priority over T

[2T_AS_SI_belt_35%_450_s2m_weights_plots.zip](https://github.com/simulationcraft/simc/files/522542/2T_AS_SI_belt_35._450_s2m_weights_plots.zip)

**Comment by Twinkeli** [comment] 2016-10-16 21:56
iirc this was working correctly before i told TT about mind blast cd not being calculated correctly.

https://github.com/simulationcraft/simc/commit/ab13410ad6b101c57ddfec6640a55649f0639704

**Comment by voidzone** [comment] 2016-10-18 16:26
https://www.dropbox.com/s/h1fajimdluudvfw/beltasdebug.html?dl=0
https://www.dropbox.com/s/mrf3cp2j682v3xk/log.zip?dl=0

CD calculation is definitely wrong:
Line 4395: 4.648 Shadow_T19M_only_S2Mdef starts cooldown for mind_blast (mind_blast, 1/1). Will be ready at 11.6030
Line 4422: 4.649 Priest_Shadow_T19M_S2MASbelt starts cooldown for mind_blast (mind_blast, 2/3). Will be ready at -3600.0000
Line 7164: 9.926 Priest_Shadow_T19M_S2MSIbelt starts cooldown for mind_blast (mind_blast, 2/3). Will be ready at -3600.0000
Line 7802: 11.160 Priest_Shadow_T19M_S2MASbelt starts cooldown for mind_blast (mind_blast, 1/3). Will be ready at -3600.0000
Line 8328: 12.105 Priest_Shadow_T19M_S2MSIbelt starts cooldown for mind_blast (mind_blast, 1/3). Will be ready at -3600.0000
Line 8544: 12.247 Priest_Shadow_T19M_S2MASbelt starts cooldown for mind_blast (mind_blast, 1/3). Will be ready at -3600.0000
Line 9657: 14.269 Priest_Shadow_T19M_S2MSIbelt starts cooldown for mind_blast (mind_blast, 0/3). Will be ready at 14.3010
Line 9789: 14.364 Shadow_T19M_only_S2Mdef starts cooldown for mind_blast (mind_blast, 1/1). Will be ready at 18.5240

**Comment by scamille** [comment] 2016-10-19 07:35
I'm looking in to it.

1) I learned that apparently cooldown charges dont recharge completly independent, so that if you have a flat 10s cooldown and cast at 0s, 2s, 4s your CD will come back at 10s, 20s and 30s. Is that correct?

> that's not correct, spell charges generate 1 every n seconds. if you dump all 3 you'll be waiting 3*n to have 3 again

2) The real issue here seems to be with cooldown hasting not getting applied (correctly or incorrectly, not sure):
If I cast at 0s with 6scd, at 2s with 4s CD and at 4s with 3s CD, when should my cooldown come back?
a) at 6s, 12s and 18s
b) at 6s, 10s, 13s
c) at 6s, 9s, 12s
?

**Comment by lgkern** [comment] 2016-10-19 10:40
> 00:00:00.000  Anshlun Mind Blast Bound Void Walker _248092_
> 00:00:01.103    Anshlun gains Power Infusion from Anshlun
> 00:00:01.103    Anshlun casts Power Infusion 
> 00:00:01.571    Anshlun begins casting Mind Blast 
> 00:00:02.457    Anshlun casts Mind Blast on Bound Void Walker
> 00:00:02.457    Anshlun begins casting Mind Blast 
> 00:00:02.457    Anshlun Mind Blast Bound Void Walker _248091_
> 00:00:03.339    Anshlun casts Mind Blast on Bound Void Walker
> 00:00:03.339    Anshlun Mind Blast Bound Void Walker 124045
> 00:00:05.543    Anshlun begins casting Mind Blast 
> 00:00:06.430    Anshlun casts Mind Blast on Bound Void Walker
> 00:00:06.430    Anshlun Mind Blast Bound Void Walker 124046
> 00:00:10.805    Anshlun begins casting Mind Blast 
> 00:00:11.671    Anshlun casts Mind Blast on Bound Void Walker
> 00:00:11.682    Anshlun Mind Blast Bound Void Walker _248091_
> 00:00:16.063    Anshlun begins casting Mind Blast 
> 00:00:16.884    Anshlun casts Mind Blast on Bound Void Walker
> 00:00:16.884    Anshlun Mind Blast Bound Void Walker _248091_`

This was taken from live right now, 6 MBs, PI after the first MB hit. 
(https://www.warcraftlogs.com/reports/wCDHjPb67zNQ9xvr/#view=events)

Charges CDs:
00:00:05.543
00:00:05.262 
00:00:05.258 

So, in your example, it looks like it is c) 6, 9 then 12, as the CD seems to be snapshotted when it starts charging. 

Also, it is worth noting that, with the belt and MB slots available, the CD starts on the begin_cast event, rather than cast_finished like normal MB.

I was talking to TT about it, he thinks that the charges not coming back has something to deal with the way the VF CD reduction (-3s to base time) is applied on every CD, having that dinamic nature may be breaking the structure.

**Comment by scamille** [comment] 2016-10-19 10:48
Ok so after getting more information and learning more of the edge cases of the SimC cooldown system, I have the following:

The problem is the Mind Blast cooldown implementation which isnt adjusted to cooldown charges and dynamic adjustment of recharge time.

Right now, since Mind Blast cooldown is always recharging, and usually started at the beginning of the fight with the 6s base cooldown, it is never dynamically shortened to the 3s cooldown time during Voidform.

Just to be 100% sure: Have you tested ingame, that with Maganzas Madness equipped, Mind Blast transforms into a 3s recharge during VoidForm/S2M, even if you keep Mind Blast on cooldown from the beginning of the fight, starting with the default 6s cooldown?

**Comment by lgkern** [comment] 2016-10-19 12:20
Further testing: Getting to 100 Insanity > MB > Void Eruption > MB on CD
https://www.warcraftlogs.com/reports/DzWTtj7Qmf8y4gCn/#type=summary&boss=0&eventstart=59326

And here some of the events filters and the time of each charge recharge calculated:
https://docs.google.com/spreadsheets/d/1lYntKrfAFbDvDgSrx037pPXEahF_g6CkKZOZgXMlBdo

It seems to me that only the first charge (that started before VF) isn't affected by the -3s reduction, while all others are.

**Comment by scamille** [comment] 2016-10-19 12:43
Thanks for doing those tests.
So in essence: Recharge time is snapshoted each time a cd recharge is started.

Can you please repeat the test with 100 insanity -> MB(#A) -> MB(#B) -> VoidForm -> MB(#C) -> MB(#D) -> MB(#E).

The question is whether only the CD between #C and #D is still 6s, or the one between #D and #E as well. 

The way we have recharge events implemented right now is that they do not snapshot recharge time independently for each charge#.

**Comment by lgkern** [comment] 2016-10-19 14:27
(Sorry by the delay, TeamViewer wasn't being kind to perform 20s VF to get some good data) 

Here are the results

Events filtered: (new tab from same spreadsheet)
https://docs.google.com/spreadsheets/d/1lYntKrfAFbDvDgSrx037pPXEahF_g6CkKZOZgXMlBdo

Logs for it:
https://www.warcraftlogs.com/reports/R8WyqFnVTCAx1JZv#view=events&pins=2%24Off%24%23244F4B%24casts%240%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24true%240

Again only the CD from the first MB was 6s, all others being affected by the -3s from VF.

**Comment by lgkern** [comment] 2016-10-19 15:37
Clearifying something, those numbers from the tests are all affected by haste, pre-haste baseline CD is still 9s without VF and 6s with VF up.

**Comment by scamille** [comment] 2016-10-20 12:05
Ok should be fixed now with 1a5fc56060e90fd187c78a6fb176741f27e6e343

The profile you posted now reaches 100 stacks and casts MB much more often. But please double check it yourself as well.

**Closed as completed by scamille** 2016-10-20 12:05 UTC
Labels: Priest

**Comment by scamille** [comment] 2016-10-20 15:41
Just for your information:
0baabdded24aa645415451f3c5b153953fc88a91 changes VoidForm to dynamically adjust the remaining time of hasted cooldowns and GCD on each stack increment. The assumption here is that Void Form works like other haste buffs, even though its probably impossible to verify if that 1% haste change really influenced your current GCD and MB/VB cooldowns dynamically.

~1% DPS difference for the Priest_Shadow_T19P_S2M.simc profile, but maybe even more relevant for your S2M only simulations.
