### ISSUE TITLE
Bug Report! (item inactive. Unexpected parameter Context"

### ISSUE THREAD

**Issue by GrantedGaming** [simulationcraft/simc#4749] opened 2019-02-25 21:11 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Demigodess': Item 'inactive' Slot 'chest': Cannot parse option from ',id=24397,enchant_id=4419,gem_id=28123/28123/28123,bonus_id=4097,drop_level=59,context=1': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.11
priest="Demigodess"
level=59
race=draenei
region=eu
server=argent_dawn
role=spell
professions=mining=3/engineering=32
talents=2130000
spec=shadow

head=,id=41112,bonus_id=1705
neck=,id=143905,enchant_id=5437,bonus_id=5472,drop_level=59
shoulder=,id=122378,enchant_id=4806
back=,id=122262,enchant_id=5314,bonus_id=582
chest=,id=24397,enchant_id=4419,gem_id=28123/28123/28123,bonus_id=4097,drop_level=59,context=1
wrist=,id=10248,enchant_id=2332,bonus_id=1707
hands=,id=24393,enchant_id=2937,gem_id=28123/28123,bonus_id=4097,drop_level=59,context=1
waist=,id=35971,bonus_id=1707/3839,drop_level=63,context=27
legs=,id=24083,enchant_id=2745,gem_id=28123/28123/28123,bonus_id=4077,drop_level=59,context=1
feet=,id=35581,enchant_id=3232
finger1=,id=7553,enchant_id=5941,bonus_id=4278,drop_level=120,context=54
finger2=,id=29159,enchant_id=5941
trinket1=,id=40865
trinket2=,id=40865
main_hand=,id=17780,enchant_id=2505,bonus_id=4022,drop_level=59,context=1
off_hand=,id=43664,enchant_id=4434

### Gear from Bags
#
# Elder Magus Pendant (57)
# neck=,id=18397,bonus_id=4014,drop_level=59,context=1
#
# Mana-Etched Gloves (57)
# hands=,id=27465,enchant_id=2937,gem_id=28123/28123,bonus_id=4077,drop_level=59,context=1
#
# Icon of Unyielding Courage (57)
# trinket1=,id=28121,bonus_id=4097,drop_level=59,context=1
#
# Arclight Spanner (10)
# main_hand=,id=6219
#
# Staats' Fishing Pole (10)
# main_hand=,id=46337,context=11
#
# Mining Pick (4)
# main_hand=,id=2901,context=14
#
# Bouquet of Scarlet Begonias (23)
# off_hand=,id=2562,context=11

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2019-02-25 21:58
Duplicate of #4613

**Closed as completed by vituscze** 2019-02-25 21:58 UTC
