### ISSUE TITLE
Multiple Copies of a Character Reduce each Characters DPS

### ISSUE THREAD

**Issue by eldir** [simulationcraft/simc#3730] opened 2017-04-27 13:15 UTC
If I sim my character on his own I get higher DPS then if I sim two copies (noticed that when comparing gear in one sim). The difference between those cases can exceed a few thousand DPS. This might be intended as Fluffy pillow has finite health?

#### Simulationcraft Version
SimulationCraft 720-03 for World of Warcraft 7.2.0 Live (wow build level 23826, git build 70d7420)

#### Reproduction Steps:
Import my character from battle.net (in my case Culicidae-ArgentDawn) hit Simulate. Copy paste everything in the Simulation window underneath the first character and hit Simulate again. Every time a character is added this way the dps for each of them goes down when compared to simulations with less characters in them.

**Comment by Jayezi** [comment] 2017-05-09 21:21
putting "fixed_time=1" in the profile should help with that

**Comment by aethys256** [comment] 2017-06-12 21:20
Duplicate of https://github.com/simulationcraft/simc/issues/2615

**Closed as completed by aethys256** 2017-06-12 21:20 UTC
