### ISSUE TITLE
Weird Error When Trying to Sim

### ISSUE THREAD

**Issue by bookshelves** [simulationcraft/simc#4630] opened 2018-12-15 02:12 UTC
So I was trying to sim my boomkin, and this error popped up. I've simmed feral, mage specs, etc., and this is the first time I've ever seen this come up. Any idea how to fix it?

SimulationCraft encountered an error!

Simulation runtime error:
Initializing: Actor 'Bookshelves': Item 'inactive' Slot 'head': Cannot parse option from ',id=160623,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/459/15/13': Unexpected parameter 'context'.

If you think this is a bug, please open a ticket, copying the detailed text below.
It contains all the input options of the last simulation and helps us reproduce the issue.

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Bookshelves': Item 'inactive' Slot 'head': Cannot parse option from ',id=160623,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/459/15/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.
# SimC Addon 1.10.8
druid="Bookshelves"
level=120
race=tauren
region=us
server=illidan
role=spell
professions=leatherworking=115/herbalism=165
talents=1333331
spec=balance

head=,id=160623,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/459/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=157883,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=250/459/15/13
back=,id=160642,gem_id=154127,bonus_id=4799/1808/1492/4786,context=5
chest=,id=163283,bonus_id=5126/1562/4786/4775,context=6,azerite_powers=488/31/15/13
shirt=,id=4333
tabard=,id=43300
wrist=,id=160621,bonus_id=4799/43/1492/4786,context=5
hands=,id=160618,gem_id=154127,bonus_id=4800/1808/1507/4786,context=6
waist=,id=163439,bonus_id=5126/1562/4786,context=6
legs=,id=163298,bonus_id=5126/1562/4786,context=6
feet=,id=160624,bonus_id=4799/41/1492/4786,context=5
finger1=,id=160645,enchant_id=5943,bonus_id=4800/1507/4786,context=6
finger2=,id=159461,enchant_id=5943,bonus_id=5002/1522/4786,context=16
trinket1=,id=163937,bonus_id=1472/4786,context=54
trinket2=,id=159126,context=13
main_hand=,id=163956,enchant_id=5963,gem_id=154127,bonus_id=4802/1472/4786,context=54

### Gear from Bags
#
# Honorbound Outrider's Headpiece (370)
# head=,id=163435,bonus_id=5125/1562/5136/5381,context=28,azerite_powers=
#
# Seafarer Headcover (325)
# head=,id=157977,bonus_id=1517/4785/5390,context=25,azerite_powers=
#
# Honorbound Outrider's Shoulderguards (355)
# shoulder=,id=163432,bonus_id=5125/1547/5140/5379,context=28,azerite_powers=
#
# Deathsnap Jerkin (370)
# chest=,id=157942,bonus_id=1562/5138/5383,context=28,azerite_powers=
#
# Jerkin of the Aberrant Chimera (360)
# chest=,id=160619,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=483/21/83/13
#
# Honorbound Outrider's Bracers (340)
# wrist=,id=163309,bonus_id=5124/1532/4786,context=3
#
# Bloodstorm Buckle (370)
# waist=,id=160622,bonus_id=4799/1492/4786,context=5
#
# Quarantine Protocol Treads (370)
# feet=,id=160624,bonus_id=4799/1492/4786,context=5
#
# Ring of the Infinite Void (375)
# finger1=,id=160647,bonus_id=4799/1497/4783,context=5
#
# Footbomb Championship Ring (380)
# finger1=,id=159462,enchant_id=5943,bonus_id=5009/1552/4784,context=35
#
# Kul Tiran Cannonball Runner (345)
# trinket1=,id=159628,gem_id=154127,bonus_id=4780/4802/1517/4786,context=16
#
# Construct Overcharger (390)
# trinket1=,id=160652,bonus_id=4800/1512/4783,context=6
#
# Darkmoon Deck: Fathoms (355)
# trinket1=,id=159125,context=13
#
# Forest Lord's Razorleaf (385)
# trinket1=,id=166794,bonus_id=5479/1502/4786,context=3
#
# Nat Pagle's Extreme Angler FC-5000 (50)
# main_hand=,id=19022,context=11
#
# Glave's Angular Glaive (350)
# main_hand=,id=163965,enchant_id=5963,bonus_id=1472/4786,context=54

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=6

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-15 02:13
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-15 02:13 UTC

**Comment by bookshelves** [comment] 2018-12-15 02:55
I uninstalled, reinstalled, and I'm still getting the same exact error code. And it's with every class and spec now.
    On Friday, December 14, 2018, 9:13:20 PM EST, AlexanderKenny <notifications@github.com> wrote:  
 
 
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Comment by AlexanderKenny** [comment] 2018-12-15 04:51
Please make sure you grab one of the nightly builds from the link I provided not the main download page. There has not been a major release in a while unfortunately. You should not be receiving that specific error if you are using a nightly.
