### ISSUE TITLE
Runtime error prompt

### ISSUE THREAD

**Issue by yomy** [simulationcraft/simc#4004] opened 2017-09-14 16:42 UTC
Was prompted to open a ticket...

#### Simulationcraft Version
730-02

# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Fireman invalid crucible rank '1783/1739/1739' for power '1739', expected a number > 0 && <= 255
Player Fireman invalid crucible rank '1783/1739/1739' for power '1739', expected a number > 0 && <= 255

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=wowhead/local/bcpapi
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=CastingPatchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=0
override.bleeding=0
override.mortal_wounds=0
threads=8
process_priority=Low
calculate_scale_factors=1
scale_only=int,crit,haste,mastery,vers
scale_over=DPS
statistics_level=1
### End GUI options ###
### Begin simulateText ###
mage="Fireman"
level=110
race=night_elf
region=us
server=kilrogg
role=spell
professions=tailoring=800/enchanting=791
talents=2132113
spec=fire
artifact=54:0:0:0:0:748:1:749:4:750:4:751:4:752:4:753:4:754:4:755:4:756:4:757:4:758:1:759:1:760:1:761:1:762:1:763:1:1340:1:1372:1:1533:4:1534:1:1535:1:1536:10:1640:1
crucible=1739:1783/1739/1739

head=,id=146990,bonus_id=3562/43/1502/3336
neck=,id=140894,enchant_id=5439,bonus_id=3444/42/1517/3337
shoulder=,id=152354,enchant_id=5931,bonus_id=3614/1482/3336
back=,id=146984,enchant_id=5436,gem_id=130248,bonus_id=3562/1808/1507/3336
chest=,id=146995,bonus_id=3562/1502/3336
wrist=,id=132406,bonus_id=3459/3570
hands=,id=147146,enchant_id=5447,bonus_id=3562/1502/3336
waist=,id=132454,bonus_id=1811/3570
legs=,id=147148,bonus_id=3562/1507/3336
feet=,id=152349,bonus_id=3614/1477/3336
finger1=,id=134532,enchant_id=5427,bonus_id=3417/1592/3337
finger2=,id=137438,enchant_id=5427,bonus_id=3418/1587/3337
trinket1=,id=147016,bonus_id=3562/1497/3528
trinket2=,id=147019,bonus_id=3562/1512/3336
main_hand=,id=128820,gem_id=151000/147076/147090,bonus_id=730,relic_id=3573:1507:3336/3562:1502:3336/3561:1502:3337
off_hand=,id=133959

### End simulateText ###
desired_targets=4
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2017-09-14 16:43
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-14 16:43 UTC
Labels: duplicate
