### ISSUE TITLE
* Error: Player Jvo invalid crucible format, expected: power_id:rank[:power_id:rank...]

### ISSUE THREAD

**Issue by jvo111** [simulationcraft/simc#4016] opened 2017-09-15 16:17 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Player Jvo invalid crucible format, expected: power_id:rank[:power_id:rank...]

## All options used for simulation:
``` ini
### Begin GUI options ###
item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=4
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
warlock="Jvo"
level=110
race=orc
region=eu
server=thunderhorn
role=spell
professions=alchemy=226/enchanting=743
talents=3113213
spec=affliction
artifact=39:0:0:0:0:915:4:916:4:917:4:918:4:919:4:920:4:921:4:922:4:923:4:924:1:925:1:926:1:927:1:928:1:929:1:999:1:1353:1:1390:1:1601:4:1602:1:1603:1:1604:12:1711:1
crucible=1739:1774/1739:1774/1739

head=,id=147183,bonus_id=3564/1472/3336
neck=,id=147014,enchant_id=5890,bonus_id=3562/1497/3528
shoulder=,id=147186,enchant_id=5883,gem_id=151584,bonus_id=3562/1808/1497/3528
back=,id=134402,enchant_id=5436,bonus_id=3418/1587/3337
chest=,id=151821,bonus_id=1811/3570
wrist=,id=134222,bonus_id=3418/1577/3528
hands=,id=147182,gem_id=151584,bonus_id=3561/1808/1497/3337
waist=,id=137488,bonus_id=3418/1597/3337
legs=,id=147184,bonus_id=3561/1482/3528
feet=,id=146987,bonus_id=3562/1497/3528
finger1=,id=151649,enchant_id=5429,gem_id=151584,bonus_id=1811/3570
finger2=,id=147195,enchant_id=5429,bonus_id=3561/1492/3528
trinket1=,id=144480,bonus_id=3573/1567/3336
trinket2=,id=134204,bonus_id=3573/604/1582/3336
main_hand=,id=128942,gem_id=137399/147081/147109,bonus_id=747,relic_id=3573:1567:3336/3562:1502:3336/3562:1497:3528

### Gear from Bags
#
# Hundred-Fathom Veil (920)
# head=,id=146990,bonus_id=3562/1502/3336
#
# Diabolic Shroud (890)
# back=,id=147181,enchant_id=5436,bonus_id=3564/1472/3336
#
# Shredded Felbroken Shawl (110)
# back=,id=152862
#
# Flameheart Vestment (935)
# chest=,id=137504,gem_id=151584,bonus_id=3418/1808/1587/3337
#
# Diabolic Robe (885)
# chest=,id=147185,bonus_id=3564/1467/3528
#
# Legwraps of Fused Loathing (925)
# legs=,id=146992,bonus_id=3562/1507/3336
#
# Band of Twisted Bark (905)
# finger1=,id=134531,enchant_id=5429,bonus_id=3509/1557/3337
#
# Band of Rescinded Truths (915)
# finger1=,id=147194,enchant_id=5425,bonus_id=3562/1497/3528
#
# Whispers in the Dark (900)
# trinket1=,id=140809,bonus_id=3517/1497/3336
#
# Charm of the Rising Tide (915)
# trinket1=,id=147002,bonus_id=3562/1497/3528
#
# Terror From Below (900)
# trinket1=,id=147016,bonus_id=3561/1482/3528
#
# Tarnished Sentinel Medallion (890)
# trinket1=,id=147017,gem_id=130222,bonus_id=3564/1808/1472/3336
#
# Kil'jaeden's Burning Wish (970)
# trinket1=,id=144259,bonus_id=3459/3570
#
# Twisting Wind (910)
# trinket1=,id=139323,bonus_id=3573/1808/1532/3528
#
# Nightborne Researcher's Phial (910)
# trinket1=,id=134292,gem_id=151584,bonus_id=3573/1808/605/1572/3528
#
# Chipped Man'ari Blade (380)
# main_hand=,id=152857
#


### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

Please include a brief overview of the issue in the title above, as well as completing the following:

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by vituscze** [comment] 2017-09-15 19:38
Duplicate of #4000

Read the comments there on how to resolve this.

**Closed as completed by vituscze** 2017-09-15 19:38 UTC
