### ISSUE TITLE
Error on level 49 frost mage - Action 'ray_of_frost': Cannot parse expression

### ISSUE THREAD

**Issue by ldemailly** [simulationcraft/simc#4604] opened 2018-11-26 05:55 UTC
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Pyrowoman': Action 'ray_of_frost': Cannot parse expression from '!action.frozen_orb.in_flight&ground_aoe.frozen_orb.remains=0': No expression found.

## All options used for simulation:
``` ini
### SimulationCraft 801-02 for World of Warcraft 8.0.1 Live (wow build 27980) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
ptr=0
item_db_source=local/bcpapi/wowhead/ptrhead
target_error=0
iterations=25000
default_world_lag=0.05
max_time=100
vary_combat_length=0.2
fight_style=LightMovement
tmi_window_global=6
target_level+=0
pvp=1
optimal_raid=0
override.bloodlust=0
override.arcane_intellect=0
override.power_word_fortitude=1
override.battle_shout=0
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=0
override.mystic_touch=0
deterministic=1
threads=12
process_priority=Normal
calculate_scale_factors=1
scale_only=int,sp,crit,haste,vers,runspeed
center_scale_delta=1
statistics_level=2
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.7
# 8.0 Note: reforge= is being used as a hacky way to capture item context. This will be changed in 8.1

mage="Pyrowoman"
level=49
race=void_elf
region=us
server=kiljaeden
role=spell
professions=alchemy=300/engineering=300
talents=3220000
spec=frost

head=,id=15999
neck=,id=13085,enchant_id=5439
shoulder=,id=122378,enchant_id=4806,bonus_id=582
back=,id=8248,enchant_id=4072,bonus_id=4276,drop_level=49,reforge=43
chest=,id=14042,enchant_id=4419,reforge=1
tabard=,id=157758,reforge=11
wrist=,id=10096,enchant_id=2332,bonus_id=1706,reforge=54
hands=,id=14043,enchant_id=4431
waist=,id=13144
legs=,id=122256,enchant_id=4109,bonus_id=3592
feet=,id=10044,enchant_id=3232
finger1=,id=21753,enchant_id=5430
finger2=,id=19523,enchant_id=5430,reforge=14
trinket1=,id=10576
trinket2=,id=34424,bonus_id=3743,drop_level=49,reforge=11
main_hand=,id=17780,enchant_id=4097,bonus_id=4022,drop_level=49,reforge=1
off_hand=,id=13353,enchant_id=4434,bonus_id=4055,drop_level=49,reforge=1

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2018-11-26 11:23
Duplicate of #4514

**Closed as completed by vituscze** 2018-11-26 11:23 UTC
