### ISSUE TITLE
SimulationCraft encountered an error!

### ISSUE THREAD

**Issue by Hermy76** [simulationcraft/simc#4628] opened 2018-12-14 20:33 UTC
### Describe the bug
SimulationCraft encountered an error when trying to sim a toon.

### Expected behavior
I expected to sim my toon.

### To Reproduce
I've tried this a few times, and have also logged out and back in, but am still getting the same error.

### Additional information
* SimulationCraft Version 801-01

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  # SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Arthérmis': Item 'inactive' Slot 'head': Cannot parse option from ',id=165483,bonus_id=5124/1457/4786/5393/4775,context=3,azerite_powers=365/30/83/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.9.6 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=4
process_priority=Low
calculate_scale_factors=1
scale_only=str,agi,sta,int,sp,ap,crit,haste,mastery,vers,wdps,wohdps,armor,bonusarmor,leech,runspeed
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
hunter="Arthérmis"
level=120
race=blood_elf
region=us
server=amanthul
role=attack
professions=alchemy=120/engineering=39
talents=1323211
spec=beast_mastery

head=,id=165483,bonus_id=5124/1457/4786/5393/4775,context=3,azerite_powers=365/30/83/13
neck=,id=158075,bonus_id=4932/4933/4936/1524,context=11,azerite_level=27
shoulder=,id=161357,bonus_id=4822/1477/4786/4775,context=3,azerite_powers=478/22/83/13
back=,id=166672,bonus_id=4803/1537/4786,context=28
chest=,id=166575,bonus_id=5124/1457/4786/5392/4775,context=3,azerite_powers=367/31/87/13
tabard=,id=43156,context=14
wrist=,id=160629,bonus_id=4798/1477/4786,context=3
hands=,id=163448,bonus_id=5126/1587/4784,context=6
waist=,id=163451,bonus_id=5125/1532/4786,context=5
legs=,id=163445,bonus_id=5124/1532/4786,context=3
feet=,id=161395,bonus_id=4798/1808/1477/4786,context=3
finger1=,id=158151,enchant_id=5938,bonus_id=4803/1532/4784,context=25
finger2=,id=158152,bonus_id=4803/1522/4781,context=26
trinket1=,id=166794,bonus_id=5479/1502/4786,context=3
trinket2=,id=127493,bonus_id=5130,drop_level=120,context=22
main_hand=,id=163879,enchant_id=5957,bonus_id=5125/1532/4786,context=5

### Gear from Bags
#
# Weather-Beaten Fishing Hat (10)
# head=,id=33820,context=11
#
# Cloak of Coordination (58)
# back=,id=65274
#
# Gauntlets of Serpent Scales (335)
# hands=,id=127572,bonus_id=5130,drop_level=120,context=22
#
# Band of the Kirin Tor (100)
# finger1=,id=40586,context=14
#
# Draenic Philosopher's Stone (136)
# trinket1=,id=109262,context=1
#
# Time-Lost Artifact (116)
# trinket1=,id=103678,context=14
#
# Seth's Graphite Fishing Pole (58)
# main_hand=,id=25978,enchant_id=5357
#
# Honorbound Pigsticker (340)
# main_hand=,id=163871,bonus_id=5125/40/1532/4786,context=5

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by AlexanderKenny** [comment] 2018-12-15 01:43
Duplicate of #4613 Please update your simc program as your current version is months out of date: http://downloads.simulationcraft.org/?C=M;O=D

**Closed as completed by AlexanderKenny** 2018-12-15 01:43 UTC

**Comment by Hermy76** [comment] 2018-12-15 08:41
I’m not sure how that is possible, as I downloaded it for the first time on this computer a week ago from the SimulationCraft website (the Mac version).

**Comment by AlexanderKenny** [comment] 2018-12-15 12:51
There has not been a major release in a while you'll need a nightly from the link I provided instead of the main download page.
