### ISSUE TITLE
Simulation runtime error: .... Item 'inactive' Slot 'head': Cannot parse option from ',id=158017,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=366/459/14/13': Unexpected parameter 'context'.

### ISSUE THREAD

**Issue by jahfarai** [simulationcraft/simc#4614] opened 2018-12-11 01:04 UTC
### Describe the bug
Simulation runtime error:
Initializing: Actor 'Youngmoney': Item 'inactive' Slot 'head': Cannot parse option from ',id=158017,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=366/459/14/13': Unexpected parameter 'context'.

### Expected behavior
Cannot run sim

### To Reproduce
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Youngmoney': Item 'inactive' Slot 'head': Cannot parse option from ',id=158017,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=366/459/14/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
hunter="Youngmoney"
level=120
race=night_elf
region=us
server=darkspear
role=attack
professions=mining=150/jewelcrafting=144
talents=1323211
spec=beast_mastery

head=,id=158017,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=366/459/14/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=159376,bonus_id=5064/1542/4786/4775,context=35,azerite_powers=479/31/469/13
back=,id=159287,bonus_id=5007/1542/4783,context=35
chest=,id=160627,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/22/469/13
wrist=,id=158357,gem_id=153708,bonus_id=5007/4802/1542/4783,context=35
hands=,id=160626,bonus_id=4800/1507/4786,context=6
waist=,id=160724,bonus_id=4799/1497/4783,context=5
legs=,id=160631,bonus_id=4800/1507/4786,context=6
feet=,id=159404,bonus_id=5005/1542/4784,context=16
finger1=,id=162541,enchant_id=5942,bonus_id=5007/1542/4783,context=35
finger2=,id=160647,enchant_id=5943,bonus_id=4799/1492/4786,context=5
trinket1=,id=160652,bonus_id=4800/1507/4786,context=6
trinket2=,id=160648,bonus_id=4799/1492/4786,context=5
main_hand=,id=159657,enchant_id=5957,bonus_id=5009/41/1547/4783,context=35

### Gear from Bags
#
# Ashenwood Helm (360)
# head=,id=158017,bonus_id=1547/5136/5378/4775,context=28,azerite_powers=366/459/14/13
#
# Dreadmire Helm (325)
# head=,id=157889,bonus_id=1517/4785,context=26,azerite_powers=
#
# Ionized Choker (345)
# neck=,id=133369,bonus_id=5130/5131,drop_level=120,context=22
#
# Deadwash Mantle (370)
# shoulder=,id=158051,bonus_id=1562/5140/5382,context=28,azerite_powers=
#
# Crosswind Shoulderguards (370)
# shoulder=,id=157987,bonus_id=1562/5140/5382,context=28,azerite_powers=
#
# Trailseeker Spaulders (176)
# shoulder=,id=153810
#
# Hook-Barbed Spaulders (325)
# shoulder=,id=159376,bonus_id=4818/1497/4785,context=2,azerite_powers=
#
# Dreadmire Shoulderguards (325)
# shoulder=,id=157891,bonus_id=1517/4785,context=27,azerite_powers=
#
# Flame-Sterilized Spaulders (370)
# shoulder=,id=160632,bonus_id=4823/1492/4786,context=5,azerite_powers=483/31/83
#
# Deadwash Mantle (370)
# shoulder=,id=158051,bonus_id=1562/5140/5382,context=28,azerite_powers=
#
# Pa'ku Windrider Shoulderguards (325)
# shoulder=,id=157923,bonus_id=1517/4785,context=27,azerite_powers=
#
# 7th Legionnaire's Monnion (340)
# shoulder=,id=163389,bonus_id=5125/1532/4786,context=5,azerite_powers=
#
# Yeti-Rager's Cloak (325)
# back=,id=155572,bonus_id=4803/1517/4785,context=26
#
# 7th Legionnaire's Chain Drape (370)
# back=,id=163351,bonus_id=5126/1562/4786,context=6
#
# Plasma-Spattered Greatcloak (370)
# back=,id=160644,bonus_id=4799/1492/4786,context=5
#
# Cloak of Rippling Whispers (370)
# back=,id=160642,bonus_id=4799/1492/4786,context=5
#
# Ebon Blood Chestguard (130)
# chest=,id=112821,bonus_id=450,context=6
#
# Crosswind Chainmail (325)
# chest=,id=157982,bonus_id=1517/4785,context=26,azerite_powers=
#
# Deathslaver's Hauberk (360)
# chest=,id=159395,bonus_id=5049/1527/4786/4775,context=35,azerite_powers=156/31/86/13
#
# Crosswind Chainmail (325)
# chest=,id=157982,bonus_id=1517/4785,context=27,azerite_powers=
#
# Crosswind Chainmail (370)
# chest=,id=157982,bonus_id=1562/5138/5383,context=28,azerite_powers=
#
# Trailseeker Vest (176)
# chest=,id=153805
#
# 7th Legionnaire's Chainmail (370)
# chest=,id=163398,bonus_id=5125/1562/5138/5383,context=28,azerite_powers=
#
# 7th Legionnaire's Bindings (340)
# wrist=,id=163277,bonus_id=5125/40/1532/4786,context=5
#
# 7th Legionnaire's Handguards (340)
# hands=,id=163397,bonus_id=5125/1532/4786,context=28
#
# Gloves of Descending Madness (370)
# hands=,id=160618,bonus_id=4799/1492/4786,context=5
#
# Wrasse Handwraps (335)
# hands=,id=133181,bonus_id=5130,drop_level=120,context=22
#
# Gloves of Involuntary Amputation (355)
# hands=,id=160626,bonus_id=4798/40/1477/4786,context=3
#
# Ionic Gloves (335)
# hands=,id=133258,bonus_id=5130,drop_level=120,context=22
#
# Blood Tick Crushers (355)
# hands=,id=159382,bonus_id=5005/1527/4786,context=16
#
# Cincture of Profane Deeds (370)
# waist=,id=160724,bonus_id=4799/1492/4786,context=5
#
# Shalebiter Interlinked Chain (370)
# waist=,id=159361,bonus_id=5007/1542/4783,context=35
#
# Anchor Chain Girdle (360)
# waist=,id=159386,bonus_id=5007/4802/1532/4786,context=16
#
# Titanspark Energy Girdle (370)
# waist=,id=160633,bonus_id=4799/40/1492/4786,context=5
#
# Anchor Chain Girdle (360)
# waist=,id=159386,bonus_id=5007/1532/4786,context=16
#
# 7th Legionnaire's Cincture (370)
# waist=,id=163401,bonus_id=5126/1562/4786,context=6
#
# Chain-Linked Safety Cord (375)
# waist=,id=159353,bonus_id=5009/43/1547/4783,context=35
#
# Legguards of Coalescing Plasma (370)
# legs=,id=160631,bonus_id=4799/1492/4786,context=5
#
# Windshear Leggings (365)
# legs=,id=161407,bonus_id=4798/1487/4783,context=3
#
# Legguards of the Storm Battalion (335)
# legs=,id=161587,context=14
#
# Chemical Blaster's Legguards (365)
# legs=,id=158341,bonus_id=5008/1537/4786,context=16
#
# Fused Monstrosity Stompers (370)
# feet=,id=160628,bonus_id=4799/1492/4786,context=5
#
# Souldrifting Sabatons (365)
# feet=,id=158308,bonus_id=5008/1537/4786,context=16
#
# Jade Ophidian Band (365)
# finger1=,id=162544,bonus_id=5008/1537/4786,context=16
#
# Murky Cerulean Signet (360)
# finger1=,id=158318,bonus_id=5007/1532/4786,context=16
#
# Band of Certain Annihilation (370)
# finger1=,id=160646,bonus_id=4799/1492/4786,context=5
#
# Spearfisher's Band (320)
# finger1=,id=158161,bonus_id=4803/4802/1512/4785,context=25
#
# Nautilus Ring (345)
# finger1=,id=133194,bonus_id=5130/5131,drop_level=120,context=22
#
# Smuggler's Cove Ring (330)
# finger1=,id=158160,bonus_id=4803/40/1522/4785,context=27
#
# Pearl Diver's Compass (325)
# trinket1=,id=158162,bonus_id=4803/1517/4785,context=26
#
# Plunderbeard's Flask (320)
# trinket1=,id=158164,bonus_id=4803/42/1512/4785,context=25
#
# Construct Overcharger (370)
# trinket1=,id=160652,bonus_id=4799/1492/4786,context=5
#
# Darkmoon Deck: Fathoms (355)
# trinket1=,id=159125,context=13
#
# Construct Overcharger (385)
# trinket1=,id=160652,bonus_id=4800/1507/4786,context=6
#
# Dread Aspirant's Insignia (340)
# trinket1=,id=162899,bonus_id=1532/4783,context=47
#
# Wavecaller Spire of the Aurora (266)
# main_hand=,id=159569,bonus_id=4796/4802/42/1705,drop_level=120
#
# Golden Fleet Waraxe of the Harmonious (266)
# main_hand=,id=159476,bonus_id=4796/4802/1716,drop_level=120
#
# Wavecaller Speargun (345)
# main_hand=,id=158084,bonus_id=4803/41/1537/4783,context=28
#
# P.A.C.I.F.I.S.T. Mk7 (360)
# main_hand=,id=159639,bonus_id=5007/1532/4786,context=16
#
# Tideguard Pike (340)
# main_hand=,id=158097,bonus_id=4803/1532/4786,context=28
#
# Tideguard Pike (340)
# main_hand=,id=158097,gem_id=154127,bonus_id=4803/4802/1532/4786,context=28
#
# Wickerbeast Mulcher (320)
# main_hand=,id=155362,bonus_id=4803/1512/4785,context=25
#
# Re-Origination Pulse Rifle (370)
# main_hand=,id=160694,enchant_id=5957,gem_id=153708,bonus_id=4799/1808/1492/4786,context=5
#
# Golden Fleet Waraxe of the Harmonious (266)
# off_hand=,id=159476,bonus_id=4796/4802/1716,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=8

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

### Additional information
* SimulationCraft Version8 01-01

* **simc_gui.simc** file or contents
# SimulationCraft encountered an error!
* Category: Simulation runtime error
* Error: Initializing: Actor 'Youngmoney': Item 'inactive' Slot 'head': Cannot parse option from ',id=158017,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=366/459/14/13': Unexpected parameter 'context'.

## All options used for simulation:
``` ini
### SimulationCraft 801-01 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095) ###
### Using QT 5.10.1 with WebEngine ###

### Begin GUI options ###
item_db_source=local/bcpapi/wowhead/bfahead
target_error=0
iterations=0
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
optimal_raid=0
override.bloodlust=1
override.arcane_intellect=1
override.power_word_fortitude=1
override.battle_shout=1
override.bleeding=1
override.mortal_wounds=1
override.chaos_brand=1
override.mystic_touch=1
threads=8
process_priority=Low
statistics_level=1
### End GUI options ###
### Begin simulateText ###
# SimC Addon 1.10.8
hunter="Youngmoney"
level=120
race=night_elf
region=us
server=darkspear
role=attack
professions=mining=150/jewelcrafting=144
talents=1323211
spec=beast_mastery

head=,id=158017,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=366/459/14/13
neck=,id=158075,bonus_id=4936/4929/4930/1534,context=11,azerite_level=32
shoulder=,id=159376,bonus_id=5064/1542/4786/4775,context=35,azerite_powers=479/31/469/13
back=,id=159287,bonus_id=5007/1542/4783,context=35
chest=,id=160627,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/22/469/13
wrist=,id=158357,gem_id=153708,bonus_id=5007/4802/1542/4783,context=35
hands=,id=160626,bonus_id=4800/1507/4786,context=6
waist=,id=160724,bonus_id=4799/1497/4783,context=5
legs=,id=160631,bonus_id=4800/1507/4786,context=6
feet=,id=159404,bonus_id=5005/1542/4784,context=16
finger1=,id=162541,enchant_id=5942,bonus_id=5007/1542/4783,context=35
finger2=,id=160647,enchant_id=5943,bonus_id=4799/1492/4786,context=5
trinket1=,id=160652,bonus_id=4800/1507/4786,context=6
trinket2=,id=160648,bonus_id=4799/1492/4786,context=5
main_hand=,id=159657,enchant_id=5957,bonus_id=5009/41/1547/4783,context=35

### Gear from Bags
#
# Ashenwood Helm (360)
# head=,id=158017,bonus_id=1547/5136/5378/4775,context=28,azerite_powers=366/459/14/13
#
# Dreadmire Helm (325)
# head=,id=157889,bonus_id=1517/4785,context=26,azerite_powers=
#
# Ionized Choker (345)
# neck=,id=133369,bonus_id=5130/5131,drop_level=120,context=22
#
# Deadwash Mantle (370)
# shoulder=,id=158051,bonus_id=1562/5140/5382,context=28,azerite_powers=
#
# Crosswind Shoulderguards (370)
# shoulder=,id=157987,bonus_id=1562/5140/5382,context=28,azerite_powers=
#
# Trailseeker Spaulders (176)
# shoulder=,id=153810
#
# Hook-Barbed Spaulders (325)
# shoulder=,id=159376,bonus_id=4818/1497/4785,context=2,azerite_powers=
#
# Dreadmire Shoulderguards (325)
# shoulder=,id=157891,bonus_id=1517/4785,context=27,azerite_powers=
#
# Flame-Sterilized Spaulders (370)
# shoulder=,id=160632,bonus_id=4823/1492/4786,context=5,azerite_powers=483/31/83
#
# Deadwash Mantle (370)
# shoulder=,id=158051,bonus_id=1562/5140/5382,context=28,azerite_powers=
#
# Pa'ku Windrider Shoulderguards (325)
# shoulder=,id=157923,bonus_id=1517/4785,context=27,azerite_powers=
#
# 7th Legionnaire's Monnion (340)
# shoulder=,id=163389,bonus_id=5125/1532/4786,context=5,azerite_powers=
#
# Yeti-Rager's Cloak (325)
# back=,id=155572,bonus_id=4803/1517/4785,context=26
#
# 7th Legionnaire's Chain Drape (370)
# back=,id=163351,bonus_id=5126/1562/4786,context=6
#
# Plasma-Spattered Greatcloak (370)
# back=,id=160644,bonus_id=4799/1492/4786,context=5
#
# Cloak of Rippling Whispers (370)
# back=,id=160642,bonus_id=4799/1492/4786,context=5
#
# Ebon Blood Chestguard (130)
# chest=,id=112821,bonus_id=450,context=6
#
# Crosswind Chainmail (325)
# chest=,id=157982,bonus_id=1517/4785,context=26,azerite_powers=
#
# Deathslaver's Hauberk (360)
# chest=,id=159395,bonus_id=5049/1527/4786/4775,context=35,azerite_powers=156/31/86/13
#
# Crosswind Chainmail (325)
# chest=,id=157982,bonus_id=1517/4785,context=27,azerite_powers=
#
# Crosswind Chainmail (370)
# chest=,id=157982,bonus_id=1562/5138/5383,context=28,azerite_powers=
#
# Trailseeker Vest (176)
# chest=,id=153805
#
# 7th Legionnaire's Chainmail (370)
# chest=,id=163398,bonus_id=5125/1562/5138/5383,context=28,azerite_powers=
#
# 7th Legionnaire's Bindings (340)
# wrist=,id=163277,bonus_id=5125/40/1532/4786,context=5
#
# 7th Legionnaire's Handguards (340)
# hands=,id=163397,bonus_id=5125/1532/4786,context=28
#
# Gloves of Descending Madness (370)
# hands=,id=160618,bonus_id=4799/1492/4786,context=5
#
# Wrasse Handwraps (335)
# hands=,id=133181,bonus_id=5130,drop_level=120,context=22
#
# Gloves of Involuntary Amputation (355)
# hands=,id=160626,bonus_id=4798/40/1477/4786,context=3
#
# Ionic Gloves (335)
# hands=,id=133258,bonus_id=5130,drop_level=120,context=22
#
# Blood Tick Crushers (355)
# hands=,id=159382,bonus_id=5005/1527/4786,context=16
#
# Cincture of Profane Deeds (370)
# waist=,id=160724,bonus_id=4799/1492/4786,context=5
#
# Shalebiter Interlinked Chain (370)
# waist=,id=159361,bonus_id=5007/1542/4783,context=35
#
# Anchor Chain Girdle (360)
# waist=,id=159386,bonus_id=5007/4802/1532/4786,context=16
#
# Titanspark Energy Girdle (370)
# waist=,id=160633,bonus_id=4799/40/1492/4786,context=5
#
# Anchor Chain Girdle (360)
# waist=,id=159386,bonus_id=5007/1532/4786,context=16
#
# 7th Legionnaire's Cincture (370)
# waist=,id=163401,bonus_id=5126/1562/4786,context=6
#
# Chain-Linked Safety Cord (375)
# waist=,id=159353,bonus_id=5009/43/1547/4783,context=35
#
# Legguards of Coalescing Plasma (370)
# legs=,id=160631,bonus_id=4799/1492/4786,context=5
#
# Windshear Leggings (365)
# legs=,id=161407,bonus_id=4798/1487/4783,context=3
#
# Legguards of the Storm Battalion (335)
# legs=,id=161587,context=14
#
# Chemical Blaster's Legguards (365)
# legs=,id=158341,bonus_id=5008/1537/4786,context=16
#
# Fused Monstrosity Stompers (370)
# feet=,id=160628,bonus_id=4799/1492/4786,context=5
#
# Souldrifting Sabatons (365)
# feet=,id=158308,bonus_id=5008/1537/4786,context=16
#
# Jade Ophidian Band (365)
# finger1=,id=162544,bonus_id=5008/1537/4786,context=16
#
# Murky Cerulean Signet (360)
# finger1=,id=158318,bonus_id=5007/1532/4786,context=16
#
# Band of Certain Annihilation (370)
# finger1=,id=160646,bonus_id=4799/1492/4786,context=5
#
# Spearfisher's Band (320)
# finger1=,id=158161,bonus_id=4803/4802/1512/4785,context=25
#
# Nautilus Ring (345)
# finger1=,id=133194,bonus_id=5130/5131,drop_level=120,context=22
#
# Smuggler's Cove Ring (330)
# finger1=,id=158160,bonus_id=4803/40/1522/4785,context=27
#
# Pearl Diver's Compass (325)
# trinket1=,id=158162,bonus_id=4803/1517/4785,context=26
#
# Plunderbeard's Flask (320)
# trinket1=,id=158164,bonus_id=4803/42/1512/4785,context=25
#
# Construct Overcharger (370)
# trinket1=,id=160652,bonus_id=4799/1492/4786,context=5
#
# Darkmoon Deck: Fathoms (355)
# trinket1=,id=159125,context=13
#
# Construct Overcharger (385)
# trinket1=,id=160652,bonus_id=4800/1507/4786,context=6
#
# Dread Aspirant's Insignia (340)
# trinket1=,id=162899,bonus_id=1532/4783,context=47
#
# Wavecaller Spire of the Aurora (266)
# main_hand=,id=159569,bonus_id=4796/4802/42/1705,drop_level=120
#
# Golden Fleet Waraxe of the Harmonious (266)
# main_hand=,id=159476,bonus_id=4796/4802/1716,drop_level=120
#
# Wavecaller Speargun (345)
# main_hand=,id=158084,bonus_id=4803/41/1537/4783,context=28
#
# P.A.C.I.F.I.S.T. Mk7 (360)
# main_hand=,id=159639,bonus_id=5007/1532/4786,context=16
#
# Tideguard Pike (340)
# main_hand=,id=158097,bonus_id=4803/1532/4786,context=28
#
# Tideguard Pike (340)
# main_hand=,id=158097,gem_id=154127,bonus_id=4803/4802/1532/4786,context=28
#
# Wickerbeast Mulcher (320)
# main_hand=,id=155362,bonus_id=4803/1512/4785,context=25
#
# Re-Origination Pulse Rifle (370)
# main_hand=,id=160694,enchant_id=5957,gem_id=153708,bonus_id=4799/1808/1492/4786,context=5
#
# Golden Fleet Waraxe of the Harmonious (266)
# off_hand=,id=159476,bonus_id=4796/4802/1716,drop_level=120

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=8

### End simulateText ###
desired_targets=1
### Begin overrides ###
# User-specified persistent global and player parameters will be set here.

### End overrides ###
### Begin final options ###
### End final options ###
### END ###
```

**Comment by vituscze** [comment] 2018-12-11 01:11
Duplicate of #4613

**Closed as completed by vituscze** 2018-12-11 01:11 UTC
